### ISSUE TITLE
[0.5pt] Найти сайт для демонстрации модели которая распознаёт Material UI

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#100]
Нужен сайт для демонстрации перед главнюками.
Сайт должен распозноваться быстро, что бы они не заснули

**Comment by lisatatarinova** [comment]
Examples:
https://material-kit-react.devias.io/
https://demos.creative-tim.com/material-kit-react/?_ga=2.103159363.295460037.1638262132-625041946.1638262132#/

**Comment by pulya-na-vullet** [comment]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/18251877/Examples+of+webpages
