### ISSUE TITLE
Копирование xPath работает неверно

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1000]
Сейчас - при копировании xPath - система помещает в буфер Full xPath (например - /html/body/div[5]/div[3]/div/div/div/div/div[2]/div/div/main/div/section/div[2]/div[1]/ul/li[52]/div/div/div[2]/div[1]/button)

А нужно, что бы она помещала туда оптимизированный xPath (ну например - //*[@aria-label='Send a message to Ekaterina Markova'])
Т.е. тот контент который у нас показывается внутри аннотации @UI("//*[@aria-label='Send a message to Ekaterina Markova']")

**Comment by arslanbekova** [comment]
[3.7.371](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.371)
