### ISSUE TITLE
[NR-12] Организовать кэширование - ДЕКОМПОЗИРОВАТЬ

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#1004]

**Comment by spiridonovfed** [comment]
- [ ] кэширование результатов тасок
- [ ] кэширование возможных промежуточных результатов на разных уровнях

**Comment by AlexeyGirin** [comment]
@MariiaNebesnova должна посмотреть и порешать - сможет ли она помочь Фёдору с сортировкой второй опции

**Comment by AlexeyGirin** [comment]
Закрыто после декомпозирования
