### ISSUE TITLE
[Retro insights] Initiatives horizon

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#1008]
- [x] Предложить возможности более высокоуровневого планирования
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/120225793/Initiatives+horizon
- [x] Kano Analysis
- [x] Purpose Alignment Model
- [ ] Story Mapping

**Comment by AlexeyGirin** [comment]
Story Mapping - решили не делать
