### ISSUE TITLE
Добавить тултип с URL оригинального сайта для PO

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1010]
Показывать тултип с URL сайта при наведении на иконку или текст (!) РО

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7890%3A363948&t=Ko2fC2sn5pQVSFBV-4)

![image](https://user-images.githubusercontent.com/101407186/215794062-5cc425c0-6bf1-47ed-b28a-018d595c32ea.png)

![image](https://user-images.githubusercontent.com/101407186/215794350-4d372ee8-53b3-465c-ae1b-6dd17492ebc7.png)

**Comment by OlgaTitovaEPAM** [comment]
При длинном URL тултип растягивается на всё окно плагина
сайт:
https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7890%3A363948&t=77Q9ONjVPZy3nUW0-0
<img width="732" alt="Screenshot 2023-02-09 at 18 59 34" src="https://user-images.githubusercontent.com/112088719/217866937-8070a3bc-6f1b-48f2-a491-ea2c91ce8ebb.png">

**Comment by MariiaNebesnova** [comment]
[3.7.388](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.388)

**Comment by OlgaTitovaEPAM** [comment]
Воспроизводится на  macOS 12.6.1
<img width="464" alt="Screenshot 2023-02-10 at 13 09 18" src="https://user-images.githubusercontent.com/112088719/218064769-2cdbbc25-93f2-4f59-8bab-5d783e2bf11c.png">

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=8034%3A369833&t=HXPpvaPXeyZZuOrA-4)

оставляем по бокам по 18px (по идее чтобы треугольник-указатель тултипа указывал на иконку РО) 


<img width="534" alt="Снимок экрана 2023-02-16 в 17 49 13" src="https://user-images.githubusercontent.com/101407186/219397853-a05919be-6310-43f9-ad4b-9321bdc3f454.png">
<img width="534" alt="Снимок экрана 2023-02-16 в 17 49 27" src="https://user-images.githubusercontent.com/101407186/219397860-6275d4b7-2017-47cf-bc62-6dedae26c404.png">

1. если url небольшой то обрезаем тултип справа 
![image](https://user-images.githubusercontent.com/101407186/219393911-292ada47-8606-4f94-85ea-9032a640ee52.png)

2. максимальная ширина тултипа в строку получается ширина белого контейнера - 36px
![image](https://user-images.githubusercontent.com/101407186/219397210-1ede7c65-76da-4af3-ba3f-2d2b9f756b64.png)

3. дальше мы просто переносим строки
![image](https://user-images.githubusercontent.com/101407186/219396856-e8c9ccde-ed82-4770-b696-1d85d7066ed3.png)

4. до 10 строк, я думаю 99,99% урлов зайдёт в это ограничение, по визуалу приемлимо
![image](https://user-images.githubusercontent.com/101407186/219396170-40843a8d-9e7a-45e8-b61a-0e4d3196df45.png)

5. но если уж больше (на всякий случай надо добавить) то элипсируем
![image](https://user-images.githubusercontent.com/101407186/219396057-2279925f-06da-47f8-a3a2-e7efa0ff7443.png)

**Comment by OlgaTitovaEPAM** [comment]
Разные отступы для длинного и короткого url, отступ не 18px
<img width="817" alt="Screenshot 2023-02-17 at 13 50 51" src="https://user-images.githubusercontent.com/112088719/219626863-bd15007f-93dd-41f9-ac20-755f75265b5b.png">
<img width="820" alt="Screenshot 2023-02-17 at 13 51 04" src="https://user-images.githubusercontent.com/112088719/219626880-02d8ff53-1770-460f-8141-7282f1e27fd1.png">

**Comment by MariiaNebesnova** [comment]
[3.8.402](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.402)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.405 Back-end v 0.2.18

Test result - **fail**

Tooltip points higher than page object name and is not cropped to 350px when page object is generated and URL is very long.

Steps to reproduce:

1. Open any web page with long URL (for instance, you can google something with ~2000 symbols in the query string, and you will get this long URL)
2. Generate page object via JDN plugin
3. Hover over the page object's name

https://user-images.githubusercontent.com/106632366/222424201-9aaad2fd-5950-4d93-8df6-c7a2502c18fb.mp4

**Comment by arslanbekova** [comment]
[3.9.419](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.419)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.421 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Test result - **pass**
The tooltip with the URL of the website is shown when hovering over the icon or text of the PO.
The [aforementioned defect](https://github.com/jdi-testing/jdn-ai/issues/1010#issuecomment-1451779174) is fixed.

https://user-images.githubusercontent.com/106632366/226567519-3e5ba296-07d6-49ed-b4bd-49b274549edb.mp4
