### ISSUE TITLE
Визуальный баг с полоской у строки РО

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1011]
У первой строки есть обводка снизу, у второй нет

<img width="545" alt="Снимок экрана 2023-01-31 в 17 58 04" src="https://user-images.githubusercontent.com/101407186/215795330-158131ad-337f-47f6-8296-2d3bc0af4249.png">

<img width="543" alt="Снимок экрана 2023-01-31 в 17 57 50" src="https://user-images.githubusercontent.com/101407186/215795286-b7928a29-e117-4a97-b57b-1d9dccf2d0e5.png">

https://user-images.githubusercontent.com/101407186/215795367-464498bc-75cf-419f-ad83-cb9df7a3238f.mov

Ожидаемое: полосок нет
- между (свёрнутыми) РО тоже нет разделителей, в дальнейшем добавим состояние ховера
- белое пространство между название РО и локаторами

**Comment by MariiaNebesnova** [comment]
[3.7.375](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.375)
