### ISSUE TITLE
Добавить ховер затемнение при наведении мышки на ПО в списке ПО

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1012]
https://user-images.githubusercontent.com/101407186/220599735-eb266cad-adaf-4143-a78f-2056a235d6f9.mov

______
1:
```
/* Neutral/1 */
background: #FFFFFF;
```

2: 
```
/* Neutral/2 */
background: #FAFAFA;
```

3:
```
/* Neutral/2 */
background: #FAFAFA;
```

[figma component](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163878%3A164876&t=SMmliZpf1EWXUlpx-4)
![image](https://user-images.githubusercontent.com/101407186/220599882-57101502-6065-425b-a738-b78b16f166db.png)
 
[Потыкать прототип на ховер можно тут](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=7897%3A435085&viewport=-398%2C-330%2C0.27&scaling=scale-down-width&starting-point-node-id=7897%3A435085)

**Comment by arslanbekova** [comment]
[3.9.420](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.420)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.421 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Test result - **pass**
When hovering over a PO in the PO list, the PO becomes light grey.

https://user-images.githubusercontent.com/106632366/226583560-74d6ba9a-72ec-4188-be70-e6bd2176bb71.mp4
