### ISSUE TITLE
Поправить текст и отступы на странице ПО-ов

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1016]
1. обновить текст
2. обновить отступ между текстом
3. добавить для текста обязательный отступ от границы блока по 16px с каждой стороны

No page objects created
Open the desired page and click the "+ Page object" button to start

<img width="424" alt="Снимок экрана 2023-02-02 в 11 41 01" src="https://user-images.githubusercontent.com/101407186/216273953-f4727529-075d-4dbd-bce6-6f2c314eca09.png">

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7897%3A364443&t=h4qP32YWnmA5xXWl-4)

<img width="683" alt="Снимок экрана 2023-02-02 в 11 40 00" src="https://user-images.githubusercontent.com/101407186/216273730-109b1b40-f844-4bf3-aa2f-0c8e983614cb.png">

**Comment by arslanbekova** [comment]
[3.7.379](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.379)
