### ISSUE TITLE
[Low] выровнять пункты в контекстном меню

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1017]
В контекстном меню у списка выровнять иконки и текст по центру

![image](https://user-images.githubusercontent.com/101407186/216278623-0ab0514c-5444-4c76-997c-b024aa278081.png)

![image](https://user-images.githubusercontent.com/101407186/216278097-5819232f-55a5-42f6-933a-384e690a7c71.png)

**Comment by arslanbekova** [comment]
[3.7.379](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.379)
