### ISSUE TITLE
Сделать инпут поиска маленького размера small (24px)

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1020]
[ссылка на ант](https://github.com/ant-design/ant-design/edit/master/components/input/demo/size.tsx)

[figma](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163576%3A163463&t=qiJ46FyDnMfQDItz-4)

![image](https://user-images.githubusercontent.com/101407186/216313931-c0b5ea3f-2372-4bc8-b460-c2de52c78753.png)

**Comment by arslanbekova** [comment]
[3.7.377](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.377)
