### ISSUE TITLE
Поменять клавишу модификатор для доп выбора на macos (теперь и на панели покрытия)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1021]
На маке вместо кнопки CTRL должна быть кнопка Сommand
Сейчас на маке при нажатии Сontrol+пкм/лкм просто открывается контекстное меню

Поэтому мульти селект блоков из-за этого не работает.

Эта задача похожа на #954 только там это делалось для панели локаторов, а тут - нужно сделать для панели покрытия

**Comment by arslanbekova** [comment]
[3.7.378](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.378)

**Comment by OlgaTitovaEPAM** [comment]
done.  tasted on macOS 12.6.1
