### ISSUE TITLE
Подправить нумерацию в ReadMe для отображения на плагине

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1022]
по идее тут должны быть пункты
1
2
3

вместо 

6
7
8

![image](https://user-images.githubusercontent.com/101407186/216332168-4623a9db-deb2-4409-9cce-ff828171f79a.png)

**Comment by AlexeyGirin** [comment]
https://github.com/jdi-testing/jdn-ai/blob/issue_894/README.md

**Comment by andrei-mikhailovskii** [comment]
Test result - pass
![image](https://user-images.githubusercontent.com/106632366/221142439-1979e3e1-23fb-4091-9f03-eab8f9fca9d1.png)
