### ISSUE TITLE
Добавить в тултип xPath (и про копирование)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1026]
В данный момент - получить информацию о локаторе элемента можно только с панели выбора локаторов.
С панели покрытия - можно посмотреть только имя и тип элемента (через тултип)

Хочется дать пользователю возможность увидеть следующую информацию о контроле:
1. Optimal xPath (после просчёта - который выдаёт робула) - тот икспас который фигурирует на панели локаторов (не показывается, если робула не отработала или пользователь сам чего то не вписал. Если отработала или пользователь сам вписал - тогда показываем)
2. CSS Selector - тот цсс который фигурирует на панели локаторов (ну или тот селектор который ввёл пользователь)

При этом - возможно стоит пересмотреть логику появления тултипа - сейчас он появляется при наведении на лэйбл блока в уголке, а стоит (так же) показывать его при простом наведении на блок (спустя, например, секунду времени)

И наконец последнее. Заманчиво дать пользователю (раз уж мы даём ему информацию по xPath и прочему) дать ему возможность скопировать эти данные через контекстное меню в том же стиле что мы даём ему сделать это на панели выбора локатора

**Comment by SemyonKuznetsov** [comment]
надо показывать все 3 варианта локатора или тот, который отображается в данный момент в списке локаторов?

**Comment by SemyonKuznetsov** [comment]
[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=8161-372947&t=boBTZy3Rs20BukeP-4)
[prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=8150-369600&viewport=592%2C-20613%2C0.37&scaling=scale-down-width&starting-point-node-id=8150%3A369600)
____

### 1. По клику на лейбл
- клик по лейблу элемента - показываем тултип сверху/снизу от лейбла, в зависимости от положения элемента относительно экрана
- в этом случае не важно сколько места занимает элемент на покрытии, если пользователь видит лейбл, этого достаточно


https://user-images.githubusercontent.com/101407186/227737288-f45a90c4-9302-4af5-89a2-5f91ca395d8d.mov

<img width="1320" alt="Снимок экрана 2023-03-25 в 22 22 27" src="https://user-images.githubusercontent.com/101407186/227737261-a05b0477-afa3-4530-b5f2-073f2e66d189.png">

____
### 2. По ховеру на элемент 
- статичный ховер на элемент в течении 2 (?) секунд - показываем тултип под/над курсором, в зависимости от положения элемента относительно экрана
- так же не важно сколько и где занимает место элемент на покрытии, если пользователь может навести курсор на его часть, этого достаточно
- если в одном месте несколько элементов друг над другом, то мы обрабатываем верхний слой

//в фигме нет возможности показать задержку анимации по ховеру

https://user-images.githubusercontent.com/101407186/227736948-621a6d9d-3590-405c-a2ef-96462e755838.mov

<img width="1320" alt="Снимок экрана 2023-03-25 в 22 15 12" src="https://user-images.githubusercontent.com/101407186/227736971-2a1e3e98-0527-47af-bd18-fefeae2f5609.png">

позиционирование тултипов
<img width="699" alt="Снимок экрана 2023-03-25 в 22 16 29" src="https://user-images.githubusercontent.com/101407186/227737043-3c9dc26e-2db5-45f9-87f3-92b47649f708.png">


___
###  3. Отступы
есть момент по расстоянию от курсора/лейбла до тултипа, в фигме у антовского элемента есть автоматический отступ, я предполагаю что и у фронт-элемента он должен быть. получается 9px от "указателя" до курсора

<img width="649" alt="Снимок экрана 2023-03-25 в 22 21 09" src="https://user-images.githubusercontent.com/101407186/227737219-ebbc4a47-2340-4582-ac5f-5939ac7274d1.png">

<img width="822" alt="Снимок экрана 2023-03-25 в 22 18 27" src="https://user-images.githubusercontent.com/101407186/227737109-ee50647f-4a09-4ff3-9757-ef06a095ce1c.png">

___
### 4. Общие моменты
- если не сгенерирован оптимальный xpath или css, не закончена генерация и т.д., то мы показываем "Calculating ..."

<img width="601" alt="Снимок экрана 2023-03-25 в 22 33 33" src="https://user-images.githubusercontent.com/101407186/227737756-b7fc208f-c139-48f2-a6a0-429aec0b941a.png">

- информация в тултипе статична, обновляется только при повторном появления (upd: если легко имплементировать обратный вариант, когда мы онлайн подгружаем в тултип что нам надо, то это конечно лучше)
- Про позиционирование и размеры

**Comment by MariiaNebesnova** [comment]
[3.10.443](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.443)

**Comment by AlexadrK** [comment]
JDN v 3.10.445 Back-end v 0.2.31

Test result - PASS

https://user-images.githubusercontent.com/21053451/232706418-a9f3c07b-40f4-4db4-a688-64614d332aad.mp4

**Comment by SemyonKuznetsov** [comment]
комментарии 

- Уменьшить время наведения вполовину
- Добавить отступ между строками Type и xPath в 8px
- Автоматическое обновление данных (должен обновляться до оптимального без hoveroff-hoveron)
