### ISSUE TITLE
Отмена Revoke'a не останавливает расчет локаторов

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#1028]
- для страницы 200+ локаторов, например https://jdi-testing.github.io/jdi-light/bootstrap-new.html открыть плагин и подключиться к удаленному серверу
- запустить генерацию, дожадаться начала расчета локаторов
- отключить впн, генерация остановится с ошибкой
- включить впн, нажать кнопку Retry
- дождаться нотификейшена о перезапуске рассчета и нажать Cancel

результат: рассчет не остановится, иконка локатора продолжает показывать состояние InProgress

должно быть: рассчет останавливается, иконка локатора возвращается к статусу Failed

**Comment by MariiaNebesnova** [comment]
после оставновки рассчета операцией отмены локаторы могут продолжать считаться 
![image](https://user-images.githubusercontent.com/82033805/217204203-12d1d012-288d-42ba-8b2e-865a023443b9.png)

**Comment by AlexeyGirin** [comment]
Есть явно проблема на бэке - Маша объяснит

**Comment by MariiaNebesnova** [comment]
со сотроны фронтэнда - фикс [3.7.380](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.380)

**Comment by AlexeyGirin** [comment]
Решили выпилить кнопку Cancel если пользователь перезапускает расчёт локатора

**Comment by MariiaNebesnova** [comment]
[3.8.400](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.400)

**Comment by MariiaNebesnova** [comment]
так же сделано для #1039

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.8.400 Back-end v 0.2.26

Cancel [button is absent](https://github.com/jdi-testing/jdn-ai/issues/1028#issuecomment-1434503163) when Retry button is clicked
![2023-02-27 17_47_44-Settings](https://user-images.githubusercontent.com/106632366/221632079-87a8ca1e-faeb-4d33-94c0-4542d7658bc7.jpg)
After retry, all remaining locators are generated successfully.
