### ISSUE TITLE
[Low] Опять едет UI плагина на шаге создания\редактирования PO при длинном имени этого PO

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#1031]
Продолжение #961 

Precons:
- JDN v 3.7.379
- https://www.google.com/search?q=qweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqweqwe
- Шаг Creating/Editing

Steps:
1. Проверить отображение кнопок Back/Save

ER:
- Под кнопками есть отступ в 16px

AR:
- Оступ под кнопками уезжает за пределы видимой области, окно плагина скроллится

![image](https://user-images.githubusercontent.com/109746268/217230437-b10ab937-68f2-4a32-8935-74fd67a35661.png)
![image](https://user-images.githubusercontent.com/109746268/217231183-66368b74-57c1-405d-9980-d0ad86b0b444.png)

**Comment by arslanbekova** [comment]
[3.7.385](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.385)
