### ISSUE TITLE
[Low] При нажатии на локатор на странице Edit Page Object происходит скрол страницы к месту его расположения

### ISSUE THREAD

**Issue by OlgaTitovaEPAM** [jdi-testing/jdn-ai#1036]
https://user-images.githubusercontent.com/112088719/217294250-2d8add83-a87a-4ecd-bf60-d89bfb61dce0.mov

Окружение
JDN v 3.7.379 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1

Шаги

1. Нажать на "+Page object" 
2. Выбрать в Library HTMl5 и нажать Generate
3. Выбрать не менее одного локатора и нажать кнопку Save
4. Нажать "..." и выбрать Edit Page Object 
5. Нажать на любой локатор

ОР
Окно покрытия имеет серый фон, нет перехода к месту расположения локатора на странице

ФР
Окно покрытия имеет серый фон, происходит скрол к месту расположения локатора

**Comment by arslanbekova** [comment]
The bug isn't reproduce anymore.
JDN 3.9.407
macOS Ventura 13.2.1

https://user-images.githubusercontent.com/59090607/223084468-543adf6f-0683-4bcf-80a1-d3f1720d68bf.mov

**Comment by arslanbekova** [comment]
It isn't reproduce on https://www.docker.com/products/docker-desktop/ either.

**Comment by OlgaTitovaEPAM** [comment]
The bug isn't reproduce anymore.
