### ISSUE TITLE
Рассчет не перезапускается, если Pause generation была быстро отменена

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#1039]
- запустить генерацию
- остановить рассчет одного локатора
- в появившемся нотификейшене нажать Cancel
результат: рассчет не перезапустится, значение остается fullXpath, статус - Revoked

последовательность сокет-сообщений на скрине:
![image](https://user-images.githubusercontent.com/82033805/217479892-d1c76470-7039-4541-8a1b-968d41367178.png)

если перезапустить рассчет этого локатора позже, он успешно расчитается: 

![image](https://user-images.githubusercontent.com/82033805/217480210-a9a8ef6b-b498-4a38-ad3b-8aa7cfed176f.png)

**Comment by AlexeyGirin** [comment]
Судя по всему - дупликат #1028 
Фёдор проверит - если да - закроет

**Comment by spiridonovfed** [comment]
> Судя по всему - дупликат #1028 Фёдор проверит - если да - закроет

Да, это дубликат №1028.
Закрываю
