### ISSUE TITLE
[Medium] Генерация локатора продолжается после нажатия на паузу

### ISSUE THREAD

**Issue by OlgaTitovaEPAM** [jdi-testing/jdn-ai#1040]
Окружение
JDN v 3.7.379 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1

Шаги

1. Нажать на "+Page object"
2. Выбрать в Library HTMl5 и нажать Generate
3. На локаторе который еще в процессе, нажать "..."
4. Нажать Pause generation

ОР
Генерация останавливается и рядом с локатором появляется знак что он на паузе.

ФР
Генерация продолжается.

**Comment by MariiaNebesnova** [comment]
[3.7.382](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.382)

**Comment by OlgaTitovaEPAM** [comment]
done. tasted on macOS 12.6.1
