### ISSUE TITLE
[Low] Состояние фильтра сохраняется при переходе на другой сайт

### ISSUE THREAD

**Issue by OlgaTitovaEPAM** [jdi-testing/jdn-ai#1044]
<img width="1792" alt="Screenshot 2023-02-09 at 13 12 26" src="https://user-images.githubusercontent.com/112088719/217785158-214c1a7c-912f-4a0c-a71b-5bca6b0db169.png">
Окружение
JDN v 3.7.383 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1

Шаги

1. Перейти на https://www.docker.com/products/docker-desktop/
1. Нажать на "+Page object" 
2. Выбрать в Library HTMl5 и нажать Generate
3. Пойти в фильт и отключить все элементы КРОМЕ button
4. В этой же вкладке перейти на https://cbracco.github.io/html5-test-page/
5. Нажать на "+Page object" 
6. Выбрать в Library HTMl5 и нажать Generate

ОР
На Окне покрытия отображены все найденные на странице локаторы, в Окне плагина список всех найденных локаторов. 

ФР
На Окне покрытия отображены **все найденные на странице локаторы**, в Окне плагина список локаторов **только с типом button.** Фильтр при переходе сохранился.

**Comment by MariiaNebesnova** [comment]
[3.7.391](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.391)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.7.391 Back-end v 0.2.22, Google Chrome Version 110.0.5481.77 (Official Build) (x86_64), macOS 12.6.1
