### ISSUE TITLE
[Medium] На окне плагина кнопка "..." для выбранных локаторов перекрывает фильтр

### ISSUE THREAD

**Issue by OlgaTitovaEPAM** [jdi-testing/jdn-ai#1046]
Окружение
JDN v 3.7.386 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1
https://cbracco.github.io/html5-test-page/

Шаги

1. Нажать на "+Page object" 
2. Выбрать в Library HTMД5 и нажать Generate
3. Выбрать не менее одного локатора

ОР
Кнопка "..." расположена на уровне чекбокса

ФР
Кнопка перекрывает фильтр.
<img width="676" alt="Screenshot 2023-02-09 at 18 34 43" src="https://user-images.githubusercontent.com/112088719/217859233-87aceb85-ca2a-4f3e-aded-29d0c50bae96.png">

**Comment by MariiaNebesnova** [comment]
[3.7.388](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.388)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.7.388 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1
