### ISSUE TITLE
[Medium] На окне плагина кнопка  Copy перекрывает "..." для сохраненных PO

### ISSUE THREAD

**Issue by OlgaTitovaEPAM** [jdi-testing/jdn-ai#1049]
Окружение
JDN v 3.7.388 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1
https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7890%3A363948&t=AEPaFyq8kh5cG41u-0

Шаги

1. Нажать на "+Page object"
2. Выбрать в Library HTML5 и нажать Generate
3. Выбрать не менее одного локатора и нажать Save
4.  Навести курсор на сохраненный РО

ОР
Кнопка  Copy расположена рядом с "..." 

ФР
Кнопка  Copy перекрыла 
<img width="646" alt="Screenshot 2023-02-10 at 13 18 31" src="https://user-images.githubusercontent.com/112088719/218069406-464ee0ec-4a8a-4452-9a46-c4b83f5b6cb5.png">
 "..."

**Comment by MariiaNebesnova** [comment]
[3.7.389](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.389)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.7.389 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1
