### ISSUE TITLE
[US-3-1] Тултип Prediction accuracy перекрывается вкладками Waiting for generation и Deleted

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#105]
<img width="695" alt="Screenshot 2021-12-02 at 11 54 54" src="https://user-images.githubusercontent.com/89466817/144555861-1e9824dd-8ec3-4a21-aa18-de69d7607f6f.png">

<img width="697" alt="Screenshot 2021-12-02 at 11 54 37" src="https://user-images.githubusercontent.com/89466817/144555902-f0ec11f4-5dec-4cc5-8eab-56dff201b29e.png">

**Comment by MariiaNebesnova** [comment]
3.0.97

**Comment by pulya-na-vullet** [comment]
Проверил на версии 
JDN v 3.0.99
Back-end v 2021-11-26-14.32.52
Баг не воспроизводится.
