### ISSUE TITLE
[Low] Кнопка Copy расположена вплотную к локатору

### ISSUE THREAD

**Issue by OlgaTitovaEPAM** [jdi-testing/jdn-ai#1053]
<img width="654" alt="Screenshot 2023-02-10 at 16 40 41" src="https://user-images.githubusercontent.com/112088719/218117373-dbc18506-9f0e-4732-9bd3-fb1d7a8671cb.png">

_____
_Semyon:_

то же решение что с PО

длинное имя локатора не будет переносится при наведении на него, тк там всегда есть кнопка copy, просто в скрытом состоянии (типа opacity: 0) и соответсвенно если название длинное и упирается в copy, то еще на этапе генерации перенесется на 2ю строку

![image](https://user-images.githubusercontent.com/101407186/220315513-28cd6073-c294-429c-ac3b-f6fd675d9ebc.png)

![image](https://user-images.githubusercontent.com/101407186/220355884-8177ca0f-ef99-4f03-ba21-604c7eea1ad2.png)

`gap: 8px;`
8px между контейнером текста и иконками

И можно ещё подвинуть тултип вверх ближе к кнопке Copy примерно в половину, у меня 4px между границей иконки и указателя тултипа. Если как-то по другому в коде выравнивание -- поправлю текст
![image](https://user-images.githubusercontent.com/101407186/220317004-7487e61d-3a5a-48f6-984e-e42f3c81bc06.png)

**Comment by SemyonKuznetsov** [comment]
длинное имя локатора не будет переносится при наведении на него, тк там всегда есть кнопка copy, просто в скрытом состоянии (типа opacity: 0) и соответсвенно если название длинное и упирается в copy, то еще на этапе генерации перенесется на 2ю строку

![image](https://user-images.githubusercontent.com/101407186/220315513-28cd6073-c294-429c-ac3b-f6fd675d9ebc.png)

`gap: 8px;`

и можно ещё подвинуть тултип вверх ближе к кнопке Copy примерно в половину
![image](https://user-images.githubusercontent.com/101407186/220317004-7487e61d-3a5a-48f6-984e-e42f3c81bc06.png)

**Comment by arslanbekova** [comment]
[3.9.407](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.407)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.407 Back-end v 0.2.27

The bug is fixed.
Long locators names are not overlap Copy button.
![image](https://user-images.githubusercontent.com/106632366/223146168-ba363991-7193-4d26-8e33-14cd782f579d.png)
