### ISSUE TITLE
Позиционировать локатор в середине видимого фрейма, а не сверху или снизу как сейчас

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1054]
Сейчас, при клике на элемент на покрытии - система скроллит список локаторов до тех пор пока соответсвующий элементу локатор не станет видимым. Практически всегда он оказывается прижат или к верхнему или к нижнему краю видимой области.
В то же время - при обратной ситуации - клике на локатор - система скролит покрытие пока элемент не оказжется в центре экрана. Это поведение очень приятно и удобно.
Необходимо, что бы при скроле локаторов - поведение была аналогичным - что бы система стремилась поместить выделяемый локатор в центр видимой области списка

**Comment by arslanbekova** [comment]
[3.9.426](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.426)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.426 Back-end v 0.2.27
Chrome Version 111.0.5563.111 (Official Build) (64-bit)

Test result - **pass**
When clicking on a locator in JDN plugin window, selected element is displayed at the center of visible area after scrolling to it.

https://user-images.githubusercontent.com/106632366/227494099-165008d6-edb4-4681-8d7a-9f07203049c4.mp4
