### ISSUE TITLE
Поправить строку состояния генерации локаторов

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#106]
JDN v 3.0.89
Back-end v 2021-11-26-14.32.52

Строка состояния генерации отображается не полностью заполненной в случаи, если есть удаленные локаторы.

**1 баг:**
1. Нажимаю identify.
2. Дожидаюсь генерации всех локаторов.
3. Строка состояния генерации заполняется на 100%, а также меняется статус на “Locator generation is successfully completed”.
4. Выделяю несколько локаторов и удаляю их.
5. Строка состояния генерации возвращается в состояние незаполненной на 100%.

<img width="697" alt="Screenshot 2021-12-02 at 11 56 22" src="https://user-images.githubusercontent.com/89466817/144556863-77a25b0d-9d96-41fc-93b0-c6a1b8322a3f.png">

**2 баг:**
1. Нажимаю identify
2. Не дожидаюсь генерации всех локаторов
3. Выделяю несколько локаторов и удаляю их
4. Строка состояния генерации не заполняется на 100%, но меняется статус на “Locator generation is successfully completed”
5. Уведомление об успешной генерации не исчезает спустя 10 сек

<img width="543" alt="Screenshot 2021-12-02 at 13 24 04" src="https://user-images.githubusercontent.com/89466817/144557330-0f91999f-2a66-4ca6-a477-ba6585cd37cf.png">

**Comment by MariiaNebesnova** [comment]
2 pt - fe

**Comment by MariiaNebesnova** [comment]
3.0.94

**Comment by pulya-na-vullet** [comment]
JDN v 3.0.94
Back-end v 2021-12-01-14.52.21
site: https://www.reddit.com/r/MaterialDesign/
При удалении сгенерированных локаторов строка теперь полностью заполняет состояние
![image](https://user-images.githubusercontent.com/61897393/145026421-895df334-92b7-41f9-9032-1a8f23ddca51.png)

**Comment by pulya-na-vullet** [comment]
JDN v 3.0.94
Back-end v 2021-12-01-14.52.21
site: https://www.reddit.com/r/MaterialDesign/
По окончании генерации локаторов нотификашка исчезает через 10 секунд.
