### ISSUE TITLE
Контекстное меню на покрытии исчезает при попытке взаимодействия с ним, если окно плагина открыто в режиме "Undock into separate window"

### ISSUE THREAD

**Issue by arslanbekova** [jdi-testing/jdn-ai#1061]
Воспроизводится только на Mac OS.

Шаги для воспроизведения:
1. Открыть окно плагина в режиме "Undock into separate window"
2. Поместить окно браузера и окно плагина на один рабочий стол (2 окна на одном скрине)
3. Запустить генерацию ПО
4. Выделить элемент на покрытии правой кнопкой мыши
5. Выбрать любой пункт контекстного меню

AR: контекстное меню исчезает при малейшем движении курсора
ER: контекстное меню остается на покрытии и с ним можно взаимодействовать.

FYI:
Когда мы открываем плагин и запускаем генерацию ПО, фокус переходит с окна браузера на окно devtools с плагином, и если при этом кликать правой кнопкой мыши на элемент на покрытии - элемент выделяется, но событие фокуса не происходит, он все еще на окне плагина и поэтому отрабатывает mouseleave - система считает что мы ушли с покрытия.

Если devtools в одном окне с покрытием, то все ок. 
Переопределить фокус на окно с покрытием мне не удалось (как я поняла это особенность события right-click на mac, нужно изучать более детально).
Нужно погружаться глубже в данный случай. Возможно, что придется играть с событиями и заменять mouseleave на blur или click.
https://superuser.com/questions/1767701/switch-focus-to-window-on-mouse-right-click-macos-13-2
https://superuser.com/questions/729554/mac-os-x-open-context-under-focus-not-cursor
https://apple.stackexchange.com/questions/269622/macos-windows-requiring-an-explicit-click-to-make-active-before-ui-elements-ins

https://user-images.githubusercontent.com/59090607/219122744-3850601b-e60c-4aa3-a63f-52423cb24403.mov

https://user-images.githubusercontent.com/59090607/219122689-a6ae13ca-69d4-46fc-95fe-c1d59b7a3133.mov

**Comment by arslanbekova** [comment]
На данный момент, у нас нет возможности реализовать вызов и начало работы с контекстным меню на покрытии с помощью только right-click события, если плагин открыт в режиме "undock into separate window". Для корректной работы контекстного меню необходимо, чтобы focus переходил с окна плагина на окно браузера, но при событии right-click этого не происходит из-за особенностей macOS.

Сейчас работа пользователей macOS с контекстным меню на покрытии затруднена, если плагин открыт в режиме "undock into separate window" и фокус находится на нем, тк после открытия меню и попытке взаимодействия с ним, оно скрывается (видео выше).

Есть несколько вариантов для пользователей macOS:
1. Оставить все как есть и в аннотации убедительно просить не использовать плагин в режиме "undock into separate window".
2. Для пользователей всех ОС или только macOS изменить поведение скрытия контекстного меню + давать рекомендацию не использовать плагин в режиме undock:
    2.1 скрывать при уходе курсора с элемента меню, а не уходе курсора с покрытия, как это реализовано сейчас
    2.2 скрывать меню только по клику в любое место покрытия (такую реализацию используют https://trello.com и https://miro.com, как пример)

**Comment by AlexeyGirin** [comment]
Давайте попробуем реализовать решение 2.2

**Comment by arslanbekova** [comment]
[3.10.439](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.439)

**Comment by SemyonKuznetsov** [comment]
https://user-images.githubusercontent.com/101407186/231437233-090fe9e5-59e7-4382-b5a2-4dc485c0b8f6.mov

**Comment by SemyonKuznetsov** [comment]
https://user-images.githubusercontent.com/101407186/231438223-355bb31a-3ead-477d-ba36-e0d1a7b09107.mov

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.439

The bug is fixed.
The context menu on the coverage does not disappear when you try to interact with it if the plugin window is open in the "Undock into separate window" mode.
See confirmation in the [comment above](https://github.com/jdi-testing/jdn-ai/issues/1061#issuecomment-1505077103).
In the first screencast, it can be observed that the bug is reproducible in the first couple of seconds. However, it was not reproduced anymore neither on the same page, nor on any other, so, based on the discussion with team members, it was decided to consider that the bug is fixed.
