### ISSUE TITLE
[US-5-6] Добавление оставшихся элементов Vuetify

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1062]
И допилить дефолтный фильтр
- [x] https://github.com/jdi-testing/jdi-qasp-ml/issues/121
- [x] https://github.com/jdi-testing/jdi-qasp-ml/issues/106

List of elements:
- [x] Alert - alerts
- [x] AppBar - 
- [x] AspectRatios - 
- [ ] Autocomplete - autocompletes - РСПОЗНАЁМ КАК комбобокс
- [x] Avatar - 
- [x] Badge - 
- [x] Banner - 
- [ ] Bars - 
- [ ] BasicBar
- [x] BottomNavigation - bottomnavigation
- [x]  - bottomsheets - ВЫПИЛИТЬ ? - в JDI нет
- [x] Breadcrumbs - breadcrumbs
- [x] ButtonGroup - 
- [x] Calendar - calendars
- [x] Card - cards
- [x] Carousel - carousels
- [x] Checkbox - checkboxes - ВЫПИЛИТЬ?
- [x] Chip - combobox
- [x] ChipGroup - 
- [x] ColorPicker - 
- [x] Combobox - 
- [x] DataIterator - dataiterators
- [x] DatePicker - datepickers
- [x] DatePickerMonth - datepickersmonth
- [x] DataTable - 
- [x] Dialog - dialog
- [x] Divider - 
- [x] ExpansionPanels - 
- [x] FileInput - 
- [x] Footer - 
 - [x] Grid - 
- [x] Icon - icons
- [x] Image - 
- [x] Input - inputs
- [x] ItemGroup - 
- [x] ListItem - lists
- [x] ListItemGroups - 
- [x] Menu - menus
- [x] NavigationDrawer - 
- [x] OtpInput - 
- [x] OverflowButton - 
- [x] Overlay - 
- [x] Pagination - pagination
- [x] PaginationPage
- [x] Parallax - 
- [x] ProgressCircular - 
- [x] ProgressLinear - 
- [x] RadioButtons - radiobuttons
- [x] RangeSlider - rangeslider
- [x] Rating - 
- [x] Select - select
- [x] SimpleTable - simpletables
- [x] Sheet - 
- [x] SimpleTable
- [x] SkeletonLoader - 
- [x] SlideGroup - 
- [x] Slider - sliders
- [x] Snackbar - 
- [ ] Sparkline - 
- [x] Stepper - stepper
- [x] Step - 
- [x] Subheader - 
- [x] SystemBar - 
- [x] Switch - switch
- [ ] Tables - datatables - ВЫПИЛИТЬ? В JDI НЕТ
- [x] TableCheckbox - 
- [x] Text - 
- [x] TextArea - 
- [x] TextField - textfields
- [x] TimeLine - timelines
- [x] TimePicker - timepickers
- [x] Tooltip - tooltips
- [x] TreeView - 
- [x] ToolBar - toolbars
- [x] VirtualScroller - 
- [x] VueCheckbox
- [x] VuetifyButton - vuetifybuttons
- [x] VuetifyList - 
- [x] VuetifyListGroup
- [x] VuetifyTabs - 
- [x] Windows -

**Comment by MariiaNebesnova** [comment]
нужен пресет для дефолтного фильтра

**Comment by MariiaNebesnova** [comment]
[3.8.399](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.399)

**Comment by MariiaNebesnova** [comment]
дефолтный фильтр взят из элементов в #771

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.8.399 Back-end v 0.2.26

Test result - **fail**
Locators that were not initially displayed in the locators tree are not displayed in it after selecting in the filter.

**Steps to reproduce:**
1. Open a website with Vuetify elements that will not be displayed initially in the locators tree (e.g. https://vuetifyjs.com/en/components/breadcrumbs/ with Breadcrumbs elements)
2. Generate page object locators using Vuetify library
3. Go to the filter and select element type that is not initially displayed (e.g. Breadcrumbs)

**Expected result:** selected element type is highlighted on the web page, and locators for this element type are **displayed** the locators tree

**Actual result:** selected element type is highlighted on the web page, but locators for this element type are **not displayed** the locators tree
![image](https://user-images.githubusercontent.com/106632366/221875490-bf17358b-8611-4ba1-958e-c0cef53afbc0.png)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.410 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Test result - **fail**
AppBar elements (v-app-bar) are not recognized by the plugin.

1. Go to https://vuetifyjs.com/en/components/app-bars/
2. Generate page object locators using Vuetify library

https://user-images.githubusercontent.com/106632366/224694041-6364533f-024e-4184-917f-5485c20cd46c.mp4

**Comment by MariiaNebesnova** [comment]
note: компонент определился как ToolBar

**Comment by MariiaNebesnova** [comment]
[3.9.416](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.416)

**Comment by MariiaNebesnova** [comment]
[3.9.425](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.425)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.426 Back-end v 0.2.27
Chrome Version 111.0.5563.111 (Official Build) (64-bit)

Test result - **fail**

1. Chip elements are not recognized on https://vuetify.cn/en/components/chip-groups/, Chip group is recognized as Slide group at the same page.

https://user-images.githubusercontent.com/106632366/227499887-568fe1b5-e6ac-45e9-92c7-b607642e6381.mp4

2. DataTable is recognized as Range on https://vuetifyjs.com/en/components/data-tables/headers/

https://user-images.githubusercontent.com/106632366/227500162-4138f210-fa01-4000-97d1-ee9e0a381feb.mp4

3. Step component is not recognized on https://v15.vuetifyjs.com/en/components/steppers/

https://user-images.githubusercontent.com/106632366/227504613-66d7f81b-cf73-496e-adde-7dcc29614b5e.mp4

4. PaginationPage component is not recognized on https://vuetifyjs.com/en/components/paginations/

https://user-images.githubusercontent.com/106632366/227505525-d24064be-a1b8-479c-a27e-6763ff72b4db.mp4

**Comment by MariiaNebesnova** [comment]
[3.9.428](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.428)
