### ISSUE TITLE
[US-14-1] Расположение в порядке селектнутых

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#1063]
UC 14-1-1 Select elements with one click
GIVEN I am a user 

AND I selected locators to add them to the PO

WHEN I click on “Confirm” selection

THEN Locators should be shown in the order they were selected

**Comment by AlexeyGirin** [comment]
Улучшить описание задачи (сторю)
Должны экспортить в том же порядке в котором оно отображается в приложении
