### ISSUE TITLE
Не добавляется подсветка при скролле

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#1069]
- открыть https://www.uplabs.com/search?q=material%20designб пролистать в самый низ, до кнопки Load more
- или открыть https://www.google.com/search?q=654541&newwindow=1&rlz=1C1GCEU_enTR1034TR1034&sxsrf=AJOqlzUt6ZxynZ-3VF_Ud4cAEnkjOB4yZA:1676537483921&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj74Lnp1Jn9AhVPPewKHarADYIQ_AUoAnoECAEQBA&biw=1536&bih=842&dpr=1.25, предварительно скроллить не надо
- сгененрировать локаторы с html5
 - начать скроллить

ожидание: при скролле должны отрисовываться блоки подстветки для локаторов, попавших в видимую область.

реальность: не отрисовываются.

!!! для нашего кейса www.google.com надо скроллить недалеко, чтобы показалась пара новых строк, которые уже есть в DOM. если скроллить дальше -  начнется подгрузка и это уже не наш кейс

**Comment by MariiaNebesnova** [comment]
[3.8.397](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.397)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.8.398 Back-end v 0.2.22, Google Chrome Version 110.0.5481.77 (Official Build) (x86_64), macOS 12.6.1
