### ISSUE TITLE
[Low] Design review [part 2]

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#107]
- [ ] поправить отображение вкладок в Locator list
- [ ] выровнять расстояние между кнопками Identify и Clear all 
- [ ] Locator list и Prediction accuracy прыгает на пару пикселей вниз при выделении локаторов
- [ ] выровнять пункты меню в хедере

все подробности в фигме ( Design review. Part 2  - [Backlog] ) по ссылке https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=3578%3A72364

**Comment by savinovava** [comment]
**Некорректное отображение чекбокса в xPath настройках**
1.Установка настроек до идентификации - выделение всех чекбоксов
2. Изменение настроек одного локатора
3. Изменение натроек другого локатора
4. При выделении всей секции "Generated" при переходе в настройки xPath появляется квадрат в первой строке
![image](https://user-images.githubusercontent.com/53625116/145207535-8bfa0a75-b169-4207-aba5-5dbe34134430.png)
_как должно быть_
настройки по умолчанию

**Comment by mariia-tokarchuk** [comment]
**New visual fixes:**

- [ ] на странице Page Objects стили видимо тянутся такие же как на странице Locators list - разные высоты строк, где-то есть полоса разделитель между ПО, где-то ее нет. Нужно все привести к единому виду:

<img width="398" alt="Screenshot 2022-02-16 at 09 34 07" src="https://user-images.githubusercontent.com/89466817/154217389-a460b36b-ef0d-484a-94cc-a2ffc3c60440.png">

- [ ] выровнять расстояния между такими элементами на странице Locators list:
1) между Locators list и Prediction Accuracy
2) между Prediction Accuracy и кнопкой Confirm
3) от кнопки Confirm до нижней границы плагина

<img width="412" alt="Screenshot 2022-02-16 at 09 34 49" src="https://user-images.githubusercontent.com/89466817/154217985-9779249e-2821-4359-b13e-3b4b2027c860.png">

Правильные стили и расстояния между элементами можно проверить в Figma по ссылке - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=0%3A1

**Comment by savinovava** [comment]
outdated
