### ISSUE TITLE
[Low]Добавить иконки пунктов контекстного меню в соответствии  дизайном

### ISSUE THREAD

**Issue by OlgaTitovaEPAM** [jdi-testing/jdn-ai#1070]
![212047563-a475e650-f1dd-4594-9903-361cb5f722d8](https://user-images.githubusercontent.com/112088719/219368355-9f1f237a-8452-4ac2-82de-ae1982d94800.png)

[link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=164096%3A167687&t=8xXppcUTmczKGOLb-4)

**Comment by MariiaNebesnova** [comment]
дублирует #846 ?

**Comment by SemyonKuznetsov** [comment]
> дублирует #846 ?

да, скорее всего задача про иконки select и Add/remove & bring/send
