### ISSUE TITLE
[US-7-] Provide understandable naming to locators

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#1075]
Based on content
#943

1. based on attribute=name
OR
2. based on (contains text(),'Example Text')
OR
3. based on aria-label: [ARIA states and properties - Accessibility | MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes)

если выбранный выше элемент всё ещё не уникальный, то

если есть атрибут id, то используем его,

в противном случае - в качестве имени используется тип элемента (JDI class)

число делающее эту комбинацию уникальной.

Для первых 3 пунктов берём один из и проверяем на уникальность. В случае не уникальности оставляем конкатенацию для последующих локаторов.

**Comment by MariiaNebesnova** [comment]
в случае, если name | text | aria-label не делают имя уникальным, то берем один из этих признаком в проядке приоритета и к нему конкатенируем id, и если понадобится, класс и индекс

**Comment by MariiaNebesnova** [comment]
[3.9.414](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.414)

**Comment by MariiaNebesnova** [comment]
[3.9.421](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.421)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.421 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Test result - **fail**
On some web pages (e.g. https://vuetifyjs.com/en/components/data-tables/basics/), locators are not generated / displayed on the plugin window.

https://user-images.githubusercontent.com/106632366/226369319-1cba539c-9965-46b8-ba06-4f37a1969502.mp4

**Comment by MariiaNebesnova** [comment]
[3.9.425](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.425)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.428 Back-end v 0.2.27
Chrome Version 111.0.5563.111 (Official Build) (64-bit)

Test result - **pass**
Locators are named according to the aforementioned [description](https://github.com/jdi-testing/jdn-ai/issues/1075#issue-1595160841).
![2023-03-27 15_12_15-Settings](https://user-images.githubusercontent.com/106632366/227948391-3a7a69a3-dddc-4648-8fce-6645ac1e3c7a.jpg)
