### ISSUE TITLE
[Low] VuetifyButton floating button is not highlighted on UI if it has not been displayed initially

### ISSUE THREAD

**Issue by andrei-mikhailovskii** [jdi-testing/jdn-ai#1077]
Steps to reproduce:

1. Open website using Vuetify and having floating button that is not visible initially (e.g. https://www.floridacitygas.com/ with "Back to top" floating button)
2. Generate Page object using Vuetify library via JDN plugin
3. Scroll down on the page so floating button become visible
4. Click VuetifyButton locator for the floating button on the JDN plugin window

Expected result: floating button is highlighted in orange

Actual result: floating button is not highlighted
![image](https://user-images.githubusercontent.com/106632366/221198477-0f53f19b-55f2-4b7d-b6f1-0464ee7496b7.png)

**Comment by MariiaNebesnova** [comment]
[3.9.414](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.414)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.416 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

The bug is fixed.
VuetifyButton floating button is highlighted on UI if it has not been displayed initially.
![2023-03-17 12_22_35-Settings](https://user-images.githubusercontent.com/106632366/225891487-d8e01abf-6bef-433b-8670-9ba8875793da.jpg)
