### ISSUE TITLE
[NR-12-1] Организовать кэширование результатов тасок

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1079]
Повторный результат расчёта локаторов на одной и той же страницы должен браться из кэша

**Comment by AlexeyGirin** [comment]
Фёдор это сделал

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.409 Back-end v 0.2.27
Win 10 / Chrome Version 111.0.5563.65

Test result - **pass**
Re-generation of locators takes less time than the original one (in the attached video, 394 locators were generated in ~3min 10s for the first time and in ~24s for the second one)

https://user-images.githubusercontent.com/106632366/224009300-9a62f1c4-5234-42e6-bb4c-11fb3c97a8b7.mp4
