### ISSUE TITLE
Remove the Upgrade item in the header for MVP

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#108]
Сейчас Upgrade не работает и не будет доступный для MVP, поэтому смысла ее показывать пользователям нет.

**Comment by MariiaNebesnova** [comment]
не знаю как оценить в сторипойнтах, 15 минут потратила

**Comment by MariiaNebesnova** [comment]
3.0.95

**Comment by MariiaNebesnova** [comment]
3.0.96

**Comment by pulya-na-vullet** [comment]
JDN v 3.0.96
Back-end v 2021-11-26-14.32.52
Функционал устранен.
