### ISSUE TITLE
[NR-12-2] Кэширование ответа от html_predict, angular_predict и mui_predict эндпоинтов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1080]
кэширование ответа от html_predict, angular_predict и mui_predict эндпоинтов - РЕШИЛИ ПОПРОБОВАТЬ СДЕЛАТЬ - МАША НЕ МОЖЕТ ПОВЛИЯТЬ НА ПРОЦЕССИНГ КЛЮЧЕЙ, но может передавать xml что бы можно было сравнить

**Comment by AlexeyGirin** [comment]
Фёдор нашёл странное поведение когда в первый раз приходит N элементов, а со второго и третьего раза и далее - начинает приходить N+1
@MariiaNebesnova должна проинвестигировать

**Comment by MariiaNebesnova** [comment]
[3.9.404](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.404)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.409 Back-end v 0.2.27
Win 10 / Chrome Version 111.0.5563.65

Test result - **pass**
See comment in the following work item - https://github.com/jdi-testing/jdn-ai/issues/1079
