### ISSUE TITLE
[NR-12-3] Кэширование возможных промежуточных результатов на разных уровнях

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1081]
В процессе расчёта локаторов для элемента - система пытается посчитать локатор для элементов который находится выше в дереве.
Нужно, что бы если локатор для родительского элемента уже считался - он бы не считался второй раз, а брался из кэша

**Comment by spiridonovfed** [comment]
Changes are merged:
https://github.com/jdi-testing/jdi-qasp-ml/pull/138

**Comment by AlexeyGirin** [comment]
В девелоперской ветке сейчас

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.416 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Test result - **pass**
Locators are generated faster by ~5-10 percent
(e.g.:
709 locators, JDN v 3.9.405 Back-end v 0.2.18 (release version) - 260 seconds, JDN v 3.9.416 Back-end v 0.2.27 - 245seconds;
642 locators, JDN v 3.9.405 Back-end v 0.2.18 (release version) - 220 seconds, JDN v 3.9.416 Back-end v 0.2.27 - 200seconds)
