### ISSUE TITLE
[High] Query parameters are not added to the @Url annotation parameters

### ISSUE THREAD

**Issue by andrei-mikhailovskii** [jdi-testing/jdn-ai#1090]
Steps to reproduce:

1. Open any web page with query parameters
2. Generate page object via JDN plugin using HTML5 library
3. Save created page object with some locators
4. Click Download All button
5. Unarchive downloaded .zip archive and open project vie IDE
6. Open src/main/java/site/MySite.java file and make sure that @Url annotation has a parameter including query parameter from initial web page (from step 1)

Expected result: @Url annotation has a parameter including query parameter from initial web page (from step 1)

Actual result: query parameters are not added to the @Url annotation parameters
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/106632366/222177966-8e8966be-78f1-4f8f-ac75-df6d37e44c1c.png)

JDN v 3.9.405 Back-end v 0.2.18

**Comment by arslanbekova** [comment]
[3.9.409](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.409)
<img width="1920" alt="Screenshot 2023-03-06 at 18 55 44" src="https://user-images.githubusercontent.com/59090607/223424877-465a19a0-c21c-44d8-91c1-663b9b5f1c3c.png">

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.409 Back-end v 0.2.27
Win 10 / Chrome Version 110.0.5481.178

The bug is fixed.
Query parameters are added to the @Url annotation parameters.
![image](https://user-images.githubusercontent.com/106632366/223466956-2f5e470c-d306-4954-b92f-9e7fccee9b93.png)
