### ISSUE TITLE
Сделать покрытие во время редактирования

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1094]
В данный момент во время редактиварония уже существующего ПО - мы просто затемняем панель покрытия и не размещаем на ней блоки элементов.
Это вызывает закономерные вопросы у пользователей.

Причина по которой мы так делаем заключается в том, что состояние страницы - может быть другим т.к. страница может быть не статической.
Однако - насколько эта разница критична - не вполне понятно, поэтому давайте - попробуем сделать покрытие блоками элементов.

При редактировании - система должна проверять - открыта ли страница с которой редактируем, если открыта - размещаем на ней блоки
Если не открыта - открываем и размещаем на ней блоки

Замощение - должно быть полным (если есть такая информация, если нет - сперва распознаём, потом замащиваем)

Если у нас есть локатор, которого на странице нет - просто не одображаем его на странице (возможно нужно придумать статус для локатора, типа глазика?)

**Comment by savinovava** [comment]
На имплементацию в release 3.11

**Comment by SemyonKuznetsov** [comment]
фактически такие локаторы похожи на custom созданный локатор, который не найдет себя на покрытии, надо соотнести эти истории и предложить одинаковое решение для статуса таких локаторов

**Comment by MariiaNebesnova** [comment]
[3.10.439](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.439)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.441 Back-end v 0.2.31
Chrome Version 112.0.5615.50 (Official Build) (64-bit)

Test result - **FAIL**
On some websites, while editing the PO, the elements on the page are not covered by blocks (HTML5 library, both xPath and CSS selector Locators type).
List of websites with this issue:
- https://telescope.epam.com/workplace/
- https://www.docker.com/
- https://habr.com/ru/all/

https://user-images.githubusercontent.com/106632366/231136223-2d97460a-4614-40c1-a07a-67769d7a93db.mp4

**Comment by MariiaNebesnova** [comment]
[3.10.442](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.442)

**Comment by AlexadrK** [comment]
JDN v 3.10.445 Back-end v 0.2.31
Chrome Version 112.0.5615.87 (Official Build) (64-bit)

Test result - **PASS**

https://user-images.githubusercontent.com/21053451/232824374-7d71b163-93df-4f32-81d1-15098441521b.mp4
