### ISSUE TITLE
[Low] Inconsistency in the wording of the message when deleting the locator from the plugin window and from the website one

### ISSUE THREAD

**Issue by andrei-mikhailovskii** [jdi-testing/jdn-ai#1100]
**Summary:** When deleting a locator from website window, the following message is displayed in the plugin window: "1 locators were deleted", which is grammatically incorrect, while when deleting a locator from the plugin window, the message is "The locator was deleted"

**Steps to reproduce:**

1. Generate locators via JDN plugin using any library (Material UI, HTML5, Vuetify)
2. Right-click on the highlighted element in the website window
3. Click Delete

**Expected result:** the following message is displayed in the plugin window: "The locator was deleted"

**Actual result:** the following message is displayed in the plugin window: "1 locators were deleted"
![2023-03-10 13_08_43-Settings](https://user-images.githubusercontent.com/106632366/224312553-a4df3713-c8f8-45de-a849-b398cd1771a5.jpg)

JDN v 3.9.411 Back-end v 0.2.27
Windows 10 (64 bit) / Chrome Version 111.0.5563.65

The bug was found during testing of the [[US-5-6] Добавление оставшихся элементов Vuetify #1062](https://github.com/jdi-testing/jdn-ai/issues/1062)

**Comment by MariiaNebesnova** [comment]
[3.9.423](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.423)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.425 Back-end v 0.2.27
Chrome Version 111.0.5563.111 (Official Build) (64-bit)

The bug is fixed.
![2023-03-23 12_09_12](https://user-images.githubusercontent.com/106632366/227185914-6c03f130-6a3c-462c-9ffe-72120214164a.jpg)
