### ISSUE TITLE
[Low] Vuetify locators generation progress bar does not getting green at the end of generation

### ISSUE THREAD

**Issue by andrei-mikhailovskii** [jdi-testing/jdn-ai#1102]
**Summary:** At the end of locators generation process, progress bar does not getting green in case of Vuetify library (checked on several different websites), while in case of Material UI or HTML5, it does (see attached screenshot)
![2023-03-10 13_51_21-Settings](https://user-images.githubusercontent.com/106632366/224321621-e5fcdcba-6e92-4611-a3ce-c9071a308b78.jpg)

**Steps to reproduce:**

1. Generate locators via JDN plugin using Vuetify library
2. Wait until generation is completed

**Expected result:** progress bar gets green with green tick on the right

**Actual result:** only message about successful generation is displayed, progress bar goes not getting green, green tick on the right is not displayed (see attached screencast)

https://user-images.githubusercontent.com/106632366/224322445-3a28ac20-e5c1-4ac9-aa78-a6c34d2f390c.mp4

JDN v 3.9.411 Back-end v 0.2.27
Windows 10 (64 bit) / Chrome Version 111.0.5563.65

The bug was found during testing of the https://github.com/jdi-testing/jdn-ai/issues/1062

**Comment by MariiaNebesnova** [comment]
[3.9.423](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.423)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.425 Back-end v 0.2.27
Chrome Version 111.0.5563.111 (Official Build) (64-bit)

The bug is fixed.
![2023-03-23 11_22_52-Settings](https://user-images.githubusercontent.com/106632366/227185021-d0cdf50c-bdee-4f77-818f-979f73ea37aa.jpg)
