### ISSUE TITLE
Поправить шаблон для Vuetify экспорта

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1104]
В данный момент - шаблон для экспорта пригоден только для элементов из Material UI и HTML5
Для Vuetify - нужен отдельный шаблон - иначе - работать не будет.
Этот шаблон должна создать Наташа - в рамках задачи https://github.com/jdi-testing/jdi-light/issues/4780
По идее - она сможет этим заняться на следующей неделе (20.03.2023 - 26.03.2023)
Если она сделает и задача https://github.com/jdi-testing/jdn-ai/issues/1062 пройдет тестирование - то можно будет включать их в релиз 3.10

Возможно - потребуется доработка от Фёдора его бэкэнд части.
Раз уж мы в 3.10 релизим бэк - релиз поддержки Vuetify тоже напрашивается

**Comment by MariiaNebesnova** [comment]
Vuetify сможем релизить когда окончательно разберемся с распознванием контента #1082

**Comment by pnatashap** [comment]
```
import com.epam.jdi.light.vuetify.elements.common.*;
import com.epam.jdi.light.vuetify.elements.complex.*;
import com.epam.jdi.light.vuetify.elements.complex.bars.*;
import com.epam.jdi.light.vuetify.elements.complex.breadcrumbs.*;
import com.epam.jdi.light.vuetify.elements.complex.panels.*;
import com.epam.jdi.light.vuetify.elements.complex.radiobuttons.*;
import com.epam.jdi.light.vuetify.elements.complex.stepper.*;
import com.epam.jdi.light.vuetify.elements.complex.tables.*;
import com.epam.jdi.light.vuetify.elements.complex.timelines.*;
import com.epam.jdi.light.vuetify.elements.composite.*;
```

**Comment by MariiaNebesnova** [comment]
upd: templates for all libraries should have a common imports: 
```import com.epam.jdi.light.elements.pageobjects.annotations.locators.*;
import com.epam.jdi.light.elements.composite.*;
import com.epam.jdi.light.ui.html.elements.common.*;
import com.epam.jdi.light.elements.complex.*;
import com.epam.jdi.light.elements.common.*;
import com.epam.jdi.light.elements.complex.dropdown.*;
import com.epam.jdi.light.elements.complex.table.*;
import com.epam.jdi.light.ui.html.elements.complex.*;```

for MUI we add special imports: ```import com.epam.jdi.light.material.elements.displaydata.*;
import com.epam.jdi.light.material.elements.displaydata.table.*;
import com.epam.jdi.light.material.elements.feedback.*;
import com.epam.jdi.light.material.elements.feedback.progress.*;
import com.epam.jdi.light.material.elements.inputs.*;
import com.epam.jdi.light.material.elements.inputs.transferlist.*;
import com.epam.jdi.light.material.elements.layout.*;
import com.epam.jdi.light.material.elements.navigation.*;
import com.epam.jdi.light.material.elements.navigation.steppers.*;
import com.epam.jdi.light.material.elements.surfaces.*;
import com.epam.jdi.light.material.elements.utils.*;```

**Comment by MariiaNebesnova** [comment]
[3.9.418](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.418)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.427 Back-end v 0.2.27

Test result - **pass**

The following libraries are added to page objects classes:

For Vuetify
![2023-03-24 13_48_12-jdi-light-testng-empty-template-main – FloridaCityGasHomePageVUExPath java](https://user-images.githubusercontent.com/106632366/227525840-c895e21d-9d64-420b-a571-ed771ef95900.jpg)

For MUI
![2023-03-24 13_47_56-jdi-light-testng-empty-template-main – FloridaCityGasHomePageMUI java](https://user-images.githubusercontent.com/106632366/227525871-4fd49a3a-7cb6-438d-a88f-78dec544fee5.jpg)

For HTML5
![2023-03-24 13_49_01-jdi-light-testng-empty-template-main – FloridaCityGasHomePage java](https://user-images.githubusercontent.com/106632366/227525912-716854c9-a5a2-4f1d-9a43-66f2346f5b9b.jpg)
