### ISSUE TITLE
Регресс-тест

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#112]
к 17.12
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/65832/SoW+Statement+of+Work#2.6-Success-Criteria

**Comment by pulya-na-vullet** [comment]
[Чек лист регресса.xlsx](https://github.com/jdi-testing/jdn-ai/files/7717020/default.xlsx)
3.0.100
Бэк последней версии. 
Старт 15.12.2021

**Comment by pulya-na-vullet** [comment]
Регрессионный тест план
https://app.qase.io/run/JDI/dashboard/1

**Comment by pulya-na-vullet** [comment]
https://github.com/jdi-testing/jdn-ai/issues/140

**Comment by pulya-na-vullet** [comment]
[JDI-Regress+run+20212F122F15.csv](https://github.com/jdi-testing/jdn-ai/files/7725086/JDI-Regress%2Brun%2B20212F122F15.csv)
Отчет о тестировании
