### ISSUE TITLE
[US-15-1] Improve css selectors

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#1124]
В текущей реализации цсс селекторов мы привязываемся к локатору от робулы который пытаемся конвернтуть в цсс селектор. У этого подхода - есть неприятная особенность. Если робуловский икспас привязывается к тексту - сконвертнуть его в цсс - невозможно, поэтому - нам приходится вместо этого показывать полный цсс селектор от корня, что никому ненравится.
Необходимо переделать эту логику и сразу генерить оптимальный цсс селектор

proposed solutions:
https://github.com/jdi-testing/jdn-ai/issues/732#issuecomment-1479027563

**Comment by AlexeyGirin** [comment]
Решили:
1. find a new tool for creating robust CSS selector
2. Применяем найденную библиотечку ко ВСЕМ локаторам, а не только к тем которые не смогли посчитаться через робулу

**Comment by MariiaNebesnova** [comment]
generation works. need to decide what to do with attribute values with `\3`
![24ff901c-be68-438b-a6d7-a74221275260](https://user-images.githubusercontent.com/82033805/235180989-264929ad-0685-48a2-a305-c7718b58ec2d.jpg)
![ca40730f-7258-4aab-b11f-c5abdf874b79](https://user-images.githubusercontent.com/82033805/235181011-71e4f854-1d60-47ac-9283-5e280e2ba850.jpg)

**Comment by MariiaNebesnova** [comment]
current results of generation, compared with xPath by Robula:
xpath:                    //*[@name='jdi-text']
css-selector-generator:   .main-txt

xpath:                    //*[contains(text(), 'JDI Github')]
css-selector-generator:   [target]

xpath:                    //*[@class='sidebar-menu left']/*[@index='2']/a
css-selector-generator:   .sidebar-menu > [index='\32 '] a

xpath:                    //div/a
css-selector-generator:   .epam-logo a

xpath:                    //*[@index='5']//*[@index='3']/a
css-selector-generator:   .menu-title[index='\35 '] [index='\33 '] a

xpath:                    //*[@id='login-button']
css-selector-generator:   #login-button

xpath:                    //*[@for='name']
css-selector-generator:   [for='name']

**Comment by MariiaNebesnova** [comment]
[3.11.456](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.456)

**Comment by AlexadrK** [comment]
Error when generation PO is started
JDN v 3.11.456 Back-end v 0.2.36
Chrome Version 113.0.5672.93 (Official Build) (64-bit)


https://github.com/jdi-testing/jdn-ai/assets/21053451/3a6910d0-1208-4ecc-b4de-48d125eda2b9

**Comment by AlexadrK** [comment]
JDN v 3.11.461 Back-end v 0.2.36
Chrome Version 113.0.5672.126 (Official Build) (64-bit)

Test result - **PASS**

https://github.com/jdi-testing/jdn-ai/assets/21053451/41ea1ff1-ff82-47a6-abc2-83fb8cb665ba
