### ISSUE TITLE
Fix advanced calculation

### ISSUE THREAD

**Issue by spiridonovfed** [jdi-testing/jdn-ai#1132]
After implementing caching advanced calculation is not working

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.433 Back-end v 0.2.31
Chrome Version 111.0.5563.147 (Official Build) (64-bit)

The bug is fixed. Advanced calculation works.

https://user-images.githubusercontent.com/106632366/228815670-101624c8-fc47-40cf-862e-3d1a99c2d633.mp4
