### ISSUE TITLE
Выключить тултипы из дефолтного набора распознавания Vuetify

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1136]
Сейчас - распознанный тултип приводит к тому, что его область отрисовки (известная ранее как размер элемента) - перекрывает вообще весь экран. Это явно вредит опыту пользователя.
Поэтому - давайте исключим тултип из дефолтного набора элементов которые мы распознаём

**Comment by MariiaNebesnova** [comment]
[Release 3.10.434](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.434)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.434 Back-end v 0.2.18
Chrome Version 111.0.5563.147 (Official Build) (64-bit)

The bug is fixed. Tooltip locators are disabled by default.

https://user-images.githubusercontent.com/106632366/228893465-0068e2e0-06b2-48a9-a8f3-958add562c72.mp4
