### ISSUE TITLE
[US-15-1][US-7-3] Сделать валидацию CSS селектора (любого)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1139]
По следам https://github.com/jdi-testing/jdn-ai/issues/370

Сейчас у нас отсутствует валидация кастомного CSS селектора и при переключении на него - мы просто не даём его редактировать т.к. отсутствует необходимая штука - валидация этого селектора.
Необходимо - заимплементировать валидацию CSS селекторов

()
_____
правила валидации
### Для следующих ситуаций мы сохраняем с иконкой варнинга
По локатору:
1. Пустое значение UC-7-3-4
2. Локатор, по которому не найден элемент US-7-2/US-7-3

### Для следующих ситуаций мы не даём сохранить и показываем ошибку
По имени:
1. Уникальность
![image](https://user-images.githubusercontent.com/53625116/234841845-585c681f-f509-4af7-a865-9b6e8fcef174.png)
campPmoTemplate - class name
2. Запрещенные символы/слова UC-7-3-1 
3. Нельзя оставлять пустым UC-7-3-4

По локатору:
1. Дублирование локатора -- Выделено в отдельную задачу (#1150)
2. Нашлись несколько элементов по введенному локатору UC-7-2-4

**Comment by arslanbekova** [comment]
Все кейсы переключения типа локатора xPath <=> CSS будут обработаны вместе с созданием валидации для CSS
https://github.com/jdi-testing/jdn-ai/issues/1190

**Comment by arslanbekova** [comment]
https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.459

**Comment by AlexeyGirin** [comment]
Fixed.
