### ISSUE TITLE
[US-18-1] Дать пользователю возможность указать атрибут, на основании которого нельзя генерировать локаторы

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#114]
в настройки генерации добавлена вкладка "Attributes", в которой пользователь может внести запрещенный атрибут вручную

<img width="1240" alt="Screenshot 2021-12-07 at 16 23 02" src="https://user-images.githubusercontent.com/89466817/145046476-19850236-6414-4674-9688-842eeddfc645.png">

**Comment by mariia-tokarchuk** [comment]
Идея на будущее.

Реально ли обучить Machine Learning автоматически распознавать автосгенеренные атрибуты и не генерировать Page Object на основании таких атрибутов.
Чтобы пользователь вручную не заходил и настраивал это.

**Comment by mariia-tokarchuk** [comment]
Исходники (пока в черновом виде):
https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(New)?node-id=0%3A1

**Comment by AlexeyGirin** [comment]
Готово. Можно приступать к девелопменту
