### ISSUE TITLE
[US-15-3][US-7-2] Разрешить создание кастомных CSS Selector локаторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1140]
К этой задаче можно будет приступить после выполнения вот этой - https://github.com/jdi-testing/jdn-ai/issues/1139

Сейчас - редактирование CSS селекторов недоступно. Необходимо сделать это возможным с имплементацией той же логики что и для xPath - мы должны позволять создвать и сохранять невалидные селекторы, но должны предупреждать что они невалидны

**Comment by ekaterinazhidkova** [comment]
Task: allow to create the custom CSS Selectors locators 

Description: 
Currently, the CSS Selectors editing is unavailable. Users should be able to create and save CSS Selectors. If the created CSS selector is invalid, the user should be warned. 

Acceptance criteria
1. The user is able to create a CSS Selector 
2. The user is able to save a created CSS Selector 
3. If the created CSS selector is invalid, the warning is displayed  
4. The warning text is:

**Comment by MariiaNebesnova** [comment]
в рамках этой задачи предусмореть кейс генерации css селектора при переключении с xpath на css у кастомного локатора

**Comment by arslanbekova** [comment]
[3.11.461](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.461)

**Comment by AlexeyGirin** [comment]
Fixed.
