### ISSUE TITLE
Система должна запоминать выбор Locator type так же как это делается для Library

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1141]
Система должна запоминать выбор Locator type так же как это делается для Library
Сейчас - даже в рамках одной сессии - выбор на запоминается и сбрасывается на xPath

Кейс:
1. Создать новый ПО, выбрав CSS Selector в качестве типа локатора
2. Начать создание следующего ПО
Наблюдаемое поведение - на форме создания значение в поле Locator type будет xPath, хотя должно быть CSS selector

**Comment by MariiaNebesnova** [comment]
[Release 3.10.435](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.435)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.435 Back-end v 0.2.18
Chrome Version 111.0.5563.147 (Official Build) (64-bit)

The bug is fixed.

https://user-images.githubusercontent.com/106632366/229106745-60295b29-9e19-458b-a58a-dd55627c61b3.mp4
