### ISSUE TITLE
Переход по адресу через редактирования поля URL делает поле плагина полностью белым

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1142]
1. Откройте сайт https://gitlab.com/-/operations/environments
2. Попытайтесь распознать там элементы Vuetify
Ничего не распознается и это - нормально - пусто.
3. В поле URL в браузере вбейте адрес - https://gitlab.com/ и нажмите Enter.
Результат - плагин сломается и станет полностью белым

![image](https://user-images.githubusercontent.com/26869421/228933132-11f84c54-ef28-4413-8070-570fcc8c3970.png)

**Comment by MariiaNebesnova** [comment]
[Release 3.10.435](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.435)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.435 Back-end v 0.2.18
Chrome Version 111.0.5563.147 (Official Build) (64-bit)

The bug is fixed.

https://user-images.githubusercontent.com/106632366/229101380-314c30e4-482d-4ca6-b669-9eab276aa951.mp4
