### ISSUE TITLE
Empty state by ERROR for Locators List

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1144]
Сейчас, если выбрать поиск по Vuetify - на сайте где Vuetify не используется - оно ничего не найдёт. Это резко отличает алгоритмический поиск от ML-ного.

Случай, когда ничего не нашлось - у нас не предусмотрен.

____
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=8422-379755&t=vwToN6WzQAgwmk8f-4)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/111ffcc1-c145-4578-a838-af0e9684bb15)

_Unable to Identify Elements
Unfortunately, we can't identify any elements. Please make sure that the correct library is selected and that general settings are properly configured._

при нажатии на кнопки Close модальное окно просто закроется и пользователь остаётся на пустом РО с возможностью создать кастомный локатор

при нажатии на Open Settings модальное окно и РО в целом закрывается и возвращаем пользователя на шаг назад к преднастройкам данного РО
![image](https://user-images.githubusercontent.com/101407186/235134947-05451f74-22b2-42e0-bd08-7924dc23bb7b.png)

Также на пустом экране локатор листа выводим текст (повторяя РО-лист)
_You can either create a Custom locator or refer to our Onboarding tutorial to understand the JDN features_
Где гиперссылки выделены синим #1890FF и font style: Display Medium
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/14c72259-e6ca-4d64-a731-370b0266b353)

**Comment by SemyonKuznetsov** [comment]
это стандартный вариант, который повторяет Emty state у страницы с РО 
![image](https://user-images.githubusercontent.com/101407186/234827390-f57aea86-c4af-4ffd-bda0-4dcfb5166ebe.png)

даём возможность попробовать ещё раз (ну вдруг) или сразу перейти в настройки, при этом зыкрыв и удалив только что созданный РО
![image](https://user-images.githubusercontent.com/101407186/234827658-3f8aae28-4cf8-4acd-a200-e18db6ed6a97.png)

отличается от предыдущего возможностью закрыть сообщение (у этого компонента есть крестик), чтобы, например создать кастомный локатор
![image](https://user-images.githubusercontent.com/101407186/234829029-6d4a8c92-49e3-4289-a877-3f043fb99d06.png)

**Comment by AlexeyGirin** [comment]
1. Убрать Retry кнопку
2. Поправить вординг - речь идёт об identify elements on the page

**Comment by MariiaNebesnova** [comment]
не применяется к ситуации, когда локаторы нашилсь, но скрыты фильтрами класса или визибилити?

**Comment by AlexeyGirin** [comment]
> не применяется к ситуации, когда локаторы нашилсь, но скрыты фильтрами класса или визибилити?

Относится к ситуации когда фильтр не наложен.

Когда из-за фильтра ничего не показывается - это другая ситуация и там должна быть другая плашка

**Comment by Iogsotot** [comment]
[3.13.536](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.536)

**Comment by AlexeyGirin** [comment]
Done.

**Comment by SemyonKuznetsov** [comment]
Ошибка = нет покрытия = нет локаторов в списке
Условия могут быть разные, для тестов берём вьютифай, который ничего не находит

1. Берём РО через Generate All
У нас пустое покрытие, на плагине показываем модалку 
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/e1dc2392-deb8-49aa-889b-f606f86ea4dd)
а после её закрытия в списке локаторов показываем текст с гиперссылками
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/666464ac-0ccc-4fc3-911b-d250420ea3c2)

2. Берём РО через Empty Page Object 
Если у нас ничего не распозналось или например выбран вьютифай то в целом происходит то же самое что и в пункте 1

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1453
https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.554

**Comment by Lisa5876** [comment]
JDN v 3.13.554 Back-end v 0.2.40
Test result - pass

https://github.com/jdi-testing/jdn-ai/assets/89458651/76fcdc52-d16a-4ea7-960b-5bff7ed17fc6

На сообщении "Unable to Identify Elements" кнопка "Cancel", а не "Close". Будет поправлено в рамках https://github.com/jdi-testing/jdn-ai/issues/1455
