### ISSUE TITLE
Add moving highlight to another element after locator editing

### ISSUE THREAD

**Issue by arslanbekova** [jdi-testing/jdn-ai#1147]
This issue follows from https://github.com/jdi-testing/jdn-ai/issues/370

If during the locator editing user assign a new valid existed page element's xPath, what wasn't recognized within generation, 
we expect that highlight will be moved from old element to new.

If user put new valid locator that leads to the new element on page, that wasn't recognized - warning message "locator leads to the new element" should be shown.

**Comment by arslanbekova** [comment]
[3.10.445](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.445)

**Comment by AlexadrK** [comment]
JDN v 3.10.445 Back-end v 0.2.31
Chrome Version 112.0.5615.87 (Official Build) (64-bit)

Test result - **PASS**
Edit generated locator

https://user-images.githubusercontent.com/21053451/232751531-e91d5e65-b5ac-40c0-af9c-4646da5818ef.mp4

Edit custom locator

https://user-images.githubusercontent.com/21053451/232751618-f1ac0522-7451-41df-9c9c-0454c6ef4217.mp4
