### ISSUE TITLE
[ML] All data bugs for ML in one task

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#115]
Все баги связанные с плохим распознаванием элементов Material UI заводятся в этот баг.
Формат:

- URL сайта
- Скриншот экрана с сгенерированными локаторами
- Участок HTML кода элемента не распознанного ML.
- Номер версии клиента и бекэнда
- Шаги

**Comment by pulya-na-vullet** [comment]
https://marmelab.com/react-admin-crm/#/

![image](https://user-images.githubusercontent.com/61897393/145167156-778d6f88-2426-4b47-a130-1c03c9038f65.png)

<span class="MuiTypography-root jss120 MuiTypography-body1" jdn-hash="0917856568472106117980227215">Wanda Cummerata</span>

JDN v 3.0.94 Back-end v 2021-12-01-14.52.21

Шаги:
Запуск приложения и поиск локаторов [Identify]

**Comment by pulya-na-vullet** [comment]
https://www.dropbox.com/features/share
![image](https://user-images.githubusercontent.com/61897393/145168882-c93ccc9e-85ed-4378-915c-c161e8196c0e.png)
"""<li jdn-hash="5663586431424904914717665143"><b jdn-hash="2682951300424904914525745286">Управление доступом.</b>&nbsp;Отправка файлов в виде вложений электронной почты может поставить под угрозу безопасность ваших данных. Через Dropbox можно отправить ссылку на файл или папку с доступом только для чтения. Дополнительно можно защитить общую ссылку <a href="/ru/features/share/password-protection" jdn-hash="1895337141424904917330034938">паролем</a>, установить срок действия ссылки и отключить скачивание файлов.</li>'''
JDN v 3.0.94 Back-end v 2021-12-01-14.52.21

Шаги:
Запуск приложения и поиск локаторов [Identify]

**Comment by bulgakovmyu** [comment]
> https://marmelab.com/react-admin-crm/#/
> 
> ![image](https://user-images.githubusercontent.com/61897393/145167156-778d6f88-2426-4b47-a130-1c03c9038f65.png)
> 
> Wanda Cummerata
> 
> ![image](https://user-images.githubusercontent.com/61897393/145169419-7b72267a-4779-435f-a4f7-da221a590cf4.png)
> 
> JDN v 3.0.94 Back-end v 2021-12-01-14.52.21
> 
> Шаги: Запуск приложения и поиск локаторов [Identify]

Здесь ошибкой является не то, что что-то не распознается, а скорее наоборот то, что эти ссылки распознаются как  chip (хоть и вероятность там небольшая). Причина в том, что этот объект по сути кастомный класс со ссылкой и типография, а такого модель не умеет хорошо распознавать так как в этом объекте очень много неопределенности и несоответствия стандартным для модели ситуации. Возможно здесь было бы хорошо распознавать это как ссылку, но модель с этим не справляется так как не ожидает такого.
Вывод - это нормальное поведение модели в случае объекта, который она не ожидает.

**Comment by bulgakovmyu** [comment]
> https://www.dropbox.com/features/share ![image](https://user-images.githubusercontent.com/61897393/145168882-c93ccc9e-85ed-4378-915c-c161e8196c0e.png)
> 
> * Управление доступом. Отправка файлов в виде вложений электронной почты может поставить под угрозу безопасность ваших данных. Через Dropbox можно отправить ссылку на файл или папку с доступом только для чтения. Дополнительно можно защитить общую ссылку [паролем](/ru/features/share/password-protection), установить срок действия ссылки и отключить скачивание файлов.
> ![image](https://user-images.githubusercontent.com/61897393/145169308-a6709e15-f455-44e7-9ba7-5134fe48526e.png)
> 
> JDN v 3.0.94 Back-end v 2021-12-01-14.52.21
> 
> Шаги: Запуск приложения и поиск локаторов [Identify]

Здесь html код очень сильно отличается от того, на котором мы учили модель (названия классов и т.п.), поэтому тут в целом модель может вести себя не всегда понятным образом. Может где-то распознать корректно, а где-то совсем нет, но ошибкой по сути такая работа модели не является, так как модель не настроена для работы на таких сайтах.

**Comment by pulya-na-vullet** [comment]
Криминала не нашел закрываю таску
