### ISSUE TITLE
[US-15-3] При создании дубликата - навигировать к существующему локатору

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1150]
При создании дубликата - навигировать к существующему локатору показывая имя или с помощью подсветки
Оригинальная задача - #370
____
Дубликат - локатор который указывает на элемент, на который уже указывает другой локатор
Валидация на дубликат в модальных окнах Отредактировать/Создать выполняется в процессе редактирование инпута
____

1. При редактировании текста выполняется валидация на дубликат, после делаем инпут Error и показываем текст:
`Duplicate locator detected. Please edit or refer to the original locator for further actions.`
, где _**refer to the original locator**_ гиперссылка, выделено с помощью подчеркивания и чуть жирнее (DisplayMedium)

2. при нажатии закрываем модальное окно, 
- если это было создание кастомного локатора, то просто закрываем
- если это было редактирование, то закрываем без сохранения, оставляя локатор в последним сохранённым виде (как при открытии)

3. и переводим пользователя на оригинал дубликата локатора 

[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=8666-398793&t=MY2sl52vmR75Cex4-4)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/8bf19e2e-bd1b-4c4d-9fe6-1ecbbc5ae269)

_____
### Inline editing
дополнительный нотификейшн для задачи #963
[figma notification component](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?type=design&node-id=164767-171350&t=1DIZnPOJoJFLYnJ3-4)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/22fd3291-5f4e-4916-aaa1-d829dc52cebd)

- при нажатии Enter или ЛКМ плагин должен пытаться сохранить редактирование, но из-за дублирования показываем нотификейшн (если уже есть, то заменять его)
- на Esc выполняется выход и отмена редактирования (т.е откат до последнего состояния)
- при нажатии на гиперссылку в уведомлении так же отменяем и закрываем редактирование и выдеяем оригинал дублирования

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/94f27339-6117-419c-9b9a-6b985612a514)

выделенный локатор после нажатия
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/155ed5a8-6b12-417f-a54d-e96db4589a12)

**Comment by AlexadrK** [comment]
JDN v 3.10.445 Back-end v 0.2.31
Chrome Version 112.0.5615.87 (Official Build) (64-bit)

Test result - **PASS**

https://user-images.githubusercontent.com/21053451/232788446-41a61aa5-b727-406c-b170-0d6535623d90.mp4

**Comment by SemyonKuznetsov** [comment]
https://github.com/jdi-testing/jdn-ai/issues/963

учесть, что в этой задаче есть нотификейшн для дубликата

**Comment by SemyonKuznetsov** [comment]
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/918c6cde-6b3b-4459-97f9-9ccc43eab3a7)

**Comment by arslanbekova** [comment]
[3.13.510](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.510)

**Comment by AlexadrK** [comment]
JDN v 3.13.516 Back-end v 0.2.40
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS

https://github.com/jdi-testing/jdn-ai/assets/21053451/0e3b1f10-6252-4a2c-afef-f447dc273457
