### ISSUE TITLE
Дописать инструкцию для локального разворота на случай, если произошло обновление версии бэкенда

### ISSUE THREAD

**Issue by spiridonovfed** [jdi-testing/jdn-ai#1153]

**Comment by spiridonovfed** [comment]
README.me is updated with updated instructions

**Comment by andrei-mikhailovskii** [comment]
Test result - **PASS**

README.md is updated
![2023-04-07 13_09_37-Update README MD with changed local deploy instructions by spiridonovfed · Pull ](https://user-images.githubusercontent.com/106632366/230599313-8ea797c3-d3bb-45d8-b51f-eb9ae4a77e5f.jpg)
![2023-04-07 13_10_11-Settings](https://user-images.githubusercontent.com/106632366/230599372-6ab17040-8d73-47c6-95a8-d2de487554ca.jpg)
