### ISSUE TITLE
[Low] Tooltips are enabled by default in Vuetify page objects

### ISSUE THREAD

**Issue by andrei-mikhailovskii** [jdi-testing/jdn-ai#1155]
**Steps to reproduce:**

1. Go to https://vuetifyjs.com/en/components/checkboxes/
2. Generate PO using Vuetify library

**Expected result:** Tooltip is disabled in filter by default

**Actual result:** Tooltip is enabled in filter by default

https://user-images.githubusercontent.com/106632366/230353100-116febc1-0438-4114-8d21-b103e69de149.mp4

**Comment by MariiaNebesnova** [comment]
please, see the latest plugin version [3.10.438](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.438)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.438 Back-end v 0.2.31
Chrome Version 112.0.5615.50 (Official Build) (64-bit)

The bug is fixed.

https://user-images.githubusercontent.com/106632366/230592399-6a380d62-ae01-40a2-a109-5c62601bf8d2.mp4
