### ISSUE TITLE
Проверять минимальную версию бэка и предлагать инструкцию по установке бэка если версия бэка старая

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1159]
В данный момент - фронт когда ищет бэк - не проверяет его версию. Просто цепляется если находит локально или облачно. Если не находит - показывает инструкцию по установке бэка.

Необходимо добавить в эту логику проверку на минимальную версию бэка. 

Общий алгоритм должен выглядеть так:
1. Ищем локальный или облачный бэк
2. Если нашёлся локальный - проверяем версию.
2.1 Если версия ниже разрешённой - ищем облачный бэк
3. Если облачный не нашёлся и версия локального ниже разрешённой (таблица минимальных версий тут - https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/69271564/FAQ#Version-compatibility-list) - показываем инструкцию по установке бэка

ДоД:
1. При установленном бэке старой версии и недоступности облачного - система должна показывать инструкцию по установке бэка.

**Comment by MariiaNebesnova** [comment]
[3.10.441](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.441)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.441

Test result - **PASS**
When an old version of backend is installed, and cloud one is not available, the plugin shows "Step 2 Server setup"

Old version of backend is installed:
![2023-04-11 17_22_40-Settings](https://user-images.githubusercontent.com/106632366/231415664-1c40761a-3ae8-4986-a76d-e78f5dea9feb.jpg)

The plugin shows "Step 2 Server setup":
![2023-04-11 17_22_57-Settings](https://user-images.githubusercontent.com/106632366/231415837-e33c4f01-d490-4e20-bdb5-1600a55877df.jpg)
