### ISSUE TITLE
[Medium] Нет контекстнго меню при клике ПКМ на локатор в окне покрытия

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1161]
1. Открыть сайт (как пример https://www.docker.com/)
2. Распознать локаторы
3. Кликнуть ПКМ на локаторе в окне покрытия
Результат - контекстное меню не выводится, в консоли браузера ошибки
![image](https://user-images.githubusercontent.com/21053451/230908223-9e3ae69e-a488-461f-b9da-7b0f2c0d9fd2.png)

**Comment by MariiaNebesnova** [comment]
мы не поддерживаем инкогнито мод https://github.com/jdi-testing/jdn-ai/issues/915
