### ISSUE TITLE
[Medium] Текстовое поле для кастомного локатора уходит за край экрана

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1165]
Шаги для воспроизведения:

1. Открыть плагин в левой или правой части браузера
2. Кликнуть на кнопку '+ Custom locator'
3. Уменьшить размер окна плагина

AR: часть тестовоо поля для локатора скрывается за пределами окна плагина
ER: текстовое поле изменяет размер как и dropdown 

![image](https://user-images.githubusercontent.com/21053451/231162105-a46cc77d-c8d8-4a30-bee1-3aaa4549d7a3.png)

**Comment by arslanbekova** [comment]
[3.10.445](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.445)

**Comment by AlexadrK** [comment]
JDN v 3.10.445 Back-end v 0.2.31
Chrome Version 112.0.5615.50 (Official Build) (64-bit)

The bug is fixed.


https://user-images.githubusercontent.com/21053451/231803266-c9bea92b-ce1a-4bf7-a2a3-38e81b754d21.mp4
