### ISSUE TITLE
[Medium] Vuetify locators are not unique on some websites

### ISSUE THREAD

**Issue by andrei-mikhailovskii** [jdi-testing/jdn-ai#1171]
Vuetify locators are not unique on some websites and plugin does not highlight them as non-unique. They are highlighted as "X elements were found with this locator" only after clicking "Edit Page Object" button of the saved page object (see attached screencast).

**Steps to reproduce:**

1. Open https://travel.gatwickairport.com/ or https://www.floridacitygas.com/
2. Generate PO using Vuetify library
3. Select some locators (or just click Select All checkbox) and Save PO
4. Click three dots button on the right of the saved PO and click "Edit Page Object" button

**Expected result:** elements on the webpage are highlighted, locators are not marked as non-unique if they have not been changed since the generation of them, user is able to unselect checkbox of any locator

**Actual result:** elements on the webpage are highlighted but some locators are marked as non-unique, user is NOT able to unselect checkbox of these locators

https://user-images.githubusercontent.com/106632366/231510798-bdedc3be-49ea-440c-bb99-2e96aebc5c7f.mp4

The bug was found during testing of the following work item: [Сделать покрытие во время редактирования #1094](https://github.com/jdi-testing/jdn-ai/issues/1094)

JDN v 3.10.442 Back-end v 0.2.31
Chrome Version 112.0.5615.50 (Official Build) (64-bit)

**Comment by AlexeyGirin** [comment]
Проблема так же легко воспроиводится на тестовой страничке для MaterialUI
https://jdi-testing.github.io/jdi-light/material/buttons
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/318dbdeb-96ef-4dc3-9fb7-1bebf45207c4)

**Comment by spiridonovfed** [comment]
Fixed in dev version:
https://github.com/jdi-testing/jdn-ai/issues/1171

**Comment by AlexadrK** [comment]
JDN v 3.12.492 Back-end v 0.2.39
Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS

https://github.com/jdi-testing/jdn-ai/assets/21053451/14e4a9a6-6b06-4179-9ade-c4e9aa605a24
