### ISSUE TITLE
Copy для контекстного меню на покрытии

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1177]
продублировать функционал для контекстного меню на покрытии

[figma example](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=8607-447744&t=J8hmaI1DmtdRGBut-4)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/dc49d478-c19f-4b47-a1af-e7f523e4419a)

**Comment by arslanbekova** [comment]
[3.12.491](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.491)

**Comment by AlexadrK** [comment]
JDN v 3.12.492 Back-end v 0.2.39
Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS
![plugin window](https://github.com/jdi-testing/jdn-ai/assets/21053451/763f035d-5074-4161-955b-d66d6880bbf6)
![browser window](https://github.com/jdi-testing/jdn-ai/assets/21053451/6869f284-a43e-4511-a428-58b57a8602fc)
