### ISSUE TITLE
Последний локатор считается ОЧЕНЬ долго

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1183]
1. Зайдите на https://www.apetito-shop.de/ (грузится очень долго - нужно подождать)
2. Запустите распознавание (HTML5, CSS Selector).

Наблюдаем:
Один их локаторов никак не может просчитаться
Вконце концов - на клиенте он падает с сетевой ошибкой, но похоже - на этом всё не заканчивается т.к. что-то продолжается и сеть на компе деградирует в ноль

Ожидаем:
Что все локаторы просчитаются

![image](https://user-images.githubusercontent.com/26869421/233070489-7118143c-b9f0-42a8-bdc1-8014ff514965.png)
![image](https://user-images.githubusercontent.com/26869421/233070865-0ed7d908-373b-4d51-914f-f98da420488e.png)

![image](https://user-images.githubusercontent.com/26869421/233070106-19f11f8a-f770-4c8b-bc7f-2f8e6924f594.png)

![image](https://user-images.githubusercontent.com/26869421/233083075-e1003607-ae44-4acc-89d0-ad0b46f4d976.png)

**Comment by spiridonovfed** [comment]
Fixed with https://github.com/jdi-testing/jdi-qasp-ml/pull/146

**Comment by AlexadrK** [comment]
JDN v 3.11.455 Back-end v 0.2.36
Chrome Version 112.0.5615.138 (Official Build) (64-bit)

Test result - PASS
