### ISSUE TITLE
Нет тултипа с локаторами в окне покрытия при клике на лейбл и по ховеру на элемент

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1184]
Шаги для воспроизведения:

1. Запустить генерацию ПО
2. Навести курсор на на распознанный элемент в коне покрытия на 2 секунды
3. Кликнуть на лейбл

AR: нет тутлтипа с локаторами
ER: показывает тултип с локаторами

**Comment by AlexadrK** [comment]
Дополнение к воспроизведению ошибки

1. Запустить генерацию ПО
2. Сохранить ПО
3. Изменить сохранённый ПО
4. Навести курсор на на распознанный элемент в окне покрытия на 2 секунды
6. Кликнуть на лейбл
AR: нет тутлтипа с локаторами
ER: показывает тултип с локаторами

**Comment by MariiaNebesnova** [comment]
[Release 3.11.446](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.446)

**Comment by AlexadrK** [comment]
JDN v 3.11.446 Back-end v 0.2.31
Chrome Version 112.0.5615.50 (Official Build) (64-bit)

The bug is fixed.

https://user-images.githubusercontent.com/21053451/233333609-6a50717f-b8e8-4d2f-8fa5-dfb34502bffa.mp4
