### ISSUE TITLE
Невозможно создать кастомный элемент - система ругается что он уже есть (а его нет)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1188]
1. Откройте и распознайте HTML5 элементы на странице - https://www.google.com/
2. Удалите один из элементов (в моём случае - это текстовое поле с именем q)
![image](https://user-images.githubusercontent.com/26869421/233316852-e34127d5-005a-4f5b-bc02-b01738776c8b.png)
(блок покрытия пропадёт - ок)
3. Откройте удалённый локатор и внесите изменения в xPath что бы сделать его невалидным и несуществующим на страничке (что бы уж наверняка - я просто добавил к нему единичку)
![image](https://user-images.githubusercontent.com/26869421/233317312-54605e43-79f8-4811-a0db-74a236223917.png)
4. Нажмите на кнопку +CustomLocator и создайте локатор - копия того что вы удалили - xPath нужно взять у удалённого
Наблюдаем: Система не позволяет создать элемент - говорит что он уже есть на страничке, что очевидно не так.
![image](https://user-images.githubusercontent.com/26869421/233318348-62d9dd5d-a492-4007-ab07-0cb1e1e8f547.png)

Ожидаем: Система позволяет создать элемент и он появляется на панели покрытия (кстати - сейчас - не появляется)

**Comment by MariiaNebesnova** [comment]
[Release 3.11.447](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.447)

**Comment by AlexeyGirin** [comment]
Fixed.
