### ISSUE TITLE
Система почему-то ругается на невалидный xPath (и он действительн невалидный), хотя я переключил локатор в CSS Selector (который валиден)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1189]
1. Распознайте элементы HTML5 на страничке https://www.google.com/
2. Откройте на редактирование любой элемент (я взял самый первый в списке) и делайте его xPath локатор невалидным (что бы был мессадж об этом под полем редактивания).
3. Ловким движением руки - переключите тип локатора в CSS Selector (он валиден и вообще - его нельзя редактировать сейчас)
4. Нажмите ОК кнопку что бы сохранить изменения
Наблюдаем:
Система удалила блок покрытия и проставила этому локатору иконку невалидности в списке локаторов
![image](https://user-images.githubusercontent.com/26869421/233330982-b81dc223-00f6-4a94-9768-03031bdd91db.png)

Ожидаем:
Система сохранит локатор и будет считать его нормальным. Блок на покрытии - тоже будет норм.

**Comment by arslanbekova** [comment]
[3.11.449](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.449)

**Comment by AlexeyGirin** [comment]
Fixed.
