### ISSUE TITLE
Система оставляет старое значение CSS локатора при переключении в xPath и при это - считает валидным (позволяет сохранить)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1190]
1. Распознайте элементы HTML5 на страничке https://www.google.com/
2. Откройте любой локатор и переключите тип в CSS, сохраните
3. Откройте тот же локатор опять и переключите обратно в xPath

Наблюдаем:
Система оставляет значение CSS локатора в поле и позволяет сохранить его.

Ожидаем:
Система подставляет последнее значение xPath локатора которое там было (если это невозможно - нужно хотя бы делать поле по умолчанию пустым - хотя это и глупо т.к. пользователь лишён возможностей узнать xPath локатор - мы не даём ему никаких возможностей для этого).

Более подробное описание логики:
1. Пользователь открывает локатор (css или xPath) который ВАЛИДЕН (у него нет иконки невалидности на панели локаторов)
Переключение на css или xPath должно работать корректно
Например: xPath (//*[@class='dRYYxd']//div[4]) ==> CSS (.dRYYxd div:nth-of-type(4))

2. Пользователь открывает локатор (css или xPath) который ВАЛИДЕН (у него нет иконки невалидности на панели локаторов). Вносит невалидные изменения которые портят локатор (появляется надпись - The locator was not found on the page.) но НЕ сохраняет изменения и решает поменять тип на другой.
Переключение на css или xPath должно работать корректно, для конвертации должно использоваться значение которое было в локаторе на момент открытия формы редактирования
Например: на момент отрытия в локаторе xPath (//*[@class='dRYYxd']//div[4]) ==> вносит невалидные изменения xPath (//*[@class='dRYYxd']/ФЫВфывФЫЦВ/ФЫВАВdiv[4]) ==> решает переключить на CSS ==> CSS (.dRYYxd div:nth-of-type(4))

3. Пользователь открывает локатор (css или xPath) который ВАЛИДЕН (у него нет иконки невалидности на панели локаторов). Вносит ВАЛИДНЫЕ изменения которые НЕ портят локатор (локатор начинает указывать на другой элемент) но НЕ сохраняет изменения и решает поменять тип на другой.
Переключение на css или xPath должно работать корректно, для конвертации должно использоваться значение которое было в форме на момент открытия окна редактирования
Например: на момент отрытия в локаторе xPath (//*[@class='dRYYxd']//div[4]) ==> вносит валидные изменения ==> xPath (//*[@class='gb_e']) ==> решает переключить на CSS ==> CSS (.dRYYxd div:nth-of-type(4))

4. Пользователь открывает локатор (css или xPath) который НЕ валиден (у него горит иконка невалидности на панели локаторов)
Переключение на css или xPath должно давать пустой результат в поле локатора.
Например: xPath (/фыва/*[@claФЫВфывss='фdывафываRYYxd']//div[4]) ==> CSS ( <тут пусто>)

**Comment by arslanbekova** [comment]
[3.11.449](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.449)

**Comment by AlexeyGirin** [comment]
Done.
