### ISSUE TITLE
Изменение локатора - не приводит к появлению иконки что локатор был отредактирован

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1191]
1. Распознайте элементы HTML5 на страничке https://www.google.com/
2. Откройте любой локатор на редактирование и измените что-нить
Наблюдаемое поведение:
Иконка что элемент был изменён - не появляется
(а иногда - появляется, но закономерность мне не получилось уловить)

**Comment by MariiaNebesnova** [comment]
иконка successfully edited появляется только в одном случае - если отредактировал икспас на новый валидный, и ведет он на тот же самый элемент
