### ISSUE TITLE
[Minor] Закрытие плагина во время редактиварония локатора - оставляет за собой серое покрытие которое блокирует доступ к сайту

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1192]
1. Распознайте элементы HTML5 на страничке https://www.google.com/
2. Откройте любой (я взял первый в списке) локатор на редактирование
3. Закройте плагин случайным нажатием на кнопку F12

Наблюдаем - серая пелена покрывает сайт и не даёт им пользоваться - нужно перегружать
![image](https://user-images.githubusercontent.com/26869421/233341002-feec28eb-98e6-487b-8842-ae22216ac2fb.png)

Ожидаем - по закрытию - плагин бы предварительно пелену ликвидировал

**Comment by arslanbekova** [comment]
[3.12.484](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.484)

**Comment by AlexeyGirin** [comment]
Fixed.
