### ISSUE TITLE
Инвестигировать страницу гугл поиска - а зачем там по две одинаковые кнопки?

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1193]
На сессии фидбэка Артём удивился тому, что несмотря на то, что система распознала элемент на страничке (https://www.google.com/) и дала ему имя "btnI", но в то же время - локатор привязался не к имени, а к атрибуту data-ved (data-ved='0ahUKEwiR-e6zpbj-AhX4T6QEHX-9Br0Q19QECBI'])
Я полез в код странички.
Там действительно - есть ДВА элемента у которых имя - name="btnI"
```
1. <input class="RNmpXc" value="Мне повезёт!" aria-label="Мне повезёт!" name="btnI" type="submit" jsaction="trigger.kWlxhc" data-ved="0ahUKEwiR-e6zpbj-AhX4T6QEHX-9Br0Q19QECAo">
2. <input class="RNmpXc" value="Мне повезёт!" aria-label="Мне повезёт!" name="btnI" type="submit" jsaction="trigger.kWlxhc" data-ved="0ahUKEwiR-e6zpbj-AhX4T6QEHX-9Br0Q19QECBI">
```

И действительно - они различаются только значением атрибута data-ved

При этом - второй элемент на страничке не виден (при клике на локатор - выделения не происходит - видимо этот элемент скрытый)
![image](https://user-images.githubusercontent.com/26869421/233351534-9d465a5c-3f6d-46fa-a7c7-0c86dab5a6d3.png)

Необходимо понять - зачем этот элемент находится в доме и возможно - такие элементы нам совсем не нужны (моя теория - это типа какой-то shadow DOM который мы не поддерживаем, может такое быть?)

[Yesterday 21:07] Artem Rozumenko
Привет 
но при этом visible только одна - и да если делать по коду страницы без контекста, то штука права, а если по контексту, то нет )

Под контекстом имеется ввиду visibility?

**Comment by AlexeyGirin** [comment]
Возможность использовать рантайм атрибуты для адресации элемента - например Visible, Clickable и Enabled (ну и там ещё другие)

**Comment by MariiaNebesnova** [comment]
потребуется доработка робулы и генераторов, чтобы возвращался неуникальный локатор, но со свойством invisible.
по этому же свойству мы добавляем флаг в значение локатора

**Comment by RomanIovlev** [comment]
В JDI
@UI('['value="Мне повезёт!"])
public  imLucky;
найдет только один элемент - видимый
ничего дополнительного делать не надо

**Comment by savinovava** [comment]
Инвестигация завершена.

**Comment by AlexeyGirin** [comment]
Эта задача будет выполнена когда мы выполним - https://github.com/jdi-testing/jdn-ai/issues/1287
