### ISSUE TITLE
Работа с иконками-статусами локаторов

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1199]
![image](https://user-images.githubusercontent.com/101407186/233982817-231cd8cd-9b13-4471-9cad-d5512449d391.png)

в каких случаях появляется:
после редактирование или создания если,
1. Локатор не был найден на странице
2. Пустое значение
3. Любая строка/символы/слова
4. Новый нераспознанный раннее элемент

![image](https://user-images.githubusercontent.com/101407186/234007433-d22366de-d5b6-43bf-a2f8-2e5c09eaa52e.png)
такая появляется, если пользователь условно "оптимизировал" локатор без ошибок валидации, найдя соответсвующий элемент и тд

**Comment by AlexeyGirin** [comment]
Done.
