### ISSUE TITLE
[US-11-1] Доработать работу скрола. При выборе локатора срабатывает скрол в не зависимости видим мы локатор или нет.

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#120]
JDN v 3.0.93
Back-end v 2021-11-26-14.32.52

1. Открываем любой сайт
2. Открываем плагин
3. Нажимаем [Identify]
4. В списке локаторов выбираем локатор который виден на странице (не находится вне видимости)
ОР:
Скрол не произойдет
ФР:
Срабатывает скрол

**Comment by savinovava** [comment]
Connected bug: https://github.com/jdi-testing/jdn-ai/issues/122

**Comment by MariiaNebesnova** [comment]
3.0.99

**Comment by MariiaNebesnova** [comment]
fe - 1 pt

**Comment by pulya-na-vullet** [comment]
Ретест бага произведен
JDN v 3.0.99
Back-end v 2021-11-26-14.32.52
Баг не воспроизводится.

Остался вопрос:
Корректное ли поведение работы скрола? при отмене чекбокса в locator list пользователя скролит на отмененный локатор.

**Comment by mariia-tokarchuk** [comment]
1) При отмене чекбокса - скролл не воспроизводить.
2) При выделении группы локаторов скролл не воспроизводить.

**Comment by MariiaNebesnova** [comment]
3.0.100

**Comment by pulya-na-vullet** [comment]
JDN v 3.0.100
Back-end v 2021-11-26-14.32.52
Chrome
https://jdi-testing.github.io/jdi-light/complex-table.html

Баг не воспроизводится
