### ISSUE TITLE
Удалить иконку "successfully edited"

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1201]
![image](https://user-images.githubusercontent.com/101407186/234274457-4f08a9d0-3b7e-4dad-90d9-5be3ff89d353.png)

решили убрать иконку, потому что она не несёт особого функционала и ни о чём не сообщает пользователю

**Comment by arslanbekova** [comment]
[3.11.449](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.449)

**Comment by AlexeyGirin** [comment]
Fixed.
