### ISSUE TITLE
[Medium] Создание некорректного локатора, а потом исправление на корректный всё равно вызывает варнинг, что "The locator leads to the new element."

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1204]
1. Распознайте элементы HTML5 на страничке https://www.google.com/
2. Нажмите +Custom locator и добавьте локатор который не является корректным (и не указывает на элемент)
![image](https://user-images.githubusercontent.com/26869421/234686325-462dee50-958b-4ee0-ba7b-61d829f41b58.png)
3. Откройте этот локатор на редактирование и введите корректный локатор (в моём случае это был полный икспас для лэйбла Настройки в правом нижнем углу - /html/body/div[1]/div[5]/div[2]/div[3]/span/span/g-popup/div[1]/div)

Наблюдаем: Система показывает варнинг, что The locator leads to the new element. Это странно т.к. ДО этого - ни на какой элемент этот локатор не указывал. Ну и при сохранении - этот варнинг остаётся
![image](https://user-images.githubusercontent.com/26869421/234687054-51f01682-6d08-46a4-b040-2ea6450d5be6.png)

Ожидаемое поведение: Система ничего не сообщает и позволяет всё нормально сохранить

**Comment by MariiaNebesnova** [comment]
[Release 3.11.453](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.453)

**Comment by AlexeyGirin** [comment]
Fixed.
