### ISSUE TITLE
[High] Система не позволяет создать больше одного кастомного локатора если последний кастомный был некорректным

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1205]
1. Распознайте элементы HTML5 на страничке https://www.google.com/
2. Нажмите +Custom locator и добавьте локатор который не является корректным (и не указывает на элемент)
![image](https://user-images.githubusercontent.com/26869421/234687950-8003cc5f-3d0a-4fd4-ba7d-f44e57920bf2.png)

Наблюдаем: Начиная с этого момента попытки создать ещё один локатор будут заканчиваться ничем. Новые локаторы появляться в списке локаторов не будут

Ожидаемое поведение: Локаторый создаются без проблем, даже если они не валидны

**Comment by arslanbekova** [comment]
[3.11.451](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.451)

**Comment by AlexeyGirin** [comment]
Fixed.
