### ISSUE TITLE
[Critical] Попытка поискать свежесозданный кастомный локатор (корректный) вызывает падение плагина в белый экран

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1206]
1. Распознайте элементы HTML5 на страничке https://www.google.com/
2. Нажмите +Custom locator и добавьте локатор который является корректным (в моём случае он казывал на лэйбл Настройки с икспасом - /html/body/div[1]/div[5]/div[2]/div[3]/span/span/g-popup/div[1]/div)
![image](https://user-images.githubusercontent.com/26869421/234689319-78f12e74-0756-4dfa-99d1-f698433b5f4b.png)
3. Попробуйте начать искать этот локатор в поиске

Наблюдаем: Система падает в белый экран
![image](https://user-images.githubusercontent.com/26869421/234689070-8a68b149-57b8-4a0b-bd8c-b6e47980b351.png)

Ожидаем: Поиск работает как надо

**Comment by arslanbekova** [comment]
[3.11.451](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.451)

**Comment by AlexeyGirin** [comment]
Fixed.
