### ISSUE TITLE
[US-7-2] The name of a locator must be changed according to block type

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#121]
JDN v 3.0.93
Back-end v 2021-11-26-14.32.52

При изменении типа локатора должно также меняться и наименование локатора

_как сейчас_
![image](https://user-images.githubusercontent.com/53625116/145375281-6a54430b-1252-4b7c-91cf-bb218095b838.png)
при смене типа блока
![image](https://user-images.githubusercontent.com/53625116/145375347-8c2cbdf7-469c-47ff-ab86-3d80e8983d23.png)

имя измениться после нажатия кнопки "Save"

_как должно быть_
1. Имя локатора меняется в соответствие с типом
2. В локатор листе при сохранении отображаются последние введённые данные

https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12877879/US-7-2+User+can+edit+locators+manually#UC-7-2-2-User-edit-Block-Type

Также возможен следующий UC:
1. Пользователь открывает edit-диалог
2. Изменяет Name локатора
3. Изменяет Type
В этом случае, имя локатора не меняется (поведение сохраняется в рамках одной сесии - одного открытого диалога)

**Comment by MariiaNebesnova** [comment]
сейчас меняется после нажатия Save. добавить, чтобы менялось сразу после смены типа, до нажатия Save

**Comment by MariiaNebesnova** [comment]
1pt - fe

**Comment by IoffeM** [comment]
not a bug

**Comment by AlexeyGirin** [comment]
Не баг, а фича для имплементации

**Comment by MariiaNebesnova** [comment]
[3.3.286](https://github.com/jdi-testing/jdn-ai/releases/tag/3.3.286)
