### ISSUE TITLE
[Minor] Дабл клик не только должен добавлять элемент в ПО, но и удалять оттуда, если он там есть

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1214]
Сейчас при дабл клике на элемент на панели покрытия - он добавляется в ПО. Это правильно.
Но если даблкликнуть на уже добавленный - ничего не происходит.
Необходимо что бы при даблклике на уже добавленный элемент - он исключался из ПО

**Comment by arslanbekova** [comment]
[3.12.478](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.478)

**Comment by AlexadrK** [comment]
JDN v 3.12.479 Back-end v 0.2.37
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

Test result - PASS

https://github.com/jdi-testing/jdn-ai/assets/21053451/f3293eae-caa1-4e9e-9add-6b8b933decb0
