### ISSUE TITLE
Нет CSS локатора при переключении с xPath на CSS если перед этим изменить xPath на невалидный.

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1217]
**Шаги воспроизведения**

1. Запустить генерацию ПО
2. Изменить для распознанного элемента xPath на невалидный и сохранить
3. Изменить для этого же элемента xPath на CSS
**AR** Для CSS нет распознанного локтора
**ER** При выборе SCC в поле с локатором подставляется сгенерированный CSS
 

https://user-images.githubusercontent.com/21053451/235705161-238a3223-66ab-4d25-95da-17906056127f.mp4

**Comment by arslanbekova** [comment]
Это ожидаемое поведение плагина, все возможные кейсы описаны тут
https://github.com/jdi-testing/jdn-ai/issues/1190
