### ISSUE TITLE
Сломан значок Return на окне покрытия

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1219]
Шаги воспроизведения

1. Запустить генерацию ПО
2. Во время генерации поставить на паузу расчёт локатора
3. На окне покрытия вызвать контесктное меню для локтора на паузе

AR Значёк Retгrn сломан в контекстном меню на окне покрытия
ER Значёк Retгrnтакой же как в окне плагина

![Return icon](https://user-images.githubusercontent.com/21053451/235922339-fda80130-7a6a-4021-8b93-a404338c0d9a.png)

**Comment by MariiaNebesnova** [comment]
[3.11.457](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.457)

**Comment by AlexadrK** [comment]
JDN v 3.11.457 Back-end v 0.2.36
Chrome Version 113.0.5672.93 (Official Build) (64-bit)
Test result - PASS

![return button is ok](https://github.com/jdi-testing/jdn-ai/assets/21053451/e7009298-97d9-4afd-a1ea-2ad945eb20e7)
