### ISSUE TITLE
[3pt][US-11-1] При клике на объект на странице не открывается соответствущая секция

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#122]
_как сейчас_
1. Выделила 1 объект - секция открылась
2. Свернула секцию
![image](https://user-images.githubusercontent.com/53625116/145421163-28afa7e5-45ae-413c-983f-7f79f7d7c04c.png)
3. Кликаю левой кнопкой мыши на объект на странице - секция не открывается 
![image](https://user-images.githubusercontent.com/53625116/145421606-ec5201d4-f34e-4dbf-9ab8-82efda2ced68.png)
_как должно быть_
Секция "Generated" открылась и фокус в списке на активном локаторе

**Comment by MariiaNebesnova** [comment]
2pt - fe

**Comment by DaryaGurtovenko** [comment]
1 pt - qa

**Comment by IoffeM** [comment]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

is not reproducible anymore
