### ISSUE TITLE
Update empty state for РО's list

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1220]
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/3aa6edbc-e518-4ce9-8b66-7e6669c718e0)

[figma](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?type=design&node-id=164053-168031&t=R4YMd14rO6gA6DcS-4)

Обновления:
- Open the desired page -> Open a needed web-page
- the "+ Page object" button -> the + Page Object button, где название кнопки становится гиперссылкой -- выделено #1890FF и font style: Display Medium (На кнопке тоже надо сделать Object с большой буквы)
- Так же в конце каждого предложения (из-за третьего предложения) надо добавить точку
- Основной шрифт 000000 65%

**Comment by AlexadrK** [comment]
JDN v 3.13.524 Back-end v 0.2.40
Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS

![empty state for РО's list](https://github.com/jdi-testing/jdn-ai/assets/21053451/ceabf98d-1600-4e47-8788-cca2efe7a35b)
