### ISSUE TITLE
Порядок элементов в панели локаторов должен соответствовать порядку элементов на панели покрытия

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1224]
Сейчас порядок локаторов в панели локаторов - фактически случаен, что вызывает недоумение у пользователей. 
Хочется что бы находящиеся рядом локаторы на панели покрытия - находились бы рядом на панели локаторов

**Comment by savinovava** [comment]
https://github.com/jdi-testing/jdn-ai/issues/1063
