### ISSUE TITLE
[High] Error when generation PO is started

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1226]
JDN v 3.11.456 Back-end v 0.2.36
Chrome Version 113.0.5672.93 (Official Build) (64-bit)

Steps to reproduce:

1. Open habr.com
2. Open JDN plugin and the plugin's console
3. Start PO generation

AR Error in console, PO not generated
ER No error PO successfully generated

Video example

https://github.com/jdi-testing/jdn-ai/assets/21053451/c0cde520-b5bd-48f6-bd35-10939fa82f17

**Comment by MariiaNebesnova** [comment]
[3.11.460](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.460)

**Comment by AlexadrK** [comment]
JDN v 3.11.461 Back-end v 0.2.36
Chrome Version 113.0.5672.126 (Official Build) (64-bit)

The bug is fixed.

https://github.com/jdi-testing/jdn-ai/assets/21053451/f4780507-fe35-4e45-883e-c058f29ec28a
