### ISSUE TITLE
Добавить два пункта в меню копирования (панель плагина + панель покрытия)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1228]
**Речь идёт про ОБА контекстных меню!**
В данный момент наше меню копирования локаторов состоит из 5 элементов:
xPath
xPath + FindBy
xPath + JDI Annotation
CSS Selector
Full code

Необходимо добавить ещё два пункта:
xPath
xPath + FindBy
xPath + JDI Annotation
CSS Selector
CSS Selector + FindBy
CSS Selector+ JDI Annotation
Full code

Кроме того, необходимо продумать вариант динамического расчёта оптимального xPath локатора.
Может так получиться, что в каких то случаях (например - когда ПО у нас создаётся с CSS Selectors по умолчанию) расчинанных оптимальных xPath не будет. А пользователь - полезет их копировать всё равно. 
Если в случае с редактированием локатора и переключением его с CSS на xPath - всё понятно (ну там - тупо дизаблим контролы пока этот конкретный локатор не просчитается) то в случае с меню копирования - нам непонятно как делать.
Сразу показывать крутящийся спиннер и не давать копировать пока он не докрутиться?
А в какой момент запускать расчёт? В момент селекта локатора? В момент когда пользователь полез в меню?
Или показывать крутящийся спиннер и давать нажать, но не закрывать меню пока оно не досчитается и не окажется в буфере обмена?
____

[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=8598-389809&t=J8hmaI1DmtdRGBut-4)

с дивайдерами, делим на группы xpath / css / fullcode
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/6f16cb3f-223a-4f67-8aaf-57dca7b0dfcd)

___

1. селект копирования
2. закрываем меню
3. просчитываем локатор со спиннером и прогресс баром (как обычно) - это происходит в панели локаторов - в самом локаторе
4. done - показываем нотификацию "copy as xpath or etc" (но их пока нет, это отдельная задача)

Если после выбора, например, xPath + FindBy и в процессе просчёта локатора пользователь выбирает ещё, например, xPath + JDI annotation, то мы просто не останавливаем просчёт локатора и в буфере обмена оставляем последний выбранный тип копирования

Если не дожидаясь результата первого локатора, пользователь начинает копировать второй локатор, то мы НЕ сбрасываем прогресс первого и начинаем считать и копировать второй, при этом гарантируем, что в буфер попадёт последний запущенный на просчёт

**Comment by arslanbekova** [comment]
[3.12.495](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.495)

**Comment by AlexadrK** [comment]
JDN v 3.12.497 Back-end v 0.2.39
Chrome Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS
![second level menu in browser window ](https://github.com/jdi-testing/jdn-ai/assets/21053451/adb2640f-fb67-4c5a-be12-9290fe235c5e)
![second level menu in plugin window ](https://github.com/jdi-testing/jdn-ai/assets/21053451/16a6bd77-72cb-4390-9f04-635996023b5b)

**Comment by AlexeyGirin** [comment]
В продолжении этой задачи - нужно будет заимплементировать https://github.com/jdi-testing/jdn-ai/issues/1315
