### ISSUE TITLE
Система должна запоминать размер TextArea редактирования локатора локатора (или открывать так что бы контент влезал)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1235]
В данный момент - если пользователь изменил размер TextArea редактирования локатора - при переоткрытии диалога - приходится его растягивать его снова. Это неудобно.

Необходимо делать размер TextArea редактирования локатора таким, что бы туда влезал контент НО не больше чем размер экрана (если упираемся в экран - врубать скролл)

**Comment by SemyonKuznetsov** [comment]
- ресайз до высоты экрана - оступы до краёв, а после добавляем скролл

**Comment by arslanbekova** [comment]
[3.11.466](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.466)

**Comment by AlexeyGirin** [comment]
Fixed.
