### ISSUE TITLE
Расчёт локаторов запускать только если тип у локатора - xPath

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1236]
Сейчас при выборе CSS Selectors - запускается и расчёт оптимальных локаторов xPath
Это действиет - излишне.

Если тип локатора CSS Selector - для него 
1. Расчёт оптимального локатора - не запускать
2. В меню локатора - дизаблить опцию Advanced Calculation #1237 

При переключении типа локатора на xPath:
1. (если локатор не был посчитан ранее)Сперва показывать full xPath в задизабленном TextArea.
2. (если был посчитан ранее) пропустить шаг 3
3. Запускать расчёт оптимального
4. После расчёта - открывать доступ
5. В меню локатора - раздизаблить опцию Advanced 

Relates to #1228 #1284 #1285

Use Case:
На форме редактирования локатора при переключении типа.

**Comment by savinovava** [comment]
https://github.com/jdi-testing/jdn-ai/issues/1375
