### ISSUE TITLE
Задизаблить Advanced Calculation

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1237]
Если тип локатора CSS Selector - для него
    В меню локатора - дизаблить опцию Advanced Calculation

При переключении типа локатора на xPath:
    В меню локатора - раздизаблить опцию Advanced

**Comment by arslanbekova** [comment]
[3.11.468](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.468)

**Comment by AlexeyGirin** [comment]
Fixed.
