### ISSUE TITLE
Пустой лист локаторов после распознавания элементов (заполняется с сильной задёржкой)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1238]
1. Зайдите на страничку https://levelup.epam.com/skill/skillId=7770000000001942895&skillLevelId=7770000000000001003
2. Выберите там HTML5 элементы и CSS Selectors
3. Запустите генерацию
4. После того как серый эран пропадёт - ситема начинает 10 секунд выглядит как пустая
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/49815fd2-1444-4469-a52e-34447bee62e1)

Это плохо
Ожидаемые результат: Либо спиннер, либо - прогресс бар

**Comment by MariiaNebesnova** [comment]
[3.11.465](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.465)
