### ISSUE TITLE
[Medium] При создании кастомного локатора со сменой типа локатора (xPath > CSS) валидация происходит после нажати кнопки OK

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1239]
Шаги воспроизведения:

1. Запустить генерацю xPath PO
2. Скопировать CSS сгенерированного локатора
3. Кликнуть на "+ Custom Locator"
4. Переключить тип локтора с xPath на CSS
5. Вставить скопированный CSS локтор
6. Кликнуть на кнопку OK

AR: Валидация происходит после нажатия кнопки OK или добавлении пробела к локатору
ER: После вставки локтора происходит валидация и показывается сообщени что такой локатор существует

JDN v 3.11.461 Back-end v 0.2.36
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

https://github.com/jdi-testing/jdn-ai/assets/21053451/c9a44b0a-3837-4aef-9da1-3ec2eb355db5

**Comment by MariiaNebesnova** [comment]
[3.11.467](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.467)

**Comment by AlexadrK** [comment]
JDN v 3.11.468 Back-end v 0.2.36
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

The bug is fixed.

https://github.com/jdi-testing/jdn-ai/assets/21053451/9d0d143c-8949-47e2-b831-13608141c102
