### ISSUE TITLE
Все настройки должны сохраняться в локальном хранилище

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1244]
**Description:** Сейчас - Настройки (выбор параметров ПО) сохраняются только в сессии. Это неудобно. Необходимо хранить всё в локальном хранилище

**Dev Notes:**
Всё то, что сохраняется в локальном хранилище, должно сохранятся

- chosen filter set (on change)
- chosen (on change) UI Library
- chosen (on change) selectors types

local storage api: https://www.npmjs.com/package/use-local-storage

**Comment by MariiaNebesnova** [comment]
local storage api: https://www.npmjs.com/package/use-local-storage

**Comment by MariiaNebesnova** [comment]
[3.12.483](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.483)

**Comment by AlexadrK** [comment]
JDN v 3.12.485 Back-end v 0.2.39
Version 114.0.5735.110 (Official Build) (64-bit)

Test result - PASS

https://github.com/jdi-testing/jdn-ai/assets/21053451/dfce9a7f-f22f-40f5-8be8-aeb1e2464110
