### ISSUE TITLE
[High] Кастомный локатор, при создании локатора со сменой типа (xPath >CSS), сохраняется как невалидный

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1245]
Шаги воспроизведения:

1. Запустить генерацю XPath PO
2. Взять валидный CSS локатор нераспознного элемента
3. Кликнуть на "+ Custom Locator"
4. Переключить тип локтора с XPath на CSS
5. Вставить скопированный CSS локатор
6. Кликнуть на кнопку OK

AR: Локатор сохранён как невалидный
ER: Локатор сохранён как валидный
Такая же проблема для CSS ->XPath

JDN v 3.11.461 Back-end v 0.2.36
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

https://github.com/jdi-testing/jdn-ai/assets/21053451/f719518b-9fdc-4883-8897-486ddfa6e84c

**Comment by MariiaNebesnova** [comment]
[3.11.467](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.467)

**Comment by AlexadrK** [comment]
JDN v 3.11.468 Back-end v 0.2.36
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

The bug is fixed.

https://github.com/jdi-testing/jdn-ai/assets/21053451/8fc8fe45-9ac3-4fd8-ad55-725b0796d6ad
