### ISSUE TITLE
Выбор в контекстном меню опции Select Element не должно закрывать меню

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1246]
1. Распознайте HTML5 элементы на страничке где есть элементы (в моём случае это была https://levelup.epam.com/skill/skillId=7770000000001942895&skillLevelId=7770000000000001003)
2. На панели покрытия выделите через ареа селекшен несколько элементов
3. Вызовите контекстное меню на выделеных элементах и кликните на опцию Select Element

Наблюдаем: Меню пропадает вспыхнув напоследок выпадушкой
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/5130eab0-aca8-4b9e-81a1-9b81db836aee)

Ожидаем: Меню не пропадает, а меню второго уровня появляется быстрее (ну или не появляется быстрее, если это тяжко сделать)

**Comment by savinovava** [comment]
В случае больших временных затрат, можно отложить

**Comment by arslanbekova** [comment]
[3.12.488](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.488)

**Comment by AlexeyGirin** [comment]
Fixed.
