### ISSUE TITLE
Add badge to filter icon

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1249]
В данный момент - мы не показываем пользователю что на результат распознования наложен фильтр.
Возможно - стоит это делать

___

[figma design](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=9247-420018&mode=design&t=CSJhi7bC3IRjFJG8-4)
[ant](https://ant.design/components/badge)

- change the icon color to character/title.85 (#000000 85%)
- check the icon size (16px)
- add badge

badge - type dot & blue (by ant)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/f879b252-3f81-4fe3-8645-1beef37accb8)

показываем в состояниях:
- Default set
- Любое наличие фильтра, кроме состояний когда все включены

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/448fc0d0-a212-4a1a-b76c-92a407bb09e3)

**Comment by savinovava** [comment]
#1244 - связано с задачей

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.542

**Comment by AlexeyGirin** [comment]
Done.
