### ISSUE TITLE
Процесс распознавания никогда не заканчивается если мы ничего не нашли

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1250]
1. Откройте страницу https://levelup.epam.com/skill/skillId=7770000000001942895&skillLevelId=7770000000000001003
2. Попробуйте на ней распознать CSS Selectors (или xPath - это не принципиально) для Vuetify элементов (которых там нет)

Наблюдаем: система вечно крутит спиннер Preparing locators...

Ожидаем: система завершит процесс

![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/0dce86a0-9e79-4e9f-a34c-40624a6bc9cb)

**Comment by MariiaNebesnova** [comment]
[3.11.469](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.469)

**Comment by AlexeyGirin** [comment]
Fixed.
