### ISSUE TITLE
CTRL+Z функциональность в области редактирования CSS и xPath

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1252]
В окне редактирования локатора в поле xPath или CSS не работает CTRL+Z
Это очень неудобно.
Хотелось бы что бы как минимум одно изменение можно было бы откатить (а лучше - много)

**Notes:**
В поле редактирования в случае, если _текстовые_ данные были введены неверно.  Как минимум 1 шаг назад.

**Comment by arslanbekova** [comment]
На macOS Ventura 13.4.1 эта функция работает по дефолту.

**Comment by Iogsotot** [comment]
works in [3.13.550](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.550)
