### ISSUE TITLE
Нажатие Enter в поле задания имени локатора должно сохранять изменения и закрывать форму редактирования локатора

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1253]
1. Откройте любой локатор на редактирование.
2. Поменяйте имя и нажмите Enter
Наблюдаем: Ничего не происходит🤷‍♂

Ожидаем:
Нажатие Enter в поле задания имени локатора должно сохранять изменения и закрывать форму редактирования локатора (если это возможно, конечно, если невозможно - т.е. поле не проходит валидацию или там по другой причине - должно ничего не происходить)
_Enter button = Save action_

**Comment by AlexeyGirin** [comment]
Решили - во всех модалках где есть формы - должна быть такая логика

**Comment by arslanbekova** [comment]
[3.13.512](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.512)

**Comment by AlexeyGirin** [comment]
Fixed.
