### ISSUE TITLE
[US-15-1] Улучшить настройки css selector генератора

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#1255]
см. документацию https://github.com/fczbkk/css-selector-generator/

Решили:
Вкрутить две библиотеки сразу (finder и css-selector-generator) и генерировать оба результата из которых выбирать меньший по размеру

**Comment by AlexeyGirin** [comment]
https://www.carolinaherrera.com/ww/en/signin/
На этом сайте расчёт CSS идёт вечно

**Comment by MariiaNebesnova** [comment]
fixed [3.12.474](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.474)

**Comment by arslanbekova** [comment]
Не всегда происходит выбор css selector'a меньшего по размеру из-за проблем finder'а
#1277

**Comment by AlexadrK** [comment]
JDN v 3.12.497 Back-end v 0.2.40
Chrome Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS

https://github.com/jdi-testing/jdn-ai/assets/21053451/9288a309-8f86-4b7b-b922-f8ba905391cb
