### ISSUE TITLE
[US-4-2] Remove prediction accuracy from tooltip

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#126]
_как сейчас_
1.  тултип отображается у объекта
![image](https://user-images.githubusercontent.com/53625116/145589706-45604568-5c12-4936-ab93-80ba789a45a9.png)
2. изменяем button на label
![image](https://user-images.githubusercontent.com/53625116/145589818-97378f3b-5bf6-4b7a-ac9d-80d4cdee89d9.png)
3. поля тултипа изменились
![image](https://user-images.githubusercontent.com/53625116/145589936-d615df91-bbff-4494-a715-fd5800e77f13.png)

в чём проблема: новый тип - не тот, что был распознан со 100% вероятностью

варианты решения:
1. Добавить в тултип строку "Was changed by User" и убрать Prediction Accuracy
2. Оставлять в тултипе исходные значения

**Comment by mariia-tokarchuk** [comment]
в случаи если пользователь меняет тип блока (или другие параметры и среди них также тип блока):
1) значение prediction accuracy меняется на N/A на покрытии и в тултипе
2) в тултипе появляется дополнительная строчка “Edited”
3) во время фильтрации с помощью слайдера такой локатор не учитывается

![tooltip](https://user-images.githubusercontent.com/89466817/146505075-e34a62f4-541d-40fd-84fd-3ab0d7d5c887.png)

**Comment by mariia-tokarchuk** [comment]
в случаи если пользователь меняет другие параметры локатора, но тип блока оставляет тот, который определенным плагином:
1) значение prediction accuracy остается прежнее на покрытии и в тултипе
2) в тултипе появляется дополнительная строчка “Edited”
3) во время фильтрации с помощью слайдера “Prediction accuracy” такой локатор учитывается со своим дефолтным значением Prediction accuracy.

![tooltip2](https://user-images.githubusercontent.com/89466817/146509521-bac50aed-264e-447b-b4b5-a6d8497b8316.png)

**Comment by MariiaNebesnova** [comment]
[3.4.294](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.294)
