### ISSUE TITLE
Создание с Пустого ПО / Empty PO

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1262]
Беседы с потенциальными и реальными стейкхолдерами выявили явное желание в формировании ПО с нуля.
А именно.

Сейчас - система распознаёт элементы на страничке, формирует из них огромный список и начинает его просчитывать. Стейкхолдеры ничего не имеют против того что бы что-то там просчитывать, но видеть огромный список элементов - не хотят. Он им не нужен.
Хотят видеть только то, что они самы выберут.
(кстати - этот выбор не велИк).

Поэтому.
Необходимо разработать такой флоу, когда список элементов в списке локаторов будет пустым и будет заполняться по мере того как пользователь выбирает элементы на покрытии

Track dependencies:
-[ ] invisible locators

_____
Коротко флоу по задаче:
1. Выбор веб страницы
2. Кнопка создания пустого РО
3. Пустой список в плагине
4. Покрытие из элементов с непросчитанными (?) локаторами (но в фоне все локаторы потихоньку оно обсчитывается)
5. Пользователь на покрытии выбирает нужные ему элементы и добавляет их в РО
6. В момент появления в списке эти локаторы начинают считаться до оптимизированных (если они не было в фоне посчитаны до этого)
7. Сохранение списка
____
[Figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=8853-447541&t=vda41a9Tf6tnTjbS-4)

1. Добавлена новая кнопка для генерации пустого РО. Старая переименована в Generate all
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/397fa6b3-d61e-49bd-b240-1a53263e34e8)

2. На пустом списке локаторов показываем текст.
`Select the elements you need on the web page coverage and add them to the PO via a double-click or through the context menu`
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/824e2b8a-0c04-4532-9608-0246939e19c1)

3. При выделении элементов на покрытии добавляем локатор в список в статусе селектнутый.
Если локатор ещё не просчитан, то при добавлении его элемента в список мы повышаем его приоритет.
Если мы убираем локатор из РО любым способом, он удаляется из списка.
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/45f48960-2bc3-499a-a109-69b60ffc1347)

4. При добавлении элементов в ПО - он тоже добавляется в списке локаторов на панели локаторов

**Comment by MariiaNebesnova** [comment]
[3.13.514](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.514)

**Comment by Lisa5876** [comment]
При создании "Empty Page Object" (не зависимо от того, какая библиотека/locator type выбраны), появляется ошибка "Unable to Identify Elements", при том, что на странице элементы выделены пунктирной рамкой
Завела баг: https://github.com/jdi-testing/jdn-ai/issues/1429
<img width="956" alt="2023-07-31_15h26_05" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/57265630-825c-4d74-823e-cdb9bfa5667d">

**Comment by Lisa5876** [comment]
При создании пустого ПО отображается неправльное сообщение на списке локаторов
<img width="711" alt="2023-08-07_11h01_57" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/3f9c2f8d-0050-4d96-bbba-2545512739f7">
Заведен баг 
https://github.com/jdi-testing/jdn-ai/issues/1449

**Comment by Lisa5876** [comment]
JDN v 3.13.554 Back-end v 0.2.40
Test result - pass

1. Добавлена новая кнопка "Empty Page Object". Старая переименована в Generate all;
2. При нажатии "Empty Page Object", элементы выделяются на странице, локаторы просчитываются. На пустом списке локаторов отображается сообщение "Select the elements you need on the web page coverage and add them to the PO via a double-click or through the context menu";
3. Когда юзер кликает один раз на жлемент на странице, элемент добавляеься в список локаторов, но есть юзер кликает на другой элемент, предыдущий не сохраняется в списке;
4. При даблклике элемент добавляется в список локаторов, в статусе селекнутый;
5. Если анчекнуть локатор, то он удалится из списка локторов (при этом сначала он останется выделенным, чтобы была возможность снова вернуть его в список)

https://github.com/jdi-testing/jdn-ai/assets/89458651/4937a0f9-c5f7-416f-b296-fcf31ef2d5bb
