### ISSUE TITLE
Update Web Store screenshots

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#1264]
![screenshot21](https://github.com/jdi-testing/jdn-ai/assets/101407186/2946becf-3f18-4500-b0ef-4fb8ea8767e5)
![screenshot22](https://github.com/jdi-testing/jdn-ai/assets/101407186/e08ca056-e3a7-4f6a-8c80-860eaa293cb6)
![screenshot23](https://github.com/jdi-testing/jdn-ai/assets/101407186/9e7d3aa8-16b4-45b0-82c2-d1236f05afe2)
![screenshot24](https://github.com/jdi-testing/jdn-ai/assets/101407186/1b2d3bb5-8a0d-4cfc-9263-71cb7dbf6bb9)
![screenshot25](https://github.com/jdi-testing/jdn-ai/assets/101407186/0fbf5371-4fa0-4585-b2d3-dd30c77ff95f)

**Comment by SemyonKuznetsov** [comment]
![screenshot21](https://github.com/jdi-testing/jdn-ai/assets/101407186/2946becf-3f18-4500-b0ef-4fb8ea8767e5)
![screenshot22](https://github.com/jdi-testing/jdn-ai/assets/101407186/e08ca056-e3a7-4f6a-8c80-860eaa293cb6)
![screenshot23](https://github.com/jdi-testing/jdn-ai/assets/101407186/9e7d3aa8-16b4-45b0-82c2-d1236f05afe2)
![screenshot24](https://github.com/jdi-testing/jdn-ai/assets/101407186/1b2d3bb5-8a0d-4cfc-9263-71cb7dbf6bb9)
![screenshot25](https://github.com/jdi-testing/jdn-ai/assets/101407186/eeeb49ed-bae6-43ce-8026-873fdb17dc8d)
