### ISSUE TITLE
Проблема зависающего фронта

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1267]
Эту задачу лучше делать ПОСЛЕ задачи - #1268

Сейчас мы засылаем на расчёт все локаторы что у нас есть. Для 400-600 локаторов это работаешь хорошо, но начиная с 1500-2000 - всё перестаёт работать. Судя по всему - умирает сетевой стек или браузер который пытается обработать такое большое количество сетевых соединений.
Поэтому. Существующая схема расчёта локаторов нуждается в улучшении

Исходные условия:
У нас есть 2000 локаторов отсортированных по расположению на экране (справа налево, сверху вниз)
Бэк у нас считает в K потоков (по умолчанию считаем что K=8)
Максимальное количество сетевых соединений которое может обработать фронт - M (по умолчанию считаем что M=32)
Счётчик посланных на расчёт локаторов - S
Счётчик расчитанных локаторов - R

Алгоритм:
Каждую секунду проверяем - если S - R < M то
Посылаем S - R локаторов на расчёт идя сверху списка увеличивая счётчик посланных локаторов S на единицу на каждый отправленный на расчёт локатор
На каждый расчитанный локатор - мы увеличиваем счётчик R на единицу

Если пользователь выделит на панели покрытия или на панели локаторов локатор который ещё не послан на расчёт или не посчитан - посылаем его на расчёт увеличиваея счётчик S на единицу

**Comment by AlexeyGirin** [comment]
Обсудить с Фёдором
Идей - засылаем всё толпой, но что бы Фёдор возвращал пачками, а не поштучно
При этом - первые в списке - должны иметь приоритет при отправке обратно

**Comment by AlexeyGirin** [comment]
Фёдор обнаружил, что коллапс фронта - не зависит от действий сервера. Даже если сервер ничего не возвращает - фронт всё равно коллапсирует

**Comment by MariiaNebesnova** [comment]
[3.13.507](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.507)

**Comment by AlexeyGirin** [comment]
Работает до размера 2000 локаторов. Начиная с 2000 - фронт просто крутит спиннеры и расчёт не идёт (хотя если стопнуть и запустить единичный локатор - он посчитается)
