### ISSUE TITLE
Дефлотная сортировка локаторов на панели локаторов должна соответствовать порядку элементов на панели покрытия

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1268]
Сейчас сортировка локаторов отсутствует - рядом находящиеся локаторы могут находится в разных частях страницы и наоборот.
Необходимо сделать так что бы локаторы рядом стоящих элементов находились рядом.
Справа налево, сверху вниз

**Comment by spiridonovfed** [comment]
Should be tested with https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.482 (and newer if exists)

**Comment by AlexeyGirin** [comment]
Works perfectly
