### ISSUE TITLE
Добавить выбор аннотации (и FindBy аннотацию)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1269]
При создании дизайна для этой задачи нужно учитывать наличие задачи #1270 (можно даже сделать их вместе в дизайне)

В данный момент мы генерим локаторы в обёртке JDI Light аннотиции UI.
В то же время JDI поддерживает и селениумные аннотации FindBy
Необходимо дать пользователю возможность: 
1. Выбрать дефолтную аннотацию для ПО (если есть такая возможность - возможно, стоит прятать эту опцию если нет возможности)
2. Менять аннотацию для конкретного локатора

Сейчас локаторы в UI аннотации выглядят так:
`@UI("%xPath_Or_CSS_Locator%") `
Напрмер:
`@UI("//label[@for='your-name']") `

В аннотации FindBy это выглядит так:
Для xPath локаторов:
`@FindBy(xpath = "%xPath_Locator%")`
Например:
`@FindBy(xpath = "//label[@for='your-name']")`

Для CSS селекторов:
`@FindBy(css = "%CSS_Selector%")`
Например:
`@FindBy(css = "[value*='Red Button']")`

Ответы на вопросы:
1. В одном ПО могут быть и те и другие аннотации одновременно

____

[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=8656-400099&mode=design&t=AtVgArM3tDLw5DwM-4)

выбор аннотации при создании РО
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/cd56567b-8950-485f-a3a5-e37a46eb2962)

выбор аннотации при редактировании локатора 
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/b9cbae9b-6eb2-484f-8c24-2bee77e52028)

выбор аннотации при создании кастомного локатора
- для jdi light по умолчанию `@UI`
- для selenium по умолчанию `@FindBy` 
- наследуем настройки от РО по умолчанию

незаполненная / заполненная форма
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/2592d49e-fe37-4f32-8cb0-ba88d21d79f7)

_p.s от Семёна: проверьте пожалуйста заголовки модалок и кнопок в них на соответствие по тексту 🙇_

_Notes:_
- JDI Light `@UI / @Findby`
- Selenium `@Findby`

**Comment by SemyonKuznetsov** [comment]
хотим ли мы добавлять это в редактирование? или локатор может быть только изначально сгенерирован одним из способов?

добавляем это в настройки?

Annotation: 1. UI 2. FindBy ?

**Comment by AlexeyGirin** [comment]
хотим ли мы добавлять это в редактирование?
Да

или локатор может быть только изначально сгенерирован одним из способов?
Нет

добавляем это в настройки?
Да

их будет только 2 или возможны ещё варианты?
в JDI Light - нет, но в других фрэймворках может быть по другому

**Comment by kostrubin** [comment]
[3.13.532](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.532)

**Comment by AlexeyGirin** [comment]
Done.
