### ISSUE TITLE
[Save] При смене Block type не сменяется поле Name

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#128]
JDN v 3.0.96
Back-end v 2021-12-01-14.52.21

1. Открываем плагин
2. Нажимаем [Identify]
3. На любом распознанном локаторе нажимаем [...]
4. Нажимаем на drop down menu
5. Выбираем любой тип
6. Нажимаем [Save]

ОР:
Окно Edit закроется.
ФР:
Окно не закрылось.

**Comment by MariiaNebesnova** [comment]
fe 1 pt

**Comment by MariiaNebesnova** [comment]
can not reproduce

**Comment by pulya-na-vullet** [comment]
Произвел ретест на версии:
JDN v 3.0.99
Back-end v 2021-11-26-14.32.52
Баг не воспроизводится.
