### ISSUE TITLE
Integration with Vividus

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1281]
Задача зависит от #1269 и от https://github.com/jdi-testing/jdn-ai/issues/1270 (их надо сделать предварительно)
Задача аналогична - https://github.com/jdi-testing/jdn-ai/issues/585 и https://github.com/jdi-testing/jdn-ai/issues/829

В данный момент - мы выгружаем элементы в проект на основе JDI Light
Нужно сделать выгрузку в проект на основе VIVIDUS

Шаблон проекта: https://github.com/vividus-framework/vividus-sample-tests/tree/main

Пэйдж объекты сохранять в файлы с именем pages.properties
в директорию /src/main/resources/properties/suite/web_app/

Формат файла:
```
variables.%Page_Object_Name%.url=(%relative_URL%)  //Например /jdi-testing/jdn-ai/issues/1281
variables.%Page_Object_Name%.%ELEMENT_TYPE%.%NAME%=By.%LOCATOR_TYPE%(%LOCATOR%)
```
и тут все локаторы для этой странички
потом пустая строка
и следующий пэйдж объект

В ту же директорию положить файл - site.properties 
с содержимым
`variables.siteURL=(%site_url%) //Например https://github.com`

ВНИМАНИЕ:
При выборе таргет экспорта в VIVIDUS - значение Library должно быть задизабленым и по умолчанию HTML5

**Имплементация:**

- [ ] на форме создания ПО добавить опцию Vividus, при выборе - записывать значение в PageObject (создать редьюсер, если его еще нет)
- [ ] скачивать темплейт для Vividus аналогично JDI Light
- [ ] изменить хендлер для кнопки `Download all`: для опции Vividus возвращать архив с темплейтом, отредактированным, как описано выше

**Comment by kostrubin** [comment]
[3.13.562](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.562)

**Comment by Lisa5876** [comment]
JDN v 3.14.2 Back-end v 0.2.40
 test result:
1. Пэйдж объекты сохранять в файлы с именем pages.properties
в директорию /src/main/resources/properties/suite/web_app/   - **passed**
2. В ту же директорию положить файл - site.properties
с содержимым variables.siteURL=(%site_url%) //Например https://github.com  - **passed**
3. При выборе таргет экспорта в VIVIDUS - значение Library должно быть задизабленым и по умолчанию HTML5 - **passed**

Related bugs:
https://github.com/jdi-testing/jdn-ai/issues/1480  - **fixed**
https://github.com/jdi-testing/jdn-ai/issues/1477 - **fixed**
