### ISSUE TITLE
Генерация локатора не ставится на паузу из контекстного меню покрытия

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1283]
Шаги воспроизведения:

1. Запустить генерацю PO
2. Поставить генерацию локатора на паузу в окне покрытия

AR: Генерация локатора не останавливается
ER: Генерация локатора останавливатся, в окне плагина около данного локатора появлятся значок паузы

JDN v 3.12.480 Back-end v 0.2.37
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

https://github.com/jdi-testing/jdn-ai/assets/21053451/d341a235-8943-48b0-8c40-9112ff62bab6

**Comment by MariiaNebesnova** [comment]
[3.12.489](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.489)

**Comment by AlexadrK** [comment]
JDN v 3.12.492 Back-end v 0.2.39
Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS


https://github.com/jdi-testing/jdn-ai/assets/21053451/c2e7ae00-a158-4502-9d44-26787a21fd3a
