### ISSUE TITLE
[US-15-1] Фоновый расчёт CSS селекторов - UI part

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1284]
**Problem:**  CSS селекторы сейчас считаются одним "куском" на фронте, и пользователю не доступна интеракция с плагином.
Необходимо ожидать конца рассчёта.

**Steps to reproduce:**
Откройте ссылку - https://www.google.by/search?q=JDN&hl=ru&tbm=isch&source=hp&biw=1221&bih=952&ei=8Kl9ZMW6Ov3lxc8PhuSj-Ag&iflsig=AOEireoAAAAAZH24ABbjpbPe-aUnZTGOy-pbxH1nhdPa&ved=0ahUKEwjF8uPS56v_AhX9cvEDHQbyCI8Q4dUDCAc&uact=5&oq=JDN&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIJCAAQgAQQChABMgUIABCABDIFCAAQgAQyBQgAEIAEOggIABCABBCxA1AAWM0EYO4HaABwAHgAgAFqiAG8ApIBAzAuM5gBAKABAaoBC2d3cy13aXotaW1n&sclient=img

и попробуйте распознать CSS селекторы для HTML5 элементов

Второй кейс:
Откройте референсный для проекта Pizza - https://www.otto.de/
Там примерно 1000 элементов на главной страничке. 
Вычисление CSS селекторов там - занимает существенное время.

**ACTUAL RESULT:** 
Процесс расчёта селекторов длится ну минут 10 примерно. Всё это время - крутится вэйт баннер.

**EXPECTED RESULT:** 
- Процесс расчёта будет производится так же как и для xPath - асинхронно и в порядке очереди (сверху вниз). Возможен перенос на backend.
- Считать CSS вместе с Xpath в том же таске

**COMMENTS:**
Возможно несколько вариантов:
1. Считать CSS вместе с Xpath в том же таске
2. Завести для CSS отдельный тип тасок и посылать на рассчёт отдельно

____

Есть вариант небольшого энхансмента, если не получится или займёт больше одного релиза:
1. Оверлей на веб-страницу
2. В лоадер Preparing locators надо дописать текст в следующую строку _"For a large number of CSS Selector locators we count them in the background, please wait"_

<img width="331" alt="Снимок экрана 2023-08-10 в 16 45 10" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/ffeaa987-c518-4f9f-a774-942c76c50b1e">

10.08.2023 Meeting Notes: https://epam-my.sharepoint.com/:v:/p/anna_iustus/EQWDvGu8gjNInth3R-PQn2QBUDfbZJ9LYs4UI-4YJI3uCg

**Comment by ivnglkv** [comment]
Можно сделать это и в рамках html5-predict эндпойнта. Это будет менее красивое решение, но более быстрое для реализации со стороны фронтенда.

html5-predict:
- Локаторы доступны сразу после ответа
- Будет некоторое замедление работы эндпойнта, _но…_
- С учетом того, что сейчас пока локаторы не посчитаются, плагин заблокирован, общее время до готовности плагина к работе уменьшится (надо протестировать, но в теории так, за счёт распараллеливания расчётов)
- Потребуются небольшие изменения на фронте для использования этих результатов

WS:
- **_Очень много_** работы на фронте
- Более стройное решение

**Comment by AlexeyGirin** [comment]
Ожидаемое решение:
Продублировать логику применяемую для расчёта xPath локаторов
Т.е. мы через WS посылаем на сервер задания на расчёт оптимального CSS и бэк - их расчитывает и возвращает обратно
В то же время на фронте - если в качестве дефолтного локатора выбран CSS то до получения посчитанного оптимального локатора - система должна отображать Full CSS (от корня) так же как это делается с xPath (отображается Full xPath)

**Comment by AlexeyGirin** [comment]
Backend part is done

**Comment by ivnglkv** [comment]
We need to remove scripts from the document sent to the backend since they can change the page source after loading the page in Selenoid containers. E.g. they are removing the `jdn-hash` attributes on [this page](https://discord.com/channels/1212086641678618715/1227543494625722419/1227611876070920212).
Also we need to fix the behaviour in #1707

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1732
[3.15.31](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.31)

FE-реализация на момент написания коммента работает с dev версией на порту 5001 (http://78.47.220.208:5001/)

Перед тестированием надо дождаться ответа от @ivnglkv , что бэкенд готов обрабатывать большие страницы (не падает селениум при обсчете CSS Selectors) и что эндпоинт [download_template](http://78.47.220.208/download_template) работает на всех энвах)

**Comment by Iogsotot** [comment]
[3.15.37](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.37)  - включены фичи с запросом расчета CSS на бэкенде (и со скачиванием PO в виде архива)

**Comment by Vehemen** [comment]
Коннекторы считаются по отдельности, доступны интеракции с ними во время просчёта
