### ISSUE TITLE
[US-7-6] Больше опций для выбора типа локатора при его редактировании

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1285]
связана с #1180

Добавить в список атрибуты ID, Name, ClassName и `*Data*` (который присутствуют только если он есть у элемента, например data-ved="0ahUKEwiR-e6zpbj-AhX4T6QEHX-9Br0Q19QECAo")
Таким образом - при открытии окна редактирования локатора в выпадушке Locator должен быть список:

- CSS selector
- className
- data-атрибуты
- id
- linkText
- name
- tagName
- xPath 

При выборе того или иного - должны получаться следующие `@UI` аннотации:
```
xPath - всё по старому (да, это так: @UI("//*[contains(text(), 'Search help')]") - Алексей)
CSS selector - всё по старому (да, это так: @UI("#Search_help_id") - Алексей)
id="AlaAlaAla": @UI("#AlaAlaAla")
name="BlaBlaBla": @UI("[name=‘BlaBlaBla‘]")
tagName="button": @UI("button")
className="ClaClaCla": @UI(".ClaClaCla")
linkText = "Home": @UI("Home")
data-ved="0ahUKEwCAo":  @UI("[data-ved=‘0ahUKEwCAo‘]")
```

Для `@FindBy` аннотаций это будет:
```
xPath - всё по старому (да, это так: @FindBy(xpath = "//*[contains(text(), 'Search help')]") - Алексей)
CSS selector - всё по старому (да, это так: @FindBy(css = "#Search_help_id") - Алексей)
id="AlaAlaAla": @FindBy(id = "AlaAlaAla")
name="BlaBlaBla": @FindBy(name = "BlaBlaBla")
tagName="button": @FindBy(tagName = "button")
className="ClaClaCla": @FindBy(className = "ClaClaCla")
linkText = "Home"
data-ved="0ahUKEwiR":  @FindBy(css = "[data-ved='0ahUKEwiR']")
```
**User Feedback:**
Артём: локаторы слишком длинные (>20-30 symbols). Оптимальным считается блее короткий.

____
## Про уникальность

- Проверяем всех на уникальность (включая ID, CSS and xPath)
- Если xpath или id, например, неуникальны по итогам проверки, то мы перекидываем его в нижнюю группу

Уникальность локатора мы можем гарантировать только для CSS и xPath (это гарантирует алгоритм который мы используем) и для id (хотя во всех книжках говорится что гарантии нет, но как правило - это не нарушается).
А вот для остальных локаторов (если они вообще применимы т.к. не гарантировано что они есть - например - атрибута name вообще может не быть) - уникальность не гарантируется и тот же name - может быть совсем не уникальным.

____
## Дизайн

[Figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=9024-404286&mode=design&t=eCFlJWwU0EcyOZvS-4)

Минифлоу:
1. Открываем Edit (на фоне запускается проверка на уникальность для списка типов локатора)
2. Меняем тип локатора
3. Тип аннотация остаётся
4. Меняется текст локатора

- Внутри групп уникальные/неуникальные сортируем по A-Z
- Для некоторых атрибутов (data или name) может не быть данных, тогда мы их дизейблим и показываем тултип с текстом "Disabled because no data"
- Предпоказанный текст локатора в уже выбранный Select не берём
- Стиль текста в дивайдере поменял на поменьше footnote/description 12/20

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/30be91b4-de6c-4cf9-9e94-8edf46bcce11)

если текст большой, то элипсируем через три точки
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/4040bd22-569d-468f-8091-0dad7440352f)

Алексей: Надо обратить внимание, чтобы scroll bar был виден и по умолчанию показывался. Нужно видеть что там больше 2-3 типов локаторов в списке Если возможно, на имплементации сделать дропдаун как можно больше (но с отступом от края, конечно же) 
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/897572f2-56c8-446b-bee6-5bb1aeb8ba44)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1573 
[3.14.27](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.27)
