### ISSUE TITLE
[US-6-8] Удалить из распознавания невидимые элементы

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1287]
> В данный момент - мы никак не помечаем invisible elements ( relates to https://github.com/jdi-testing/jdn-ai/issues/171 и https://github.com/jdi-testing/jdn-ai/issues/1286)

При этом - их наличие - имеет сомнительную ценность: 
1. Мешает подбирать более простые уникальные локаторы - см. пример из задачи https://github.com/jdi-testing/jdn-ai/issues/1193) 
2. Всё равно будут проигнорированы JDI Light (и VIVIDUS, но не Selenium) по умолчанию, поэтому даже если локаторы у них будут уникальными - всё равно не найдутся (для того что бы нашлись - нужно поставить аннотацию `@GetAny` или ещё не сделанную аннотацию `@GetInvisible` (задача на импелементацию - https://github.com/jdi-testing/jdi-light/issues/4971)  (у Вивидуса - нужно смотреть сюда - https://docs.vividus.dev/vividus/latest/plugins/plugin-web-app.html#_visibility_types)

Поэтому
Необходимо удалить из дерева (если это возможно) все элементы которые не являются видимыми. И только после этого - отправлять это дерево на расчёт локаторов
Если таргет фрэймворк - Selenium, то дерево не чистить - отправлять как есть

Невидимые элементы:
1. Видимость элемента: Selenium проверяет, что элемент имеет ненулевую ширину и высоту, а также что он не скрыт с помощью CSS-свойства display: none или visibility: hidden. Если элемент имеет нулевые размеры или скрыт, то он считается невидимым.
2. При отрисовке DOM еще используется index элемента. То есть из-за этого возможна ситуация, когда другой прозрачный/непрозрачный слой перекрывает наш объект и тогда объект визуально мы видим, но клик или другое действие корректно не отрабатывает.
Еще проверяет, что не перекрыт другим элементом. Спека ведет сюда в качестве референса:
https://github.com/SeleniumHQ/selenium/blob/a6b161a159c3d581b130f03a2e6e35f577f38dec/javascript/atoms/dom.js#L573

Элементы которые считаются невидимыми:

    css property display: none
    DOMRect: width/height === 0
    css property opacity: 0 - Всё равно видимый элемент
    css property visibility: hidden
    html attribute "hidden"
    css property visibility: collapse
    OVERLAPPED by another element
    Hidden parrent

**Имплементация:**

- [ ] на этапе вычисления аттрибутов для рассчета локатров определять видимость элемента ( `sendMessage.generateAttributes` ). см. комментарий ниже
- [ ] создать скрипт, который будет возвращать DOM с исключенными из него невидимыми элементами
- [ ] создать новый фильтр `showInvisible: false`, по которому элементы будут фильтроваться в плагине и на странице
- [ ] получать этим скриптом дом для сокета `schedule_multiple_xpath_generations` в случае, если фильтр `showInvisible === false`
- [ ] учитывать видимость при валидации локатора
- [ ] учитывать видимость при отображении фильтра классов
- [ ] на фронтэнде поднять минимальную поддерживаемую версию сервера

**Comment by MariiaNebesnova** [comment]
апи Селениума: https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/webdriver_exports_WebElement.html#isDisplayed

**Comment by artshvyrkov** [comment]
Need to add a new attribute to predict endpoint to pass html pages

**Comment by AlexeyGirin** [comment]
Маша будет чистить страницу на фронте

**Comment by spiridonovfed** [comment]
https://github.com/jdi-testing/jdi-qasp-ml/tree/1287-remove-hidden-elements - ссылка на ветку с работой Артема

**Comment by Iogsotot** [comment]
FE PR: https://github.com/jdi-testing/jdn-ai/pull/1553
FE extension's zip: [3.14.22](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.22)
minimum compatible version of BE: `0.2.41`

**Comment by Ekaterina-Zykova** [comment]
BE PR: https://github.com/jdi-testing/jdi-qasp-ml/pull/160
BE version 0.2.45

**Comment by Ekaterina-Zykova** [comment]
added parameter: "is_shown"

**Comment by Ekaterina-Zykova** [comment]
fix in mui predict and angular predict
BE PR: https://github.com/jdi-testing/jdi-qasp-ml/pull/165
BE version 0.2.48
