### ISSUE TITLE
[Critical] Парсинг страницы длится бесконечно

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1288]
1. Откройте страничку https://www.google.co.il/search?q=JDN&hl=ru&tbm=isch&source=hp&biw=1920&bih=927&ei=wz2AZJGUNt_KkdUP6cCf0AU&iflsig=AOEireoAAAAAZIBL03n4ccuZzZAHSLWmsN37Rub8AX-5&ved=0ahUKEwjRgdnz3LD_AhVfZaQEHWngB1oQ4dUDCAY&uact=5&oq=JDN&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIJCAAQgAQQChABMgUIABCABDIFCAAQgAQyBQgAEIAEUABY5wRghgxoAHAAeACAAdQBiAHsBJIBAzItM5gBAKABAaoBC2d3cy13aXotaW1n&sclient=img
2. Попробуйте распознать xPath HTML5 элементы

Наблюдаем: Плагин замирает в состоянии Preparing locators...

Ожидаем: Всё грузится быстро

![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/90470050-7a3e-4f03-9511-46d879504d21)

**Comment by AlexeyGirin** [comment]
Временно отключим расчёт CSS селекторов при расчёте xPath

**Comment by spiridonovfed** [comment]
Works great with new frontend build (link above)

**Comment by AlexeyGirin** [comment]
Done.
