### ISSUE TITLE
[NR][US-7-2][Edit] При открытии окна Edit на нескольких вкладках не получается закрыть окно кнопкой [X]

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#129]
JDN v 3.0.96
Back-end v 2021-12-01-14.52.21

1. Открываем несколько вкладок
2. Распознаем элементы на нескольких страницах
3. Открываем на каждой странице окно "Edit"
4. Ждем пару минут
5. Закрываем меню edit на нескольких страницах нажимая кнопку [X]

ОР: 
Окно закроется.
ФР:
Окно не закрывается.
Окно закроется

**Comment by AlexeyGirin** [comment]
Почти дупликат #135
Будет пофикшено автоматом после имплементации #195
