### ISSUE TITLE
[Critical] CSS locators are not unique when user edits saved PO

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1290]
**Steps to reproduce:**

1. Open as an example https://www.docker.com
2. Generate PO using any library and Locators type: CSS
3. Select All checkbox and Save PO
4. Click three dots button on the right of the saved PO and click "Edit Page Object" button

**Expected result:** elements on the webpage are highlighted, and locators are not marked as non-unique

**Actual result:** all elements on the webpage are marked as non-unique

https://github.com/jdi-testing/jdn-ai/assets/21053451/bc464352-adea-4aac-ae94-13cf70e82c28

**Comment by MariiaNebesnova** [comment]
Please, pay attention that locator is not unique if error message is "N elements were found with this locator". In this bug error is "The locator was not found on the page."

**Comment by MariiaNebesnova** [comment]
[3.12.487](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.487)

**Comment by AlexadrK** [comment]
JDN v 3.12.487 Back-end v 0.2.39
Chrome Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS

https://github.com/jdi-testing/jdn-ai/assets/21053451/18945772-e380-484e-9ed7-639025ce8745
