### ISSUE TITLE
Поправить качество и скорость работы генераторов CSS селекторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1291]
1. Откройте страничку - https://www.google.com/search?q=JDN&rlz=1C1YTUH_enTR1013__1014&sxsrf=APwXEdeYqtmhne7RSdlNxJznl8D364_gPQ:1686212061488&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi1ksO3nbP_AhWIUXcKHXkTDvoQ_AUoAXoECAEQAw&biw=1904&bih=895&dpr=1
2. Попробуйте распознать HTML5 элементы и их xPath

Наблюдаем: Система надолго задумывается после того как модель распознала элементы

Ожидаем: Система будет задумываться на меньшее время

Требуется - Провести анализ происходящего и по возможности сделать так, что бы без потери качества время работы генераторов CSS стало меньше

**Comment by MariiaNebesnova** [comment]
[3.12.496](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.496)

**Comment by AlexeyGirin** [comment]
Fixed.
