### ISSUE TITLE
[Low] Сортировка локаторов в панели плагина для некторых сайтов частично не соответствует порядку элементов на панели покрытия

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1294]
**Шаги воспроизведения:**

1. Открыть сайт https://habr.com/ru/all/
2. Запустить генерацю PO
3. Сравнить порядок элементов в панели плагина и панели покрытия

**AR:** Некорые локаторы в плагине не соотвествуют порядку справа налево, сверху вниз
**ER:** Локаторы расположенны в  порядке справа налево, сверху вниз

Видео пример
https://epam-my.sharepoint.com/:v:/p/aleksandr_kashin1/EZU0IzuHRHRDoY6wRrbux4gBwdd411E_ZCnOtEgyPAuoug?e=NlJn9A

https://github.com/jdi-testing/jdn-ai/assets/21053451/39d612d0-2e6c-4f1e-9a3b-61508ec8c0e0

**Comment by AlexeyGirin** [comment]
Not a bug.
