### ISSUE TITLE
[Critical] Copy buttons stopped working on Installation guide page

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1295]
Try to copy any back end run string on Installation guide page.
It doesn't work - it doesn't put anything to the buffer
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/6d7cb661-86cf-4d9b-b886-35f9bc26af3a)

**Comment by arslanbekova** [comment]
bug isn't reproduced [3.12.485](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.485)

**Comment by AlexeyGirin** [comment]
Not reproduced.
