### ISSUE TITLE
[US-9-1] Перенос генерации и отправки письма на бэкэнд

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#13]
В данный момент - отправка писем осуществляется через фронт и весьма ограниченным образом (через внешний вызов внешнего клиента с передачей ему ограниченного числа параметра). Это неудобно.
Необходимо перенести функцию генерации и отправки письма на бэкэнд где нет тех ограничений которые есть на фронте.

- [x] Добавить поддержку в бэкэнде
В письмо должен быть вложен json файл генерации которую возвращает модель + скриншот страницы с покрытием. Сабжект письма и тело - получать с фронта (как и скриншот, видимо)

- [ ] Добавить поддержку во фронте

[Optional] Title - max size: 200 chars
[Mandatory] Description - max size: 10000 chars

![image](https://user-images.githubusercontent.com/26869421/139393803-6f59a650-6f50-4b85-809e-bca9d448b925.png)

[Related US-9-1](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910713/US-9-1+Report+a+problem)

**Comment by savinovava** [comment]
2 pt - backend
3 pt - frontend
2 pt - QA

**Comment by rrr3try** [comment]
@MariiaNebesnova 
json файл генерации которую возвращает модель у тебя получится мне на бек отсылать? Сейчас оно нигде не сохраняется на бекенде, если это не потребует каких-то модификаций на фронте может сделаем так?

**Comment by MariiaNebesnova** [comment]
> @MariiaNebesnova json файл генерации которую возвращает модель у тебя получится мне на бек отсылать? Сейчас оно нигде не сохраняется на бекенде, если это не потребует каких-то модификаций на фронте может сделаем так?

модификации потребуются, результат в чистом виде на фронте не хранится

**Comment by AlexeyGirin** [comment]
Решили что письмо будет посылаться от имени Вадима (на первом этапе, с мэйл ру, создать с именем JDN-no-reply) и потом создадим отдельный аккаунт на epam.com

**Comment by MariiaNebesnova** [comment]
implementation blocked, progress is in #395, waiting for mockups

**Comment by SemyonKuznetsov** [comment]
1. Можем прикрепить несколько файлов?
2. Нужна функция дрег&дроп файлов? (пример)
<img width="1063" alt="Снимок экрана 2022-04-13 в 10 30 33" src="https://user-images.githubusercontent.com/101407186/163123449-ea7b97af-d227-4cbf-8fee-65a28d3beb4f.png">

**Comment by SemyonKuznetsov** [comment]
Аттач файла - только просмотр того, что прикрепилось через фронт

**Comment by SemyonKuznetsov** [comment]
[figma screen link](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=5198%3A59623) and [link to modal window component](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=5194%3A59514)
![report a problem](https://user-images.githubusercontent.com/101407186/163284235-2e69d5a5-6a17-4aa7-a03c-2a4c6dc411b1.png)

hover state
![2345](https://user-images.githubusercontent.com/101407186/163284657-f8488bc8-00ff-4b40-932b-5e77b503434b.png)




[attach component link](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=5198%3A59579)
<img width="510" alt="Снимок экрана 2022-04-14 в 02 05 42" src="https://user-images.githubusercontent.com/101407186/163283918-51333e71-1bef-4df8-8ed2-3930899d1829.png">

**Comment by SemyonKuznetsov** [comment]
@savinovava изменения логике дизайна?

**Comment by MariiaNebesnova** [comment]
обсудили с @SemyonKuznetsov, лейблы полей решили выводить слева, единнобразно с Edit и Rename

**Comment by SemyonKuznetsov** [comment]
visual update
<img width="467" alt="Снимок экрана 2022-04-17 в 19 36 57" src="https://user-images.githubusercontent.com/101407186/163723881-00857dfe-86e7-4c8a-aded-2001fd36ffc4.png">

**Comment by MariiaNebesnova** [comment]
fe - 3.1.173

**Comment by MariiaNebesnova** [comment]
needed further improvements from backend
![image](https://user-images.githubusercontent.com/82033805/165946786-c927c618-de0b-49de-a717-8291a5967a2a.png)
![image](https://user-images.githubusercontent.com/82033805/165946819-57bcd1c9-a1a3-4e1e-ac3f-0c681f052452.png)

**Comment by MariiaNebesnova** [comment]
3.1.201
following report_problem request is sent successfully:
![image](https://user-images.githubusercontent.com/82033805/176167094-ac557aa7-4ee7-4371-bf47-41faff5fb585.png)
![image](https://user-images.githubusercontent.com/82033805/176167365-3a09cfd1-211b-4178-a7b0-1e5bab3ec961.png)
