### ISSUE TITLE
[0.5pt][US-6-1] Не отображается locator list при распознанных и отображенных элементах на самой странице. Консоль плагина: 500 Status Code/

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#130]
JDN v 3.0.96
Back-end v 2021-12-01-14.52.21

Периодически при работе с плагином JDN происходит ошибка при которой распознанные элементы не отображаются списком в locator list.

Шаги:
1. Открыть страницу
2. Открыть плагин
3. Нажать [Identify]

ОР:
В locator list будет список элементов
ФР: 
В locator list нет списка элементов. Локаторы распознаны и отображены на странице.

**Comment by pulya-na-vullet** [comment]
На момент 13.12.2021 не воспроизводится.

**Comment by AlexeyGirin** [comment]
Диме - перепроверить актуальность

**Comment by DaryaGurtovenko** [comment]
0.5 pt - qa

**Comment by IoffeM** [comment]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

is not reproducible anymore
