### ISSUE TITLE
Welcome to Onboarding Tutorial pop-up has the button OK instead Start

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1305]
**Steps to reproduce:**

1. Open https://www.docker.com/
2. Start onboarding 

**Actual result:**
Welcome to Onboarding Tutorial pop-up has the button OK instead Start
![Welcome to Onboarding Tutorial](https://github.com/jdi-testing/jdn-ai/assets/21053451/835406b3-4aee-4224-ac59-585d493879aa)

**Expected result**
![Welcome to Onboarding Tutorial design](https://github.com/jdi-testing/jdn-ai/assets/21053451/2a6c8499-dfd8-4849-9b5d-10482ffb6f22)

**Comment by MariiaNebesnova** [comment]
[3.12.494](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.494)

**Comment by AlexadrK** [comment]
JDN v 3.12.495 Back-end v 0.2.39
Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS
![onboarding the start button](https://github.com/jdi-testing/jdn-ai/assets/21053451/5053cbf2-06f0-4f90-b4ab-57bf3b974659)
