### ISSUE TITLE
Tutorial pop-ups do not adjust to the size of the plugin window

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1306]
Steps to reproduce:

1. Open https://www.docker.com/
2. Start onboarding
3. Proceed to tutorial pop-ups from 1 to 14

**Actual result:**
Tutorial pop-ups do not adjust to the size of the plugin window

![tutorial pop-up does not adjust](https://github.com/jdi-testing/jdn-ai/assets/21053451/45084e07-45f5-431c-8b65-6e7f75411763)

https://github.com/jdi-testing/jdn-ai/assets/21053451/9e6cc90b-2253-4b9d-9b33-368bdd89f570

**Expected result**
Tutorial pop-ups adjust to the size of the plugin window

**Comment by MariiaNebesnova** [comment]
[3.12.494](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.494)

**Comment by AlexadrK** [comment]
JDN v 3.12.495 Back-end v 0.2.39
Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS
![adjust is ok](https://github.com/jdi-testing/jdn-ai/assets/21053451/977eeef0-4884-44f6-bc96-745e4cf35720)
