### ISSUE TITLE
[Critical] Расчёт локатора падает

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1307]
0. JDN v 3.12.488 Back-end v 0.2.39
1. Распознайте HTML5 элементы на страничке где есть элементы (в моём случае это была https://levelup.epam.com/skill/skillId=7770000000001942895&skillLevelId=7770000000000001003)

Наблюдаем: Некоторые локаторы (например myDashboard) не смогли посчитаться.
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/2f3f4a61-ea16-4ee5-a214-5ef039bb3082)

При попытке пересчитать - в логах сервера:
jdi-qasp-ml-celery  | [2023-06-16 12:34:25,593: ERROR/ForkPoolWorker-15] Task app.tasks.task_schedule_xpath_generation[___2492321474187950835273414686] raised unexpected: XPathDocumentDoesntContainElement('Document does not contain given element {xpath}!')
jdi-qasp-ml-celery  | Traceback (most recent call last):
jdi-qasp-ml-celery  |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
jdi-qasp-ml-celery  |     R = retval = fun(*args, **kwargs)
jdi-qasp-ml-celery  |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
jdi-qasp-ml-celery  |     return self.run(*args, **kwargs)
jdi-qasp-ml-celery  |   File "/jdi-qasp-ml/app/tasks.py", line 23, in task_schedule_xpath_generation
jdi-qasp-ml-celery  |     result = generate_xpath(element_id, page, document_uuid, config)  # calculation itself
jdi-qasp-ml-celery  |   File "/usr/local/lib/python3.7/site-packages/cachetools/__init__.py", line 737, in wrapper
jdi-qasp-ml-celery  |     v = func(*args, **kwargs)
jdi-qasp-ml-celery  |   File "/jdi-qasp-ml/utils/robula.py", line 523, in generate_xpath
jdi-qasp-ml-celery  |     "Document does not contain given element {xpath}!"
jdi-qasp-ml-celery  | utils.robula.XPathDocumentDoesntContainElement: Document does not contain given element {xpath}!

Ожидаем: Считаться должно без ошибок.
[Level Up.zip](https://github.com/jdi-testing/jdn-ai/files/11785404/Level.Up.zip)

**Comment by AlexeyGirin** [comment]
Обнаружили что из-за внутренней работы самой странички - JDN хэши которые мы проставили элементам - ВНЕЗАПНО - исчезли. Из-за чего - бэкэнд не находит этот элемент.
Необходимо:
1. Маша: при возврате ошибки с бэка - проверять начие JDN, если его нет - восстанавливать его и посылать на расчёт снова. НО - делать это только один раз!
2. Фёдор: Определять, что запрошенный JDN хэш не найден - возвращать корректную ошибку на фронт

**Comment by spiridonovfed** [comment]
№2 из сообщения выше - имплементировано в back-end 0.2.40

**Comment by MariiaNebesnova** [comment]
[3.12.504](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.504)

**Comment by AlexeyGirin** [comment]
Fixed.
