### ISSUE TITLE
Extend second level menu to fit all options

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1317]
1. Try to find HTML elements on page https://levelup.epam.com/skill/skillId=7770000000001942895&skillLevelId=7770000000000001003
2. Open context menu for any element

Observed result: Not all elements fits the menu
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/55073784-4656-404e-b928-d1047bc7fe51)

Expected: All menu elements are visible

**Comment by arslanbekova** [comment]
[3.12.497](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.497)

**Comment by AlexadrK** [comment]
JDN v 3.12.497 Back-end v 0.2.39
Chrome Version 114.0.5735.134 (Official Build) (64-bit)

Test result - PASS
![second level menu in browser window ](https://github.com/jdi-testing/jdn-ai/assets/21053451/b7bc5065-09b7-40f0-bad0-c93a456e57c0)
![second level menu in plugin window ](https://github.com/jdi-testing/jdn-ai/assets/21053451/b35c19d6-1fab-40d8-beb4-ae632f0dc5e3)
