### ISSUE TITLE
Coverage crash

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1318]
1. Try to find HTML elements on page https://levelup.epam.com/skill/skillId=7770000000001942895&skillLevelId=7770000000000001003
2. (some locators failed to calculate - ok)
3. Try to scroll down the site

Observed: All cover blocks disappear

Expected: All cover block remain

![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/582531c8-10b5-476c-a5ae-ef08a4220d9b)

**Comment by MariiaNebesnova** [comment]
[3.12.498](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.498)

**Comment by AlexeyGirin** [comment]
Fixed.
