### ISSUE TITLE
Групповое копирование с панели покрытия и с панели локаторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1323]
В данный момент - групповое копирование локаторов - работает только из трёх точечного меню в панели локаторов.
Из контекстного меню - не работает (там копируется только один локатор на который мы кликнули в процессе вызова контекстного меню)
А на панели покрытия - вообще отсутствует опция копирования в случае группового выделения

Необходимо, что бы - групповое копирование работало и на панели покрытия и на панели локаторов.

ВНИМАНИЕ.
На панели локаторов - нужно смотреть откуда было вызвано контекстное меню. Если оно вызвано от одного из выделенных локаторов - должны копировать всю группу. Если оно вызвано от одного не выделенного элемента - нужно копировать его одного.

**Comment by arslanbekova** [comment]
[3.12.503](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.503)

**Comment by AlexeyGirin** [comment]
Fixed.
