### ISSUE TITLE
Сделать Edit недоступным в случае группового выделения

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1324]
Сейчас - на панели локаторов при групповом выделении локаторов - в контекстном меню - есть опция Edit
Она открывает на редактирование тот локатор от которого мы вызвали контекстное меню.

Необходимо убирать опцию Edit если есть групповое выделение

ВНИМАНИЕ.
На панели локаторов - нужно смотреть откуда было вызвано контекстное меню. Если оно вызвано от одного из выделенных локаторов - должны убирать Edit. Если оно вызвано от одного не выделенного элемента - Edit убирать не надо

**Comment by arslanbekova** [comment]
[3.13.509](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.509)

**Comment by AlexeyGirin** [comment]
Fixed.
