### ISSUE TITLE
Групповой Advanced Calcolation

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1327]
В данный момент - при групповом выделении локаторов - опция Advanced Calculation есть только на панели покрытия.
Причём - она работает только на один локатор от которого было вызвана групповое меню.

Необходимо:
1. Запускать Advanced Calculation для всех выделенных локаторов если контекстное меню было вызвано от одного из выделенных локаторов (если оно было вызвано от невыделенного локатора - должно запускаться только для невыделенного локатора)
2. Добавить опцию Advanced Calculation в контекстное меню на панели покрытия

**Comment by arslanbekova** [comment]
[3.13.509](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.509)

**Comment by AlexeyGirin** [comment]
Fixed.
