### ISSUE TITLE
Групповой Delete

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1328]
Сейчас при групповом выделении на панели локаторов - опция Delete в контекстном меню работает только для того элемента от которого было вызвано меню.
(а вот на панели покрытия - всё норм - операция удаления применяется ко всем выделенным элементам)

Необходимо сделать, что бы на панели локаторов опция Delete выполнялась ко всем выделенным элементам

**Comment by arslanbekova** [comment]
[3.13.509](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.509)

**Comment by AlexeyGirin** [comment]
Fixed.
