### ISSUE TITLE
Снимать групповое выделение при клике правой кнопкой по невыделенному элементу (на панели локаторов)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1330]
1. Поищите HTML5 элементы для странички https://www.google.com/search?q=JDN&hl=ru&tbm=isch&source=hp&biw=1904&bih=952&ei=NF6UZOi1IYa8xc8PjPOhOA&iflsig=AOEireoAAAAAZJRsRNpF-sCSbFwfotvdYdoHh-KkHkTY&ved=0ahUKEwjon9XTjtf_AhUGXvEDHYx5CAcQ4dUDCAc&uact=5&oq=JDN&gs_lcp=CgNpbWcQAzIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQyBQgAEIAEMgUIABCABDIJCAAQgAQQChABMgUIABCABDIFCAAQgAQyBQgAEIAEUABYxwRgpgtoAHAAeACAAYQBiAHtApIBAzAuM5gBAKABAaoBC2d3cy13aXotaW1n&sclient=img 
Хотя можно и для любой.
2. Выделите (ипользуя CTRL) несколько локаторов на панели локаторов
3. Кликните правой кнопкой мыши не невыделенный локатор для вызова контекстного меню

Наблюдаем: Групповое выделение сохраняется, контекстное меню вызывается, элемент на которые мы кликнули - остаётся невыделенным

Ожидаем: Групповое выделение сбрасывается, контекстное меню вызывается, элемент на которые мы кликнули - становится выделенным (кстати - на панели покрытия - работает именно так)

**Comment by arslanbekova** [comment]
[3.12.503](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.503)

**Comment by AlexeyGirin** [comment]
Fixed.
