### ISSUE TITLE
Update ReactJS

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#1345]
Performance optimization is expected

After update, check that Locator menu update isn't fired on Add/Remove option click.
and `useLayoutEffect` callbacks still works as expected

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1491
[3.14.4](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.4)

**Comment by AlexeyGirin** [comment]
JDN v 3.14.10 Back-end v 0.2.40

Fixed.
