### ISSUE TITLE
[Minor] Попытка использовать русские буквы в названии - делает прохождение валидации невозможным даже если потом исправили на корректное имя

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1346]
JDN v 3.13.506 Back-end v 0.2.40

1. Попробуйте поискать HTML5 элементы с xPath на страничке https://www.linkedin.com/mynetwork/invite-connect/connections/ (хотя можно и на любой, наверное)
2. Выделите пару локаторов и создайте ПО.
3. Попробуйте переименовать ПО
4. Введите ПОЛНОСТЬЮ новое имя на русском
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/6e850599-e186-414d-b2f4-27ba3b44de10)

Наблюдаем: Начиная с этого момента даже если вы введёте абсолютно корректное имя - оно всё равно не будет проходить валидацию
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/267284aa-f4bf-4eb8-b24f-fcd6ce6e4bab)

Ожидаем: Должно проходить

**Comment by arslanbekova** [comment]
Описаный кейс - валидное поведение системы, так как название Java класса должно начинаться с заглавной буквы.

**Comment by AlexeyGirin** [comment]
Not a bug - first letter should be capital
