### ISSUE TITLE
Onboarding - small fixes

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1348]
- [x] попап онбоардинга открывается каждый раз, хотели вроде отслеживать этот момент  - Verified.

____

- [x] Это иконка варнинга, нужно её убрать - Verified.
<img width="300" alt="Снимок экрана 2023-06-30 в 13 27 23" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/41edbb7c-1cf5-4ab4-8644-ab9ae2c0003e">

____
- [x] переименовать кнопку «Cancel» в «Skip» - Verified.
<img width="500" alt="Снимок экрана 2023-06-30 в 13 42 58" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/16b7a133-f77f-4d22-95b6-e9f63af83d08">

_____
- [x] съехало выделение + можно прожать только 2 состояния чекбокса, в моём случае он выделяет все локаторы в дереве, нет состояния Indeterminate 
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/742e7b8f-6982-429a-b92e-268037af1e83)

<img width="500" alt="Снимок экрана 2023-06-30 в 13 31 55" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/6b5da08f-0411-42ef-a4c2-d8ad2be8ee6d">

___
- [x] переименовать кнопку «Save PO» в «Save Page Object»  - Verified.
<img width="500" alt="Снимок экрана 2023-06-30 в 13 32 32" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/6d7ab8f0-6f9d-4fe6-917d-6b2c6ab850c0">

___
- [x] 4ая иконка съехала (просто первые 3 окей) - Verified.
<img width="129" alt="Снимок экрана 2023-06-30 в 13 35 06" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/8f033afb-c16a-4df6-aa29-dff5b4cd930d">

___
- [x] Не блокируется контекстное меню - Verified.
![Context menu not blocked](https://github.com/jdi-testing/jdn-ai/assets/21053451/d5ab0cf3-7d0c-4cb8-9c9d-33c7b9f72e32)

___
- [x] Не блокируется иконка онбординга при прохождении онбординга - Verified.
![Onboarding tutorial icon not blocked](https://github.com/jdi-testing/jdn-ai/assets/21053451/10692111-6ea6-4e04-ba4e-e014100c78a0)

___
- [x] Не блокируется иконка Report a problem - Verified.
![Report a problem icon not blocked](https://github.com/jdi-testing/jdn-ai/assets/21053451/bda998ab-c183-4ec2-975f-9c467fc2e15d)

**Comment by kostrubin** [comment]
П.1: после любого закрытия онбоардинг диалога (cancel, start, X) устанавливать соответствующее значение в local storage.

**Comment by kostrubin** [comment]
6 пункт (выделение контекстного меню локатора) и расчёт состояния чекбокса лучше вынести в отдельные таски, так как это не просто визуальные фиксы онбоардинга. Остальное сделано.

**Comment by kostrubin** [comment]
[3.13.538](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.538)

**Comment by AlexeyGirin** [comment]
@SemyonKuznetsov - можешь отверифаить что пункт "съехало выделение + можно прожать только 2 состояния чекбокса, в моём случае он выделяет все локаторы в дереве, нет состояния Indeterminate" пофиксился и закрыть таску?

**Comment by Lisa5876** [comment]
JDN v 3.13.540 Back-end v 0.2.40
-  попап онбоардинга открывается только после установки новой версии фронта. Если открыть плагин второй раз с той же версией, попап онбординга не появляется
- иконка ворнинга не отображается
<img width="417" alt="2023-08-01_16h27_18" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/716cc479-565e-4098-a001-10883f68df82">
- кнопка "Cancel" переименована в "Skip"
<img width="436" alt="2023-08-01_16h27_45" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/344c9a82-044f-4a06-abc2-6dd286332d9e">
- поправлено выделение. В рамках онбординга можно выделить только 1 локатор
<img width="461" alt="2023-08-01_16h37_59" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/639560bf-772f-4ed6-a07e-fe34d4de4d5d">
- кнопка «Save PO» переименована в «Save Page Object»
<img width="443" alt="2023-08-01_19h52_25" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/ef572f3c-5a3d-4866-a09f-3139c7dfa0c4">
- кнопки контекстного меню, онбординга и Report a problem задизейблены. Кнопка Readme активна (ожидаемое поведение)
-  4ая иконка поправлена, съехала третья (заведу отдельный баг)

<img width="437" alt="2023-08-01_16h50_28" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/3f22f95f-2bff-4840-b7a1-da2de0038fd6">
