### ISSUE TITLE
[Medium] Обоардинг удаляет РО

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1349]
- [ ] онбоардинг при его завершении удаляет все созданные до этого РО и оставляет только созданный при его прохождении

___
- [ ] неначатый  онбоардинг тоже удаляет все созданные до этого РО

https://github.com/jdi-testing/jdn-ai/assets/101407186/afbc632c-38c1-4bb6-adca-f04f2ced6a5a

___

**Comment by SemyonKuznetsov** [comment]
Несбрасываемые состояния:

1. PO-лист пустой (нечего сбрасывать)
2. РО-лист с сохранёнными РО

Начиная с этих экранов хотелось бы после окончания туториала вернуться сюда с +1 созданным РО
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/9089e104-601a-43d6-b4b2-9cb4b12cf2b8)

Сбрасываемые состояния:
Если коротко то все формы редактирования РО

1. Создание РО (первичные настройки), удаляем тот РО, который развёрнут
2. Создание РО, так как это только создание и он не был сохранён, то мы удаляем его полностью
3. Создание РО, тот же что и пункт 2, просто что-то натыкано, всё ещё ничего не сохранено, удаляем полностью
4. Редактирование РО, если мы открыли его, ничего не изменили и включили РО, то мы просто закрываем редактирование РО, но не удаляя его
5. Редактирование РО, если мы что-то поменяли и не сохранили, то мы закрываем РО без сохранения, но не удаляем сам РО

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/9a741514-be95-478e-a955-625ee39f45f8)

**Comment by AlexeyGirin** [comment]
Пока добавляем заглушку (предупреждение) что всё будет удалено, и по нормальному - будем фиксить в следующем релизе

**Comment by SemyonKuznetsov** [comment]
обычный без РО:
Would you like to start the onboarding?
__
обычный с РО:
Your Page Objects will be deleted. 
Would you like to start the onboarding?
__
прогресс без РО:
Your current progress will not be saved. Are you sure you want to start the onboarding?
__
прогресс с РО:
Your Page Objects will be deleted and the current progress will not be saved. Would you like to start the onboarding?

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1466
[3.13.561](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.561)
