### ISSUE TITLE
[US-9-3][US-7-2][Edit] Открытое окно Edit в двух окнах приводит к невозможности закрытия окна сохранения. Полностью блокирует работу пользователя

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#135]
JDN v 3.0.99
Back-end v 2021-11-26-14.32.52
mail.ru
github.com

1. Открываем оба сайта
2. Открываем плагин на обоих страницах
3. Нажимаем [Identify] на одной из страниц
4. После распознания списка элементов, нажимаем [Identify] на второй странице
5. Нажимаем [...] в списке элементов 
6. Открываем предыдущую страницу
7. Нажимаем [...] в списке элементов
8. Переходим на страницу где окно edit открыли в первый раз
9. Нажимаем кнопки [edit] \ [save] \ [cancel] \ [x]

 ОР: 
Кнопки будут работать в соответствии с ТЗ
ФР:
Кнопки не работают

Дополнительное действие:
- Закрываем первое открытое меню edit 
- При открытом окне Edit можно нажать кнопку  [Clear all]
- Нажать [Identify]
- Открыть меню edit 
Работа с плагином заблочена на обоих страницах

**Comment by AlexeyGirin** [comment]
При открытии второго (и далее) инстанса плагина - нужно запретить пользователю пользоваться плагином на второй страничке - возможно - выводить красненьким мессадж про это и блокировать кнопку Identify
@mariia-tokarchuk отрисовать дизайн

**Comment by mariia-tokarchuk** [comment]
При открытии второй и более вкладки плагина, вместо стандартного интерфейса, пользователю должно отображаться уведомление об ошибке:

<img width="1400" alt="error" src="https://user-images.githubusercontent.com/89466817/149281512-22cedcc1-1f6c-4db2-8217-3c2bf4ed7faa.png">

**Comment by AlexeyGirin** [comment]
Duplicates #195
