### ISSUE TITLE
[Medium] Для локаторов добавленных в PO, удалённых а затем восстановленных нет выделения синим в окне покрытия

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1353]
**Шаги востпроизведения:**
1. Добавить несколько локаторов в PO (галочка в чекбокс)
2. Удалить локаторы
3. Восстановить удалённые локаторы

**Ожидаемый результат:**
Восстановленные локаторы, добавленные в РО, выделены синим в окне покрытия.
**Фактический результат:**
Восстановленные локаторы, добавленные в РО, не выделены синим в окне покрытия.

https://github.com/jdi-testing/jdn-ai/assets/21053451/6dfbd86b-4b45-45fa-88bc-990c23be60f8

**Comment by MariiaNebesnova** [comment]
TOGGLE_DELETED срабатывает для нескольких кейсов: для удаления/восстановления через контекстное меню и через кнопку Cancel на нотификейшене. Фикс надо будет проверить для всех этих случаев

**Comment by vitaepam** [comment]
[3.13.521](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.521)

**Comment by AlexadrK** [comment]
JDN v 3.13.524 Back-end v 0.2.40
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS
