### ISSUE TITLE
[Critical] Использовать двойные кавычки внутри двойных кавычек нельзя. У нас используются в CSS селекторах

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1356]
1. Попробуйте поискать CSS селекторы для HTML5 элементов на сайте https://www.google.com/
2. Система найдёт селекторы которые выглядят во так: `@UI("[data-ved=" ahUKEwixyMKarPX_AhUPCewKHeH2AscQ4dUDCA4"]")`

Наблюдаем: Система использует двойные кавычки внутри двойных кавычек.

Ожидаем: Правильно будет вот так: 
При экспотре в файл или при копировании в буфер - все двойные кавычки внутри первых двойных кавычек должны заменяться на экранированные двойные кавычки: `"` --> `\"`
`@UI("[data-ved=\" ahUKEwixyMKarPX_AhUPCewKHeH2AscQ4dUDCA4\"]")`
В самом локаторе в плагине и в редакторе - оставить всё как есть

**Comment by arslanbekova** [comment]
[3.13.513](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.513)

**Comment by AlexeyGirin** [comment]
Работает в 3.13.513
Но в 3.14 - нужно будет проверить отдельно

**Comment by AlexeyGirin** [comment]
Fixed.

**Comment by AlexeyGirin** [comment]
Fixed.

**Comment by AlexeyGirin** [comment]
Описание обновлено

**Comment by arslanbekova** [comment]
[3.13.526](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.526)

**Comment by AlexadrK** [comment]
JDN v 3.13.529 Back-end v 0.2.40
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS

![image](https://github.com/jdi-testing/jdn-ai/assets/21053451/66a3fcfe-1883-42a2-baa7-181984689961)
