### ISSUE TITLE
Система неправильно копирует локатор если его содержимое содержит эскейп последовательность

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1357]
1. Попробуйте поискать CSS селекторы для HTML5 элементов на сайте https://www.google.com/
2. Система найдёт селекторы которые выглядят во так: `@UI("[data-ved="\30 ahUKEwixyMKarPX_AhUPCewKHeH2AscQ4dUDCA4"]")`
3. Попробуйте скопировать его в буфер обмена и вставить куда-нить

Наблюдаем: Эскейп последовательность превратилась в символ: `@UI("[data-ved=" ahUKEwixyMKarPX_AhUPCewKHeH2AscQ4dUDCAk"]")`

Ожидаем: Превращения происходить не должно - `@UI("[data-ved="\30 ahUKEwixyMKarPX_AhUPCewKHeH2AscQ4dUDCA4"]")`

**Comment by arslanbekova** [comment]
[3.13.513](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.513)

**Comment by AlexeyGirin** [comment]
Работает в 3.13.513
Но в 3.14 - нужно будет проверить отдельно

**Comment by AlexeyGirin** [comment]
Fixed.
