### ISSUE TITLE
[US-15-4] data-ved атрибут - это временный хэш. Привязываться к нему плохо

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1359]
**Проблема:** атрибут data-ved - это временный хэш и при перезагрузке страницы - он поменяется.
Привязываться к нему плохо.

**Actual result:**
1. Попробуйте поискать CSS селекторы для HTML5 элементов на сайте https://www.google.com/
2. Система найдёт селекторы которые выглядят во так: `@UI("[data-ved='\30 ahUKEwixyMKarPX_AhUPCewKHeH2AscQ4dUDCA4']")`
Если искать xPath то найдётся этот - //*[@data-ved='0ahUKEwixyMKarPX_AhUPCewKHeH2AscQ4dUDCAk']

**Expected result:** Надо дать пользователю возможность исключить использование конкретных атрибутов при поиске локатора или селектора.

**Notes:** Видимо - такая возможность нужна когда пользователь уже видит посчитанный локатор или селектор - нужно дать ему возможность сказать системе что данный атрибут не подходит и пересчитать этот или все локаторы с подобным атрибутом

**Comment by savinovava** [comment]
#1575
