### ISSUE TITLE
Не происходит генерация локаторов

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#136]
macOS

JDN v 3.0.99
Back-end v 2021-11-26-14.32.52

после нескольких запусков плагина подряд начала возникать ошибка на каждой новой странице, которую пытаюсь сгенерировать в пределах этой сессии:

пример:
1. открываю страницу https://jdi-testing.github.io/jdi-light/complex-table.html
2. нажимаю Identify
3. все локаторы зависли в статусе "ожидают генерации"
<img width="636" alt="Screenshot 2021-12-14 at 10 44 37" src="https://user-images.githubusercontent.com/89466817/145966163-faded5b7-30ea-4052-8573-b885b0b9464c.png">

4. Inspect - Network 
<img width="933" alt="Screenshot 2021-12-14 at 11 02 29" src="https://user-images.githubusercontent.com/89466817/145966833-7f60bcfc-a0d5-4c75-b020-56e497bc6c55.png">

5. get_task_status
<img width="1437" alt="Screenshot 2021-12-14 at 10 42 36" src="https://user-images.githubusercontent.com/89466817/145967074-ea353f6d-4300-4e69-a550-f5110a9d41e2.png">

**Comment by aleksandrovskiys** [comment]
Не получилось воспроизвести. Такое поведение только с какими-то определенными настройками?
Вообще выглядит так, будто по предыдущим страницам локаторы еще не досчитались и до новых просто не доходит очередь.

**Comment by mariia-tokarchuk** [comment]
> aleksandrovskiys

нет, никак настроек. сначала сгенерировала несколько страниц, затем в таком состоянии плагин начал виснуть постоянно, когда пыталась каждую новую страницу сгенерировать.

вот что еще обнаружила, видимо из-за этого и возникает такая проблема. работа процессора во время этого:
<img width="953" alt="Screenshot 2021-12-14 at 13 58 25" src="https://user-images.githubusercontent.com/89466817/146324790-5f29cfed-25c8-47b2-ac8f-41e69fa88b7f.png">

а вот работа процессора после того как остановила докер:
<img width="956" alt="Screenshot 2021-12-14 at 13 59 43" src="https://user-images.githubusercontent.com/89466817/146325030-e83c0984-f9f9-4a94-a516-676b3a681f0b.png">

**Comment by MariiaNebesnova** [comment]
задачки на фронт: #146 #148

**Comment by aleksandrovskiys** [comment]
Добавил отмену задач при закрытии соединения с сокетом. Для проверки добавил эндпоинт с списком активных задач (как тех, которые уже выполняются, так и запланированных) http://localhost:5050/celery_tasks. По этому урлу можно проверить, что задачи отменяются при закрытии плагина и, если нужно, то отменить старые.
Версия  - Back-end v 2022-02-06-12.08.33

**Comment by IoffeM** [comment]
JDN v 3.1.118
Back-end v 2022-01-31-15.52.11
Chrome

done.
should be retested after https://github.com/jdi-testing/jdn-ai/issues/249 fix
