### ISSUE TITLE
[Medium] При создании дубликата в окне плагина не навигирует к существующему локатору.

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1363]
**Шаги воспроизведения:**

1. Распознать локаторы на странице
2. Скопировать локатор из верхней части страницы
3. В окне плагина прокрутить страницу вниз до конца
4. Нажать кнопку "+ Custom locator"
5. Указать скопированный локатор
6. Нажать на refer to the original locator

**Ожидаемый результат:**
При создании дубликата - навигировать к существующему локатору в окне покрыти и окне плагина

**Фактический результат:**
В окне плагина не навигирует к существующему локатору

https://github.com/jdi-testing/jdn-ai/assets/21053451/e6d20612-628f-41fc-9a4f-05313715daee

The issue blocks https://github.com/jdi-testing/jdn-ai/issues/1150

**Comment by arslanbekova** [comment]
[3.13.516](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.516)

**Comment by AlexadrK** [comment]
JDN v 3.13.516 Back-end v 0.2.40
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS

https://github.com/jdi-testing/jdn-ai/assets/21053451/d7dc7727-ca7a-4873-9954-2cadc429f7cc
