### ISSUE TITLE
[High] No able to edit not valid custom locator

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1365]
JDN v 3.13.512 Back-end v 0.2.40

**Steps to reproduce:**

1. Create and save a custom locator without or not valid locator expression
2. Open the  locator to edit
3. Edit name/Block type/locator expression and save

**ER:** locator saved with a new name/Block type/locator expression

AR: Changes not saved
![No able to edit not valid custom locator](https://github.com/jdi-testing/jdn-ai/assets/21053451/b041d60a-b04a-44ed-b481-18bb3d4ef0ec)

**Comment by arslanbekova** [comment]
[3.13.517](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.517)

**Comment by AlexadrK** [comment]
Fixed.
