### ISSUE TITLE
Вызов и отработка пункта контекстного меню не должна сбрасывать селекшен блока на панели покрытия

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1368]
1. Используя Empty Page Object путь - поищите xPath локаторы для HTML5 элементов на сайте https://www.otto.de/
2. Кликните правой кнопкой мышки по любому блоку и выберете Edit

Наблюдаем: Меню закрывается, селекшен сбрасывается, диалог редактирования - не открывается (на более лёгком сайте - открывается, конечно)

Ожидаем: Меню закрывается, селекшен НЕ сбрасывается, диалог редактирования - открывается

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.540

**Comment by AlexeyGirin** [comment]
Fixed.
