### ISSUE TITLE
Удаление неселектнутого локатора из ПО - должно его селектать (что бы дать возможность его обратно добавить в ПО если удалили по ошибке)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1373]
1. Используя Empty Page Object путь - поищите xPath локаторы для HTML5 элементов на сайте https://www.linkedin.com/mynetwork/invite-connect/connections/
2. Добавьте пару-тройку локаторов в ПО (важно что бы по итогу этой операции они не были бы выделени в панели локаторов)
3. Нажмите на галочку присутствия локатора в ПО

Наблюдаем: Локатор исчез из списка как его и не было

Ожидаем: Система выделит его в списке локаторов, снимет галочку (давая таким образом шанс вернуть его обратно + экран покрытия метнётся и покажет этот элемент - это тоже нужно)

**Comment by MariiaNebesnova** [comment]
[3.13.548](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.548)

**Comment by Lisa5876** [comment]
JDN v 3.13.550 Back-end v 0.2.40
Test result - pass
, 
При снятии галочки с чекбокса присутствия локатора в ПО, локатор селектается, а не удаляется сразу. Юзер может снова поставить галочку. Экран покрытия скролится до анчекнутого элемента, сам элемент выделяется оранжевой рамкой.

Если юзер после этого селекнет другой локатор в списке локаторов, докатор, у которого убрали галочку, удалится из списка

https://github.com/jdi-testing/jdn-ai/assets/89458651/c025658c-ab4d-41bd-bbd2-34fbb10968ea
