### ISSUE TITLE
Не собирать статистику если бэк запущен локально

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1374]
В данный момент мы уменьшаем количество используемых ядер для расчётов на два, если знаем что бэк запущен локально.
В то же время - сбор статистики так же осуществляется и тогда когда мы гоняем бэк локально, хотя шансов эту статистику получить и как-то использовать - НЕТ.

Поэтому.

Давайте отключим функциональность по сбору статистики если бэк запущен локально в докере.

**Comment by mobilisf** [comment]
JDN v 3.14.23 Back-end v 0.2.45

Статистика больше не собирается локально
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/d6c0148f-da94-4d77-93cf-88e662869907)
