### ISSUE TITLE
Не запускать расчёт CSS селекторов и xPath локаторов в бэкграунде есть количество локаторов более 500 (в случае пустого ПО)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1375]
В данный момент - система работает с приемлемой производительностью, если элементов на покрытии 500 и менее. При этом - фоновый расчёт локаторов дико перегружает систему и работать с ней - становится решительно невозможно. А ожидание расчёта CSS селекторов - вызывает ощутимую задержку перез началом открытия окна ПО.
Поэтому.
Если у нас более 500 локаторов, то:
В случае пустого ПО:
1. Расчёт селекторов перед открытием окна редактирования ПО - не запускать
2. Расчёт локаторов в фоне - не запускать
3. Расчёт для локатора запускать только в тот момент когда пользователь выделяет его на покрытии

В случае полного ПО:
1. Если выбраны xPath как дефолтный тип - расчёт CSS не запускать, а запускать его если пользователь меняет тип элемента на CSS или хочет скопировать (расчёт xPath оставляем как сейчас - всё считаем)
2. Если выбран CSS как дефолтный тип - расчёт xPath в фоне не запускать, а запускать его если пользователь меняет тип элемента или хочет скопировать (расчёт CSS оставляем как сейчас - всё считаем, но потом есть задача что бы делать это в фоне)

**Comment by AlexeyGirin** [comment]
Если CSS не просчитан - что делать? ПРОИНВЕСТИГИРОВАТЬ - конвертация full xPath?
Обсудим за пределами дейлика

**Comment by MariiaNebesnova** [comment]
[3.13.528](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.528)

**Comment by AlexeyGirin** [comment]
Done.

**Comment by Lisa5876** [comment]
JDN v 3.13.557 Back-end v 0.2.40
Если выбраны xPath как дефолтный тип - расчёт CSS не запускать, а запускать его если пользователь меняет тип элемента на CSS или хочет скопировать  - pass
Если выбран CSS как дефолтный тип - расчёт xPath в фоне не запускать, а запускать его если пользователь меняет тип элемента или хочет скопировать - pass
