### ISSUE TITLE
Селектор найденный для элемента - перестаёт работать после редактирования без внесения изменений

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1376]
1. Используя Generate All путь - поищите CSS селекторы для HTML5 элементов на сайте https://www.otto.de/
2. Найдите элемент с именем damenMode (вообще подойдет любой элемент их меню в шапке)
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/f3ed527c-f2b0-4fb2-911b-c9b02bd6e766)
3. Откройте этот элемент на редактирование, добавьте любой символ к селектору и тут же сотрите его

Наблюдаем: Начиная с этого момента - система сообщает, что The locator was not found on the page.
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/ad22322b-e23d-4656-beab-d1aee63a5fda)

Ожидаем: С локатором всё нормально

**Comment by arslanbekova** [comment]
[связано с 1356](https://github.com/jdi-testing/jdn-ai/issues/1356)

**Comment by arslanbekova** [comment]
[3.13.526](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.526)

**Comment by AlexadrK** [comment]
JDN v 3.13.529 Back-end v 0.2.40
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS
