### ISSUE TITLE
[Minor] Анимация раскрытия контекстного меню всегда идёт от левого верхнего угла, хотя уместно это не всегда

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1377]
В большинстве случаев - вызов контекстного меню на панели покрытия - вызывает появление меню левым верхним углом к мышке. И анимация раскрытия - тоже идёт от левого верхнего угла. Красиво.

Однако. Есть случаи когда меню возникает правым верхним или нижним углом к мышке (или даже левым нижним углом), но анимация раскрытия - всё равно идёт от левого верхнего угла что смущает.

При этом - для контекстного меню на панели локаторов - такой проблемы нет. Там анимация раскрытия - идёт от верхней или от нижней грани и корректно согласуется с положением мыши

Необходимо согласовать анимацию отрисовки контекстного меню на панели покрытия с положением курсора мышки

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1570
[3.14.26](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.26)

**Comment by AlexeyGirin** [comment]
Fixed.
