### ISSUE TITLE
[Critical] Нужно экранировать двойные кавычки в тексте локаторов при экспорте и при копировании в буфер обмена

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1379]
1. Поищите xPath локаторы для HTML5 элементов на сайте https://www.otto.de/ через Generate All
2. Найдите локатор с именем inspiration и добавьте его в ПО
(Текст xPath'а будет типа - `//*[@data-nav-tracking-menu-navigate-down='[{"method":"submitEvent","dataContainer":{"nav_MenuAction":"down","nav_MenuRank":1,"nav_MenuLevel":1,"nav_MenuTitle":"Inspiration","nav_MenuType":"curated","nav_GlobalNavigation":"inspiration"}}]']` )
3. Создайте ПО
3. Экспортните его в проект и откройте в IDEA
4. Попробуйте скомпилировать

Наблюдаем: Идея ругается и не компилит
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/4acf6789-efe4-4a17-82ca-ea0713f1edc9)

Ожидаем: В момент экспорта и/или копирования локатора в буфер - все двойные кавычки буду экранироваться обратным слешем, т.е. символ `"` будет заменятся на `\"`
И наш локатор будет выглядеть в итоге так: `@UI("//*[@data-nav-tracking-menu-navigate-down='[{\"method\":\"submitEvent\",\"dataContainer\":{\"nav_MenuAction\":\"down\",\"nav_MenuRank\":1,\"nav_MenuLevel\":1,\"nav_MenuTitle\":\"Inspiration\",\"nav_MenuType\":\"curated\",\"nav_GlobalNavigation\":\"inspiration\"}}]']")
`
Идеально, конечно - на панели локаторов тоже отображать правильно, а вот в окне редактировать - должно оставаться как обычно

**Comment by AlexeyGirin** [comment]
Панель локаторов - пока не меняем

**Comment by arslanbekova** [comment]
[3.13.525](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.525)

**Comment by AlexadrK** [comment]
JDN v 3.13.525 Back-end v 0.2.40
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS
![shielded double quotes in locator text](https://github.com/jdi-testing/jdn-ai/assets/21053451/1d3edfdd-cc84-4e09-a369-cb4869c8eba7)
