### ISSUE TITLE
[design] User Flow for new design

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#138]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424911/User+Flow

**Comment by mariia-tokarchuk** [comment]
New version - Task Flow / User Flow

Figma file: https://www.figma.com/file/4S6WCTPeRhJlfz6pR56GGv/JDN?node-id=0%3A1

**Comment by mariia-tokarchuk** [comment]
Done
