### ISSUE TITLE
Не задвоенные обратные слеши в CSS селекторах

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1385]
**Шаги воспроизведения:**
1. Распознать CSS локаторы на странице https://habr.com/ru/all/
2. Сохранить локаторы в PO
3. Скачать и открыть PO в IDE

**Ожидаемый результат:**
Обратные слеши задвоенны

**Фактический результат:**
Обратные слеши не задвоенны, из за этого локаторы не валидны для IDE
![IDE non-twinned backslashes ](https://github.com/jdi-testing/jdn-ai/assets/21053451/c68e8fd3-26aa-4d6b-828d-86fb2a80f730)

**Comment by arslanbekova** [comment]
[3.13.525](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.525)

**Comment by AlexadrK** [comment]
JDN v 3.13.525 Back-end v 0.2.40
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS
![2023-07-14 16_14_53-DevTools - habr com_ru_all_](https://github.com/jdi-testing/jdn-ai/assets/21053451/3c4088e2-a159-465b-a2e8-66e0b192f73b)
