### ISSUE TITLE
Зависает расчёт локаторов когда их много

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1386]
1. Откройте приаттаченный файл
[LinkedInConnections.zip](https://github.com/jdi-testing/jdn-ai/files/12036359/LinkedInConnections.zip)
2. Попробуйте поискать xPath локаторы для HTML5 элементов
Наблюдаем: Локаторы не считаются, хотя инфа от бэка приходит

![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/ab57a89e-d294-435a-b77d-ef09012a6488)

**Comment by MariiaNebesnova** [comment]
проверить с #1375

**Comment by MariiaNebesnova** [comment]
[3.13.528](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.528)

**Comment by AlexadrK** [comment]
JDN v 3.13.529 Back-end v 0.2.40
Chrome Version 115.0.5790.102 (Official Build) (64-bit)

Test result - PASS
![2023-07-25 09_49_50-LinkedIn](https://github.com/jdi-testing/jdn-ai/assets/21053451/37e00d18-e33a-4e82-b7d5-ec2b67cf42e9)
