### ISSUE TITLE
[Critical] No able to copy generated xPath locator

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1388]
**Steps to reproduce:**
JDN v 3.13.525 Back-end v 0.2.40

1. Generate xPath locators
2. Copy locator by copy icon
3. Copy via the context menu: xPath, xPath+FindBy, xPath+JDI Annotation

**AR:** locators are not copied to the clipboard
**ER:** locators are successfully copied to the clipboard

**Comment by arslanbekova** [comment]
[3.13.526](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.526)

**Comment by AlexadrK** [comment]
Not copy by click on copy icon
![image](https://github.com/jdi-testing/jdn-ai/assets/21053451/402883b6-3033-4270-81d2-cfba0dc696f9)

**Comment by arslanbekova** [comment]
[3.13.529](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.529)

**Comment by AlexadrK** [comment]
JDN v 3.13.529 Back-end v 0.2.40
Chrome Version 114.0.5735.199 (Official Build) (64-bit)

Test result - PASS
