### ISSUE TITLE
[US-11-1] Непросчитанный локатор должен быть обведён штриховой линией на панели покрытия пока он не расчитан или расчёт не закончился

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1398]
1. Поищите все xPath локаторы HTML5 элементов на сайте https://www.otto.de/
Система не будет запускать авторасчёт локаторов т.к. их более 500 (это ок)
Наблюдаем: Все локаторы на панели покрытия - имеют сплошную линию обводки
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/6da0f3f8-60a8-45cd-beec-b4d9fd094aa7)

Ожидаем: Пока локатор не просчитан или просчёт ещё не закончен - обводка должна быть тонкой пунктирной линией

___
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910721/US-11-1+Interaction+with+an+element+on+page

The dashed stroke style means that:
- The locator is not calculated 
- First locator was generated (for example xPath) and the generation of the second one (for example CSS) was started

**Comment by SemyonKuznetsov** [comment]
[14:57] Mariia Nebesnova

Alexey Girin, опять по ней кейс с вопросом: икспас, уже рассчитан, потому что по умолчанию. Пользователь запускает рассчет селектора. Граница подсветки должна становиться штрихованой?

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1456
[3.13.556](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.556)

**Comment by AlexeyGirin** [comment]
Fixed.
