### ISSUE TITLE
обновить библиотеку иконок Phosphor до второй версии

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1406]
[phosphoricons](https://phosphoricons.com/) 
[phosphoricons github](https://github.com/phosphor-icons/homepage#readme)
[figma library](https://www.figma.com/file/VmPPmpZO1UN0DAT8wuqnln/Phosphor-Icons-(v2)?type=design&t=ZRAJnPeLt6kumapU-6)

**Comment by MariiaNebesnova** [comment]
обвновить `phosphor-react` до последней версии. см. https://github.com/phosphor-icons/react

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1497
[3.14.6](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.6)

**Comment by AlexeyGirin** [comment]
Fixed.
