### ISSUE TITLE
addition to the onboarding

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1407]
у нас появилась новая кнопка, надо дополнить текст про неё

шаг 4/14, генерация РО
добавить текст: "Also, you can create an Empty Page Object and then select the elements you need for generation."

[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=8391-377434&mode=design&t=FFREBsKS7moX16bj-4)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/936fd130-6c2c-4ea7-b6c8-29ad062c04ff)

- подсветка такая же, на одной кнопке
- для Empty Page Object онбординг должен уводить в другой флоу (#1411), который должен быть реализован одновременно/после задачи #1218

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1510
https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.9

**Comment by AlexeyGirin** [comment]
JDN v 3.14.10 Back-end v 0.2.40

Not fixed.
Сейчас - система по какой-то причине пропускает шаг 4/14. 
Т.е. после шага 3/14 при нажатии шага Generate:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/22510f6b-7167-465f-8822-990286a6c53a)
Что-то моргает и мы сразу оказываемся на шаге 5/14
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/bb6b0f19-63aa-4be2-9150-01415682457f)

**Comment by AlexeyGirin** [comment]
JDN v 3.14.10 Back-end v 0.2.40

Fixed.
