### ISSUE TITLE
[High] РО сгенерированный с аннотацией @FindBy сохраняется в файл как @UI

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1408]
**Шаги востпроизведения:**

Запуситить генерацию PO c аннотацией @FindBy
Сохранить РО
Скачать РО как файл или архив
Открыть в блокноте или IDE

**Фактический результат:**
Для всех локаров аннотация `@UI`
**Ожидаемый результат:** 
В файле локаторы с аннотацией `@FindBy`

![2023-07-26 09_33_06-Settings](https://github.com/jdi-testing/jdn-ai/assets/21053451/cdcbaaa3-3b2e-4806-a3d3-5dd46e069088)

Блокирует таску https://github.com/jdi-testing/jdn-ai/issues/1269

**Comment by kostrubin** [comment]
[3.13.539](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.539)
