### ISSUE TITLE
Онбоардинг - Система не указывает на иконку контекстного меню, элемент онбоардинга появляется раньше чем локаторы, может быть его как-то придержать и показать когда локаторы появятся на странице?

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1415]
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/66e9c8fc-c9bc-4b8f-84ec-5ae32e57d238)

Подробности у Семёна

**Comment by MariiaNebesnova** [comment]
[3.13.540](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.540)

**Comment by AlexeyGirin** [comment]
Fixed.
