### ISSUE TITLE
[1pt][US-6-4][Regress] Не правильная работа выделения  сгенерированных локаторов

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#142]
JDN v 3.0.100
Back-end v 2021-11-26-14.32.52
Chrome
https://jdi-testing.github.io/jdi-light/complex-table.html
Шаги:
1. Открываем сайт
2. Нажимаем [identify]
3.  Выбираем все локаторы в списке локаторов (общим чек боксом)
4.  Снимаем все выделенные локаторы тем же самым чек боксом

ОР:
Прорисованные локаторы снова станут оранжевого цвета
ФР:
Локаторы остались окрашены в синий цвет
<img width="1440" alt="Снимок экрана 2021-12-15 в 5 37 36 PM" src="https://user-images.githubusercontent.com/61897393/146208542-de835c2c-430d-4d22-aa8e-def01418eaee.png">

**Comment by MariiaNebesnova** [comment]
3.0.101

**Comment by MariiaNebesnova** [comment]
fe  - 0.5pt

**Comment by pulya-na-vullet** [comment]
https://user-images.githubusercontent.com/61897393/146522459-c13326e9-dc6f-4bbf-9c4b-05f87ac9c92f.mp4
Ретест бага произвел, баг не воспроизводится 
JDN v 3.0.101
Back-end v 2021-12-01-14.52.21
