### ISSUE TITLE
Уменьшить время показа уведомлений в окне плагина

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1420]
При работе с локаторами уведомления показываются очень долго, надо уменьшить до прежнего значения, 2 секунды?

**Comment by MariiaNebesnova** [comment]
по дизайну, 5 секунд

**Comment by MariiaNebesnova** [comment]
[3.13.542](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.542)

**Comment by AlexeyGirin** [comment]
Fixed.
