### ISSUE TITLE
[Blocker] При любом взаимодействии с сгнерерированным локтором или соддании кастомного локатора плагин крашится

### ISSUE THREAD

**Issue by AlexadrK** [jdi-testing/jdn-ai#1422]
Шаги востпроизведения:

1. Распознайте локаторы на странице или создайте кастомный локатор
2. Выбирите опцию Edit для локатора
3. Измените любой атрибут у локатора 

Ожидаемый результат: атрибут изменяется
Фактический результат: плагин крашится

![2023-07-31 13_26_18-Docker_ Accelerated, Containerized Application Development](https://github.com/jdi-testing/jdn-ai/assets/21053451/652efc1e-850b-4484-ad97-3b61156f17c6)

**Comment by MariiaNebesnova** [comment]
[3.13.543](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.543)

**Comment by Lisa5876** [comment]
JDN v 3.13.543 Back-end v 0.2.40
Chrome Version 115.0.5790.110 (Official Build) (64-bit)
Test result - pass
Юзер может умпешно изменять атрибуты локатора и сохранять изменения

https://github.com/jdi-testing/jdn-ai/assets/89458651/794d5721-fcf8-4af0-b3be-8756782ba55b
