### ISSUE TITLE
[Medium] Процесс онбоардинга должен обнулять существующий фильтр или корректно работать с ним. Иначе - начинается расколбас

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1425]
1. Поищите xPath локаторы для HTML5 элементов на  страничке https://www.linkedin.com/messaging/
2. (оно что-то найдёт) Пойдите в фильтр и отключите все элементы кроме UIElement
3. Запустите Onboarding нажав на кнопку сверху
Наблюдаем: Начиная с 6 шага (Context menu) начинается полный расколбас и завершить онбоардинг уже не получится
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/d47669f8-7609-4740-8e74-1352bdf5a7ce)
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/125f4183-ac3f-4857-ba75-5937c35adde2)
Отмотать назад - тоже
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/273d67f5-dc38-46b0-abeb-fbb951613c01)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1608
[3.14.37](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.37)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.38 - Passed
All 14 steps finished successfully
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/e644098c-3a77-45f4-8be4-32b3e28b279c)
