### ISSUE TITLE
[Critical] Empty Page Object путь теперь всегда сообщает что элементы не нашлись (хотя они нашлись)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1427]
Видимо баг наведён вот этой фичей: https://github.com/jdi-testing/jdn-ai/issues/1144

JDN v 3.13.540 Back-end v 0.2.44

1. Поищите xPath локаторы для HTML5 элементов на страничке https://www.otto.de/ используя **Empty Page Object** кнопку

Наблюдаем: Несмотря на то, что на покрытии элементы есть - система рапортует что их не нашли
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/f8f27ffa-6fae-41be-81f4-3d8d9bb7d569)

**Comment by Iogsotot** [comment]
Fixed https://github.com/jdi-testing/jdn-ai/pull/1446
[3.13.550](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.550)
