### ISSUE TITLE
[High] При попытки создания "Empty Page Object" появляется ошибка "Unable to Identify Elements"

### ISSUE THREAD

**Issue by Lisa5876** [jdi-testing/jdn-ai#1429]
При создании "Empty Page Object" (не зависимо от того, какая библиотека/locator type выбраны), появляется ошибка "Unable to Identify Elements", при том, что на странице элементы выделены пунктирной рамкой
<img width="956" alt="2023-07-31_15h26_05" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/847a26f1-d3cc-4960-b272-513dc810676e">

Env:
JDN v 3.13.540 Back-end v 0.2.40
Version 115.0.5790.110 (Official Build) (64-bit)

Шаги востпроизведения:
1. Запустите плагин;
2. Нажмите "Page object";
3. Нажмите "Empty Page Object" (с любыми настройками)

Фактический результат:
Появляется ошибка "Unable to Identify Elements", при том, что на странице отображается, что локаторы считаются.
Если нажать "Open Settings" создается пустой объект. При попытке его редактировать появляется та же ошибка
<img width="876" alt="2023-07-31_15h40_14" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/3bc08723-c35c-4275-af68-d426e43cda98">

Ожидаемый результат:
На пустом списке локаторов отображается текст: "Select the elements you need on the web page coverage and add them to the PO via a double-click or through the context menu", юзер может выбрать элементы.
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/50daadca-53d2-4469-8c9b-ee3fd16f4869)

Workaround:
Можно нажать "Cancel" на сообщении об ошибке, тогда можно будет добавить локаторы

https://github.com/jdi-testing/jdn-ai/assets/89458651/5051c9c2-0949-46da-a3a8-00662559bb7b

**Comment by Iogsotot** [comment]
duplicate https://github.com/jdi-testing/jdn-ai/issues/1427

**Comment by Iogsotot** [comment]
Fixed https://github.com/jdi-testing/jdn-ai/pull/1446
[3.13.550](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.550)

**Comment by Lisa5876** [comment]
Дубликат
Протестировано в рамках  https://github.com/jdi-testing/jdn-ai/issues/1427
