### ISSUE TITLE
[Critical] Во время множественного копирования локаторов система начинает экранировать все кавычки кроме двух на всю группу, а не двух на кадлый локатор

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1431]
1. Начните создавать ПО для всех локаторов со следующими параметрами для страницы https://jdi-testing.github.io/jdi-light/contacts.html:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/9014d352-c32c-4d53-bf5e-b2d1b9941fba)
2. Выделите несколько (4) верхних локаторов и скопируйте xPath + JDI annotation для группы
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/1e2d2601-faef-4a88-8c92-f8f08122381a)

Наблюдаем:
```
@UI}("//*[@class='logout']/button\")
@UI}(\"//*[@index='5']//*[@index='9']/a\")
@UI}(\"//*[contains(text(), 'User Table ')]\")
@UI}(\"//*[@class='dropdown salad']/ul/li[3]/a")
```

Ожидаем:
```
@UI("//*[@class='logout']/button")
@UI("//*[@index='5']//*[@index='9']/a")
@UI("//*[contains(text(), 'User Table ')]")
@UI("//*[@class='dropdown salad']/ul/li[3]/a")
```

**Comment by MariiaNebesnova** [comment]
[3.13.547](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.547)

**Comment by Lisa5876** [comment]
JDN v 3.13.547 Back-end v 0.2.40
Test result - passed

https://github.com/jdi-testing/jdn-ai/assets/89458651/1c922365-2a0f-491d-ae2f-cff3dd92b0f3
