### ISSUE TITLE
Поднять минимальную версия бэка до v 0.2.44

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1436]
Поднять минимальную версия бэка до v 0.2.44 для Лизы, что бы она могла проверить  баг

**Comment by MariiaNebesnova** [comment]
[3.13.545](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.545)

**Comment by AlexeyGirin** [comment]
Done.
