### ISSUE TITLE
[Regress] Bring to front \ Bring to background не работает функцилнал

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#144]
JDN v 3.0.100
Back-end v 2021-11-26-14.32.52
Chrome
https://jdi-testing.github.io/jdi-light/complex-table.html

ОР: Фрейм выделенного локатора будет перемещен
ФР: Фрейм не перемещается

**Comment by MariiaNebesnova** [comment]
Пожауйста, приложи скрин, какой именно блок ты перемещаешь

**Comment by pulya-na-vullet** [comment]
<img width="789" alt="Снимок экрана 2021-12-16 в 10 35 25 AM" src="https://user-images.githubusercontent.com/61897393/146327880-c0d2651b-ffcc-4a27-b487-ead42f85a1ec.png">

**Comment by savinovava** [comment]
@pulya-na-vullet обнови статус, пожалуйста
