### ISSUE TITLE
[Minor] Дабл-клик в панели локаторов не селектает (не выделяет) локатор

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1443]
1. Дабл-кликните по локатору в панели локаторов.

Наблюдаем: Открывается окно редактирования (это корректно и правильно), но сам локатор - не получает селекшена (выделения элемента списка) как это происходит в случае одиночного клика

Ожидаем: Открывается окно редактирования (это корректно и правильно), сам локатор - получает селекшен (выделения элемента списка) так же как это происходит в случае одиночного клика

**Comment by MariiaNebesnova** [comment]
[3.13.548](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.548)

**Comment by Lisa5876** [comment]
JDN v 3.13.550 Back-end v 0.2.40
test result - pass

https://github.com/jdi-testing/jdn-ai/assets/89458651/e35b1a6d-9589-4126-9d18-0fd04141ade1
