### ISSUE TITLE
[Medium] Система не хочет считать оптимальный кастомный локатор

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1445]
1. Поищите все xPath локаторы для HTML5 элементов на сайте https://www.google.com/
2. Добавьте катомный локатор для лэйбла Настройки (нижний правый угол - там удачно этот лэйбл не распознался)
Используйте xPath который можно взять в закладке Elements через копирование
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/a6f61165-8f0a-46ac-b985-c9d5fd118fd5)
В моём случае это было /html/body/div[1]/div[5]/div[2]/div[2]/span/span/g-popup/div[1]/div
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/79864ee0-9ada-4638-bf06-34a305434482)

Наблюдаем: Несмотря на то, что локатор не оптимальный - попытки его просчитать через Advanced Calculation ни к чему не приводит

Ожидаем: Локатор должен отправляться на просчёт и просчитываться

**Comment by MariiaNebesnova** [comment]
[3.13.552](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.552)

**Comment by AlexeyGirin** [comment]
Fixed.
