### ISSUE TITLE
Расчёт локаторов не стартует (хотя должен)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1450]
Видимо баг наведён вот этим фиксом: #1428

JDN v 3.13.551 Back-end v 0.2.44

1. Поищите xPath локаторы для HTML5 элементов на страничке https://www.otto.de/ используя **Generate All** кнопку

Наблюдаем: Согласно требованиям из #1375 - расчёт локаторов должен запускаться автоматически если они выбраны в качестве основного типа локаторов даже если их более 500 для Generate All пути, чего не происходит
(а вот если основным выбран CSS, то в этом случае - он не должен начинать считаться)

**Comment by MariiaNebesnova** [comment]
[3.13.555](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.555)

**Comment by AlexeyGirin** [comment]
Баг воспроизводится (хотя у Маши - нет). Маша сейчас не может его пофиксить - занятя. Попросила повесить на Аню

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1457
[3.13.557](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.557)

**Comment by Lisa5876** [comment]
JDN v 3.13.557 Back-end v 0.2.40
Test result - pass

https://github.com/jdi-testing/jdn-ai/assets/89458651/950670cf-c35b-40b1-9b82-692823a78245
