### ISSUE TITLE
small fixes UI

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1455]
задача составлена в процессе релиза 14, что-то может быть неактуально, писать с вопросами к @SemyonKuznetsov 
____

- [x]  переименовать кнопку "Cancel" в "Close" https://github.com/jdi-testing/jdn-ai/issues/1144
<img width="400" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/0fad0166-8e6e-44b9-a0ff-84e56dff0539">

____

- [x]  _No Page Objects created_ пейдж объект с больших букв и добавить небольшой отступ в 12px
<img width="400" alt="Снимок экрана 2023-10-12 в 12 21 36" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/be0fcf94-b557-46dc-b902-20fb6ba89f45">

должно быть так
<img width="400" alt="Снимок экрана 2024-01-22 в 14 37 13" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/492c324d-adcf-4f29-9064-03f4fc5785d4">
____

- [x] в модалках "Удаление одного или нескольких РО" должно быть написано  _Page Objects_ с больших букв в заголовке и внутри текста

должно быть так
<img width="800" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/5a1d34ac-aa1d-4a18-acb7-a8d636b18c37">

____

- [x]  Rename PO -> _Page Objects_ пейдж объект с больших букв в заголовке

<img width="400" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/c7a02177-0c96-4a70-9d14-5bd2d005b34e">

____

- [x]  не совпадает отступы-паддинги

должно быть так (сверху элемент, снизу часть css кода)

```
<div class="ant-space ant-space-vertical" style="gap: 8px;">flex
element.style {gap: 8px; }
```

```
<div class="jdn__generationButtons">
.jdn__generationButtons {padding-top: 0px;}
```

и вот тут снизу 8px  паддинга добавить

```
<div class="jdn__pageObject__settings">
.jdn__pageObject__settings {padding: 8px 20px 16px 20px;}
```

<img width="400" alt="Снимок экрана 2023-08-29 в 12 47 50" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/1281c529-7935-450a-ae4c-19d23e52d8ef">

____

- [x]  убрать точку в середине предложения

это пустое состояние РО  если оно создано с ошибкой генерации (вьютифай сейчас)
<img width="400" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/70a399bd-9a70-4f38-bd3c-6eaf740896f0">

____

- [x] поправить паддинги у локаторов в готовом РО в соответствии с [дизайном](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?type=design&node-id=164382-169770&mode=design&t=tU6VR9LB3EtLYCod-4)

```
<div class="jdn__xpath_container">
<span class="ant-typography jdn__xpath_item">
```
<img width="607" alt="Снимок экрана 2023-10-12 в 12 34 19" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/d969bb0d-7cf7-400b-aab7-2874b06d3fed">

<img width="193" alt="Снимок экрана 2023-10-12 в 12 33 05" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/8e2cd231-6fba-4738-850d-4a355ce22802">

____

- [x] сделать лейбл текст для задизейбленных селектов #000000 25%

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/19381341-b130-4b80-863d-5894090d07bc)

____

- [x] сделать дефолтный размер Search-Input больше чтобы текст влезал + минимальный отступ до иконки
<img width="228" alt="Снимок экрана 2024-02-12 в 12 14 09" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/47b707a3-aecb-4666-97fd-4dd238fc0df7">

фигма:
<img width="530" alt="Снимок экрана 2024-02-12 в 12 16 59" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/b33301be-0823-41c2-83b2-53a07b84d8fd">

**Comment by savinovava** [comment]
#1605

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1667
[3.15.6](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.6)

**Comment by InnaRadionova** [comment]
JDN v 3.15.12 Back-end v 0.2.62
**1. "переименовать кнопку "Cancel" в "Close"**
В текущей реализации данное всплдывающее окно не отображается (при поиске элементов Vuetifu): сразу видим фрейм плагина с текстом "You can either create a  or refer to our  to understand the JDN features". Я бы считала это багом, потому что пользователь должен получать внятное сообщение об отсутствии искомых элементов. 
![2024-03-20 13 57 50](https://github.com/jdi-testing/jdn-ai/assets/162306672/c5bbfb0a-98b3-4bbf-8b71-5d4a3a906492)

**2. "No Page Objects created пейдж объект с больших букв и добавить небольшой отступ в 12px"**
Реализовано:
![2024-03-20 13 57 50](https://github.com/jdi-testing/jdn-ai/assets/162306672/111593bc-166c-4eed-aae7-9964498cd78a)

**3. "в модалках "Удаление одного или нескольких РО" должно быть написано Page Objects с больших букв в заголовке и внутри текста"**
В модалках "поехало" выравнивание текста сообщения, и иконка (!) выглядит иначе. Текст исправлен верно. Требуется комментарий, считаем ли мы несоответствия на скринах - багами:
![2024-03-20 14 01 50](https://github.com/jdi-testing/jdn-ai/assets/162306672/c15c1eea-40dc-4a13-9218-419e5602de72)
![2024-03-20 14 04 29](https://github.com/jdi-testing/jdn-ai/assets/162306672/33d192b5-0212-45cf-bdeb-78487320d2cd)

4. "Rename PO -> Page Objects пейдж объект с больших букв в заголовке"
Текст перемименованг верно, но, как и в п.3, есть отличия реализации от приведенного в задаче скрина: вместо задизейбленной кнопки Save отображается кнопка Ок, а поле Name стало выделяться, как обязательное к заполнению. Требуется комментарий, считаем ли мы несоответствия - багами:
![2024-03-20 14 06 42](https://github.com/jdi-testing/jdn-ai/assets/162306672/1edf505d-6dd8-488a-b622-57a3acdfa9fc)
![2024-03-20 14 09 15](https://github.com/jdi-testing/jdn-ai/assets/162306672/008f2707-9f15-42c7-90df-f87fbb90b1b3)

**5. "не совпадает отступы-паддинги"**
Пофикшено:
![2024-03-20 14 13 48](https://github.com/jdi-testing/jdn-ai/assets/162306672/f149d003-ad2b-4d9c-bf26-0fc5435eaced)
![2024-03-20 14 16 17](https://github.com/jdi-testing/jdn-ai/assets/162306672/368a22db-4e38-4528-a2e1-b23f2f79761e)
![2024-03-20 14 19 03](https://github.com/jdi-testing/jdn-ai/assets/162306672/5471bb32-059b-40fa-ad20-b426c00412a9)

**6. "убрать точку в середине предложения"**
Пофикшено:
![2024-03-20 13 57 50](https://github.com/jdi-testing/jdn-ai/assets/162306672/1bc9f9eb-0468-4fb0-b166-4eb6ff55067d)

**7. поправить паддинги у локаторов в готовом РО в соответствии с [дизайном](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?type=design&node-id=164382-169770&mode=design&t=tU6VR9LB3EtLYCod-4)**
Не нашла в инспекте указанные элементы. Наверное, нужно уточнить сценарий воспроизведения:
![2024-03-20 14 33 03](https://github.com/jdi-testing/jdn-ai/assets/162306672/f6e52592-9368-4de2-b75f-6a8d9896d98e)


**8. "сделать лейбл текст для задизейбленных селектов #000000 25%"**
Пофикшено:
![2024-03-20 14 28 58](https://github.com/jdi-testing/jdn-ai/assets/162306672/6c1b61de-6a13-4ca0-82f9-500267726c36)

**9. "сделать дефолтный размер Search-Input больше чтобы текст влезал + минимальный отступ до иконки"**
Пофикшено:
![2024-03-20 14 31 04](https://github.com/jdi-testing/jdn-ai/assets/162306672/4c269018-4a61-4caa-959d-07447acf4b82)

**Comment by Iogsotot** [comment]
> **1. "переименовать кнопку "Cancel" в "Close"** - ЗАВЕСТИ В БЕКЛОГ В текущей реализации данное всплдывающее окно не отображается

Это баг - в коде модалка есть, в этом релизе - нет

> **3** В модалках "поехало" выравнивание

Если поехало именно в этой версии, а в предыдущей было ок, то вернуть эту задачу на доработку в ToDo 

> **4** 
Это баг, но можно уточнить у @SemyonKuznetsov 
Если баг, то рекомендую такой же алгоритм, как в П. 3

> **7** цвета для локаторов
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/a416eb6f-01cf-4bca-9d17-025087b99d26)
https://github.com/jdi-testing/jdn-ai/issues/1394
цвета совпадают с последним ТЗ по дизайну

**Comment by InnaRadionova** [comment]
Обсудили с Лешей, 'ту задачку переношу в Done.
Завела три бага:
- [[Medium] В случае, когда не найдены PO, не отображается всплывающее окно с сообщением об этом](https://github.com/jdi-testing/jdn-ai/issues/1685)
- [[Low] Поправить верстку диалогового окна при удалении PO](https://github.com/jdi-testing/jdn-ai/issues/1686)
- [[Medium] Неверное поведение формы переименования списка PO](https://github.com/jdi-testing/jdn-ai/issues/1687)

**Comment by SemyonKuznetsov** [comment]
про 7

извините, текст задачи был устаревший немного, теперь это действительно div class="jdn__locator_container" и размеры в пикселях тоже неактуальны, видимо там что-то прибавилось

там суть в том чтобы сделать ровно с иконкой, 42px? или там не фикс размер:
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/183b0f5b-c19c-43f5-a29c-f2fdd2e3a373)

в дизайне так:
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/0fc16aa7-21b3-4060-ba93-66a5a44d5315)
