### ISSUE TITLE
[3pt][US-6-2] Останавливать задачи по нажатию Clear all

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#146]
- при нажатии Clear all
- по рефрешу/навигации страницы

**Comment by MariiaNebesnova** [comment]
fe - 2pt

**Comment by MariiaNebesnova** [comment]
3.0.102

**Comment by pulya-na-vullet** [comment]
JDN v 3.0.101
Back-end v 2021-12-01-14.52.21
Функционал работает так как планировалось.
