### ISSUE TITLE
[Critical] локторы не расчитываются для xPath, при попытке вернуться на страницу с найстройками, плагин виснет

### ISSUE THREAD

**Issue by Lisa5876** [jdi-testing/jdn-ai#1461]
JDN v 3.13.559 Back-end v 0.2.40

1. Поищите xPath локаторы для HTML5 элементов на страничке https://jdi-testing.github.io/jdi-light/html5.html

Фактический результат: локаторы не рассчитываются
Ожидаемый результат: локаторы расчитываются

2. Отмените создание ПО нажав на Back, Discard

Фактический результат: планиг возвращает на страницу настроек, но виснет, невозможно нажать на какие-либо кнопки/дропдауны, помогает только переоткрыть плагин или перезагрузить страницу

Ожидаемый результат: юзер возвращется на страницу настроек, может изменить настройки и заново запустить расчет локаторов

Note: для CSS локаторы расчитываются, но при попытке вернуться к настройкам плагин так же виснет

https://github.com/jdi-testing/jdn-ai/assets/89458651/e77f991e-260d-4be2-9b15-3ba2214a2054

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1462
[3.13.560](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.560)

**Comment by Lisa5876** [comment]
JDN v 3.13.560 Back-end v 0.2.40
Test result - pass

Uploading 1462.mp4…
