### ISSUE TITLE
Описание основных сущностей JDN/JDI

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#1464]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/1605925/Project+Glossary

В частности:
1. Page Object - просто говоря это Java класс (если речь про стек java) который содержит методы по работе с конкретной страничкой веб приложения. Метод может имплементировать как простое действие - например - нажатие на кнопку, так и реализацию бизнес логики - например - залогиниться по конкретным пользователем и паролем.
В JDN автоматическая имплементация бизнес логики весьма затруднительна, а вот действия с контролами - вполне возможны.
Пример пэйдж объекта в стеке Java с использованием JDI Light:
```
public class ContactFormPage extends WebPage {
    @FindBy(xpath = "//*[@index='5']//*[@index='2']/a")
    public Button okButton;
}
```

2. Сделать классификацию/древовидную структуру терминов, чтобы было понятно, что к чему относится. Например:
- Frameworks (JDI Light, Vividus, Selenium, Selenide)
Фрэймворки для автоматизации - это библиотеки которые предоставляют API для работы с элементами на веб страничке. Первой такой библиотекой которая стала отраслевым стандартом - Selenium. Все другие библиотеки в массе своей - используют Selenium в качестве основы расширяя его возможности, однако делают - это по разному (поэтому их так много). Скажем - JDI Light предоставляет API для работы с типизированными элементами (в то время как остальные - рассматривают элементы как просто универсальный WebElement для которого предоставляются все возможные методы и только автоматизатор должен решать - какие из них применимы, а какие - нет). 
К преимуществам VIVIDUS относится дефолтная имплементация BDD подхода написания тестов что по задумке разработчиков может позволить писать тесты даже не автоматизаторам.

- Libraries (HTML5, Material UI, Vuetify)
Библиотеки элементов. Сейчас на рынке - существует много фрэймворков для девелопмента фронтэнда. Хотя 95% рынка покрывается пятью - HTML5, Angular, React, Bootstrap и Vue.js. Каждый из этих девелоперских фрэймворков имплементирует в себе одну или более библиотек элементов (как правило - от 30 до 70). JDN будет поддерживать самые популярные, скажем для React - это Material UI, для Vue.js - это Vuetify.
Выбор поддерживаемых библиотек элементов зависит от JDI Light - какие он поддерживает - такие поддерживает и JDN. Смысла поддерживать другие - нет.

- Annotations (UI, FindBy)
Почитать что такое аннотации - можно тут: https://javarush.com/groups/posts/1896-java-annotacii-chto-ehto-i-kak-ehtim-poljhzovatjhsja
Но если кратко - это такие метки в коде, которые позволяют обогащать сущности в коде разными свойствами и возможностями.
JND использует аннотации JDI Light (который так же использует аннотации Selenium) что бы обогащать элемент который мы собираемся объявить в коде - локатором, используя который, можно его найти на страничке
Например:
```
    @FindBy(xpath = "//*[@index='5']//*[@index='2']/a")
    public Label mobileAndHtml5;

```
В этом коде мы объявляем элемент типа Label (по сути - создаём объект) с именем mobileAndHtml5 найти на страничке можно с помощью локатора `//*[@index='5']//*[@index='2']/a`. И тип локатора у него xPath. 
Использование аннотаций не является обязательным. Некоторые фрэймворки, например VIVIDUS, не поддерживают аннотации, поэтому объявление элементов там выглядит вот так:
`variables.MetalAndColorsPage.Label.mobileAndHtml5=By.xPath(//*[@index='5']//*[@index='2']/a)`

- Locator types (CSS, xPath)
Локаторы - просто говоря - это текстовая строка позволяющая найти элемент на странице (в зависимости от типа - строка трактуется по разному).
Прочитать про них можно тут: https://toolsqa.com/selenium-webdriver/selenium-locators/
Всего существует 8 разных типов локаторов которые можно разделить на 3 группы.
Локаторы которые привязываются к DOM атрибутам элемента - например - id, name class name и так далее. Их наличие у элементов - не гарантируется, поэтому их использование не всегда возможно.
Две других группы содержат в себе по одному типа - xPath и CSS Selector
xPath - это the language used to query the XML document. The same can uniquely identify the web element on any page. Самый универсальный тип.
CSS Selector - это used to create style rules for webpages and can be used to identify any web element.
как и xPath - всегда присутствует у элемента, но не такой удобный и универсальный по свойствам
...
3. Поменять термин в скобках в п. 12 (Web Object —> Page Object), чтобы была понятна связь с сущностями в коде. - DONE.

4. Добавить понятие Project template со ссылкой на документацию, которую мы напишем, когда обсудим изменение архитектуры (или как-то описать это в определении фреймворков).
Project template - это тестовый проект для автоматизации тестирования который объединяет в себе все необходимые библиотеки для того, что бы писать автотесты. Набор этих библиотек зависит от выбора пользователя который он делает при создании первого page object в JDN. Проще говоря - под каждый фрэймворк автоматизации - JDI Light, VIVIDUS и другие - project template будет свой.

5. Добавить термины из предстоящих стори (`data-*` attributes, visibility, etc.)

Visibility - не все элементы, которые есть на страничке - видимы (isDisplayed) для пользователя. Разные свойства элемента могут влиять на это. 
В интернете, а так же в [коде селениума](https://github.com/SeleniumHQ/selenium/blob/a6b161a159c3d581b130f03a2e6e35f577f38dec/javascript/atoms/dom.js#L569) можно найти следующие правила:
1.  css property display: none
2. DOMRect: width/height === 0
3. css property opacity: 0 
4. css property visibility: hidden
5. html attribute "hidden"
6. css property visibility: collapse
7. OVERLAPPED by another element
8. Hidden parent element

Однако - видим ли элемент для пользователя (является ли он Displayed) решает ВНЕЗАПНО - сам браузер. Разные бразуеры - решают по разному например вот такой элемент:
```
<select name="select" style="max-width: 0px; max-height: 0px; border: 0px;">
<option value="0">test</option>
</select>
```
в хроме у него будет размер 0x0, а в файрфоксе 8x2, так что даже если бы, например, правило номер 2 работало — всё равно кроссбраузерность не достигается, из-за различия в самих браузерах.
Поэтому - для определения видимости элемента - мы спрашиваем у селениума, который в своею очередь спрашивает у браузера через вебдрайвер.
Об этом честно написано в стандарте - https://www.w3.org/TR/webdriver2/#element-displayedness
вкратце, там написано, что:
1) "WebDriver does not define a primitive to ascertain the visibility of an element"
2) Here we include a recommended approach which will give a simplified approximation of an element’s visibility

этот "рекомендованный способ" как раз и есть функция bot.dom.isShown , но производители браузеров и драйверов имеют право сделать свою собственную реализацию. поэтому опираться на функцию bot.dom.isShown с уверенностью нельзя, нужно смотреть код драйверов

**Comment by kostrubin** [comment]
Что на мой взгляд было бы хорошо доработать:
1. Сделать классификацию/древовидную структуру терминов, чтобы было понятно, что к чему относится. Например:
- Frameworks (JDI Light, Vividus, Selenium, Selenide)
- Libraries (HTML5, Material UI, Vuetify)
- Annotations (@UI, @FindBy)
- Locator types (CSS, xPath)
...
2. Поменять термин в скобках в п. 12 (Web Object —> Page Object), чтобы была понятна связь с сущностями в коде.
3. Добавить понятие Project template со ссылкой на документацию, которую мы напишем, когда обсудим изменение архитектуры (или как-то описать это в определении фреймворков).
4. Добавить термины из предстоящих стори (`data-*` attributes, visibility, etc.)

**Comment by AlexeyGirin** [comment]
Все изменения переведены на английский и перенесены в https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/1605925/Project+Glossary
