### ISSUE TITLE
Обновить текст для модального окна Онбординга

### ISSUE THREAD

**Issue by Iogsotot** [jdi-testing/jdn-ai#1469]
workaround для https://github.com/jdi-testing/jdn-ai/issues/1349

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1466
[3.13.561](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.561)
https://github.com/jdi-testing/jdn-ai/issues/1349#issuecomment-1684081257

**Comment by Lisa5876** [comment]
JDN v 3.13.561 Back-end v 0.2.40
Test result - pass
<img width="423" alt="2023-08-22_14h25_50" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/3ed886f5-8336-460c-8f72-3ed0d293b444">
