### ISSUE TITLE
Поправить механизм работы с выбором локаторов на покрытии

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#147]
Нужно обдумать работу выбора локаторов на покрытии в случаи если у нас есть один локатор и сверху накладывается другой.

**Например,** есть один большой локатор с типом table и сверху накладываются еще несколько локаторов поменьше с типом link.
<img width="701" alt="Screenshot 2021-12-16 at 13 39 22" src="https://user-images.githubusercontent.com/89466817/146365200-cf56abc5-8f5a-45ad-89bc-23a1977974f6.png">

1) если мы кликаем на верхний локатор, автоматически выбирается тот который снизу также. Итог: вместо 1 выбранного локатора у нас их 2.

2) каждый раз когда мы подряд выбираем несколько разных локаторов link, нижний большой локатор table тоже каждый раз выбирается/не выбирается поочередно при каждом следующем клике.

3) когда мы на большом локаторе table нажимаем "bring to front" - а далее пытаемся его выбрать кликая, на область, которая находится над другим локатором - выбор не происходит.

**Comment by MariiaNebesnova** [comment]
3.0.105

**Comment by pulya-na-vullet** [comment]
JDN v 3.0.105
Back-end v 2021-11-26-14.32.52
Не воспроизводится
