### ISSUE TITLE
[High] [Vividus] При выборе фреймворка Vividus и создании нескольких page objects, выгружается только последний созданный объект

### ISSUE THREAD

**Issue by Lisa5876** [jdi-testing/jdn-ai#1477]
JDN v 3.13.562 Back-end v 0.2.40

При выборе фреймворка Vividus и создании нескольких page objects, выгружается только последний созданный объект

Шаги воспроизведения:
1. Поищите локаторы  элементов на страничке https://jdi-testing.github.io/jdi-light/html5.html
- Framework - Vividus 
- Library - HTML5 (dropdown is disabled)
- Annotation - any
- Locators type - any
2. Выделите любые 2 локатора и сохраните объект;
3. Создайте новый Page obgect с теми же настройками;
4. Выделите любые другие 2 локатора и сохраните объект;
5. Нажмите Download all;
6. Откройте проект в idea;
7. Перейдите в в /src/main/resources/properties/suite/web_app/pages.properties

Фактический результат:
В файле только локаторы из последнего созданного объекта

Ожидаемый результат:
В файл включены локаторы для всех созданных page objects
<img width="572" alt="2023-08-23_13h28_22" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/31200db0-ce66-4e40-91be-68d7a823d087">
<img width="933" alt="2023-08-23_13h29_22" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/9b838ea8-236a-44bc-9a06-5991d5a741a4">

**Comment by kostrubin** [comment]
[3.14.1](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.1)

**Comment by Lisa5876** [comment]
JDN v 3.14.1 Back-end v 0.2.40
test result - pass
<img width="423" alt="2023-08-24_14h01_46" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/7c85bb1f-b181-4f85-b92a-1a2dd3737289">
<img width="423" alt="2023-08-24_14h01_46" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/2a585aa9-37b2-4e19-8f3e-fbd18e0a0aa9">
