### ISSUE TITLE
[2pt][NR-4]Останавливать задачи при закрытии плагина

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#148]
Исследовать возможность отправки Revoke запроса на бэкенд при закрытии плагина

**Comment by MariiaNebesnova** [comment]
fe - 1pt

**Comment by savinovava** [comment]
1. Ждём перехода на веб-сокеты
2. Необходимо расписать возможные Use Case

**Comment by AlexeyGirin** [comment]
Линкую на #136 - same problem

**Comment by AlexeyGirin** [comment]
@IoffeM нужно проверить, что долгие задачи по расчёту (те которые в прогрессе) исчезают с сервера если мы нажимаем на кнопку Clear All или обновляем страничку по F5 или путём перехода по ссылке.

**Comment by IoffeM** [comment]
DN v 3.1.117
Back-end v 2022-01-31-15.52.11
Chrome

done
