### ISSUE TITLE
[High][Vividus] РО сгенерированный с  locator type CSS selector сохраняется в файл как xpath

### ISSUE THREAD

**Issue by Lisa5876** [jdi-testing/jdn-ai#1480]
JDN v 3.14.1 Back-end v 0.2.40

РО сгенерированный с  locator type CSS selector сохраняется в файл как xpath
Шаги воспроизведения:

1.Поищите локаторы элементов на страничке https://jdi-testing.github.io/jdi-light/html5.html
Framework - Vividus
Library - HTML5 (dropdown is disabled)
Annotation - @Findby
Locators type - CSS selector
2. Выделите любые локаторы и сохраните объект;
3.Нажмите Download all;
4. Откройте проект в idea;
5. Перейдите в в /src/main/resources/properties/suite/web_app/pages.properties

Фактический результат:
В локаторе в скобках указан xpath
<img width="577" alt="2023-08-24_15h37_06" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/85d817f1-3c8a-427b-a128-2878feef87be">

<img width="935" alt="2023-08-24_15h37_55" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/26c7d68f-9d3b-4ec6-a707-44d480e1acc0">

Ожидаемый результат:
В файле у локаторов locator type -  CSS selector

**Comment by kostrubin** [comment]
https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.2

**Comment by Lisa5876** [comment]
JDN v 3.14.2 Back-end v 0.2.40
test result - pass
<img width="525" alt="2023-08-25_13h46_33" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/60457796-3688-44f9-803d-b2dfee8d6884">
<img width="933" alt="2023-08-25_13h46_24" src="https://github.com/jdi-testing/jdn-ai/assets/89458651/24538eed-c871-4797-b426-5e39a860b4b4">
