### ISSUE TITLE
Парсинг страницы идёт слишком долго и непрозрачно на больших страницах

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1482]
### Problem statement/business needs:
Процесс парсинга и прогрузки в целом непрозрачен и на больших страницах пользователю может быть непонятно что происходит, в каком статусе создание РО и всё ли окей

### Definitions of Done:
- получаем данные о количестве локаторов
- убрали затемнение и добавили progress bar на несколько шагов

### Design:
[prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&type=design&node-id=10295-87142&viewport=248%2C-16651%2C0.19&t=DmMemK5ITzXfQpm8-1&scaling=scale-down-width&starting-point-node-id=10295%3A87142&mode=design)

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/50993622-a1e8-4e13-b20b-7ce8c76e6404)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/7739ef17-b625-41f5-9d7a-1b7f96ac92b9)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/05f91fa5-984f-43de-95dd-a436a75b9f36)![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/caf1c7e2-66a9-4597-ac6b-3ca2878bbcac)
на 1 секунду (не критично, можно больше, если будет дёргаться) зафиксировать экран с успешным завершением
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/5f94b9c5-ac92-4e6c-ba74-651eaf232dd3)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/e1bf3be9-d1f1-42f3-91aa-601435dd5949)

### Comments:

1. Откройте сайт https://www.otto.de/
2. Поищите локаторы со следующими элементами:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/8f8aa4e7-aaf1-4605-bdc7-2588bc39dfcb)

Наблюдаем: Система затемняет экран и задумывается очень надолго. Это некомфортно

Ожидаем: Как минимум - поясняющую надпись, что система парсит страницу и это может занять даже минуту или даже две. Как максимум - прогресс бар

Что просиходит между нажатием кнопки и появлением локатор листа:
- парсинг элементов (можем считать)
- расчёт визибилити локаторов (можем считать)
- расчёт css локаторов (не можем считать, одним куском, но если меньше 500)

**Нужно посчитать количество элементов, которые мы получаем в обратную сторону.
После этого мы сможем предположить сколько у нас в среднем проходной процент для элементов (тенденция) и помножить на необходимое среднее время для одного и мы получим примерный таймер для лоадера**

**Анимацию лоадера мы делаем обобщённой, предположим что посчитается за 30 секунд, лоадер будет самостоятельно двигаться по отрезкам 100/30, если нужно больше времени в конце то он подвиснет, если меньше, то последние отрывки пройдут быстрее (рывком закончит загрузку)**

https://ant.design/components/progress

**Comment by SemyonKuznetsov** [comment]
надо спрашивать бэкенд о том, насколько возможно реализовать передачу данных о прецессе на фронтенд в каждом из трёх шагов

**Comment by AlexeyGirin** [comment]
Делаем один этап - а пока - эмулируем

**Comment by Iogsotot** [comment]
- https://github.com/jdi-testing/jdn-ai/pull/1616
[3.14.40](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.40)

**Comment by MayaElf** [comment]
Проверено. Закрыто. Доабвлены две задачи по улучшениям, #1622 #1623
