### ISSUE TITLE
Обновить изображения на странице плагина

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1486]
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=10562-90078&mode=design&t=qW2MI8LEEFQXBbju-4)

<img width="1280" alt="1" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/ed0a0bcb-17cc-4c36-a461-05ffd6e40818">
<img width="1280" alt="2" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/7f3163bf-6863-407b-a7a6-29e90d75cace">
<img width="1280" alt="3" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/ba76d83a-0697-42dd-a154-4006800944b0">
<img width="1280" alt="4" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/892dbf4f-b697-4a6f-8951-6eba047c1490">
<img width="1280" alt="5" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/9c12a716-e76b-4dbd-aecc-bb862d709899">

**Comment by AlexeyGirin** [comment]
1. Дефолтную аннотацию надо сделать `@FindBy` (она более знакома для людей)
2. Страничка - должна быть чистой https://www.epam.com/ в строке URL браузера (сейчас там какие-то параметры - нужно их вычистить)
3. Листануть список локаторов что бы там были локаторы красивее без div\div\div\ и без индексов по возможности - [3]
4. И что бы названия контролов были не очень длинные

**Comment by Iogsotot** [comment]
@SemyonKuznetsov  добавь, пожалуйста, архив с ассетами, из гитхаба не получается скачать

**Comment by AlexeyGirin** [comment]
Узнать у Семёна - почему нет большой рекламной картинки

**Comment by Iogsotot** [comment]
Чтобы проверить эту задачу надо найти приложение в Chrome Store и посмотреть скриншоты:
https://chromewebstore.google.com/detail/jdn/dldagjdnndapekahhbpeemjifghccldg?hl=en-US&utm_source=ext_sidebar

**Comment by AleksandraSmolianinova** [comment]
Tested - скриншоты верные
