### ISSUE TITLE
При выборе таргет платформы Vividus - дизаблить выбор аннотации с дефолтным значением @FindBy

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1487]
1. Попробуйте создать ПО на страничуке https://jdi-testing.github.io/jdi-light/html5.html нажав кнопку +Page Object
Наблюдаем:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/9e3333a3-bd13-47f2-a72c-5f0346c3c528)

Видим, что можно комбик аннотейшен доступен для изменения и там можно выбрать значение `@UI`

Ожидаем:
Этот комбик будет задизаблен, а его значение принудительно изменено на `@FindBy`

2. Попробуйте распознать элементы и открыть любой локатор на редактирование
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/86f23247-ef89-43aa-8eff-363b4103199c)

Видим, что комбик аннотации `@FindBy / @UI` доступен для изменения.
Ожидаем: Этот комбик будет вообще скрыт (ну или хотя бы задизаблен с принудительным выставлением значения `@FindBy`)

**Comment by kostrubin** [comment]
[3.14.5](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.5)

**Comment by kostrubin** [comment]
[3.14.2.5](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.2.5)

**Comment by AlexeyGirin** [comment]
Fixed.
