### ISSUE TITLE
[Critical] Выбор (правильной) аннотации @FindBy для вивидуса - делает экспорт локаторов неверным

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1489]
1. Попробуйте создать ПО для странички https://jdi-testing.github.io/jdi-light/contacts.html (пароль - Roman, пассворд - Jdi1234) со следующими параметрами:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/5cd98631-6d0d-44de-9487-94a7cfa62d85)
В данном случае - аннотация `@FindBy` единственно верный вариант (и после исправления бага - #1487 оно там будет всегда)
2. Добавьте в ПО один элемент (в моём случае это была кнопка Submit)
3. Сохраните ПО
4. Экспортните проект в архив

Наблюдаем: Если открыть файл \src\main\resources\properties\suite\web_app\pages.properties, то там элемент будет объявдлен как:
`variables.ContactFormPage.Button.submit=By.xPath(xpath = //*[contains(text(), 'Submit')])`
в то время как правильное объявление:
`variables.ContactFormPage.Button.submit=By.xPath(//*[contains(text(), 'Submit')])`
Аналогично для типа локаторов CSS - оно объявляет как `By.cssSelector(css = .col-sm-12 > [type="submit"])`, а нужно - `By.cssSelector(.col-sm-12 > [type="submit"])`

При этом - для JDI Light - всё должно остаться ПО-ПРЕЖНЕМУ!
Для `@FindBy` элемент должен каститься как `@FindBy(xpath = "//*[contains(text(), 'Submit')]")`
а для `@UI` как `@UI("//*[contains(text(), 'Submit')]")`

**Comment by kostrubin** [comment]
[3.14.2.5](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.2.5)

**Comment by AlexeyGirin** [comment]
Fixed.
