### ISSUE TITLE
[Critical] Наличие открытой под-формы создания ПО - ломает экспорт в случае если существующие ПО созданы для вивидуса

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1490]
1. Попробуйте создать ПО для странички https://jdi-testing.github.io/jdi-light/contacts.html (пароль - Roman, пассворд - Jdi1234) со следующими параметрами:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/5cd98631-6d0d-44de-9487-94a7cfa62d85)
В данном случае - аннотация `@FindBy` единственно верный вариант (и после исправления бага - #1487 оно там будет всегда)
2. Добавьте в ПО один элемент (в моём случае это была кнопка Submit)
3. Нажмите кнопу +Page Object, но создание ПО не запускайте, что бы была такая картина:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/2a44b9d6-cce4-4a6c-b6c4-039c2cf00b2b)
4. Нажмите кнопку Download all as .zip и экспортните всё в архив
5. Откройте архив.

Наблюдаем: Внутри архива шаблон JDI Light

Ожидаем: Внутри архива шаблон VIVIDUS и всё остальное

**Comment by kostrubin** [comment]
[3.14.2.5](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.2.5)

**Comment by kostrubin** [comment]
https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.2.6

**Comment by AlexeyGirin** [comment]
Fixed.
