### ISSUE TITLE
[High] AntD fixes

### ISSUE THREAD

**Issue by Iogsotot** [jdi-testing/jdn-ai#1493]
**Describe the bug**
После обновления AntD до 5 версии необходимо поправить отступы, кнопки, иконки, положения шрифта

**To Reproduce**
1. Go to app

**Expected behavior**
Дизайн не выглядит плохо, преимущественно соответствует дизайну из Figma

**Screenshots**
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/38acf92c-bd47-40fa-b992-4364fe30ec2c)

**Comment by AlexeyGirin** [comment]
JDN v 3.14.10 Back-end v 0.2.40

Две проблемы были не пофикшены:

1. 
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/49952218-b7c0-481a-b572-0f0433dae810)

2. 
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/dd57e335-51bf-4658-b8ce-cef8524c4a7c)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1528
[3.14.12](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.12)

**Comment by AlexeyGirin** [comment]
Fixed.
