### ISSUE TITLE
[High] плагин крашится, если на странице выбрать элемент через опцию "Select element"

### ISSUE THREAD

**Issue by Lisa5876** [jdi-testing/jdn-ai#1495]
JDN v 3.14.2 Back-end v 0.2.40

Шаги воспроизведения:
1. Поищите локаторы элементов на страничке https://jdi-testing.github.io/jdi-light/html5.html
Framework - JDI Light
Library - HTML5 
Annotation - `@UI`
Locators type - xPath
2. На странице выделите несколько локаторов рамкой;
3. Кликнте правой кнопкой мыши по любому из локторов;
4. Выберете опцию "Select element" -> любой локтор

Фактический результат: 
плагин крашится, окно плагина становится белым

Ожидаемый результат:
Выбранный локтор остается выделенным оранжевым, все остальные выделены желтым

https://github.com/jdi-testing/jdn-ai/assets/89458651/29ce4f94-cf08-4236-ad96-9fa1e5f24869

**Comment by AlexeyGirin** [comment]
Баг воспроизвёлся

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1698
[3.15.18](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.18)

**Comment by mobilisf** [comment]
Bug fixed on DN v 3.15.20 Back-end v 0.2.64
