### ISSUE TITLE
Изменить вид списка локаторов для случая ВИВИДУСа

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1496]
Проблема: В данный момент список локаторов у нас выглядит как он бы выглядел для JDI Light:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/f6490eb2-5667-4d8f-bb16-220c0b48c8c9)

В то же время - для VIVIDUS - содержимое Page Object выглядит по другому (см дизайн снизу).
Необходимо для ПО которые созданы для VIVIDUS - показывать такой вид.
Для локаторов типа xPath это должно выглядеть как 
`variables.ContactFormPage.Button.submit=By.xPath(//*[contains(text(), 'Submit')])`
Аналогично для типа локаторов CSS - оно объявляет как 
`By.cssSelector(.col-sm-12 > [type="submit"])`

[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=9602-149270&mode=design&t=CiCuWioQvTG6hCgl-4)

тело локатора помечаем #66000A, это то что в скобках
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/46ea41a4-c8cd-4d8b-8640-7926ad91568c)

**Comment by kostrubin** [comment]
[3.14.2.5](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.2.5)

**Comment by AlexeyGirin** [comment]
Done.
