### ISSUE TITLE
[Medium] System allows to create Page Objects for different frameworks at the same time

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1499]
- JDN v 3.14.2 
 - Back-end v 0.2.40

System allows to create Page Objects for different frameworks at the same time. The result would not work

1. Open plugin
2. Create new PO for JDI Light framework
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/f0bce954-c433-4036-93f0-97018eed6726)

3. Start to creation of another PO (open creation dialog)
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/c1764bb0-903d-4234-bc60-b00546c0ce19)

**Actual behavior**
Note that Framework combobox is enabled and let you choose VIVIDUS

**Expected behavior**
System should disable Framework combobox if more than zero Page Object already exists (and remain value of already created POs)

**Comment by kostrubin** [comment]
Будет пофикшено в https://github.com/jdi-testing/jdn-ai/issues/1490

**Comment by kostrubin** [comment]
[3.14.2.5](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.2.5)

**Comment by AlexeyGirin** [comment]
Fixed.
