### ISSUE TITLE
Обновить маппинг модели

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#151]
DONE

**Comment by MariiaNebesnova** [comment]
после обновления JDI документации, проверить, что все классы продолжают соответствовать маппингу

**Comment by AlexeyGirin** [comment]
@savinovava должна завести это в требования (интеграционная проверка для плагина и JDI Light)

**Comment by savinovava** [comment]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/28016716/US-8-1+Model+mapping+with+JDI created
