### ISSUE TITLE
[Medium] Refactoring for onboarding to fix 8 step

### ISSUE THREAD

**Issue by Iogsotot** [jdi-testing/jdn-ai#1512]
**Environment details  (please complete the following information):**
 - Front-end version: 3.14.8
 - Back-end version: 0.2.40

**Describe the bug**
Иногда теряется таргет для онбординга и попап просто рендерится по центру листа (как будто таргет: null, а не реф на ноду) и не подсвечивается нода для степа онбординга

**To Reproduce**
1. Начать онбординг
2. Пройти до конца или до возникновения бага
3. На каком-то шаге (8 например) может произойти баг и не будет подсветки шага
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/21f4089e-3a3b-429e-8cce-dddc71441ac7)

**Actual behavior**
Кнопка Save Locator не подсвечивается

**Expected behavior**
У всех шагов онбординга происходит подсветка необходимого участка интерфейса, если это предусмотрено дизайном

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.38 - Passed
Все 14 шагов пройдены и везде была подсветка шага
