### ISSUE TITLE
[Minor] Some typo in onboarding tutorial wording

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1516]
### Environment details  (please complete the following information):
JDN v 3.14.2.6 Back-end v 0.2.40
Win10

### To Reproduce
1. Start Onboarding tutorial
2. Pass it till step 14/14

### Actual behavior
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/4c0110ce-6fb6-45db-9fed-b1cddbccf6c0)

### Expected behavior
Text should be, highlighted the changed text in green
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/a9cd5c6f-cdb4-4912-8cde-d7405eb298d9)

Server connection type
Displays the current type of connection being used by JDN, whether it's the local server or the cloud server.
(i) — you are connected to the cloud server
(i) — you are connected to the local server

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1566
[3.14.24](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.24)

**Comment by AlexeyGirin** [comment]
Fixed.
