### ISSUE TITLE
[Minor] Надо бы подровнять иконку, чекбокс и текст

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1517]
**Environment details  (please complete the following information):**
JDN v 3.14.2.6 Back-end v 0.2.40
Win10

**Describe the bug**
Чекбокс, вейт иконка и текст - не заинлайнены. Нужно заинлайнить

**To Reproduce**
1. Поищите HTML5 элементы для вивидуса на сайте https://www.epam.com/
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/658515cc-9f6d-49b9-b937-07f32c1d2b92)

2. Посмотрите на локаторы которые обсчитываются

**Actual behavior**
Наблюдаем
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/15bde597-b1eb-4c03-9f78-27824e140758)

**Expected behavior**
Ожидаем что чекбокс, вейт иконка и текст будут вертикально зацентрированы
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/3dac830d-9d8a-4150-85ab-0b21f8641d83)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1621
[3.14.43](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.43)

**Comment by SemyonKuznetsov** [comment]
решили выравнивать по центру **первой** строки, в целом локатор выравниваем по верху

**Comment by AleksandraSmolianinova** [comment]
надо выравнять ещё вот этот символ:
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/273579b1-f8f3-45eb-8d2e-30f6614bdbc3)
и поправить выравнивание по центру первой строки (и в вивидусе и в лайте)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1626
[3.14.46](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.46)

- Поправлены иконки:
  - startedIcon (спиннер)
  - revokedIcon (PauseCircle)
  - deletedIcon (Trash)
  - failureIcon (WarningCircle)
  - warningEditedIcon (треугольник)
- Поправлен текст - теперь однострочники и абзацы всегда выравниваются по верхнему краю блока
- Поправлено выравнивание чекбокса и коллапса (теперь как в Фигме - ровно и выравнивание совпадает с чекбоксом и коллапсом в Locator List)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/65e0c054-2173-479f-ab8a-965e3c51d38e)
