### ISSUE TITLE
[High] В онбоардинге присутствует лишний шаг который пропускается при проходе - нужно его удалить

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1518]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40
Win10

**Describe the bug**
В онбоардинге присутствует лишний шаг который пропускается при проходе - нужно его удалить

**To Reproduce**
1. Будучи на страничке https://jdi-testing.github.io/jdi-light/contacts.html начните онбоардинг и обратите внимание что шагов 14
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/246d4a5a-6a72-43c0-a4eb-f8abc81f0b6d)

2. Дойдите до шага 3/14 и нажмите кнопку Generate
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/c0399de6-2ab4-45e0-bd79-92162ee3992b)

3. Система моргнёт и перейдёт сразу к шагу 4/14
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/01c63a79-6fb3-4cd0-b692-17b2b4e8528d)

**Actual behavior**
На самом деле - шага 4/14 просто нет - это была резервация под глобальные настройки

**Expected behavior**
Нужно исправить - что бы показывалось 13 шагов и после 3го шага шёл не 5й, а 4й

**Comment by kostrubin** [comment]
4 шаг — это создание локаторов:
<img width="591" alt="Screenshot 2023-09-21 at 16 29 38" src="https://github.com/jdi-testing/jdn-ai/assets/23456679/9fe0043e-6ff2-44f9-a681-13997daef213">

Возможно, есть смысл не закрывать его автоматически после завершения процесса, чтобы не смущать пользователя кажущимся «пропуском» шага, когда он выполняется очень быстро, а добавить кнопку Ok, после нажатия которой пользователь будет переходить к шагу 5.

@SemyonKuznetsov, что думаешь по этому поводу?

**Comment by SemyonKuznetsov** [comment]
> Member

тогда я бы оставил так как есть, просто убрал бы с него кнопки, вообще, они всё равно задизейбленные и ничего не делают
<img width="141" alt="Снимок экрана 2023-09-22 в 17 23 06" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/8b3afec4-bb53-4dd1-a877-d92df17ec288">

как вариант можем добавить минимальное время показа этого шага? ну чтобы 1 или 1.2 секунды хотя бы

**Comment by AlexeyGirin** [comment]
Сделать так:
![MicrosoftTeams-image (2)](https://github.com/jdi-testing/jdn-ai/assets/26869421/de02d9bf-52e4-4c2c-910b-94fb7b8c6ac8)

**Comment by kostrubin** [comment]
[3.14.16](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.16)

**Comment by SemyonKuznetsov** [comment]
> ![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/26869421/270645306-de02d9bf-52e4-4c2c-910b-94fb7b8c6ac8.png)


Кнопки будут просто задизейблены, убрать их полностью -- проблема с Антом.
Коммент с моей стороны -- не критично

**Comment by mobilisf** [comment]
Validated on JDN v 3.14.19 Back-end v 0.2.40 

Шаг 4/14  - поиск локаторов.
Минимальная задержка присутствует.

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/3694d5ca-4e5f-4679-b00a-10c1a2ba1443)
