### ISSUE TITLE
[High] На шаге онбоардинга Finish creating the Page Object элементы на заднем фоне доступны для действий (а не должны)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1519]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40
Win10

**Describe the bug**
На шаге онбоардинга Finish creating the Page Object элементы на заднем фоне доступны для действий (а не должны)

**To Reproduce**
1. Будучи на страничке https://jdi-testing.github.io/jdi-light/contacts.html запустите онбоардинг и дойдите до шага Finish creating the Page Object
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/8a262a39-709b-48d0-a194-536787c2b1c3)

**Actual behavior**
На этом шаге - элементы которые накрыты серым фоном - внезапно доступны для манипуляций

**Expected behavior**
На этом шаге - элементы которые накрыты серым фоном - НЕ доступны для манипуляций

**Comment by kostrubin** [comment]
[3.14.18](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.18)

**Comment by mobilisf** [comment]
Validated on JDN v 3.14.19 Back-end v 0.2.40

Весь задний фон недоступен для действий.
