### ISSUE TITLE
Выложить на GitHub release

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#152]
- [x] создание отдельного пути для контейнера release, обновить документацию @aleksandrovskiys 
- [x] обновление документации для пользователя readme @mariia-tokarchuk 
- [x] frontend part
- [x] обновить стабильную версию бэкенда

**Comment by aleksandrovskiys** [comment]
Добавил сборку stable версии, команды для загрузки compose file доступны тут: https://github.com/jdi-testing/jdi-qasp-ml#stable-version

@bulgakovmyu воскресил мастер, стабильные версии будут собираться при пуше (либо мр) туда. 
Мне кажется лучше хотя бы мастер закрыть от прямого пуша и вносить туда доработки только через МР с код ревью.

P.S. Github Packages бесплатное для открытых проектов, так что при желании мы можем и сами сборки версионировать, а не только stable/develop
![image](https://user-images.githubusercontent.com/4266410/146580460-eb7d4f56-cb32-46c2-8186-388579a51e83.png)

**Comment by pulya-na-vullet** [comment]
<img width="1253" alt="Снимок экрана 2021-12-28 в 11 57 14 AM" src="https://user-images.githubusercontent.com/61897393/147548471-14af43a3-ed7e-4b77-8cc9-0a850004d86d.png">
