### ISSUE TITLE
[Minor] На шаге Finish creating the Page Object не подсвечивается кнопка Save

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1520]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40
Win10

**Describe the bug**
На шаге Finish creating the Page Object не подсвечивается кнопка Save

**To Reproduce**
1. Будучи на страничке https://jdi-testing.github.io/jdi-light/contacts.html стартаните онбоардинг и дойдите до шага Finish creating the Page Object
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/8ba6aa2c-91f4-4784-8403-011fb148e7b3)

**Actual behavior**
Видим, что кнопка Save не подсвечиваеся.

**Expected behavior**
Согласно дизайну из https://github.com/jdi-testing/jdn-ai/issues/800 - она должна подсвечиваться
![244338490-a262e5d8-a079-43c1-afb4-8f8a28561d12](https://github.com/jdi-testing/jdn-ai/assets/26869421/be69fb78-6e1d-4df8-8312-747bbfac7a57)

**Comment by kostrubin** [comment]
[3.14.18](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.18)

**Comment by mobilisf** [comment]
Validated JDN v 3.14.19 Back-end v 0.2.40

Кнопка подсвечивается.
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/5cd02cb3-9c38-42c1-97b4-c945820fcbcd)
