### ISSUE TITLE
[High] Отмена создания ПО на этапе посчитанного списка локаторов ломает настройки создания ПО в онбоардинге

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1521]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40
Win10

**Describe the bug**
Отмена создания ПО на этапе посчитанного списка локаторов ломает настройки создания ПО в онбоардинге

**To Reproduce**
1. Запустите плагин
2. Начните создание ПО будучи на странице https://jdi-testing.github.io/jdi-light/contacts.html
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/d8b48f1a-9270-41eb-b0e4-28437cc5f058)

3. Нажмите Generate All
4. Дождитесь окончания генерации
5. Нажмите кнопку Back и Discard в появившемся диалоге
6. Нажмите на кнопку старта онбоардинга в верхней части плагина
7. Дойдите до второго шага
Уже на этом шаге - всё выглядит странно - диалога создания - НЕТ!
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/c28398c1-f784-4095-b3ad-d4b2d9a51462)

8. Нажмите кнопку Next
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/afb11c4a-38d8-49a0-b6fe-9e08c3d9f91f)

9. Нажмите кнопку Generate
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/4e268663-ef33-4402-aa89-b7510e807b7e)

**Actual behavior**
На этом этапе - что-то идёт не так - система ищет не все элементы, а генерация оптимальных локаторов заканчивается ошибкой
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/65f9e71b-daf3-45b8-8c81-9ea0e34d088d)

Если на этом этипе прекратить онбоардинг, дискарднуть существующий недосозданные ПО, то мы увидим такую картину:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/cabef880-a4e6-4b45-833f-6caa9eb01ede)

Даже если выбрать там какое-то значиние HTML5, наример, то всё равно - плагин полностью ломается и перестаёт считать локаторы

**Expected behavior**
Всё работает нормально.

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1565
[3.14.23](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.23)

**Comment by AlexeyGirin** [comment]
Текущая проблема - исчезла (обе)
