### ISSUE TITLE
[High] Копирование локаторов копирует JDI Light код даже если выбран VIVIDUS

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1523]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40
Win10

**Describe the bug**
Копирование локаторов копирует JDI Light код даже если выбран VIVIDUS

**To Reproduce**
1. Начните создавать ПО для странички https://jdi-testing.github.io/jdi-light/contacts.html с настройками:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/79f78243-00b5-4662-8a0f-df7d8c0a05c7)

2. Дождитесь пока всё просчитается
3. Нажмите на кнопку копирования для локатора который первый в списке
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/f4080bed-7384-46b3-970b-c9f30ac21598)

4. Посмотрите содержимое буфера:

**Actual behavior**
В буфере обмена будет 
```
@FindBy(xpath = "//*[@for='weather']")
public UIElement weatherUielement;
```
**Expected behavior**
`variables.ContactFormPage.UIElement.weatherUielement=By.xPath(//*[@for='weather'])`

Подправить копирование так же надо для опций копирования в 
1. Меню локатора - пункт Copy -> Full code
2. Контекстном меню панели локаторов - пункт Copy -> Full code
3. Контекстном меню панели покрытия - пункт Copy -> Full code
4. Кнопка копирования Page Object'а
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/1288e49f-7f66-4893-b4fa-a4eb58933e27)

**Comment by kostrubin** [comment]
[3.14.14](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.14)

**Comment by AlexeyGirin** [comment]
Выглядит так, что фикс привёл к регрессу - вместо символа перевода строки система вставляет \n в результат который помещается в буфер обмена

variables.search.Button.search=By.xPath(//*[@class=\'search-global-typeahead__collapsed-search-button\'])\n\nvariables.newFeedUpdatesNotificationsHome.Label.newFeedUpdatesNotificationsHome=By.xPath(//nav/ul/li[1]/a)

**Comment by kostrubin** [comment]
Можно будет тестить после аппрува и мёрджа ПРа https://github.com/jdi-testing/jdn-ai/pull/1555

**ВАЖНО!**
Фикс мог привести к регресу этого бага https://github.com/jdi-testing/jdn-ai/issues/1431
Я протестировал, вроде бы всё работает, но на всякий случай перепроверить.

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1555
[3.14.23](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.23)

**Comment by mobilisf** [comment]
Validated on JDN v 3.14.23 Back-end v 0.2.45

В моем случае первый локатор почему то был другой локатор:
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/4e9bb37f-d15a-4f24-933a-f071148cf836)

Но формат копирования сходится во всех 4 вариантах копирования.
variables.complexTable.Label.complexTable=By.xPath(//a[contains(text(), 'Complex Table ')])

Меню локатора - пункт Copy -> Full code  Passed
Контекстном меню панели локаторов - пункт Copy -> Full code  Passed
Контекстном меню панели покрытия - пункт Copy -> Full code  Passed
Кнопка копирования Page Object'а  Passed
