### ISSUE TITLE
[Severity] fix styles for locator list

### ISSUE THREAD

**Issue by Iogsotot** [jdi-testing/jdn-ai#1524]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40

**Describe the bug**
Контекстное меню прячется (поправить стили, чтобы либо оно всегда влазило по высоте, либо всегда было сверху и видно)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/a31c27e4-1cf6-443e-9551-6be954a2e7b8)

Ожидаемое поведение:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/6149f492-aeec-4769-88c8-afa284142f12)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1700
![319090035-adcce775-c7fe-4414-91c6-c1d62b985574](https://github.com/jdi-testing/jdn-ai/assets/50149163/38435a9a-d0ee-4197-85ae-cdd4aa7c5336)
[3.15.20](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.20)

**Comment by mobilisf** [comment]
Bug fixed on JDN v 3.15.20 Back-end v 0.2.64

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/3a9d6dbb-9c12-4b2e-a918-691072fb6393)
