### ISSUE TITLE
[Critical] Кнопка копирования запуска бэка - не работает

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1525]
**Environment details  (please complete the following information):**
JDN v 3.14.10
Win10

**Describe the bug**
Кнопка копирования запуска бэка - не работает

**To Reproduce**
1. Откройте плагин таким образом, что бы бэк был недоступен или не запущен
2. Попробуйте скопировать строку для запуска локального бэка для винды
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/4ab9404b-4487-4c27-aabe-c9d6d36820b3)

**Actual behavior**
В буфер обмена эта строка так и не попадёт

**Expected behavior**
В буфер обмена строка попадает

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1532
[3.14.13](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.13)

**Comment by AlexeyGirin** [comment]
Fixed.
