### ISSUE TITLE
[Minor] Тултип к пэйдж объекту - не идеален

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1529]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40
Win10

**Actual behavior**
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/c8e24f89-1cb6-4e7e-bb5d-0ec256e54212)

**Comment by TossACoinToUrProgrammer** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1677
[3.15.12](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.12)

**Comment by InnaRadionova** [comment]
Пофикшено:
JDN v 3.15.12 Back-end v 0.2.62
Chrome Version 122.0.6261.129 (Official Build) (64-bit)
Win10
![2024-03-20 15 56 12](https://github.com/jdi-testing/jdn-ai/assets/162306672/fd82ce86-8726-4d4d-9331-8e50b5a0889a)
