### ISSUE TITLE
[Minor] На форме редактирования ПО - есть ненужный коллапс элемент который ничего не делает

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1534]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40
Win10

**To Reproduce**
1. Откройте страничку https://www.linkedin.com/feed/ (но вообще - можно любую)
2. Начните создавать ПО, в моём случае настройки были такие:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/1df1fbc5-c273-47fd-a344-dffa18f51836)

**Actual behavior**
На экране редактирования ПО - есть коллапс элемент которого видимо быть не должно
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/09459f77-2b7f-42fe-b0db-ecf189234099)

**Expected behavior**
[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=11149-981208&mode=design&t=Vi48fU9Tf0iswZfo-4)
ЕСЛИ в РО нет элементов, которые могут быть развёрнуты, то элемент должен быть задизейблен
т.е.:
1. быть НЕкликабельным
2. смотреть вниз
3. цвет 000000 25% (Character/Disabled)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/c598d8f3-b735-42d4-a81e-3ed263336db8)

**Comment by SemyonKuznetsov** [comment]
поменял Expected behavior, было - убрать элемент

элемент нужен, просто в другом состоянии, нужно проверить что соответствует критериям задизейбленного элемента

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1742
[3.15.36](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.36)

Note:
`Фичи с расчетом CSS selector на бэкенде и download all as zip (см https://github.com/jdi-testing/jdn-ai/issues/1284 https://github.com/jdi-testing/jdn-ai/issues/1734) работают только для локального бэкенда ( issue_1284-backend-calculation-of-css-selectors -l pr-192)
`

**Comment by Vehemen** [comment]
Воспроизводится на 3.15.36

**Comment by Vehemen** [comment]
На страницах без дочерних элементах кнопка задизейблена. Коректно работает на остальных страницах

**Comment by Vehemen** [comment]
Пофикшено
