### ISSUE TITLE
[Medium] Система не распознает элементы в каком-то верхнем слое

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1535]
**Environment details  (please complete the following information):**
JDN v 3.14.10 Back-end v 0.2.40
Win10

**To Reproduce**
1. Перейдите на страничку https://www.linkedin.com/feed/ и попытайтесь написать новый пост (кликнув на надпись Start a post )
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/de9ab3da-9971-453c-96b1-9f02fbc4a05b)

2. Вот в этом состоянии начните создавать ПО, в моём случае - настройки были такие:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/f4184194-0662-4844-b83a-fa67c62efaad)

**Actual behavior**
Система распознает что-то там, но странным образом - результаты будут не в самом верхнем слое, и ПОД окном редактирования нового поста
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/59c5a8e5-1f31-4230-9121-7de854ec1bd3)

**Expected behavior**
Хотелось бы что бы результаты былив самом верхнем слое, и ПОД окном редактирования нового поста

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/issues/1504
[3.14.15](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.15)

**Comment by mobilisf** [comment]
Validated on JDN v 3.14.19 Back-end v 0.2.40

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/04c07ac4-ae79-4f06-949f-eea8affd3317)
