### ISSUE TITLE
[Critical] Крэш после того как удаляем новый ПО который мы ещё не создали

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1536]
**Environment details  (please complete the following information):**
JDN v 3.14.14 Back-end v 0.2.40
Win10

**To Reproduce**
1. Создайте ПО с несколькими локаторами для странички https://jdi-testing.github.io/jdi-light/bootstrap-new.html (напоминаю что надо залогинится Roman/Jdi1234 , иначе не пустит), настройки любые, но у меня были такие:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/2f868d9b-909e-478f-94a3-edbf27ff98c7)

2. Нажмите кнопку + Page Object
3. Пойдите в меню этого не созданного ПО и нажмите Delete
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/fbd237cf-8192-4db9-ae5f-c032fbc21d01)

**Actual behavior**
Плагин упадёт. Панель плагина целиком белая

**Expected behavior**
Плагин не упадёт. Панель плагина белая не целиком

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1552
[3.14.20](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.20)

**Comment by mobilisf** [comment]
Validated on JDN v 3.14.21 Back-end v 0.2.40

Плагин не упал, появилось сообщение об удаленном объекте.

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/5797a573-9fa6-4f43-baed-6fc4dca2418a)
