### ISSUE TITLE
[Critical] Добавление локаторов в ПО через панель покрытия не работает (в обратку тоже)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1537]
**Environment details  (please complete the following information):**
 JDN v 3.14.14 Back-end v 0.2.40
Win10

**To Reproduce**
1. Начните создавать ПО для любой странички, в моём случае это была https://jdi-testing.github.io/jdi-light/bootstrap-new.html (надо залогинится с Roman/Jdi1234) и такие настройки:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/efeb18e0-d84f-48c8-b53a-3948e4edd9b5)

2. Попробуйте добавить ПО через дабл клик по локатору на покрытии
3. Попробуйте добавить ПО через выделение локатора на покрытии и через контектное меню через пункт
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/3dd29bec-1d7e-46cf-9f46-38f160691833)

**Actual behavior**
На панели локаторов - добавления локатора (проставления галочики) не произойдёт
В обратку - если добавить локатор в ПО с панели локаторов - на панели покрытия локатор не станет синим

**Expected behavior**
Добавление локатора в ПО произойдёт

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1550
[3.14.19](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.19)
