### ISSUE TITLE
[High] Значение variables.ContactFormPage.url в экспорте для VIVIDUS должно быть без скобок

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1539]
**Environment details  (please complete the following information):**
JDN v 3.14.2.6 Back-end v 0.2.40
Win10

**To Reproduce**
1. Создайте ПО для странички https://jdi-testing.github.io/jdi-light/contacts.html со следующими настройками:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/bad8a54d-3795-4fef-b9c6-23ebd2106eea)

2. Добавьте в него несколько элементов и нажмите Save
3. Нажмите кнопку Download all as .zip
4. В скачанном архиве откройте файл \src\main\resources\properties\suite\web_app\pages.properties

**Actual behavior**
В файле переменная variables.ContactFormPage.url имеет значение (/jdi-light/contacts.html)
variables.ContactFormPage.url=(/jdi-light/contacts.html)

**Expected behavior**
В файле переменная variables.ContactFormPage.url имеет значение /jdi-light/contacts.html
variables.ContactFormPage.url=/jdi-light/contacts.html
Без скобок должно быть

**Comment by kostrubin** [comment]
[3.14.20](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.20)

**Comment by mobilisf** [comment]
Failed on JDN v 3.14.2.6 Back-end v 0.2.40 [Win 10]

Скобки присутствуют @kostrubin 
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/4b609371-610f-42a1-b84b-fbd7aca9e8fc)
