### ISSUE TITLE
[US-12-4] Шаблон для VIVIDUS нужно поменять на другой

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1540]
### Problem statement/business needs:
От разработчиков вивидуса был получен фидбэк что использование текущего шаблона с примерами (https://github.com/vividus-framework/vividus-sample-tests) - не очень корректно т.к. есть шансы что этот шаблон будет меняться и всё может сломаться с одной стороны + шаблон с примерами содержит много мусора из которого нужен только пример для веба (что правда)

## Description

- Необходимо поменять шаблон с https://github.com/vividus-framework/vividus-sample-tests на https://github.com/vividus-framework/vividus-starter

### Definitions of Done:

- Необходимо поменять шаблон с https://github.com/vividus-framework/vividus-sample-tests на https://github.com/vividus-framework/vividus-starter

В результирующем проекте не будет папок относящихся к НЕ вебу - rest_api, mobile_app и electron

### Dependencies or related tasks:

https://github.com/jdi-testing/jdn-ai/issues/1547

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1662
[3.15.4](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.4)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.4 Back-end v 0.2.64
Vividus works =)
