### ISSUE TITLE
[Severity] Wrong text in onboarding 2

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1541]
## Environment details:
 - 3.14.2.6
 - 0.2.40

## Describe the bug
 On 7/14 the wrong text

## To Reproduce
1. Go to Onboarding
3. in the process, select the Vuetify library 
4. Go to 7/14 step

## Actual behavior
<img width="418" alt="Снимок экрана 2023-09-22 в 19 00 46" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/0e84420e-e125-4578-b5fa-5e2409e4c056">

## Expected behavior
[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=8450-383463&mode=design&t=3bK0M77aAZywnlvp-4)

```
Custom locators are added as selected by default.
```
<img width="418" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/df02e3b9-4f0f-4d24-9f84-f9ff4d1220ce">

**Comment by SemyonKuznetsov** [comment]
<img width="570" alt="Снимок экрана 2024-01-30 в 20 06 21" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/355e4ada-9e64-4767-be89-b648d76b0a46">

**Comment by Iogsotot** [comment]
Blocked by [Severity] Wrong state for new custom locator #1627

**Comment by mobilisf** [comment]
Currently updated text on step 7 is displayed when we choose Vuetify and also when we choose HTML 5 or Material UI.
New text should be displayed only for Vuetify onboarding.

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1696
[3.15.17](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.17)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.17 Back-end v 0.2.69

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/b795d9aa-060e-4ec5-b808-b2019a792c66)
