### ISSUE TITLE
[Minor] Wrong text in onboarding

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1542]
**Environment details:**
 - 3.14.2.6
 - 0.2.40

**Describe the bug**
Step 5/14 change the text, as it is taken from the usual onboarding

**To Reproduce**
1. Go to Onboarding
3. in the process, select the Vuetify library 
4. Go to 5/14 step

**Definitions of Done**
- The text has been changed
- Back button goes into 2/14 or 3/15 (settings, this one ↓ ↓ ↓)
<img width="251" alt="Снимок экрана 2023-09-22 в 19 24 48" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/c218104c-c68e-450b-81fd-4c80c6d6478e">

____

**Actual behavior**
<img width="400" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/05ca8d00-bbdb-4cad-aca8-66e1d26a8d13">

**Expected behavior**
[figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=9378-51187&mode=design&t=3bK0M77aAZywnlvp-4)

```
No elements were found on this page. 
You can go back and change the library settings or create a Custom locator.
```

<img width="400" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/41940760-f926-4472-8ce5-4a5b3d33025a">

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1619
[3.14.41](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.41)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.41 -Passed (Text has been changed)
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/3d70ccd4-4278-463c-865e-c135c514f662)
