### ISSUE TITLE
[Severity] fallen step in onboarding

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1543]
**Environment details:**
 - 3.14.2.6
 - 0.2.40

**Describe the bug**
Then, on 9/14, the plugin just got locked with all the buttons and onboarding ui

**To Reproduce**
1. Go to Onboarding
3. in the process, select the Vuetify library 
4. Go to 9/14 step

**Actual behavior**
<img width="418" alt="Снимок экрана 2023-09-22 в 19 01 14" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/33796fe2-220e-4ccb-b505-b4a64a50caed">

**Expected behavior**
<img width="418" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/c99bd7fb-80ab-468e-9b2e-d8d2d6f4b383">

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.38 - Passed
All 14 steps finished successfully
