### ISSUE TITLE
[US-4-5] Выделение нескольких локаторов на покрытии одним движением мышки

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#155]
Нужно дать пользователю возможность выделять несколько локаторов на покрытии одновременно, зажав левую кнопку мыши и двигая ею в нужном направлении

Связанные задачи:
+ #766
+ #759
+ #758
+ #757

**Comment by savinovava** [comment]
The task is connected with #172

**Comment by IoffeM** [comment]
QA note: check hover

**Comment by SemyonKuznetsov** [comment]
# На экране

## Выделение мышкой
Подводите указатель мыши к первому объекту группы. Указатель нужно поместить возле объекта, но не на объект, иначе начнете перетаскивать объект. Нажмите кнопку мыши в точке слева и вверху относительно фигур, которые необходимо выделить, и перетащите указатель, чтобы создать вокруг фигур рамку выделения.

## Выберите вложенные слои
Когда нажимаете на объект, который является частью группы, выбирается родительский объект по умолчанию. Дважды щелкните объект, чтобы выбрать один уровень вложенности вниз. Повторять, пока не выберете правильные дочерние элементы.

## Глубокий выбор
Если существует много уровней вложенности, вы можете использовать глубокий выбор для выбора вложенного дочернего локатора на экране. Удерживая нажатой клавишу модификатора, выберите рамку верхнего уровня или вложенный объект, щелкнув по нему на экране
* Mac: ⌘ Command
* Windows: Control

## Меню слоёв
1. Выделите группу объектов
2. Щелкните правой кнопкой мыши, чтобы открыть контекстное меню
3. Наведите указатель мыши на опцию выбора локатора
4. Выберите локатор из списка выделенных локаторов
5. Локатор будет выделен, остальное выделение будет снято

## Выделение группы
<img width="347" alt="Navigation" src="https://user-images.githubusercontent.com/101407186/199457234-798849b7-d4ce-4fd6-b61c-ac8f5db8c436.png">
Здесь должны выделиться все и в меню должны быть общие действия, сейчас выполняются только для одного


# Список

## Для выбора нескольких отдельных локаторов:
1. Выберите локатор
2. Удерживая нажатой клавишу Shift, щелкните на другом локаторе
3. Все локаторы между первым и вторым выберутся

это может работать как с чекбоксами, так и с выделением строк

**Comment by SemyonKuznetsov** [comment]
Несоответствие цветов, цвета поменяны наоборот

проработать дополнительно цвета с правильном "выделенное темнее выбранного"

<img width="1222" alt="Снимок экрана 2022-11-07 в 14 32 54" src="https://user-images.githubusercontent.com/101407186/200300591-d7ccaf4c-db13-4fa5-8a47-93cfca207cc5.png">

**Comment by SemyonKuznetsov** [comment]
Переработка логики визуального ховера, выбора и в целом выделения локаторов в списке

Наведение на локатор подсвечивает (Neutral/2) строку и чекбокс (status Hovering), первое нажатие на локатор ставит чекбокс в статус Checked и не меняет фон, при открытии контекстного меню на экране или в списке у выбранных локаторов (любого статуса - выбранные, невыбранные, удалённые или с ошибкой) фон становится темнее (Neutral/4)

Идея удаления синего выделения:
+ к любым выделенным локаторам независимо от статуса будет применяться единое действие, а синий = ассоциация активных локаторов
+ старая логика путала в цвете (ховер=выбор, разный цвет состояния ховера и выбора)
+ синий цвет это primary, он нужен для самых важных элементов и действий с активной логикой

[Figma prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=7106%3A350971&viewport=945%2C-11682%2C0.38&scaling=scale-down-width&starting-point-node-id=7106%3A352318)

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7106%3A352318)

<img width="1278" alt="Снимок экрана 2022-11-07 в 19 48 28" src="https://user-images.githubusercontent.com/101407186/200367196-384a0c46-9eef-4cd0-9b61-1915b7146674.png">

**Comment by savinovava** [comment]
Скроллинг: 
- вести курсором к нижней части экрана
Solution: страница скролиться не будет

CTRL (вместо SHIFT) : добавить в выделение

**Comment by MariiaNebesnova** [comment]
dev notes: https://www.cssscript.com/select-multiple-elements-mouse-drag-selectables/

**Comment by savinovava** [comment]
Появилась разметка 
ЛКМ по объекту -> active
ПКМ -> active+контекстное меню + сбрасывается выделение прошлой группы

**Comment by MariiaNebesnova** [comment]
спрятана кнопка групповых операци в плагине. будет перераюотана в рамках #759 

[3.4.296](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.296)

**Comment by MariiaNebesnova** [comment]
[3.4.299](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.299)

**Comment by Maksim-Kviatkovskii** [comment]
Баг https://github.com/jdi-testing/jdn-ai/issues/795
