### ISSUE TITLE
Прогресс определения видимости локаторов нужно отображать в логе

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1554]
### Problem statement/business needs:
Сейчас расчёт видимости элементов представляет собой чёрный ящик - что-то происходит, причём - просиходит весьма долго, но каков прогресс и двигается ли что либо - непонятно.
Необходимо выводить в лог результат определения для каждого элемента. Должна быть (помимо всего прочего) информация - JDNHash элемента (или его локатор, если JDNHash недоступен), его визибилити - Visible/Invisible

### Definitions of Done:

- DoD1
- DoD2

**Comment by mobilisf** [comment]
Validated on JDN v 3.14.23 Back-end v 0.2.48

Хеш и видимость выводятся в логах.
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/a3ea76e4-e2a2-4123-af1a-225ffb7c32e1)
