### ISSUE TITLE
Распознавание невидимых элементов должно происходить на всех ядрах многопоточно

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1556]
### Problem statement/business needs:
Сейчас определенение - является ли элемент видимым (изменение сделанное в рамках https://github.com/jdi-testing/jdn-ai/issues/1287) через вызов селениума сейчас происходит очень долго. На 100 элементов - уходит примерно 7 секунд. Это много.
При этом - если смотреть на загрузку процессора - видно что все ядра простаивают и не загружены.

Необходимо осуществлять эту операцию многопоточно - на всех ядрах за вычетом двух (т.е. если на машине 16 ядер - считать надо в 14 потоков)

### Definitions of Done:

- DoD1
- DoD2

**Comment by mobilisf** [comment]
Validated on JDN v 3.14.47 Back-end v 0.2.62

Многопоточность загружает ЦП 90-100% при поиске локаторов.
