### ISSUE TITLE
[Critical] Шестой шаг онбоардинга позиционируется неправильно

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1567]
**Environment details  (please complete the following information):**
JDN v 3.14.24 Back-end v 0.2.48
Win10

**Describe the bug**
Начиная с шестого шага онбоардинга - его продолжать невозможно

**To Reproduce**
1. Запустите плагин
2. Начните онбоардинг будучи на странице https://jdi-testing.github.io/jdi-light/contacts.html
3. Дойдите до 6 шага

Наблюдаем:
Система позиционирует область доступную для манипуляций в углу где это не имеет смысла
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/f2024bdc-a3e9-4d38-af21-119ce4c54123)

Ожидаем:
Система позиционирует область доступную для манипуляций над чекбоксом первого локатора

**Comment by Iogsotot** [comment]
> To Reproduce
Steps to reproduce the behavior:
        Запустите плагин....

Проверять на больших сайтах, где есть вложенность компонентов (чем сложнее структура, тем лучше), на "плоских" структурах баг может не показаться.

**Comment by AlexeyGirin** [comment]
Fixed.
