### ISSUE TITLE
Сделать HTML5 библиотеку элементов дефолтной

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1569]
В данный момент - дефолтным выбором является Material UI, что не очень хорошо т.к. его поддержка находится этапе бета тестирования.
Необходимо сделать дефолтным выбором HTML5
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/070feae6-a42d-412e-bc3a-074a4ad433fc)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1580
[3.14.30](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.30)

Теперь при первом запуске приложения будет предложена HTML5 библиотека по умолчанию.
После выбора любой другой библиотеки - выбор будет сохранен в Local Storage как вариант по умолчанию.
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/18f3bbc7-1f35-4d0b-8c06-f14e6aa44677)

**Comment by AlexeyGirin** [comment]
Fixed.
