### ISSUE TITLE
[US-6-8] Удалять невидимые элементы из DOM дерева которое мы посылаем в робулу для расчёта локаторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1575]
### Problem statement/business needs:
В данный момент - мы исключаем из рассмотрения невидимые элементы (после выполнения задачи https://github.com/jdi-testing/jdn-ai/issues/1287) однако эти элементы - присутсвуют в дереве на основании которого робула расчитывает локаторы.
Из-за этого оптимальные локаторы получаются не всегда оптимальные :-)

Классический пример описан в таске - https://github.com/jdi-testing/jdn-ai/issues/1193

### Definitions of Done:

- Невидимые элементы исключены из рассмотрения поэтому их проперти и поля - не влияют на генерацию оптимальных локаторов.
- Будет обрабатываться на фронтенде.

### Dependencies or related tasks:
#1287

**Comment by Iogsotot** [comment]
Если имплементировать через FE, то менять надо значение поля document в WS:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/87b8f487-b336-46e4-ac54-022a3a2934b7)
с FE отсылать "очищенный" от невидимых (isShown: false) нод (информацию об isShown можно брать в response html-predict)

**Comment by InnaRadionova** [comment]
Возможно, фикс сделан не до конца. По следующим шагам нашелся спорный момент:
1. Зайти на страницу google.com
2. Добавить PO и выполнить поиск с дефолтными параметрами
3. Выделить кнопку "мне повезет!" или поиск в Google":
![2024-03-25 02 54 52](https://github.com/jdi-testing/jdn-ai/assets/162306672/3dd0bcf2-b631-4bf8-b88d-0bfeca320316)
![2024-03-25 02 55 17](https://github.com/jdi-testing/jdn-ai/assets/162306672/1d34fee8-94dc-4b0d-831d-399a8b5eb2d2)
4. Для любого из элементов шага 3 открыть редактирование:
![2024-03-25 03 00 26](https://github.com/jdi-testing/jdn-ai/assets/162306672/870204be-c1e4-4428-8245-4af9190846d5)
5. Выбрать локатор, отличный от xPass:
![photo_2023-10-18_19-10-06](https://github.com/jdi-testing/jdn-ai/assets/162306672/3740bb1b-379a-45a5-91de-118b323dded6)
6. Потом снова выбрать xPass:
![photo_2023-10-18_19-10-06](https://github.com/jdi-testing/jdn-ai/assets/162306672/406c3d6e-4a16-44e2-a453-af17b9480184)
После шага 6 в форме отображается ошибка, хотя локатор - уникален. Возможно, фикс выполнен не до конца и не учитывает подобный сценарий.

**Comment by InnaRadionova** [comment]
Возможно, фикс сделан не до конца. По следующим шагам нашелся спорный момент:
1. Зайти на страницу google.com
2. Добавить PO и выполнить поиск с дефолтными параметрами
3. Выделить кнопку "мне повезет!" или поиск в Google":
![2024-03-25 02 54 52](https://github.com/jdi-testing/jdn-ai/assets/162306672/3dd0bcf2-b631-4bf8-b88d-0bfeca320316)
4. Для любого из элементов шага 3 открыть редактирование:
![2024-03-25 03 00 26](https://github.com/jdi-testing/jdn-ai/assets/162306672/870204be-c1e4-4428-8245-4af9190846d5)
5. Выбрать локатор, отличный от xPass:
![2024-03-25 03 01 02](https://github.com/jdi-testing/jdn-ai/assets/162306672/d02283a3-a1dc-46ae-9a32-e9a4eb43c973)
6. Потом снова выбрать xPass:
![2024-03-25 03 02 00](https://github.com/jdi-testing/jdn-ai/assets/162306672/bd88dfe6-0d82-4212-8062-5096f730b807)

После шага 6 в форме отображается ошибка, хотя локатор - уникален. Возможно, фикс выполнен не до конца и не учитывает подобный сценарий.

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.12 Back-end v 0.2.69

Video instruction https://epam-my.sharepoint.com/personal/anna_iustus_epam_com/_layouts/15/stream.aspx?id=%2Fpersonal%2Fanna%5Fiustus%5Fepam%5Fcom%2FDocuments%2FRecordings%2FCall%20with%20Inna%20and%201%20other%2D20240321%5F120555%2DMeeting%20Recording%2Emp4&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview
