### ISSUE TITLE
[US-7-5] Edit types and unique/non-unique for Custom locator

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1576]
### Problem statement/business needs:
Custom locator - конструктор и нам надо давать возможность выбирать что угодно 
![MicrosoftTeams-image (5)](https://github.com/jdi-testing/jdn-ai/assets/101407186/1e822709-72f1-4589-922a-570bcce84f7f)

### Definitions of Done:
- все типы раздизейбливаем и совмещаем в один список без дивайдеров
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/91703378-9644-4e23-8a67-24432f51a508)

### Dependencies or related tasks:
Main - #1285

**Comment by Iogsotot** [comment]
В ходе обсуждений и уточнений задачи, остались только эти 8 типов локаторов:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/11213afc-e6d6-401f-8886-b37f8b032b60)
опция "dataAttributes"(data-*) добавляется только если у локатора есть данные по этому атрибуту

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1688
[3.15.14](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.14)

**Comment by mobilisf** [comment]
Validated on v 3.15.16 Back-end v 0.2.64

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/161cc56f-f242-469c-9a9f-52cce099fdb3)
