### ISSUE TITLE
[Medium] Система закрывает фильтр при включении или отключении типа элемента

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1581]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
Win10

**Describe the bug**
Откликивание и прокликивание единичного типа элемента в фильтре - вызывает его (фильтра) закрытие. Что дико неудобно в том случае если нужно отключить или включить сразу несколько типав элементов

**To Reproduce**
1. Откройте плагин на страничке https://jdi-testing.github.io/jdi-light/contacts.html (пароль - Roman, Pass - Jdi1234)
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All
4. Откройте фильтр
5. Попытайтесь снять чекбоксы с нескольких типов элементов

**Actual behavior**
Сразу после первого клика по любому чекбоксу - система закрывает окно фильтра

**Expected behavior**
Система должна закрывать фильтр только если мы кликнем за пределы его окна

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/issues/1581
The behavior of closing the filter has been changed - now the filter is closed `only by buttons (filter button and close button)`

[3.14.38](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.38)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.38 - Passed
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/54f03d40-2de1-438f-926f-e20155d0941b)
