### ISSUE TITLE
[Critical] Система при копипасте локаторов почему то заключает локатор в одинарные кавычки, а при экспорте - двойные (что правильно)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1582]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
win10

**Describe the bug**
Система при копипасте локаторов почему то заключает локатор в одинарные кавычки, а при экспорте - двойные (что правильно)

**To Reproduce**
1. Откройте плагин на страничке https://jdi-testing.github.io/jdi-light/html5.html (пароль - Roman, Pass - Jdi1234)
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All
4. Добавьте два локатора в ПО и создайте его
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/008598bc-e410-4242-ac40-eb95f5dc782f)

5. Скопируйте ПО в буфер обмена и экспортните в жава файл

**Actual behavior**
В буфере будет (одинарные кавычки, неправильно):
```
@UI('//*[@class='uui-button display-none']')
public Button invisibleButtonCssDisplayNone;

@UI('//*[@id='password']')
public TextArea password;
```
а файле будет (двойные кавычки, правильно):
```
public class Html5Page2 extends WebPage {
    @UI("//*[@class='uui-button display-none']")
    public Button invisibleButtonCssDisplayNone;

    @UI("//*[@id='password']")
    public TextArea password;
}
```

**Expected behavior**
В буфере результат как в экспорте

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1596
[3.14.32](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.32)

**Comment by AlexeyGirin** [comment]
Fixed.
