### ISSUE TITLE
[Minor] Недоступные для экшена локаторы становятся серыми не полностью

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1583]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
win10

**Describe the bug**
Недоступные для экшена локаторы становятся серыми не полностью
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/884e9b38-8c4e-448e-8ecc-e44301db9e63)

**To Reproduce**
1. Откройте плагин на страничке https://jdi-testing.github.io/jdi-light/html5.html (пароль - Roman, Pass - Jdi1234)
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All
4. Введите в качестве фильтра значение `@id='a`

**Actual behavior**
Значение локатора и модификатор доступа - не становятся серыми
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/8de27e63-4891-4949-89a5-c3c47f94d15d)

**Expected behavior**
Должны полноценно становиться серого цвета (ОБСУДИТЬ С СЕМЁНОМ!)

**Comment by Iogsotot** [comment]
@SemyonKuznetsov посмотри, пожалуйста, Expected behavior

**Comment by SemyonKuznetsov** [comment]
вот так - хорошо, я согласен 

<img width="534" alt="Снимок экрана 2024-01-26 в 16 03 54" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/273ae537-3c29-410a-a4df-f1636de9fc53">

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1626
[3.14.46](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.46)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.46 - Passed
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/ddf7ce1d-99a8-481c-b0b0-87d0eb175102)
