### ISSUE TITLE
[High] data* атрибуты должны быть в секции non-unique и быть non-actionable если у них нет значения

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1587]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
win10

**Describe the bug**
`data*` атрибуты должны быть в секции non-unique и быть non-actionable если у них нет значения

**To Reproduce**
1. Откройте плагин на страничке https://www.linkedin.com/mynetwork/invite-connect/connections/
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/5998b59a-0ce9-4b4a-b622-01d6b8da21e2)

4. Откройте на редактирование локатор с именем label (самый верхний)
5. Откройте список возможных локаторов
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/95f72573-347d-4121-a2d7-f8bcafc2c90d)

**Actual behavior**
В списке unique присутствует атрибут data-test-app-aware-link который не имеет значения (и в принципе - тултип правильно говорит, что атрибут не имеет значения)
Проблема в том, что этот атрибут можно выбрать - и тогда начинается раскобалс со значением
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/67f354a0-237a-4856-bc77-e6330be44769)

**Expected behavior**
Атрибут data-test-app-aware-link находится в списке non-unique и недоступен для выбора

Зип файл со страничкой:
[(18) LinkedIn.zip](https://github.com/jdi-testing/jdn-ai/files/13582162/18.LinkedIn.zip)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1606
[3.14.35](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.35)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.38 - Passed
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/ebf2a74f-1cfd-4689-b8c3-4d5e4bf219bb)

**Comment by AleksandraSmolianinova** [comment]
Closed
