### ISSUE TITLE
[Medium] Значения linkText локатора могут содержать спецсимволы, все они должны быть экранированы

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1588]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
win10

**Describe the bug**
Значения linkText локатора могут содержать спецсимволы, все они должны быть экранированы

**To Reproduce**
0. Откройте страничку https://www.linkedin.com/mynetwork/invite-connect/connections/
1. Используя средства браузера добавьте спец символов - двойные, одинарные кавычки в любой контент ссылки
В моём случае это было тут:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/39144810-2f73-468d-96fe-1e5b66babdb3)
а переносы строки - там будут и так
2. Откройте плагин на страничке https://www.linkedin.com/mynetwork/invite-connect/connections/
3. Нажмите кнопку +Page Object
4. Распознайте там HTML5 элементы через кнопку Generate All
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/5998b59a-0ce9-4b4a-b622-01d6b8da21e2)
5. Поищите элемент текст ссылки которого вы поменяли (в моём случа это был элемент с именем membersNameAlexandeRDErevyankoMembersOccupationQaAutomationE)
6. Откройте его на редактирование и поменяйте локатор на linkText
Увидим такую картину:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/39d215b8-b910-48f2-9483-14e75f5859d6)
7. Сохраните локатор

**Actual behavior**
На панели локаторов мы видим такую картину:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/d6602c72-3298-4e7b-bc1b-19b8350d9094)
В экспорте и копипасте в буфер значение такое:
```
@FindBy(linkText = 'Member’s "name
          
            Alexande"r D""er'e''vyanko
          
          Member’s occupation
          
            QA Automation Engineer | SDET | Java, Kotlin | 4.5+ years of experience | Mentor, trained over 40 people in automation')
public Label membersNameAlexandeRDErevyankoMembersOccupationQaAutomationE;
```

**Expected behavior**
Все специальные символы на панели покрытия, в экспорте и в результате копирования в буфер должно быть экранированы, как это написано в разделе Escape Sequences тут - https://docs.oracle.com/javase/tutorial/java/data/characters.html
и результат должен быть такой:
```
@FindBy(linkText = "Member’s \"name\n          \n            Alexande\"r D\"\"er\'e\'\'vyanko\n          \n          Member’s occupation\n          \n            QA Automation Engineer | SDET | Java, Kotlin | 4.5+ years of experience | Mentor, trained over 40 people in automation")
public Label membersNameAlexandeRDErevyankoMembersOccupationQaAutomationE;
```

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1727
[3.15.28](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.28)

**Comment by InnaRadionova** [comment]
Фикса прока не видно.
JDN v 3.15.28 Back-end v 0.2.70

![2024-05-01 15 19 51](https://github.com/jdi-testing/jdn-ai/assets/162306672/a5c04942-89d7-4dcb-92e1-6e390e922fd2)

**Comment by KateDronova** [comment]
Для экранирования использовались только спец. символы из предложенного раздела: https://docs.oracle.com/javase/tutorial/java/data/characters.html (см. в задании в Expected behavior)

**Comment by InnaRadionova** [comment]
> Для экранирования использовались только спец. символы из предложенного раздела: https://docs.oracle.com/javase/tutorial/java/data/characters.html (см. в задании в Expected behavior)

Эти символы присутствовали и в моем наборе тоже

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1731
[3.15.30](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.30)
