### ISSUE TITLE
[High] На панели покрытия потерялись точки с запятой после локаторов (а в экспорте и буфере - они есть)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1589]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
win10

**Describe the bug**
На панели покрытия потерялись точки с запятой после локаторов (а в экспорте и буфере - они есть)

**To Reproduce**
1. Откройте плагин на страничке https://jdi-testing.github.io/jdi-light/html5.html (пароль - Roman, Pass - Jdi1234)
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All

**Actual behavior**
У всех локаторов отсуствуют точки с запятой
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/45720ea3-3583-4347-b129-7f041b0de6e0)

**Expected behavior**
Должны присутствовать:
```
@FindBy(xpath = '//a[contains(text(), 'Search')]')
public Label search;
@FindBy(xpath = '//a[contains(text(), 'Support')]')
public Label supportLabel;
```

**Comment by Iogsotot** [comment]
их никогда(6+ месяцев) и не было
скрин из старой версии, в коде тоже изменения не производились для public
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/5cf9afad-6b4f-4a5e-ac66-5dc80ae543f4)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1596
[3.14.32](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.32)
