### ISSUE TITLE
[High] Система говорит что локатор name уникальный но если его выбрать - сохранить не даёт

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1590]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
win10

**Describe the bug**
Система говорит что локатор name уникальный но если его выбрать - сохранить не даёт - говорит, что не уникальный

**To Reproduce**
1. Откройте плагин на страничке https://www.google.com/
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All
4. Откройте на редактирование локатор с именем btnK
5. Откройте выпадушку вариантов локаторов

**Actual behavior**
Наблюдаем, что локатор name в списке уникальных. Однако если его выбрать - говорит что он не уникальный. 

**Expected behavior**
Тут надо что-то придумать. Например - если он единственный visible локатор, то разрешать сохранять (неразрешать только для селениума

**Comment by Iogsotot** [comment]
не воспроизводится:
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/43bca8a4-fe91-46fc-b7a7-88bad44898d1)

https://github.com/jdi-testing/jdn-ai/assets/50149163/4105ae3f-1b48-49fc-b495-143752c72b2a

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1607
[3.14.36](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.36)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.38 - Passed
