### ISSUE TITLE
[High] Невозможно сделать локатор с кастомным значением (который не xPath и не CSS)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1591]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
win10

**Describe the bug**
[High] Невозможно сделать локатор с кастомным значениме (который не xPath и не CSS - для них это работает)

**To Reproduce**
1. Откройте плагин на страничке https://www.google.com/
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All
4. Откройте локатор с именем magyar на редактирование
5. Переключите локатор на linkText и задайте любое значение которое вызовет ошибку "The locator was not found on the page."
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/fe15dc71-4c5e-40ca-a282-9d73eafd77a7)

6. Сохраните локатор (это возможно и это правильно - мы разрешаем сохранять невалидные локаторы (но не разрешаем сохранять локаторы которые ссылаются на более чем один элемент))

**Actual behavior**
На панели локаторов введённое значение НЕ появится - там будет старое значение (в копировании в буфер и в экспорте - тоже)
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/827104ad-f4e8-4421-8182-b56540c5fe81)

**Expected behavior**
На панели локаторов введённое значение появится.
ОДНАКО - при повторном открытии - значение должно быть перетёрто дефолтным. И комбик выбора типа локатора - должен быть раздизаблен

ВНИМАНИЕ: Жёлтую валидацию (что например локатор не валиден) - мы сохранять позволяем, а вот красную валидацию (что 2 elements were found with this locator) - НЕ позволяем сохранять

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1592
[3.14.31](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.31)

**Comment by AlexeyGirin** [comment]
Fixed.
