### ISSUE TITLE
Передвинуть Annotation select-item для Edit & Create Locator

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1593]
### Problem statement/business needs:
В данный момент - у нас порядок комбобоксов:
1. Тип локатора
2. Аннотация
3. Значение локатора
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/2c04a185-0c00-485a-90e0-491ace9fb63b)

Это немного ломает логику т.к. локатор формируется по принципу: Аннотация-ТипЛокатора-ЗначениеЛокатора
Например:
`By.xPath(//a[contains(text(), 'magyar')])`
или
`@UI("//a[contains(text(), 'magyar')]")`

Хочется что бы порядок в окне едитора был таким:
1. Аннотация
2. Тип локатора
3. Значение локатора

### Definitions of Done:
Аnnotation select передвинут выше Locators type в:
- Edit locator
- Create locator

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/f0336779-35ab-4f2d-9cd3-fb86e24188f4)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1624
[3.14.44](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.44)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.44 - Passed
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/3200a4d5-c5ac-416b-a382-eed57ec4557d)
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/4bf4a303-5e33-42d2-8602-45af1674d943)
