### ISSUE TITLE
[Critical] Плагин падает если кастомный неправильный локатор вернуть в нормальное состояние

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1594]
**Environment details  (please complete the following information):**
JDN v 3.14.31 Back-end v 0.2.58
win10

**Describe the bug**
Плагин падает если кастомный неправильный локатор вернуть в нормальное состояние

**To Reproduce**
1. Откройте плагин на страничке https://jdi-testing.github.io/jdi-light/html5.html (пароль - Roman, Pass - Jdi1234)
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All
4. Откройте на редактирование любой локатор с делайте его невалидным
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/dd743110-753d-4eac-9c47-e5383c0ec1a1)
5. Сохраните
6. Откройте его снова и сделайте валидным (убрать внесённые изменения)
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/34294cc1-8a32-4934-9a41-cd78e454e463)
7. Сохраните

**Actual behavior**
Плагин упадёт в белый экран

**Expected behavior**
Плагин не падает

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1601
[3.14.33](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.33)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.38 - Passed
Invalid:
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/9eb2ff28-aff4-440c-b611-d49c090adeaf)
Valid:
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/a44e2d8a-02f4-4f7a-9d53-6cccd96bda00)
