### ISSUE TITLE
[Medium] Неправильно формируется VIVIDUS имя переменной при копировании в буфер обмена (в экспорте - норм)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1600]
**Environment details  (please complete the following information):**
JDN v 3.14.32 Back-end v 0.2.58
win10

**Describe the bug**
При копировании вивидус локатора в буфер - имя его формируется неверно

**To Reproduce**
1. Откройте плагин на страничке https://jdi-testing.github.io/jdi-light/html5.html (пароль - Roman, Pass - Jdi1234)
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы для VIVIDUS через кнопку Generate All
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/5259ddf1-8ca1-416b-968d-0c9434471925)
4. Скопируйте любой локатор в буфер обмена 
в моём случае это был вот этот:
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/0ff70381-e560-4eca-b7ef-579f16043dda)
5. Вставьте из буфера в редактор

**Actual behavior**
Вставляется вот этот локатор:
`variables.bootstrapForm.Label.bootstrapForm=By.xPath(//*[@index='5']//*[@index='4']/a)`
Система почему-то вместо имени пэйдж обжекта (ContactFormPage) использует тип элемента (bootstrapForm)

**Expected behavior**
Должен вставляться вот этот:
`variables.ContactFormPage.Label.bootstrapForm=By.xPath(//*[@index='5']//*[@index='4']/a)`

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1604
[3.14.34](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.34)

**Comment by AleksandraSmolianinova** [comment]
Tested in 3.14.38 - Passed
![image](https://github.com/jdi-testing/jdn-ai/assets/130548475/d32582eb-1fc4-4566-9863-788ff672b1f3)
Copied:
variables.ContactFormPage.Label.simpleTableLabel=By.xPath(//*[contains(text(), 'Simple Table ')])
variables.ContactFormPage.Label.dates=By.xPath(//*[@index='3']//*[@index='2']/a)

**Comment by AleksandraSmolianinova** [comment]
Closed
