### ISSUE TITLE
[Minor] UI fixed

### ISSUE THREAD

**Issue by Iogsotot** [jdi-testing/jdn-ai#1605]
**Environment details  (please complete the following information):**
 - Front-end version
 - Back-end version

**Describe the bug**
Need to fix this UI bugs:

**Onboarding**:
 - [x] check all disabled buttons and add tooltip (onboarding flow)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/65d031b5-ceea-422d-9b6a-0cfc03ab6824)

 - [x] replace to cursor default
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/bbcbc910-3882-43f8-baad-0e0a78917faa)     

- [x] fix text align
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/82e88fd9-1ff5-4aaa-917c-d5f07ed15639)

- [x] fix height and scroll behavior for locator's list
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/30a75522-bf09-4385-9d99-d77a5b261524)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/a30632a6-8a2c-433f-bca2-aaadaabe13b1)

- [x] fix cancel button on notification
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/2b950385-cb82-4005-adf1-15c7d956b415)

**To Reproduce**
[Optional] Screenshots are welcomed in any step

**Actual behavior**
A clear and concise description of what happens.

**Expected behavior**

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1635
[3.14.48](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.48)

**Comment by mobilisf** [comment]
1) Tooltip added +
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/e639fb71-fc1f-4243-a763-d91312e3c05c)

2) Tooltip added +
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/5aec8bfc-010a-4fae-a313-b5d619377f3a)

3) Is it aligned?
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/9ead3a46-c7c6-45c5-8284-d3a99f7f6dce)

4) Is it fixed? fix height and scroll behavior for locator's list
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/b9ba06d1-770b-4e21-a367-b2711fed97ed)

5) Now it's two separate buttons with one functionality. Is it what we wanted?
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/3dcb8f8c-5677-4411-80f2-4b7ae546e92f)

**Comment by AlexeyGirin** [comment]
All is fine and fixed.
