### ISSUE TITLE
[High] Когда создаем несколько Page Objects в выгрузке теряется последний

### ISSUE THREAD

**Issue by MayaElf** [jdi-testing/jdn-ai#1611]
**Environment details  (please complete the following information):**
JDN v 3.14.30 Back-end v 0.2.58
win10

**Describe the bug**
Когда создаем несколько Page Objects в выгрузке(декларации) теряется последний

**To Reproduce**
1. Откройте плагин на страничке https://jdi-testing.github.io/jdi-light/contacts.html
2. Нажмите кнопку +Page Object
3. Распознайте там HTML5 элементы через кнопку Generate All
4. Сохраните Page Object с локаторами
5. Повторите пп1-4 для странички https://jdi-testing.github.io/jdi-light/html5.html
6. Скачайте Download all as .zip
7. Откройте декларацию MySite

**Actual behavior**
Последний Page Object не выгружается
![image](https://github.com/jdi-testing/jdn-ai/assets/55189259/99e2545b-92af-497c-bd1f-79b98906690c)

**Expected behavior**
Все созданные Page Objects выгружаются
![image](https://github.com/jdi-testing/jdn-ai/assets/55189259/a0720d69-21d0-40a2-a621-b52569b3d21d)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1612
[3.14.39](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.39)

**Comment by AleksandraSmolianinova** [comment]
Tested - passed
`package site;

import com.epam.jdi.light.elements.pageobjects.annotations.Url;
import site.pages.*;

public class MySite {
    //region Example page description - to be removed
    // This is an example of Url definition for the page (not required)
    //@Url("{ENTER_HOME_PAGE_URL}")
    // This is an example of Page description in the Site
    public static FirstPage firstPage;
    //endregion

    // ADD SITE PAGES WITH URLS

    @Url("/jdi-light/metals-colors.html")
    public static MetalAndColorsPage metalAndColorsPage;

    @Url("/jdi-light/contacts.html")
    public static ContactFormPage contactFormPage;
}
`
