### ISSUE TITLE
добавить "Not applicable" для аннотации при выборе Vividus

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1617]
### Problem statement/business needs:
сейчас при создании РО с Vividus у нас селект Annotation дизейблится со значением @ FindBy, что неправильно, так как для Vividus аннотации не доступны
<img width="350" alt="Снимок экрана 2024-01-25 в 12 53 29" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/af46234b-4743-470b-b51e-2515d1f95e32">

### Definitions of Done:

- при выборе Vividus селект Annotation должен быть задизейблен со значением "Not applicable"
<img width="250" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/85361bec-8e73-421f-b397-c76c99b684a6">

- при наведении на этот селект показываем тултип с текстом "Not available for Vividus framework"
<img width="250" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/3229187a-4ae6-44ce-97dc-fedbd7453eaa">

### Dependencies or related tasks:
#799 

### Comments:

Disabled Filled != Disabled Empty
Disabled Filled = значение, которые **выбрано** и ты не можешь его изменить

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1705
[3.15.22](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.22)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.22 Back-end v 0.2.69

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/9c903755-ce75-4a09-a857-59ee7b1566c3)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.22 Back-end v 0.2.69

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/f83d64d4-9727-4ac6-9c2d-2d68d8874691)

**Comment by Iogsotot** [comment]
https://discord.com/channels/1212086641678618715/1212086641678618718/1228252242243616828
