### ISSUE TITLE
Длительность прогресс бара при парсинге увеличить во времени

### ISSUE THREAD

**Issue by MayaElf** [jdi-testing/jdn-ai#1622]
### Problem statement/business needs:
Прогресс бар при парсинге быстро доходит до конца и замирает. Если элементов много, то картинка "замораживается" на 10-12 минут(иногда больше).

### Definitions of Done:

- Прогресс бар идет в течение 12 мин (или какое-то усредненное длительное время)
- Если парсинг заканчивается быстро, то прогресс бар добегает до истечения установленного времени

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1625
[3.14.45](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.45)

**Comment by MayaElf** [comment]
Проверено, все ок, закрыто.
