### ISSUE TITLE
Прогресс бар не должен доходить до конца, если парсинг страницы еще не закончен

### ISSUE THREAD

**Issue by MayaElf** [jdi-testing/jdn-ai#1623]
### Problem statement/business needs:
Прогресс бар доходит до конца даже если парсинг страницы еще не закончен.

### Definitions of Done:

- Пока парсинг страницы не закончен прогресс бар должен остановиться и не доходить до конца.

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1628
[3.14.47](https://github.com/jdi-testing/jdn-ai/releases/tag/3.14.47)

**Comment by mobilisf** [comment]
После парсинга и прогресс бара появляется следующий процесс и он выглядит так:
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/bc19af9a-34f1-435b-83d9-8a0e2a67a40e)

Он должен включаться в процесс прогресс бара или нет?

**Comment by AlexeyGirin** [comment]
Создать отдельный импрувмент на 3.16

**Comment by mobilisf** [comment]
Validated

Improvement created  Also some attention was also paid to checking the performance and ease of use of the application itself.
