### ISSUE TITLE
[US-5-3] Натренировать модель на распознавание HTML5 элементов

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#163]
- [x] создать новый генератор, или обновить старый
- [x] протестировать генератор
- [x] создать простую модель

**Comment by MariiaNebesnova** [comment]
'colorpicker' 'fileinput' 'link' 'radiobutton' 'range' 'table' 'checkbox' 'progressbar' 'textarea' 'button' 'textfield' 'dropdown' 'numberselector' 'datetimeselector' 'selector'

**Comment by aleksandrovskiys** [comment]
@bulgakovmyu Обновленный генератор залил в develop

**Comment by DaryaGurtovenko** [comment]
4 pt (2 full days) for the first round
2 pt (min) for retests and so on
Sum: 6 pt - qa

**Comment by AlexeyGirin** [comment]
Можно начинать тестирование как только пофиксят #221

**Comment by IoffeM** [comment]
REOPENED

JDN v 3.1.117
Back-end v 2022-01-21-15.18.28
Chrome
https://cbracco.github.io/html5-test-page/

1) open the page from the precondition or any other page, it doesn't matter
2) open JDN tab
3) select HTML5 library
4) identify

AR: console error and no correct data
<img width="1304" alt="Screen Shot 2022-02-03 at 12 39 56 PM" src="https://user-images.githubusercontent.com/98175427/152319721-841485f3-d2d4-49a1-92a9-5d4f1a35eed2.png">

ER: it should work as expected

(!) material UI library is ok

**Comment by IoffeM** [comment]
JDN v 3.1.117
Back-end v 2022-01-31-15.52.11
Chrome
https://validator.w3.org/nu/

locators list contains lots of data, but it doesn't marked on the page. More over, when you click any locator in the list or on the page, it doesn't become marked.

**Comment by AlexeyGirin** [comment]
Посмотреть так же страничку - https://jdi-testing.github.io/jdi-light/html5.html на предмет корректности распознавания типа элементов

**Comment by suppnova** [comment]
html-5 модель корректно распознает title и text элементы данной странице (протестировала в test_backend jupyter notebooks). Необходимо выяснить, в какой момент корректный predicted_label из response теряется или заменяется.

![title_text](https://user-images.githubusercontent.com/65091469/170939163-69644129-b8fb-4b70-9852-b30eb263ba64.PNG)


> Посмотреть так же страничку - https://jdi-testing.github.io/jdi-light/html5.html на предмет корректности распознавания типа элементов

**Comment by AlexeyGirin** [comment]
Проблема с мэпингом?
@MariiaNebesnova надо разобраться

**Comment by AlexeyGirin** [comment]
Выяснили, что пока мапинга нет, нужно его сделать.

**Comment by MariiaNebesnova** [comment]
fe 3.1.185
