### ISSUE TITLE
[High] Server crashes on big sites (otto.de)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1630]
**Environment details  (please complete the following information):**
JDN v 3.14.38 Back-end v 0.2.61
win10

**Describe the bug**
Server crashes on big sites (otto.de)

**To Reproduce**
1. Open https://www.otto.de/
2. Open JDN
3. Press Generate All button
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/be0e1be0-0b91-4e2b-9e19-100f927f2f9c)

**Actual behavior**
Server crashes. See log here: [ServerCrash.txt](https://github.com/jdi-testing/jdn-ai/files/14124575/ServerCrash.txt)

**Expected behavior**
No crashes

**Comment by mobilisf** [comment]
Validated on JDN v 3.14.49 Back-end v 0.2.63
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/597d73ec-6301-48fe-939f-552e5d7d4398)

**Comment by AlexeyGirin** [comment]
Fixed.
