### ISSUE TITLE
Реорганизовать облачный сервер

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1634]
### Problem statement/business needs:
В данный момент - инстанс нашего облачного сервера (оба - дев и прод) работает из личной папки @spiridonovfed 
Это неудобно т.к. требует привлечения Фёдора для обновления версии.

### Definitions of Done:
- [x] Инстансы серверов наботают из общей папки не привязанной к конкретному пользователю
- [x] Документация по релизу бэка - обновлена

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.1 Back-end v 0.2.64

Docs on https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/44728321/Back-end+server+in+EPAM+Cloud

/opt/jdi-qasp-ml/{dev,prod} server ecsb003017b9.epam.com
