### ISSUE TITLE
Создать дев энваромент для бэка

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1642]

**Comment by ivnglkv** [comment]
Адрес для подключения и проверки плагина: http://78.47.220.208:5001
![image](https://github.com/jdi-testing/jdn-ai/assets/13216638/908112e3-b721-4c26-b6f4-0ea2413237da)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.24 Back-end v 0.2.71
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/4c22cfa4-a5ea-4404-ae57-bdd8d3d19799)
