### ISSUE TITLE
[High] Scrolling to target locator on locator page doesn't work

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1644]
**Environment details  (please complete the following information):**
JDN v 3.15.0 Back-end v 0.2.64
Win10
Chrome Version 121.0.6167.161 (Official Build) (64-bit)

**Describe the bug**
Scrolling to target locator on locator page doesn't work

**To Reproduce**
1. Go to page https://jdi-testing.github.io/jdi-light/html5.html (Login: Roman / Pass: Jdi1234)
2. Search All locators for page
![image](https://github.com/jdi-testing/jdn-ai/assets/26869421/95abe40b-a971-4e14-9cd8-6fbfc66e7447)
3. Scroll page to the bottom
4. Click on any cover block

**Actual behavior**
System selects coverage block, but nothing else happens

**Expected behavior**
System selects coverage block, system scroll list of locators to make selected locator visible

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1650
[Release 3.15.1: with Hotfix 1644](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.1)
