### ISSUE TITLE
Создать страницу настроек приложения

### ISSUE THREAD

**Issue by ivnglkv** [jdi-testing/jdn-ai#1645]
### Disclaimer
Отчасти эта задача описывает альтернативный подход к интерфейсу настроек описанному в #799, отчасти – описывает новую опцию.

### Problem statement/business needs
В данный момент невозможно подключить плагин к серверу за пределами запрограммированной логики, которая во-первых, не даёт гибкости, а во-вторых, кажется трудно расширяемой.
Как разработчик, я хочу иметь возможность работать с несколькими версиями бэкенда для экспериментов. Сейчас это возможно только с попеременным запуском этих версий, что очевидно неудобно, потому что требует ручной остановки/запуска приложения.
Как пользователь, я хочу иметь возможность развернуть сервер где-то в своей организации и настроить к нему подключение плагина у тестировщиков.

Этого можно достичь добавив нативную для Chrome страницу настроек (документация https://developer.chrome.com/docs/extensions/develop/ui/options-page) на которой сделать возможность задать адрес бэкенд сервера для подключения. Пример как это выглядит у другого плагина:

![image](https://github.com/jdi-testing/jdn-ai/assets/13216638/e8ec93ef-97bd-473a-901f-c4161922900e)

### Definitions of Done

- Страница настроек доступна через меню плагина в Chrome (как на скриншоте)
![image](https://github.com/jdi-testing/jdn-ai/assets/13216638/e2c77ddc-2bd2-4495-a219-f1118ebd08bf)
- На странице настроек можно ввести адрес сервера для подключения.
- Указанный сервер должен иметь приоритет над автоматическим алгоритмом выбора сервера. Возможно даже нужно сделать так, что если пользователь указал адрес сервера вручную, то автоматический выбор сервера не будет включаться, чтобы не было неожиданного поведения, когда локальный сервер не работает, плагин подключился к облачному, а пользователь думает, что он работает с локальным.

### Dependencies or related tasks
\-

### Comments
Есть два варианта реализации такой страницы: в отдельном табе или в небольшом всплывающем окне. Разница описана в документации: https://developer.chrome.com/docs/extensions/develop/ui/options-page#considerations. Возможно выбор между этими двумя опциями нужно обсуждать, чтобы учесть предполагаемое направление дальнейшего развития продукта.

По сути на эту страницу можно будет внедрить и опции предполагаемые в #799, #1531.
Либо как альтернатива – наоборот, вынести выбор сервиса в интерфейс настроек описанный в #799.

**Comment by AlexeyGirin** [comment]
Первая версия должна быть без дизайна Семёна
Но потом - сделаем с дизайном

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.22 Back-end v 0.2.69

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/8e57940b-befb-4200-9f04-cfcf8cffb863)

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/33874653-40f4-4750-a64d-d5ffa901a248)
