### ISSUE TITLE
[Medium] Notify the user when the backend fails

### ISSUE THREAD

**Issue by Iogsotot** [jdi-testing/jdn-ai#1651]
### Problem statement/business needs:
При сбое со стороны бэкенда UI просто останавливается в статусе 'ok' и никак не обозначает, что произошла ошибка.
Если есть сбой, надо как-то об этом сообщать и, возможно, реинициировать коннект.

Эндпоинт, с которого не отлавливается ошибка - html5-predict
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/9c48687f-5ebf-4f43-8cb7-ec0310afa216)
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/e1890a4a-f43e-415e-9038-286157a361fb)

### Definitions of Done:

- в случае ошибки прогресс бар красный и статус failed
- текст ошибки `Server unavailable: check connection or settings (номер ошибки)`

### Design

[figma component link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=10268-86109&mode=design&t=YBI1m6juDwQJFNPx-4)
[figma design](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=11079-94399&mode=design&t=kWV6N32kvZZrhYmh-4)

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/97ccde8b-08f4-4e4b-907f-8cb7a856815a)

**Comment by SemyonKuznetsov** [comment]
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/894c5e93-d255-47e5-b2a8-0dadbd4472b8)

**Comment by bklimov-web** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1673
[3.15.13](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.13)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.14 Back-end v 0.2.69

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/c2afcf16-aa77-49e1-9d57-248e9d5d83ff)
