### ISSUE TITLE
[Critical] При изменении некоторых локаторов отсутствуют данные при редактировании CSS и xPath

### ISSUE THREAD

**Issue by mobilisf** [jdi-testing/jdn-ai#1655]
**Environment details:**
JDN v 3.15.1 Back-end v 0.2.64

**Describe the bug**
При редактировании некоторых локаторов отсутствуют данные CSS и xPath.
И это не зависит от того, что мы выбираем в настройках перед поиском локаторов, - CSS или xPath.

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/79136c7d-118e-42f4-93e7-85bbc4296a10)
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/6d418034-20fe-41ba-98f1-637c74208f68)

**To Reproduce**
1. Запустить поиск локаторов на сайте https://www.otto.de/inspiration/
с выбранными настройками (Locators Type - CSS or xPath)
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/7000d473-9e73-46b3-8450-2141f15e6c06)
2. Нажать на редактирование следующих локаторов
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/9752b2dc-c266-48cf-8e1c-ef4deac8a603)

**Actual behavior**
"No Data"

**Expected behavior**
Данные есть.

**Comment by AlexeyGirin** [comment]
Проверить на обоих бэках

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1712
[3.15.24](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.24)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.24 Back-end v 0.2.70

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/f61bb29b-3aec-4033-ab2c-8af59bfd48c2)
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/b2936831-64cb-438c-b617-915441a9b1bb)
