### ISSUE TITLE
[Low] Поправить анимацию у иконок локатора

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1656]
**Environment details:**

**Describe the bug**
 Квадрат анимации при при клике на 3 точки не выровнен относительно них

**To Reproduce**
1. сгенерировать РО
2. навести курсор на локатор
3. кликнуть на иконку копирования или иконку меню

**Actual behavior**
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/9c2ec9c5-1003-4286-9a7d-0dfc1f953ad2)

**Expected behavior**
у нас нет точного дизайна ховера кнопок, используем антовские стили, по идее ховером должен быть Stroke этого квадрата
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/9d9e7c39-f67f-4d88-86af-801e9ed4f43a)

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1666
https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.7

**Comment by InnaRadionova** [comment]
![2024-03-11 17 11 58](https://github.com/jdi-testing/jdn-ai/assets/162306672/e0e12b33-34c3-4c32-b87f-74fd8cf9df1d)
Validated in JDN Version 3.15.9 
Chrome Version 122.0.6261.112 (Official Build) (64-bit)
