### ISSUE TITLE
[High] Передавать стили в селеноид

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1657]
Очень похоже что мы не передаём стили в селеноид для определения невидимых элементов
Из-за этого - на сайте epam.com находит много элементов даже невидимых т.к. невидимость задаётся стилями
Это было обнаружено в процессе инвестигации https://github.com/jdi-testing/jdn-ai/issues/1633

**Comment by Iogsotot** [comment]
На странице [www.epam.com](http://www.epam.com/) с BE приходят как видимые элементы, которые не видно: 
у них нет класса active => display: none
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/8dccb1a0-324c-48af-8e2a-b01610bc87dc)

**Comment by AlexeyGirin** [comment]
Инлайн вставка стилей в HTML - будет делать Аня - для каждой ноды

**Comment by AlexeyGirin** [comment]
Мяч на стороне Ани

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1672
[3.15.8](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.8)

**Comment by InnaRadionova** [comment]
Validated in JDN v 3.15.10 Back-end v 0.2.62
Chrome Version 122.0.6261.112 (Official Build) (64-bit)

![Uploading 2024-03-14 12 23 56.png…]()
