### ISSUE TITLE
Отключить выбор локаторов правой кнопкой мыши

### ISSUE THREAD

**Issue by mobilisf** [jdi-testing/jdn-ai#1661]
Сейчас выделить и выбрать локаторы можно как правой, так и левой кнопкой мыши.
При этом клик правой кнопкой мыши также открывает контекстное меню, и при групповых операциях, если выбрать несколько локаторов, при сдвиге курсора сбрасывается выделение выбранных локаторов.

Нужно убрать селект правой кнопкой мыши и оставить селект только на левой кнопке.
На клике правой остается только выбор контекстного меню.

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1694
[3.15.16](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.16)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.16 Back-end v 0.2.64
