### ISSUE TITLE
Фичи и их группировка

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1669]
- [x] 1. расписать фичи
- [x] 2. сгруппировать по осмысленным группам (карточная сортировка)
- [x] 3. составить схему
- [x] 4. обновить доку

[figma](https://www.figma.com/file/nYXIrsq1BevSaYBcumAo8o/Architecture?type=whiteboard&node-id=0-1&t=5fan3vcbXmFoprac-0)

**Comment by Iogsotot** [comment]
![JDN Components diagram drawio](https://github.com/jdi-testing/jdn-ai/assets/50149163/0078bd74-e5a7-4613-a9bf-1fab81282be2)

https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/176455703/Architecture
