### ISSUE TITLE
[0.5pt][NR-1][NR-4] Вылетает back-end

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#167]
JDN v 3.0.104
Back-end v 2021-12-01-14.52.21

MacOS

сайт - https://material.io/components/buttons

<img width="1005" alt="Screenshot 2021-12-21 at 09 51 39" src="https://user-images.githubusercontent.com/89466817/146898684-80631185-9369-4f3f-b092-72e42a888cf4.png">

<img width="1424" alt="Screenshot 2021-12-21 at 09 52 05" src="https://user-images.githubusercontent.com/89466817/146898491-51255d5c-b61e-49d9-84b4-425e3b93145f.png">

<img width="1119" alt="Screenshot 2021-12-21 at 09 51 27" src="https://user-images.githubusercontent.com/89466817/146898554-6754ad9c-1be5-4f4f-b46d-854406e16d16.png">

<img width="1118" alt="Screenshot 2021-12-21 at 09 51 14" src="https://user-images.githubusercontent.com/89466817/146898567-ce81e83f-3e64-4d8c-8be9-6224ddc9758b.png">

<img width="1429" alt="Screenshot 2021-12-21 at 09 50 53" src="https://user-images.githubusercontent.com/89466817/146898619-ea652fc0-5218-4bc1-8781-898f367960f9.png">

**Comment by mariia-tokarchuk** [comment]
JDN v 3.0.105
Back-end v 2021-12-20-14.57.33

Обновила версию back-end, но проблема осталась.

**Comment by DaryaGurtovenko** [comment]
Maria should retest on her env because no one has this issue

**Comment by savinovava** [comment]
Может быть связано с #148 ("есть вероятность, что тут та же проблема с тем, что остаются висеть задачи на расчете, они грузят процессор и DS код просто не успевает выполниться за какое-то разумное время и отваливается по таймауту")

**Comment by mariia-tokarchuk** [comment]
JDN v 3.1.106
Back-end v 2021-12-28-09.22.43
MacOS
сайт - https://material.io/components/buttons

**Повторный тест:**
**Шаг 1:** Нажимаю Identify - Дожидаюсь загрузки локаторов - Начинаю пролистывать страницу вниз.
**Результат:** c плагина пропадает Locator List, плагин самостоятельно обновляется до начальной страницы.

**Шаг 2:** Пытаюсь делать повторно генерацию локаторов
**Результат:** вылетает бек-енд.

Баг повторяется каждый раз, когда провожу данные действия.

Ссылка на запись экрана - https://drive.google.com/drive/folders/1bKgU-33CZnWAfNBC2-OlvXwPXk3koJhi?usp=sharing
