### ISSUE TITLE
Переименовать JDN в магазине плагинов и подправить описание

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1671]
- [x] Переименовать JDN в магазине плагинов
Причина - не зная JDN, невозможно найти плагин по ключевым словам
Предложение - "JDN — Page Object Generator"

- [x] И заодно - убрать форматирование текста в описании

<img width="395" alt="Снимок экрана 2024-03-08 в 12 49 04" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/e8760244-cd74-484c-9965-4460625dcec8">

[линк](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=11081-94238&mode=design&t=Op24r8r9jVeAoveE-4)

Just Do Nothing (JDN) — a Google Chrome plugin, which enhances the experience of the Page Objects TF layer creation process. Based on the Robula+ algorithm plugin provides optimized locators for elements.

JDN — helps Test Automation Engineer to create Page Objects in the test automation framework and speed up test development.

The solution delivers the following functionality:  
1. Automatic recognition of objects on the web page
2. Java code creation for UI testing of web objects
3. Ability to manage objects while creating code
4. Recognition of MUI, Vue.js and HTML5 elements

For instructions please follow the link: https://github.com/jdi-testing/jdn-ai#readme

WHAT'S NEW:
- **Improved multithreading support**: Invisible elements are now recognized on all cores, speeding up page processing. 
- **Advanced progress bar**: Added a progress bar that displays parsing and locator calculation processes. 
- **Enhanced locator type selection**: The editing functionality now offers an extended range of locator types including CSS selector, className, data-attributes, id, linkText, name, tagName, and xPath. 
- **Performance improvements**: Parsing of large pages is now faster and more transparent to the user. 
- **HTML by default**: Transitioned to an HTML5 element library to ensure better compatibility and performance. 
- **Enhanced UI**: The interface looks more modern. 

BUF FIXES: 
- **Critical Errors Resolved**: Fixed issues leading to server crashes on large sites, as well as VIVIDUS export errors and incorrect locator copying. 
- **Increased Stability**: Solved problems with locator display on various sites and improved the handling of custom locators. 
- **UI Improvement**: Minor interface corrections, including icon alignment, text, and other UI elements for enhanced usability.

TECHNICAL UPDATES: 
- **ReactJS and Phosphor Icons**: Updated core libraries.

Thanks for your feedback and support!
Have problems or suggestions? Contact us at https://join.skype.com/clvyVvnZvWqc

![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/2aa6649c-38d5-4205-9824-4d80c078264f)

**Comment by InnaRadionova** [comment]
Verified
![2024-03-18 13 49 12](https://github.com/jdi-testing/jdn-ai/assets/162306672/c4c9a848-150f-479d-8ab7-6c7267d346d4)
![2024-03-18 13 49 30](https://github.com/jdi-testing/jdn-ai/assets/162306672/54ae41e7-2b66-493f-b17d-5da2458773b9)
