### ISSUE TITLE
[Medium] Кастомный локатор добавляется с пустым значением xPath

### ISSUE THREAD

**Issue by InnaRadionova** [jdi-testing/jdn-ai#1679]
**Environment details  (please complete the following information):**
JDN v 3.15.10 Back-end v 0.2.62
Chrome Version 122.0.6261.113 (Official Build) (64-bit)

**Describe the bug**
При добавлении кастомного локатора он добавляется с пустым значением xPass

**To Reproduce**
1. Открыть страницу (например, google.com), проинспектировать элемент и скопировать его Full xPass (например, для кнопки "Настройки")
2. Открыть плагин JDN и нажать кнопку + Page Object -> Generate All
3. После создания списка объектов, нажать кнопку + Custom Locator
4. В полях создания локатора заполнить поля: внести имя (любое), Block Type (Button), в поле Locator внести скопированное значение xPass из первого шага.
5. Сохранить локатор

**Actual behavior**
Локатор добавляется с пустым значением xPass

**Expected behavior**
Значение xPass успешно добавляется в созданный локатор и отображается в нем.

![2024-03-15 13 49 36](https://github.com/jdi-testing/jdn-ai/assets/162306672/e18309e7-285f-4bb7-824d-7f7720c51c8a)

![2024-03-15 13 56 40](https://github.com/jdi-testing/jdn-ai/assets/162306672/1005f90e-8f5a-4689-bd01-d340bb23c33a)

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1704#pullrequestreview-1982375140

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.21 Back-end v 0.2.69

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/6af8786b-65ee-4046-8b83-8553875d0bb4)
