### ISSUE TITLE
[US-6-6] Локаторы самостоятельно без действия пользователя перемещаются в вкладку Deleted

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#168]
это происходит когда на странице существует внутренний скролл, например в боковом меню, таблице и т.д., когда мы начинаем скролить этот элемент, покрытие пропадает, а локаторы перемещаются во вкладку Deleted.

примеры:
https://sveltematerialui.com/demo/button/ - при скроле бокового меню
https://mui-treasury.com/components/list-item/ - при скроле бокового меню

Нужно продумать механизм работы плагина в таком случаи. Как понятно для пользователя показать, что локаторы недоступны из-за скрола. Сейчас это неочевидно.

**Comment by savinovava** [comment]
Сейчас при скролле локаторы, которые уходят за header, перемещаются в deleted (в будущем в invisible).

**Comment by savinovava** [comment]
#178 -  посмотреть пример для скролла

**Comment by IoffeM** [comment]
is not actual anymore
