### ISSUE TITLE
[2pt][US-6-1] При клике на локатор на странице, скролл в локатор листе не всегда срабатывает корректно

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#169]
Когда мы кликаем на локатор на странице, при этом локатор в локатор листе находится вне зоны видимости пользователя, плагин автоматически скролится до нужного локатора в локатор листе. 

Но существует проблема: когда у нас есть вкладки в локатор листе Genereted, Waiting for generating, Deleted, при скроле локаторы в некоторых случаях все равно не отображаются пользователю, так как они "прячутся" за вкладками.

**Примеры:**

скрол осуществился, но часть локатора "спряталась" за вкладкой Generated:
<img width="1412" alt="Screenshot 2021-12-21 at 14 50 05" src="https://user-images.githubusercontent.com/89466817/146933075-a5cb186c-1697-40c9-99a0-a52fb5f04bd3.png">

скрол осуществился, но часть локатора "спряталась" за вкладкой Deleted:
<img width="1427" alt="Screenshot 2021-12-21 at 14 50 20" src="https://user-images.githubusercontent.com/89466817/146933097-f91a71d7-3db4-40a9-a442-d996a8b7e60a.png">

скрол осуществился, но пользователь не видит локатор, так как он полностью спрятался за вкладками Waiting for genereting, Deleted:
<img width="1433" alt="Screenshot 2021-12-21 at 15 06 26" src="https://user-images.githubusercontent.com/89466817/146935339-d41e9d5d-b725-4d6d-b909-64d6d9ccf4a4.png">

**Comment by MariiaNebesnova** [comment]
1pt - fe

**Comment by DaryaGurtovenko** [comment]
0.5 pt - qa

**Comment by MariiaNebesnova** [comment]
3.1.110

**Comment by IoffeM** [comment]
JDN v 3.1.112
Back-end v 2021-12-28-09.22.43

Chrome
https://jdi-testing.github.io/jdi-light/index.html 

Is blocked by https://github.com/jdi-testing/jdn-ai/issues/213  
Should stay in Testing before fix.

**Comment by AlexeyGirin** [comment]
Done.
