### ISSUE TITLE
Сделать рефакторинг

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#17]
1. Мы растём из приложения про рулы. Был моб.икс который притащил Рома для стейт менеджмента с которым мы мучаемся. Приходилось писать своё, вместо того что бы притащить Ридекс. Сейчас всё усложнилось, поэтому самописный стейт - ещё будет жить но это самописная штука - на неё нету документации - есть от чего прийти в отчаянье. Это усложняет порог входа на фронте - тем более что у нас большая текучка людей разного уровня. Хочется максимально упростить стейт что бы все видели Ридекс который знают все. И меньше времени тратилось на онбоардинг. Мы избавляемся от рулов и всего остального - два стейт мендежера - это неприемлемо.
Резюмирую - нужно делать рефакторинг (займёт 3-4 дня). Это решит нам ряд проблем.

Задача связана с #11
Но рефакторинг надо начать раньше.
Потом выпиливаем старый код.

**Comment by lisatatarinova** [comment]
test passed
