### ISSUE TITLE
[US-7-3][US-7-2]Валидация локатора

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#170]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/17956888/US-7-3+Validate+user+changes+of+locator+s+path

**Comment by MariiaNebesnova** [comment]
connected #158

**Comment by mariia-tokarchuk** [comment]
<img width="1400" alt="locator validation" src="https://user-images.githubusercontent.com/89466817/148898738-a2060def-a725-4cc3-a4a1-12933063c7c5.png">

Ссылка на figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(New)?node-id=2691%3A37681

**Possible errors after validation of the entered data:**
1) The locator was not found on the page
2) Several elements were found on the page

**Уточнения:**
- Не писать валидацию вручную. Найти и подключить библиотеку, которая валидирует xpath/css. 
- Нужно давать пользователю сохранить введенную ним информацию, даже если возникает ошибка при валидации.
- Использовать inline-валидацию при вводе данных

**Comment by DaryaGurtovenko** [comment]
4 pt - qa (with creating/updating test cases, it's vital on current stage)

**Comment by mariia-tokarchuk** [comment]
Также необходимо сделать валидацию поля Name. Имя локатора должно быть уникальное.

connected #158

<img width="1400" alt="name validation" src="https://user-images.githubusercontent.com/89466817/149727164-c7156a4a-98b3-4f01-99cd-81785e3c0a8e.png">

**Comment by MariiaNebesnova** [comment]
5 pt - fe

**Comment by MariiaNebesnova** [comment]
пока что валидацию css-селекторов не рассматриваем

**Comment by AlexeyGirin** [comment]
Договорились помечать отредактированные элементы карандашиком

**Comment by AlexeyGirin** [comment]
Имя элемента должно быть валидным именем переменной в Java

**Comment by savinovava** [comment]
> 1. Имя элемента должно быть валидным именем переменной в Java
> 2. Если имя не валидно - показываем эррор и не даём сохранять
[UC-7-3-1](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/17956888/US-7-3+Validate+user+changes+of+locator+s+path#UC-7-3-1-Validate-input-field-locator%E2%80%99s-name)
> 3. Если не валиден локатор - показываем варнинг и даём сохранять
[UC-7-3-2](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/17956888/US-7-3+Validate+user+changes+of+locator+s+path#UC-7-3-2-Check-the-locator%E2%80%99s-path)
> 4. В локатор листе тогда показываем варнинг с карандашиком напротиво такого элемента
[UC-7-2-2](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12877879/US-7-2+User+can+edit+locators+manually#UC-7-2-4-User-save-new-parameters-(with-a-warning))
> 5. Если локатор стал указывать на другой элемент - то мы показываем на форме варнинг, но после сохранения - в списке отображаем как саксесс с карандашиком
[UC-7-2-4](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12877879/US-7-2+User+can+edit+locators+manually#UC-7-2-4-User-save-xPath%2C-that-leads-to-another-locator-in-list)

**Comment by AlexeyGirin** [comment]
https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html

**Comment by MariiaNebesnova** [comment]
3.1.115

**Comment by IoffeM** [comment]
REOPENED

JDN v 3.1.117
Back-end v 2022-01-31-15.52.11
Chrome
https://cbracco.github.io/html5-test-page/

1) Если локатор стал указывать на другой элемент - то мы показываем на форме варнинг, но после сохранения - в списке отображаем как саксесс с карандашиком - FAILED

now we see the warning and pencil icon for this case, not success 
we should show success and pencil icon

2) if we enter invalid name, X icon for this name deleting doesn't work
it should delete the invalid name

**Comment by savinovava** [comment]
https://github.com/jdi-testing/jdn/issues/330

**Comment by MariiaNebesnova** [comment]
depends on #427

**Comment by MariiaNebesnova** [comment]
3.1.181
