### ISSUE TITLE
[Severity] Поправить редактирование локатора

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1701]
**Environment details  (please complete the following information):**
JDN v 3.15.1 Back-end v 0.2.62

**Describe the bug**
1. При редактировании внутри самого инпута не должен быть написан локатор

**To Reproduce**
1. Сгенерировать РО
3. Открыть редактирование локатора
4. Открыть дропдаун локатора

**Actual behavior**
Локатора написан внутри инпута типа локатора (дублируется)
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/dcf823e8-be41-46f5-82da-769e2a89e493)

**Expected behavior**
Локаторы видно в только дропдауне при выборе другого типа локатора
![image](https://github.com/jdi-testing/jdn-ai/assets/101407186/07ce4dc1-a75b-402b-952b-0255e75af8ef)

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1725
[3.15.26](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.26)

**Comment by InnaRadionova** [comment]
JDN v 3.15.27 Back-end v 0.2.64

![2024-04-26 16 38 33](https://github.com/jdi-testing/jdn-ai/assets/162306672/32d870d7-e44a-4e2d-a522-411b74c93c61)

![2024-04-26 16 38 06](https://github.com/jdi-testing/jdn-ai/assets/162306672/51e19869-a183-4971-b45b-414b9e4ca541)

**Comment by SemyonKuznetsov** [comment]
<img width="730" alt="Снимок экрана 2024-06-20 в 13 04 01" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/62b575f4-b949-43f7-a602-e2f2c396495f">

можем добавить кавычки? название и локатор слипаются
