### ISSUE TITLE
[Severity] Select element на покрытии крашит плагин

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1702]
**Environment details  (please complete the following information):**
JDN v 3.15.1 Back-end v 0.2.62
Mac Sonoma 14.4.1
Chrome Версия 123.0.6312.87 (Официальная сборка), (arm64)

**Describe the bug**
Select element на покрытии крашит плагин

**To Reproduce**
1. Сгенерировать РО
2. Выделить локаторы на покрытии
3. Выбрать локатор через Select element

**Actual behavior**

https://github.com/jdi-testing/jdn-ai/assets/101407186/77eb007c-3c33-4a9a-b4de-e906bb509aad

**Expected behavior**
Плагин не крашится, можно выбрать локатор из списка

**Comment by Iogsotot** [comment]
possible duplicate https://github.com/jdi-testing/jdn-ai/issues/1495
Fixed by https://github.com/jdi-testing/jdn-ai/pull/1698
[3.15.18](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.18)
