### ISSUE TITLE
Поправить расстояния между элементами

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#1703]
### Problem statement/business needs:
1.
Поправить расстояние для строки РО
<img width="700" alt="Снимок экрана 2024-04-04 в 14 46 38" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/c3bd5d87-fd03-44b0-8f09-00bb570bf2a2">

сейчас там есть ненужный padding в 12
<img width="700" alt="Снимок экрана 2024-04-04 в 14 44 35" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/e591b475-5f9a-456d-8f2f-2c307b74a59a">

2.
Поправить общие отступы в панели создания РО
<img width="999" alt="Снимок экрана 2024-04-04 в 14 40 01" src="https://github.com/jdi-testing/jdn-ai/assets/101407186/22c6b160-d720-469b-a357-cf7621114adb">

[Figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?type=design&node-id=11754-114345&mode=design&t=9NGVQKcIlbj0GEs5-4)

пишите по доп деталям или вопросам к @SemyonKuznetsov 

### Definitions of Done:

-

**Comment by KateDronova** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1724
[3.15.25](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.25)

**Comment by mobilisf** [comment]
Validated on JDN v 3.15.25 Back-end v 0.2.70

![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/a2b37ab1-77de-47ab-90bc-d7553b7925b9)
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/e24674b6-ebd6-46fa-b6c7-b2cc6956ee0d)
