### ISSUE TITLE
Подправить инструкцию по запуску бэка

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#1706]
После внесения изменений в бэк - изменилась строка запуска локального бэка.
Необходимо внести изменения в:
1. Рид ми файл на гитхабе
2. Инструкция зашитая в код

@ivnglkv - предоставь новый строки запуска (4 штуки)

**Comment by ivnglkv** [comment]
В dev-ветке бэка это уже есть:
https://github.com/jdi-testing/jdi-qasp-ml/tree/develop?tab=readme-ov-file#take-docker-image-from-github

**Comment by InnaRadionova** [comment]
![2024-04-26 18 12 13](https://github.com/jdi-testing/jdn-ai/assets/162306672/6bf05995-ff7a-4df7-9ca2-388d175f7ed1)
Посмотрела на Win версию Development, все работает ок)
