### ISSUE TITLE
[Medium] Если на странице есть одинаковые элементы, то такой объект нельзя отредактировать 

### ISSUE THREAD

**Issue by InnaRadionova** [jdi-testing/jdn-ai#1714]
**Environment details  (please complete the following information):**
 - JDN v 3.15.22 Back-end v 0.2.62
 - Chrome Version 123.0.6312.122 (Official Build) (64-bit)

**Describe the bug**
Если на странице есть одинаковые элементы, то такой объект нельзя отредактировать 

**To Reproduce**
1. Зайти на страницу google.com
2. Добавить PO и выполнить поиск с дефолтными параметрами
3. Выделить кнопку "мне повезет!" или поиск в Google":
![2024-03-25 02 54 52](https://github.com/jdi-testing/jdn-ai/assets/162306672/f04478f0-dd32-46e3-88f4-d243cfcbe836)
4. Для любого из элементов шага 3 открыть редактирование:
![2024-03-25 03 00 26](https://github.com/jdi-testing/jdn-ai/assets/162306672/3cf3e03a-5627-45c9-b7a6-6e8cc3fddc51)
5. Внести любое изменение, чтоб активировалась кнопка сохранения изменений (например, добавить "1" в поле Name) и нажать Ок

**Actual behavior**
В форме отображается ошибка:
![2024-03-25 03 02 00](https://github.com/jdi-testing/jdn-ai/assets/162306672/f5395b98-d46f-455a-b3f8-d348b1e69084)

**Expected behavior**
Необходимо избегать такой ошибки для объектов: вероятно, сделать локатор уникальным. 

**Примечание:**
Проблема возникает по той причине, что создание списка объектов идет на "обрезанном" дереве, а валидация при редактировании - на полном. Чтобы избежать этой проблемы, нужно проводить валидацию на том же дереве, на котором создавался список объектов.

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1740
включена фича с расчетом CSS selector на бэкенде и download all as zip (см https://github.com/jdi-testing/jdn-ai/issues/1284 https://github.com/jdi-testing/jdn-ai/issues/1734) для **локального бэкенда** ( issue_1284-backend-calculation-of-css-selectors -l pr-192)
[3.15.35](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.35)
