### ISSUE TITLE
Unable to fetch Page css by link

### ISSUE THREAD

**Issue by Iogsotot** [jdi-testing/jdn-ai#1715]
**Проблема**
при попытке загрузить стили страницы (для нужд бэкенда), появляется ошибка в консоли плагина и часть стилей не загружается
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/e2b797a5-dfc3-4482-b24a-c6a5447cd906)

**Что хотелось бы**
Ошибки в консоли нет, все стили загружаются

**Как проверить**
1. зайти на сайты типа 
     - google.com
     - otto.de
2. Запустить плагин JDN
3. Нажать Generate All
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/8a8b6e20-a9cd-4836-87a6-6ae1c086ef29)
4. Открыть dev tools console и  проверить на error (см скрин ошибки в разделе "Проблема")

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1735
[3.15.32](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.32)

**Comment by Iogsotot** [comment]
Временно отключена фича с расчетом CSS selector на бэкенде и download all as zip (см https://github.com/jdi-testing/jdn-ai/issues/1284 https://github.com/jdi-testing/jdn-ai/issues/1734)
Без этих фич можно смотреть билд версии [3.15.34](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.34)

**Comment by Iogsotot** [comment]
Включены фичи с расчетом CSS selector на бэкенде и download all as zip (см https://github.com/jdi-testing/jdn-ai/issues/1284 https://github.com/jdi-testing/jdn-ai/issues/1734) для **локального бэкенда** ( issue_1284-backend-calculation-of-css-selectors -l pr-192)
[3.15.35](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.35)

**Comment by Vehemen** [comment]
Не вижу ошибки ни на одном из представленных сайтов.
