### ISSUE TITLE
[Medium] Ошибки при определении локаторов

### ISSUE THREAD

**Issue by mobilisf** [jdi-testing/jdn-ai#1716]
https://www.otto.de/inspiration/
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/b6da02b0-f600-4fdd-863a-81436b072cee)

При подсчете локаторов возникают ошибки:
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/65c03bcf-c9d6-40f4-a775-d9178c89f2c8)

Большая часть ошибок на сайте находится в карусели, но при этом часть локтаторов в карусели правильная, а часть с ошибками:
![image](https://github.com/jdi-testing/jdn-ai/assets/26061296/eddacc6b-c36a-4147-afc3-835a952b8598)

Нужно понять возникают ли ошибки на нашей стороне, или действительно "Document does not contain given element".

**Comment by Iogsotot** [comment]
Возможно, связано с неполученим ответа на одном из звеньев WS (не приходит ответ на запрос по обсчету CSS selector и падает ошибка)

**Comment by Vehemen** [comment]
Выглядит нормально на версии 3.15.36
