### ISSUE TITLE
[4 pt]Drop id, title and name attributes from model's attributes list

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#173]
These labels shouldn't affect on recognition
[ "aria-label","aria-describedby","aria-colindex","aria-expanded","aria-rowcount","aria-controls","aria-valuenow","aria-selected","aria-rowindex","aria-labelledby","aria-valuemin","aria-invalid","aria-checked","aria-hidden","aria-haspopup","aria-sort","aria-valuemax","aria-disabled","aria-multiselectable","aria-current","aria-colcount","aria-orientation","placeholder","focusable","rows","title","typenumber","viewBox","value","for","id","name","min","max"]

**Comment by pulya-na-vullet** [comment]
Все ок на версии
JDN v 3.0.106
Back-end v 2021-12-22-14.54.53
