### ISSUE TITLE
[High] download_template endpoint not working 

### ISSUE THREAD

**Issue by Iogsotot** [jdi-testing/jdn-ai#1734]
**Environment details  (please complete the following information):**
 - Front-end version: 3.15.31
 - Back-end version: 0.2.71

**Describe the bug**
на dev энве не приходит ответ с эндпоинта - http://78.47.220.208:5000/download_template  (порт 5001 аналогично не работает)
на prod аналогично http://78.47.220.208/download_template 

(локальный энв возвращает файл  http://localhost:5050/download_template)

Если фронт не получает ответ с download_template , то ему нечего предложить на скачивание в виде архива (отдельные js и java фронт формирует) и поэтому не работает функционал `download all as .zip`

Connection Error: Cannot connect to host github.com:443 ssl:default [Connection timed out]
![image](https://github.com/jdi-testing/jdn-ai/assets/50149163/a42dbf78-addc-4ace-9f12-80269dd03b75)

**To Reproduce**
1. Run JDN extension
2. Open network, wait ~60s
3. See error

**Actual behavior**
 не приходит ответ с эндпоинта download_template

**Expected behavior**
эндпоинт download_template возвращает blob для формирования архива

**Comment by ivnglkv** [comment]
Скорее всего файрвол неправильно настроен, я посмотрю

**Comment by Iogsotot** [comment]
[3.15.37](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.37) - включены фичи со скачиванием PO в виде архива (и с запросом расчета CSS на бэкенде)

**Comment by Vehemen** [comment]
Если я правильно понял: 
1) установить 37 версию плагина
2) выбрать бэк по http://78.47.220.208:5000
3) создать pom
4) Выгрузить pom
Раньше была ошибка, сейчас pom выгружается. Версия http://78.47.220.208:5000 - 0.2.64 При этом селекторы до конца не грузятся, Internet error, в inspect ошибок не вижу

**Comment by Vehemen** [comment]
На прод поведение аналогичное (на xpath). Локально, предсказуемо, всё отрабатывает нормально

**Comment by Iogsotot** [comment]
Порт 5001, тк было изменение апи. И нам надо обеспечивать одновременно поддержку сторовского приложения (старый бэк) и дев версии (новый бэк, 5001 порт)
