### ISSUE TITLE
Rework section "Allow indexes" in settings

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#174]
Подумать о том что бы слить все три опции про индексы в одну опцию

**Comment by mariia-tokarchuk** [comment]
Планирую провести исследования данной функциональности:

- показать респондентам реальные примеры работы плагина, используя данные настройки; 
- насколько эти настройки необходимы, удобны, в каких случаях их можно использовать;
- действительно ли есть кейсы когда можно применять все 3 разные "Allow indexes".

**Comment by IoffeM** [comment]
QA note: actualize all depended test cases after implementation

**Comment by AlexeyGirin** [comment]
Пользователи говорят, что использование индексов - явно не желательно.
Решение - ОТКЛЮЧИТЬ использование всех индексов в конце по умолчанию

**Comment by MariiaNebesnova** [comment]
в результате будет одна дефолтная настройка, не доступная к редактированию пользователю?

**Comment by AlexeyGirin** [comment]
Duplicates #279
