### ISSUE TITLE
[Regress 3.0.106] Увеличенное время распознавания страницы в сравнении с предыдущей версией ПО backend

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#176]

**Comment by pulya-na-vullet** [comment]
Стенд:
JDN v 3.0.106
Back-end v 2021-11-26-14.32.52
Сайт:
https://mui.com/components/buttons/

Долгое распознование локаторов 

На версии:
JDN v 3.0.106
Back-end v 2021-12-17-16.46.12
Распознается гораздо быстрее

**Comment by AlexeyGirin** [comment]
Not a bug
