### ISSUE TITLE
[1.5pt][NR-2][Regress 3.0.106] Нарушены стили в меню Edit

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#177]

**Comment by pulya-na-vullet** [comment]
https://mui.com/components/buttons/
JDN v 3.0.106
Back-end v 2021-12-22-14.54.53

Переходим из списка локаторов в меню Edit

ОР: стили корректны и соответствуют дизайну

ФР: стили нарушены
<img width="1432" alt="Снимок экрана 2021-12-24 в 8 56 30 AM" src="https://user-images.githubusercontent.com/61897393/147322410-f8df4ef8-cfda-4858-9578-a125b063cea8.png">

**Comment by pulya-na-vullet** [comment]
<img width="350" alt="Снимок экрана 2021-12-24 в 10 11 47 AM" src="https://user-images.githubusercontent.com/61897393/147328089-266bc5fc-041c-47cc-a456-8ad26c0c0474.png">

**Comment by AlexeyGirin** [comment]
Нужно залить в мастер и можно будет тестировать

**Comment by MariiaNebesnova** [comment]
3.1.108

**Comment by IoffeM** [comment]
JDN v 3.1.113
Back-end v 2022-01-21-15.18.28
Chrome

AR:
<img width="475" alt="Screen Shot 2022-01-26 at 2 17 20 PM" src="https://user-images.githubusercontent.com/98175427/151154606-cfa505cc-1317-4e5f-8971-5c6d00ec6131.png">
<img width="475" alt="Screen Shot 2022-01-26 at 2 20 54 PM" src="https://user-images.githubusercontent.com/98175427/151154655-5cd551af-15b0-40f4-9ad2-ba2f65b66587.png">

ER:
<img width="475" alt="Screen Shot 2022-01-26 at 2 17 40 PM" src="https://user-images.githubusercontent.com/98175427/151154693-f3f67c39-34ed-47cc-bd24-560d5d423ee7.png">
<img width="475" alt="Screen Shot 2022-01-26 at 2 21 03 PM" src="https://user-images.githubusercontent.com/98175427/151154716-279d56a4-e863-4254-8e62-8ccd1be7e2e4.png">

Reopen.

QA - 0.5pt

**Comment by IoffeM** [comment]
the same issue
<img width="338" alt="Screen Shot 2022-01-26 at 3 34 13 PM" src="https://user-images.githubusercontent.com/98175427/151163819-96bbaf5f-37ba-4e9b-9128-648104800c6b.png">

**Comment by IoffeM** [comment]
QA note: check all modals styles on different webpages

**Comment by MariiaNebesnova** [comment]
closing icon "X" is fixed in 3.1.115

**Comment by IoffeM** [comment]
There are system styles applied to our modal. 
Discussed with @MariiaNebesnova , we decided to close current issue.
Issue with system style is too low priority, no need to waste time.
Close.
