### ISSUE TITLE
[NR][Regress 3.0.106] Ошибка скрола локаторов на странице

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#178]
https://mui.com/components/buttons/
JDN v 3.0.106
Back-end v 2021-12-22-14.54.53
При прокрутке страницы с распознаными локаторами съезжает список локаторов:
До скрола:
![image](https://user-images.githubusercontent.com/61897393/147353838-74456b21-72d9-4735-a397-baf795169c78.png)
После скрола:
![image](https://user-images.githubusercontent.com/61897393/147353874-32587c1a-8136-4f9c-a081-5378295edce3.png)

**Comment by MariiaNebesnova** [comment]
также смотреть #169

**Comment by AlexeyGirin** [comment]
Вернуться к этому багу после #171

**Comment by IoffeM** [comment]
will be tested in invisible locators feature. no need to save this ticket
