### ISSUE TITLE
[US-9-2]Инструкция по установке бэкэнда - декомпозиция

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#18]
Система должна проверять наличие доступного и запущенного бэкэнда (одновременно проверять два источника - наличие локального сервера и доступность клауд сервера).
1. Если таковые недоступны совсем вообще - выводить на экран инструкцию по запуску и инсталляции серверной части (раздел "Setup server part" из файла https://github.com/jdi-testing/jdn-ai/blob/master/README.md).
2. Если что-то есть - подключаться к нему. 
3. Если доступны оба - подключаться к тому который обнаружили первым.
4. Если версия первого попавшегоя сервера - несовместима с версией плагина - пробовать подключиться ко второму источнику. 
5. Если его нет или его версия тоже не совместима с версией плагина - выводить инструкцию по обновлению плагина и/или серверной части (разделы "Setup plugin to Chrome" и "Setup server part" из файла https://github.com/jdi-testing/jdn-ai/blob/master/README.md)

- [x] https://github.com/jdi-testing/jdn-ai/issues/333
- [x] https://github.com/jdi-testing/jdn-ai/issues/646
- [x] https://github.com/jdi-testing/jdn-ai/issues/647
- [ ] Имплементация плагина

US: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/19398677/US-9-2+Instruction+for+downloading+the+plugin

ф5 - б10
клауд бэк 9 - версия старая
клауд бэк 11 - он старый
докер бэк v.9 - предлагаем обновить сервер
докер бэк v.11 - предлагает обновить плагин

**Comment by mariia-tokarchuk** [comment]
![Are you using the JDN plugin for the first time_](https://user-images.githubusercontent.com/89466817/140697215-a8e82317-0361-4d5f-8c9a-ae42459e92bb.png)

![you need to setup server part](https://user-images.githubusercontent.com/89466817/140697235-25dd6484-bf9c-43f8-8612-26eb3b03df1a.png)

![you need to run back end](https://user-images.githubusercontent.com/89466817/140697252-505c71c2-a964-493e-b747-d04c5d071fa9.png)

![Notification  - Ooooops   The back end is not installed or not running!](https://user-images.githubusercontent.com/89466817/140697296-44c81d01-cc58-49f2-a5f6-83e05b3d971c.png)

**Comment by AlexeyGirin** [comment]
Дизайн готов, но текст надо обновить т.к. Мансур перенёс на гитхаб

**Comment by MariiaNebesnova** [comment]
5 pt - fe

**Comment by AlexeyGirin** [comment]
1. Нужен UX показа инструкции на панели плагина (не модалкой, как это хотели изначально)
2. Нужна ручка от Фёдора для выдачи контента с плагину
3. Имплементация плагина

**Comment by MariiaNebesnova** [comment]
3.2.253
