### ISSUE TITLE
US Extension

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#183]
Здесь будут собраны вопросы по новым доработкам и дизайну

**Comment by savinovava** [comment]
US-6-8 Manage invisible locators https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/21594181/US-6-8+Manage+invisible+locators comment
- [ ] US-6-8-Q1. Будем ли отображать статус генерации элемента?
- [ ] US-6-8-Q2. Какие действия доступны с элементом?

**Comment by savinovava** [comment]
US-13-1 Create the archive of generated objects https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22315012/US-13-1+Create+the+archive+of+generated+objects (comment)

- [ ] 13-1-Q1: Можем ли мы скачать несколько объектов со страницы Page Objects, а не все? Если так, то будет ли отображено, какие объекты/пакеты были скачаны?
- [ ] 13-1-Q2: Что происходит после скачивания: всё объекты остаются? Будут ли помечены скачанные объекты? 
- [ ] 13-1-Q3: Должен ли как-то поддерживаться порядок в конечном архиве? Если так, то можем ли мы перемещать packages в списке объектов? Или в целом устанавливать порядок?
- [ ] 13-1-Q4: Есть ли разница в формате файла при скачивании нескольких локаторов, одного Page Object всего архива?

**Comment by savinovava** [comment]
US-14-2 Identify elements in Page Objects
- [ ] US-14-2-Q1: Как мы генерируем имя Page Object? Просто по порядку Page Object 1, Page Object 2 или мы можем как-то идентифицировать группу выделенных объектов?

**Comment by savinovava** [comment]
US-14-4 Include section https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22347783/US-14-4+Include+section
- [ ] US-14-4-Q1 Какой тип у этих Page Objects?

**Comment by savinovava** [comment]
US-4-4 Highlight elements on hover in locators' list https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22380596/US-4-4+Highlight+elements+on+hover+in+locators+list (comment)

US-4-4-Q1 Будем ли мы аналогично подсвечивать элементы в локатор листе при наведении на странице?
US-4-4-Q2 Есть ли такая же логика для invisible locators?

**Comment by savinovava** [comment]
US-6-8-Q3 Как локаторы могут стать обратно видимыми? 
US-6-8-Q4 Локаторы, которые не видны на странице, например футер, будут ли распознаваться сразу как invisible?
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/21594181/US-6-8+Manage+invisible+locators

**Comment by savinovava** [comment]
US-7-3 Validate user changes of locator's path
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/17956888/US-7-3+Validate+user+changes+of+locator+s+path
US-7-3-Q1 What are these reserved key words?
US-7-3-Q2 What Java rules can be applied for the locator?

**Comment by savinovava** [comment]
US-7-1-Q1 Имена генерируются на основе типа элемента. Идея привязаться к его атрибутам (caption-название кнопки). Например, button_cancel, editbox_description.
Как генерировать элемент - Ольга Иванова.

**Comment by savinovava** [comment]
US-14-6 Page Object's settings
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27721756/US-14-6+Page+Object+s+settings

- [ ] US-14-6-Q1 Будем ли мы показывать какое-либо предупреждение или попап при удалении Page Object?
- [ ] US-14-6-Q2 Page Object validation - требования к ней

**Comment by savinovava** [comment]
US-14-8 Add locators to existing Page Object
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27852825/US-14-8+Add+locators+to+existing+Page+Object

 - [ ] US-14-8-Q1 Какой должен быть статус у сгенерированных локаторов? Если пользователь добавляет новые локаторы:
- С изменённой страницы (feed page)

**Comment by savinovava** [comment]
US-6-3 Prioritize the generation of elements

US-6-3-Q1: Что произойдёт, если локатор уже сгенерируется, но пользователь будет с ним взаимодействовать?

**Comment by AlexeyGirin** [comment]
Done
