### ISSUE TITLE
[US-7-4] Usage of emoji

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#185]
If elements on the page contain emoji it shouldn't crush XPath and names of downloaded files

**Comment by spiridonovfed** [comment]
No issues found while testing several cases.
Need clarification what cases can cause failure if any

**Comment by MarinaFm** [comment]
Task is checked. If element on the page contains emoji it is displayed in locator. If title of the page contains emoji it doesn't displayed in Page Object name
