### ISSUE TITLE
Update feature scope

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#186]
- [ ] Update dependencies
- [ ] Update design links

**Comment by savinovava** [comment]
- [ ] for Upgrade
- [ ] for CSS setting 
- [x] for move to back/front - created US-4-6 (https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/24772609/US-4-6+Moving+highlited+objects+to+back+to+front)
- [x] update US-7-3

**Comment by savinovava** [comment]
- [ ] Update Feature List for US-7-3, 7-2

**Comment by savinovava** [comment]
#183 - will be closed after updating

**Comment by savinovava** [comment]
- [ ] Update all US in the Epic 15

**Comment by savinovava** [comment]
- [ ] Update US-2-2

**Comment by AlexeyGirin** [comment]
Done.
