### ISSUE TITLE
[US-14-1] Разбиение на секции - имплементация

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#194]
Общая ссылка на Figma:
https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(New)?node-id=0%3A1

Также ссылка на новый дизайн добавлена в Confluence:
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2261362/UI+UX+design#UI%2FUX-Design-for-the-next-release

**Comment by savinovava** [comment]
Duplicate: #242
