### ISSUE TITLE
[US-9-3] Запретить открывать и пользоваться вторым инстансом плагина - ИМПЛЕМЕНТАЦИЯ

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#195]
В рамках фиксации #135

**Comment by mariia-tokarchuk** [comment]
При открытии второй и более вкладки плагина, вместо стандартного интерфейса, пользователю должно отображаться уведомление об ошибке:

<img width="1400" alt="error" src="https://user-images.githubusercontent.com/89466817/149282350-e98a670d-e789-47a6-b22d-82f81b68b54e.png">

**Comment by MariiaNebesnova** [comment]
4pt - fe

**Comment by DaryaGurtovenko** [comment]
0.5 - qa

**Comment by MariiaNebesnova** [comment]
3.1.113

**Comment by IoffeM** [comment]
JDN v 3.1.113
Back-end v 2022-01-21-15.18.28
Chrome
<img width="1315" alt="Screen Shot 2022-01-26 at 12 38 13 PM" src="https://user-images.githubusercontent.com/98175427/151139472-c0fa61dc-988d-4240-8bdf-b6fd12a3ecaf.png">

As i understood, we should avoid and show warning alway if there is already opened tab. No matter which status has our progress, we should show warning immediately. 
If selected 1 tab and closed others, warning should be hidden immediately with no reload and start working correctly.

@AlexeyGirin what about this logic?

Reopen the issue.

**Comment by IoffeM** [comment]
0.5pt

**Comment by AlexeyGirin** [comment]
Добавить кнопку Retry и немного изменить мессадж

**Comment by mariia-tokarchuk** [comment]
<img width="1400" alt="error" src="https://user-images.githubusercontent.com/89466817/151912808-60f533bd-18a8-4325-a471-524794e75172.png">

Ссылка на фигму - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=2669%3A36218

___

Если в будущем будет возможность реализировать вариант с автоматическим обновлением информации, как предложила Маргарита - будет хорошо. Он более user-friendly.

**Comment by MariiaNebesnova** [comment]
3.1.116

**Comment by AlexeyGirin** [comment]
Понять связан ли критический баг со всей задачай в целом (если не связан - пофиксить только баг)

**Comment by MariiaNebesnova** [comment]
3.1.169
