### ISSUE TITLE
[US-6-3] Приоритезация локаторов в Locator List

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#196]
Новый функционал: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/17956865/US-6-3+Prioritize+the+generation+of+elements

**Comment by MariiaNebesnova** [comment]
3pt - fe

**Comment by DaryaGurtovenko** [comment]
1.5 pt - qa

**Comment by mariia-tokarchuk** [comment]
Актуальный дизайн здесь - 
https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=2958%3A41698
[US-6-3] Prioritize the generation of elements

**Comment by savinovava** [comment]
https://github.com/jdi-testing/jdn-ai/issues/183#issuecomment-1029726942

US-6-3-Q1: Что произойдёт, если локатор уже сгенерируется, но пользователь будет с ним взаимодействовать?

**Comment by MariiaNebesnova** [comment]
мы приоретизируем только тех, кто еще не начал считаться (статус PENDING)?

**Comment by AlexeyGirin** [comment]
Манипулировать локаторами в любом состоянии можно. Важно, что в расчёт брался первый не просчитываемый локатор сверху списка. (т.е. манипулировать локаторами которые уже считаются - тоже можно)

**Comment by MariiaNebesnova** [comment]
3.1.158

**Comment by VSemendiy** [comment]
Приоретизация локаторов доступна только в "Waiting for generation". Однако соответствующий значок есть и в "Generated". Полезной нагрузки там он не несёт, но в заблуждение вводит.

**Comment by VSemendiy** [comment]
P.S. Как по мне, более жизнеспособная модель приоретизации - это выбор для выделенной чекбоксами группы одного из трех приоритетов (высокий, средний или низкий). Перетаскивание локаторов по одному, например в списке из 120 штук, да ещё из разных его частей - это не то, что называется usability.

**Comment by VSemendiy** [comment]
В Deleted значок так же наличествует.

**Comment by Aniuta907** [comment]
version: 3.1.167
