### ISSUE TITLE
[2pt]Найти пару-тройку HTML5 сайтов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#198]
Найти пару-тройку HTML5 сайтов для тестирования и предоставить их Михаилу

**Comment by savinovava** [comment]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/23691272/HTML5+Examples - please place it there too

**Comment by DaryaGurtovenko** [comment]
1-1.5 pt (divided between different QA-team members to speed up)

**Comment by bulgakovmyu** [comment]
Я тут еще сам нашел парочку, на которых вроде +- похоже на классический хтмл, на них вроде прилично работает:
* https://www.udemy.com/
* https://developer.mozilla.org/ru/docs/Learn/HTML
Посмотрите на них тоже пожалуйста, годятся ли они в тестовый пул

**Comment by IoffeM** [comment]
[](http://www.u-d-a.com/html-markup-test-page/  )
[](https://cbracco.github.io/html5-test-page/  )
[](https://validator.w3.org/nu/ )
[](https://discoverlexus.com/experiences )

**Comment by AlexeyGirin** [comment]
Done.
