### ISSUE TITLE
[US-5-2][US-5-3] Добавить опцию выбора модели для распознования в опции - КАК ВРЕМЕННОЕ РЕШЕНИЕ - декомпозировать на две имплементации

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#203]
UI will be implemented if there won't be an opportunity to recognize the model automatically (#204 )

**Comment by mariia-tokarchuk** [comment]
**For version 1 (MVP):**

![start screen](https://user-images.githubusercontent.com/89466817/150484315-7d0d1a0f-373a-4f47-85d6-03bde419150d.png)

![Loading](https://user-images.githubusercontent.com/89466817/150484306-92d45bb9-b813-4370-a55f-79a52cb9a8ac.png)

Link to Figma - https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN-(v.1---MVP)?node-id=4575%3A71801

**For version 2:**

![choose a library](https://user-images.githubusercontent.com/89466817/150484625-a4da40b5-920e-4f17-afdc-fa30bcddce6a.png)

![open dropdown](https://user-images.githubusercontent.com/89466817/150484655-13380710-91aa-4d9c-880c-097ad96256d6.png)

![loading](https://user-images.githubusercontent.com/89466817/150484678-d99c02c6-9051-49eb-8887-656524c4bbbc.png)

Link to Figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=3083%3A52644

**Comment by AlexeyGirin** [comment]
Отрисовать вариант решения "в настройках"

**Comment by mariia-tokarchuk** [comment]
For version 1 (MVP):
![xpath settings open](https://user-images.githubusercontent.com/89466817/150744089-0f94e7a8-407a-497e-8d4b-e82629b8e518.png)

For version 2:
![choose a page](https://user-images.githubusercontent.com/89466817/150744030-7cce2a02-e5f6-42cf-917f-0f62a8ada12d.png)

**Comment by AlexeyGirin** [comment]
Декомпозировано в #221 #222
