### ISSUE TITLE
[NR-6] Code rules for locator - ИМПЛЕМЕНТАЦИЯ

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#205]
From user testing:
_По джава код конвенции поля класса и аннотации моугт быть записаны в одну строку, но только если длина не более чем 60 символов.
Лично я бы рекомендавал записывать поля класса и аннотации на разных строках, это добавит читаемости коду._

Было предложено разделить класс и путь к локатору при генерации и/или в UI

**Comment by mariia-tokarchuk** [comment]
![default](https://user-images.githubusercontent.com/89466817/150924866-f662e17b-5557-4ff0-8793-53bd07d964d6.png)

![main variant](https://user-images.githubusercontent.com/89466817/150924963-5db6cd8a-0f7c-440d-a48a-359f2a05cfbb.png)

**Comment by VSemendiy** [comment]
![image](https://user-images.githubusercontent.com/77847287/162969503-7083b914-b8bb-48bc-bc76-8d72c113375b.png)

**Comment by VSemendiy** [comment]
Нужно реализовать не только в UI, но и в скачиваемом файле.

**Comment by Aniuta907** [comment]
Version: 3.1.163

**Comment by VSemendiy** [comment]
Tested
[pageObjects.zip](https://github.com/jdi-testing/jdn-ai/files/8513564/pageObjects.zip)
.
