### ISSUE TITLE
Починить сборку

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#206]
![ce104960-91d8-4420-b4a8-81a5522ea16d](https://user-images.githubusercontent.com/82033805/150287067-0e85352c-978c-4ee8-80e2-61aaf1077a8a.jpg)

**Comment by MariiaNebesnova** [comment]
0,5 pt - fe

**Comment by MariiaNebesnova** [comment]
3.1.111

**Comment by AlexeyGirin** [comment]
Done.
