### ISSUE TITLE
Цвет и список локаторов не меняются и поп-ап не появляется после клика на локатор

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn-ai#208]
JDN v 3.1.111
Back-end v 2021-12-28-09.22.43

1. зашла на сайт https://www.doit-intl.com/?utm_source=materialui&utm_medium=referral%E2%80%9D
2. нажала identify
3. кликнула на button div
![image](https://user-images.githubusercontent.com/34272388/150322902-3fe35215-87aa-4984-a95f-77d77f729242.png)
 
Ожидаемый результат: локатор подсветился и стал кликнутым в списке локаторов, появился попап с сетингами
Актуальный результат: ничего не произошло 

_Note:_ репродьюсится пока только на этом сайте

**Comment by MariiaNebesnova** [comment]
0.5 pt - fe

**Comment by MariiaNebesnova** [comment]
@lisatatarinova ссылка корректная? не могу пройти по этому адресу

**Comment by lisatatarinova** [comment]
@MariiaNebesnova да, у меня открывается

**Comment by MariiaNebesnova** [comment]
модель поменялась и, к сожалению, пример больше не доступен

**Comment by IoffeM** [comment]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

is not reproducible anymore
