### ISSUE TITLE
[US-6-4] Для выбранного локатора показывается кнопка Select Locator вместо Unselect

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn-ai#209]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

1. зашла на https://docs.oracle.com/javase/tutorial/java/javaOO/anonymousclasses.html
2. нажала New page object - Generate
3. выбрала локатор правок кнопкой мыши
4. кликнула на локатор левой кнопкой мыши

Expected: 
первая кнопка в появившемся меню - Unselect locator
![image](https://user-images.githubusercontent.com/34272388/150326422-b4af3833-d744-4c0c-bbac-cda509ae1dbd.png)

Actual: 
первая кнопка в появившемся меню - Select locator
![image](https://user-images.githubusercontent.com/34272388/150326391-dbb722df-294f-4f46-a427-bc72c84b0db3.png)

**Comment by MariiaNebesnova** [comment]
0.5pt - fe

**Comment by Aniuta907** [comment]
version: 3.1.162

**Comment by VSemendiy** [comment]
![image](https://user-images.githubusercontent.com/77847287/162964282-d5ed938a-666c-460c-8e3f-b879b855d24f.png)
