### ISSUE TITLE
При первой идентификации генерируется 8 локаторов, при второй - 36

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn-ai#210]
JDN v 3.1.111
Back-end v 2021-12-28-09.22.43

1. зашла на https://www.serioverify.com/
2. нажала identify
**Actual result:** сгенерировалось 8 локаторов
![image](https://user-images.githubusercontent.com/34272388/150487391-b74cfed7-0fcc-4a0c-b86b-87578cdae656.png)

3. нажала clear all
4. нажала identify
**Actual result:** сгенерировалось 36 локаторов
![image](https://user-images.githubusercontent.com/34272388/150487533-c8ebc4a5-0163-43ef-a58e-a058cd9765c8.png)

5. повторила шаги 3 и 4
**Actual result:** сгенерировалось 36 локаторов

6. почистила куки браузера, потом повторила шаги 3 и 4
**Actual result:** сгенерировалось 8 локаторов

**Comment by MariiaNebesnova** [comment]
@lisatatarinova на странице много lazy контента. между identify сайт скроллился? если да - то все работает как и должно

**Comment by AlexeyGirin** [comment]
@IoffeM пересмотреть и попробовать повторить. Если не получится - закрыть

**Comment by IoffeM** [comment]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

is not reproducible anymore
