### ISSUE TITLE
QA task: Системное тестирование дизайна попапов на разных сайтах

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn-ai#211]
1. Все виды попапов
    -> нужно их все перечислить, чтобы не пропустить, смотрю по дизайну https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN-(v.1---MVP)?node-id=1144%3A97056
2. Обратить внимание на стиль шрифта, названия кнопок, цвета, размер
3. Обратить внимание на приоритезацию стилей на разных сайтах (как это узнать?)

**Comment by IoffeM** [comment]
seems to be a duplicate of https://github.com/jdi-testing/jdn-ai/issues/177
