### ISSUE TITLE
Update product vision

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#212]
- [x] Create page for releases https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/25985027/Releases
- [x] Update product vision

**Comment by savinovava** [comment]
Product Backlog was updated https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/1638412/Product+Backlog
SoW was updated: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/65832/SoW+Statement+of+Work#2.6-Success-Criteria

**Comment by AlexeyGirin** [comment]
Done.
