### ISSUE TITLE
Minimal limit generation time of one locator values should be changed to 1

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#217]

**Comment by IoffeM** [comment]
As user
I prefer not to use values which can break functions
In order not to be confused

Current behavior:
1) open any example site
2) open JDN in browser console
3) click Settings
4) limit generation time of one locator = 0
5) save
6) Identify

AR: 
process drops on waiting group with console error
<img width="1373" alt="Screen Shot 2022-01-25 at 10 30 01 AM" src="https://user-images.githubusercontent.com/98175427/150930955-429d952a-8561-4207-9042-af9cb324e2ae.png">

ER: no 0 - no drops

Minimal integer limit value should be 1 sec

**Comment by AlexeyGirin** [comment]
Ждём результатов тестирования на пользователях от Маши

**Comment by IoffeM** [comment]
is not actual anymore
