### ISSUE TITLE
[Medium] Meatball menu doesn't depend on JDN browser console position

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#218]
JDN v 3.1.112
Back-end v 2022-01-21-15.18.28
Chrome
https://www.behance.net/

Scenario 1:
1) open any page
2) open JDN in browser console
3) separate it from the main tab
4) click Settings

Scenario 2:
1) open any page
2) open JDN in browser console
3) separate it from the main tab
4) click Identify
5) click any meatball menu in locators list

AR: settings popup can be covered by console tab
<img width="955" alt="Screen Shot 2022-01-25 at 10 41 34 AM" src="https://user-images.githubusercontent.com/98175427/150932895-60a9613a-9c2a-4817-8d2d-e897d6133a5d.png">

ER: settings popup should always be in the front of the JDN console browser tab

**Comment by AlexeyGirin** [comment]
Not a bug
