### ISSUE TITLE
[NR-7] Механика информирования пользователя если расчёт локатора затянулся - ИМПЛЕМЕНТАЦИЯ

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#219]
В данный момент - расчёт одного локатора - может занимать десятки минут. Это вызывало недовольство пользователей.
Что бы как-то это ограничить - мы ввели предельное время расчёта одного локатора (10 секунд) и этот лимит спрятали куда-то в настройки.
Это привело к тому, что много локаторов не успевает посчитаться и теперь пользователи недовольны что локаторы остаются фул икспасами.
При этом - наличие настройки которую можно изменить, что бы дать локаторам посчитаться - не очевидно.
Необходимо подумать над тем, как бы нам избавиться от лимита на расчёт локатора, но дать понять пользователю, что если расчёт затянулся и он устал ждать - можно что-то сделать, что бы остановить вычисление и пойти дальше с тем, что успели насчитать

**Comment by AlexeyGirin** [comment]
Поиграться с настройкой времени - увеличить лимит с текущий 10 секунд и посмотреть насколько изменятся локаторы и насколько станет удобней

**Comment by IoffeM** [comment]
Тестирование проводилось из расчета, что мы не используем индексы и что максимально допустимое время расчета локатора - 300 секунд

1) увеличение лимита вообще никак не влияет на качество локаторов
2) если за 10 секунд локаторы нормально не сгенерились, то и за большее время не смогут
3) на страницах с большим количеством локаторов это и вовсе превращается в бесконечно долгую генерацию, что недопустимо. тут и на 10 секундах ждать надо, что уж говорить о большем времени

вывод: так ли нужна эта настройка для юзера? ясное дело, не нам решать, сколько он готов ждать, но очевидно, что чем быстрее, тем лучше. 10 секунду - вполне нормальное время. можно захардкодить 10 секунд и все

Есть предложение по оптимизации: если локатор застрял в расчете и превышает лимит, то убираем его в отдельную группу и переходим к следующему локатору. Если юзеру будет надо, он сможет отдельно этот долгий локатор запустить вновь или понять, что проще написать его от руки. Так мы избавимся от очереди из локаторов, которые могли бы быть посчитаны, если бы не тот самый долгий локатор. И так с каждым локатором, который всех тормозит

**Comment by AlexeyGirin** [comment]
Окей, убираем настройку (прячем её) и хардкодим ограничение в 10 секунд

**Comment by MariiaNebesnova** [comment]
duplicates #279

**Comment by AlexeyGirin** [comment]
Not actual any more
