### ISSUE TITLE
US-6-9 Filter locators in the Locator list

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#220]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/25231386/US-6-9+Filter+locators+in+the+Locator+list

**Comment by AlexeyGirin** [comment]
Разбить на 3 задачи

**Comment by mariia-tokarchuk** [comment]
1) Search - #267 
2) Filter - #268 
3) Sort - #269
