### ISSUE TITLE
[US-5-2][US-5-3] Добавить опцию выбора модели для распознования - ВРЕМЕННОЕ РЕШЕНИЕ

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#221]
For version 1 (MVP):

Link to Figma - https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN-(v.1---MVP)?node-id=7433%3A89730

![image](https://user-images.githubusercontent.com/26869421/150947717-f421bd3f-83e6-4ce8-a50e-f4344a7734b3.png)

![image](https://user-images.githubusercontent.com/26869421/150947771-c98b5fe2-0a10-453a-8515-a8cc21324a8b.png)

For version 2:

Link to Figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=3489%3A49008

![image](https://user-images.githubusercontent.com/26869421/150947803-c09c5eac-34b7-4cf0-a362-356c7d0f41d8.png)

![image](https://user-images.githubusercontent.com/26869421/150947834-0a92bacf-2ff3-4057-9a36-edac5b24e310.png)

![image](https://user-images.githubusercontent.com/26869421/150947856-b77cfb1f-5920-479b-8f3f-ec0ece6a08e0.png)

**Comment by MariiaNebesnova** [comment]
3.1.114

**Comment by IoffeM** [comment]
1 pt - qa

**Comment by IoffeM** [comment]
JDN v 3.1.116
Back-end v 2022-01-21-15.18.28
Chrome

V1 - passed
V2 - failed

Should be reopened cause there is no V2 ready for testing.
