### ISSUE TITLE
[US-5-2][US-5-3] Добавить опцию выбора модели для распознования - ПОСТОЯННОЕ РЕШЕНИЕ

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#222]
For version 1 (MVP):
Link to Figma - https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN-(v.1---MVP)?node-id=4618%3A71997

![image](https://user-images.githubusercontent.com/26869421/150948089-ba5517d5-b2d6-4104-85e8-12f469be2ecf.png)

For version 2:
Link to Figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=3127%3A41228

![image](https://user-images.githubusercontent.com/26869421/150948114-76b6d444-0f91-48cc-a415-4e9dfd4b9370.png)

**Comment by MariiaNebesnova** [comment]
due to removed Settings, do we really need pop up with an only drop down?
