### ISSUE TITLE
[Low] Selected locator scrolls a bit in locators list

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#224]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome
https://github.com/jdi-testing/jdn-ai/releases

1) open page from the precondition
2) open JDN browser console tab
3) click New page object
4) generate
5) select any locator in any locators list group

AR: it scrolls a bit for 1 sec
ER: no scroll without user activity

(!) QA note: check also https://github.com/jdi-testing/jdn-ai/issues/169 and be sure that locators are not covered by groups names

**Comment by AlexeyGirin** [comment]
@IoffeM добавь, пожалуйста, скриншоты или видео, что бы стало чуть более яснее в чём баг (т.к. у Маши есть разные идеи, а нам нужна однозначность)

**Comment by IoffeM** [comment]
There is a gif with actual result:

![224](https://user-images.githubusercontent.com/98175427/152313192-e2a82df6-97b6-432e-9fed-3b66e856af52.gif)

**Comment by AlexeyGirin** [comment]
Решили, что прокручивать список локаторов для элементов(локаторов) которые полностью видны при выделении - не нужно.
Авто-прокрутка должна срабатывать когда элемент не виден полность и перекрывается другими UI элементами (табами) или чуть вылезает за пределы видимости всего контрола.
В это случае - постараться сделать такую минимальную прокрутку что бы полностью показать элемент или (если это невозможно) чекбокс должен быть прижат к вернему краю всей области листа

**Comment by MariiaNebesnova** [comment]
got rid of this list
