### ISSUE TITLE
[Critical] Identifying fails with no response from backend

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#225]
JDN v 3.1.113
Back-end v 2022-01-21-15.18.28
Chrome
https://github.com/orgs/jdi-testing/projects/6

1) open the page from the precondition
2) open JDN browser console tab in separated window
3) open the debug console for JDN
4) click Identify

AR: errors and no result
<img width="1315" alt="Screen Shot 2022-01-26 at 1 29 39 PM" src="https://user-images.githubusercontent.com/98175427/151147861-f24a8037-ead4-4eab-acfd-5651251a01e6.png">
<img width="642" alt="Screen Shot 2022-01-26 at 1 34 56 PM" src="https://user-images.githubusercontent.com/98175427/151147976-5df23005-2c95-4d67-8fb6-b4ea8c04f9d0.png">

5) close JDN tab and reload the page
6) open JDN tab again 

AR: backend failed, there is backend version at title and lots of errors
<img width="713" alt="Screen Shot 2022-01-26 at 1 39 19 PM" src="https://user-images.githubusercontent.com/98175427/151148622-77b1eb5c-2074-4548-983e-e414915ae6e3.png">

ER: JDN should work correctly no matter what site is used

**Comment by aleksandrovskiys** [comment]
Получилось воспроизвести при выделенной для докера памяти < 6гб, на 8гб работает нормально.

Для этой страницы json, который уходит на бэк получается около 500 мб. Питон не может его распарсить и молча валится на чтении, т.е. там даже ошибку не отловить чтобы хотя бы бэк целиком не падал.

Насколько я понял эффективного по памяти парсинга json для такого формата как у нас не существует, т.е. нам либо нужно будет что-то делать с нашим файлом (убирать оттуда неиспользуемые данные или преобразовывать в формат, который пандас может читать частями) либо предупреждать пользователей, что на сложных страницах с большим количеством элементов такое может происходить.

Сейчас очень много инфы приходит в style, хотя вроде эта инфа никак не должна использоваться при распозновании. @bulgakovmyu, можешь глянуть, эти данные нужны в предиктах? Думаю, если их удалить из входного json, то это решит проблему.

**Comment by aleksandrovskiys** [comment]
@bulgakovmyu еще заметил, что во всех предиктах все входящие jsonы сохраняются на диск, может это тоже лучше убрать из кода? А то очень уж много они места будут отъедать при активном использовании.

**Comment by AlexeyGirin** [comment]
@MariiaNebesnova 
1. Убрать стили
2. Поставить лимит на размер передаваемого джейсона (увязать его с размером памяти под докер)
3. Сделать пейджинг

@aleksandrovskiys 
1. Добавить информирование фронта о разпологаемой докером памиять

**Comment by aleksandrovskiys** [comment]
@MariiaNebesnova добавил ручку /system_info в которой будет информация и о количестве ядер и о памяти. cpu_count можно будет удалить если на фронте будет реализовано через этот эндпоинт.

**Comment by MariiaNebesnova** [comment]
3.1.117
убрала стили из джейсона, должно помочь

**Comment by MariiaNebesnova** [comment]
0,5 pt - fe

**Comment by IoffeM** [comment]
Reproduced again in accordance with scenario. Should be reopened.

JDN v 3.1.116
Back-end v 2022-01-21-15.18.28
Chrome
https://github.com/orgs/jdi-testing/projects/6
<img width="1304" alt="Screen Shot 2022-02-03 at 12 16 02 PM" src="https://user-images.githubusercontent.com/98175427/152314270-70c1c11b-5515-4749-b0bd-e7f6e753e73d.png">
<img width="1304" alt="Screen Shot 2022-02-03 at 12 16 31 PM" src="https://user-images.githubusercontent.com/98175427/152314297-e8acf8f0-6960-4f0c-a93f-445112a8c31c.png">
