### ISSUE TITLE
[0.5pt] Add info about backend update to README

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#226]
For backend updating
1) stop terminal
2) docker system prune
3) run curl again
Done.

This info should be added to README in order to prevent such questions from newcomers and new customers.

**Comment by savinovava** [comment]
Connected: https://github.com/orgs/jdi-testing/projects/6#card-76664396

**Comment by IoffeM** [comment]
https://github.com/jdi-testing/jdn-ai/commit/9ea5e9394526ec735454d6b4eece08fbae07c6ba

done
