### ISSUE TITLE
[Medium] Issues with several webpages

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#227]

**Comment by MariiaNebesnova** [comment]
[3.1.125](https://github.com/jdi-testing/jdn-ai/releases/tag/3.1.125)

**Comment by MariiaNebesnova** [comment]
bug occurs when LocatorsList was opened once and then hidden. no matter, by clear all or moving to page objects list

**Comment by IoffeM** [comment]
JDN v 3.1.125
Back-end v 2022-02-12-11.36.19
Chrome

done
