### ISSUE TITLE
[US-6-2][Medium] Save and regenerate button doesn't regenerate  

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#229]
JDN v 3.1.113
Back-end v 2022-01-21-15.18.28
Chrome
https://docs.nocodb.com/?ref=madewithvuejs.com

1) open the page
2) open jdn tab
3) identify
4) wait for finish
5) select 1 or more locators
6) open Settings
7) change some values 
8) save and regenerate

AR: changes were saved but there was no regeneration (no new request in Network tab)
ER: save and regenerate means to save and to regenerate, so it should be done immediately

**Comment by MariiaNebesnova** [comment]
потому что это веб сокет )
1. открываешь консоль через F12
2. ВАЖНО! вкладка JDN должна быть неактивной. жмешь ctrl+shift+J
3. переключаешься на JDN, проходишь тест кейс
4. Network -> WS, все запросы происходят внутри сокета, на вкладке messages
![image](https://user-images.githubusercontent.com/82033805/152532950-9e9564a8-5ea0-4009-aea9-b9b2eb80759c.png)

**Comment by MariiaNebesnova** [comment]
3.1.118

**Comment by MariiaNebesnova** [comment]
0,5 pt - fe

**Comment by IoffeM** [comment]
JDN v 3.1.118
Back-end v 2022-01-31-15.52.11
Chrome
https://docs.nocodb.com/?ref=madewithvuejs.com

done
