### ISSUE TITLE
[US-15-3] Добавить поддержку генерации локаторов по кастомному атрибуту заданному пользователем

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#23]
Сейчас Робула+ ищет оптимальный локатор основываясь на всех атрибутах. Но иногда - автоматизатор договаривается с девелоперами что бы они добавили к элементам какой-то конкретный атрибут, что бы делать локаторы на его основе.
Требуется добавить возможность пользователю плагина добавить этот атрибут что бы все локаторы пытались генериться на его основе

**Comment by mariia-tokarchuk** [comment]
**[US-17-1] Добавить поддержку генерации локаторов по кастомному атрибуту заданному пользователем**

в настройки генерации добавлена вкладка "Attributes", в которой пользователь может внести кастомный атрибут вручную

<img width="1240" alt="Screenshot 2021-12-07 at 16 08 33" src="https://user-images.githubusercontent.com/89466817/145044150-43d3fbd4-91b8-4aae-9e79-94ae673ff982.png">

**Comment by mariia-tokarchuk** [comment]
Идея на будущее. 

Реально ли обучить Machine Learning **автоматически** распознавать кастомно добавленные атрибуты для автотестировщиков, и на их основе генерировать Page Object. 
Чтобы пользователь вручную не заходил и настраивал это.

**Comment by mariia-tokarchuk** [comment]
Исходники (пока в черновом виде):
https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(New)?node-id=0%3A1

**Comment by AlexeyGirin** [comment]
Готово. Можно приступать к девелопменту
