### ISSUE TITLE
[US-4-4] Add marking by hover

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#230]
As user
I want to mark locators through hover
In order to use plugin as basic elements console tab

The example of desirable behavior:
open Elements console tab
click the arrow button (showed on the screenshot)
hover elements on the page and look at the behavior of the Elements tab
<img width="1363" alt="Screen Shot 2022-01-28 at 3 31 45 PM" src="https://user-images.githubusercontent.com/98175427/151547597-4325c978-284c-411a-8ec8-d094a014b482.png">

So the scenario for JDN plugin:
click Identify
hover locators on the page by mouse
AR: hovered locators will be marked up in blue while the mouse is hovering it, this locator should be marked in the locators list like blue checkbox frame (not selected by checkbox)

It will help user to find locators quickly and work as he used.

**Comment by savinovava** [comment]
connected: https://github.com/jdi-testing/jdn-ai/issues/172

**Comment by IoffeM** [comment]
is duplicate
