### ISSUE TITLE
[NR-4][Low] Different locators amount for one page in different languages

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#232]
JDN v 3.1.113
Back-end v 2022-01-21-15.18.28
Chrome
https://www.netflix.com/ru-en/

1. open page from the precondition
2. open JDN
3. click Identify
AR: 7 locators
4. reload page
5. click right mouse button and select Translate
6.  translate to Icelandic 
7. identify
AR: 6 locators

ER: the same result for different languages

**Comment by savinovava** [comment]
maybe it's connected with transliteration: https://github.com/jdi-testing/jdn/issues/229

**Comment by IoffeM** [comment]
will be checked as a part of #229. remove
