### ISSUE TITLE
[High] Limit time in settings works as time setting

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#233]
JDN v 3.1.113
Back-end v 2022-01-21-15.18.28
Chrome
https://getbootstrap.com/

1) open the page from the precondition
2) open JDN console tab
3) identify with default settings (limit = 10 sec)
AR=ER: generation was finished successfully
4) clear all
5) open settings
6) change limit to, e,g 90 sec
7) identify again

AR: it's waiting and no generated locator.
ER: limit is not a time setting. it is a max available time. So if plugin can generate faster (we know, it can, we checked it on the 3 step), it should work faster. Easy logic: t <= lim t, NOT t = lim t

**Comment by AlexeyGirin** [comment]
Подумать над дизаблиньем опций если проставлено ограничение по времени на расчёт локатора.
Задача для @mariia-tokarchuk

**Comment by IoffeM** [comment]
decided to hide time settings. this ticket should be deleted
