### ISSUE TITLE
[Critical] Lots of MUI elements are not identified

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#235]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

_Webpages examples:_
https://www.buybags.de/ 
https://backstage.io/ - identifying works only with separated/bottom JDN tab (#237 )
http://googlekeep-anselm94.herokuapp.com/login
https://d-cide.me/
https://www.buybags.de/umhaengetaschen/ 
https://fanspo.com/
https://www.tagspaces.org/demo/

_Scenario:_
1) open webpage
2) open JDN console tab
3) new page object
4) generate

AR: lots of elements are lost - buttons, inputs, hyperlinks, bottom navigation, breadcrumbs (sometimes), dropdowns
There are no console errors or bad requests. Only ignored page elements.

ER: all elements from the https://github.com/jdi-testing/jdi-qasp-ml/blob/develop/data/mui_dataset/classes.txt should be identified. If this file should be fixed, we can use the basic logic - **identify every element that user can interact and that can change page content**

**Comment by IoffeM** [comment]
Files for all pages from the precondition. Now just for locators  fixing not for unstable work research
[test java files.zip](https://github.com/jdi-testing/jdn-ai/files/7984747/test.java.files.zip)

**Comment by MariiaNebesnova** [comment]
Investigated.
* https://www.buybags.de/, https://d-cide.me/, https://fanspo.com/ (if it's about tabs at the top navigation panel) - MUI styles are presented on elements as expected. need investigation from model developer
https://backstage.io/, https://www.tagspaces.org/demo/ - styles are not typical MUI, not sure model will work with such things
http://googlekeep-anselm94.herokuapp.com/login - links don't have MUI styles

* Investigation from model developer is needed.

**Comment by AlexeyGirin** [comment]
1. Создать баг про разные json от размера окна
2. Разабраться с кнопками которые не распоснаются

**Comment by suppnova** [comment]
Created #385 issue

**Comment by suppnova** [comment]
Model updated. InputBase (search line) and separated buttons identifiсication improved

**Comment by suppnova** [comment]
Tested: inputbase identification improved. 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/65091469/164254233-09361b4b-5b21-4c07-bcb9-d141bb7839f0.png">
If we need more predicted probability (now its about 0.88)  - > complete model training (+1-2 epoch)

**Comment by AlexeyGirin** [comment]
Нужно протестировать на референсных сайтах
