### ISSUE TITLE
[US-15-1] Добавить возможность преимущественной генерации локаторов с использованием CSS

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#24]
Иногда - пользователь заинтересован в том, что бы дать все локаторы были сгенереры на основе CSS.
Нужно предусмотреть возможность дать пользователю указать что результат генерации должен выполняться на основе CSS в первую очередь и только если это не возможно - использовать другие варианты

**Comment by mariia-tokarchuk** [comment]
в настройки генерации добавлена вкладка "Locator types", в которой пользователь может указать генерировать на основе CSS, или xPath

<img width="1251" alt="Screenshot 2021-12-07 at 16 26 50" src="https://user-images.githubusercontent.com/89466817/145047944-bf2b7408-cb51-417e-bb03-8491aef84bd4.png">

**Comment by mariia-tokarchuk** [comment]
Исходники (пока в черновом виде):
https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(New)?node-id=0%3A1

**Comment by AlexeyGirin** [comment]
Готово. Можно приступать к девелопменту
