### ISSUE TITLE
[US-14-2] Identify elements in Page Objects

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#243]
Need for tech decomposition
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22315067/US-14-2+Identify+elements+in+Page+Objects

Design: https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=0%3A1

- [x]  #256 
- [x]  #258 
- [x] #259 
- [x] #260
- [x] #278 
- [x] #279 
- [x] #277 
- [x] #276
- [x] #280 
- [ ] #281 
- [x] #282 
- [x] #283 
- [x] #288 
- [x] #285 
- [x] #290

**Comment by AlexeyGirin** [comment]
#281 in backlog.
Closed.
