### ISSUE TITLE
[US-14-3] Moving Page Objects

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#244]
Need for tech decomposition
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22282279/US-14-3+Moving+Page+Objects

Design: https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=0%3A1

**Comment by savinovava** [comment]
- Отрисовать нотификацию при перемещении
@mariia-tokarchuk

**Comment by MariiaNebesnova** [comment]
assume that we already have packages before take this task in TODO

**Comment by savinovava** [comment]
blocked: #241
