### ISSUE TITLE
[NR-7] Add a message for empty response

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#248]
If there are no found locators, user should get a message like "No found locators for this model"

**Comment by AlexeyGirin** [comment]
Подправить сообщение - Попросить вернуться назад и выбрать другую элемент лайбрари

**Comment by mariia-tokarchuk** [comment]
![no locators found](https://user-images.githubusercontent.com/89466817/153172822-21718070-d405-440a-8de0-7d91d0c3ca19.png)

Link to Figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4057%3A45714

**Comment by savinovava** [comment]
was added to https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/26902553/NR-7+Identification+warnings

**Comment by MariiaNebesnova** [comment]
I believe design should be actualized (or approved), because UX and functionality was changed dramatically since this task was created

**Comment by AlexeyGirin** [comment]
Not actual any more
