### ISSUE TITLE
[High] Wrong message after empty cache and hard reload

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#249]
JDN v 3.1.117
Back-end v 2022-01-31-15.52.11
Chrome
https://www.buybags.de/luxustaschen/

1) open the page from the precondition
2) open JDN tab
3) empty cache and hard reload (command + shift + r)
4) identify

AR:
<img width="1403" alt="Screen Shot 2022-02-03 at 3 42 15 PM" src="https://user-images.githubusercontent.com/98175427/152348154-341146ae-ebac-44b6-8928-9dba1db5d949.png">

ER: these locators are here and we can find it just if we close the page and open it again. Identifying will be successful. 
This gif shows how it work at first before our scenario and in scenario:
![mess](https://user-images.githubusercontent.com/98175427/152348625-e3daa4dd-35bb-49b1-a2fb-8047008ea02a.gif)

**Comment by MariiaNebesnova** [comment]
1pt - fe

**Comment by IoffeM** [comment]
QA note: retest https://github.com/jdi-testing/jdn-ai/issues/136 after fix
