### ISSUE TITLE
[6pt][US-11-2] Notifications for actions with locators

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#25]
Implement notifications appearing in the bottom of the locators list.
https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=1224%3A70877

- [x] create notification component
- [x] create notification for actions with locators: delete, stop, rerun, change settings
- [x] notification for file download

**Comment by savinovava** [comment]
[4pt] - front
[2pt] - QA

**Comment by AlexeyGirin** [comment]
Будет готов второй пункт сегодня
Маша допишет экшены для других пунктов

**Comment by AlexeyGirin** [comment]
Договорились сделать по одному уведомлению

**Comment by MariiaNebesnova** [comment]
3.0.81

**Comment by pulya-na-vullet** [comment]
Не работает пауза и сохранение настроек. Таска блокирована багами. Как заведу баги прилинкую к таске

**Comment by pulya-na-vullet** [comment]
Task is blocked by: 
https://github.com/jdi-testing/jdn-ai/issues/88
https://github.com/jdi-testing/jdn-ai/issues/89

**Comment by pulya-na-vullet** [comment]
По всем таскам есть резолюция: #88 #89 #90
Таску закрываю.
