### ISSUE TITLE
[US-14-6] Page Object's actions

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#252]
Need for tech decomposition

https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27721756/US-14-6+Page+Object+s+settings

Design: https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=0%3A1

Tech tasks:

- [ ]  #298 
- [x]  #299 
- [x] #300

**Comment by savinovava** [comment]
US-14-6-Q2 Page Object validation - требования к ней

**Comment by AlexeyGirin** [comment]
US-14-6-Q1 Будем ли мы показывать какое-либо предупреждение или попап при удалении Page Object?
Ответ: Да будем, Маша отрисует
 US-14-6-Q2 Page Object validation - требования к ней
Ответ: http://dolszewski.com/java/java-class-naming-ultimate-guideline/

**Comment by savinovava** [comment]
- [ ] Отрисовать popup для удаления, переименовывания
@mariia-tokarchuk

**Comment by AlexeyGirin** [comment]
#298 will be done soon.
Closed.
