### ISSUE TITLE
[US-14-7] Copy locators from Page Object

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#253]
Need for tech decomposition

**As** a user
**I want to** reuse locators in the Page Object
**So that** allow me to generate code faster

https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27852806/US-14-7+Copy+locators+from+Page+Object

Design: https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=0%3A1

**Comment by AlexeyGirin** [comment]
Ограничение на имя пакета - https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

**Comment by savinovava** [comment]
Необходимо отрисовать экран со скрытыми возможностями (появляются при наведении):
![image](https://user-images.githubusercontent.com/53625116/162190422-d55b6391-6a7c-4689-901d-64e5cd92d1ef.png)
@SemyonKuznetsov

**Comment by SemyonKuznetsov** [comment]
[Существующий дизайн,](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=1932%3A2398655)  чтобы сделать новый надо переделать, подправить дизайн локатора не могу

**Comment by Aniuta907** [comment]
Version: 3.1.163
