### ISSUE TITLE
[US-11-3] Copy locator's path

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#257]
**As a** user
**I want to** copy locator’s path to the clipboard
**So that** I will have a quick access to the code of element

https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27852880/US-11-3+Copy+locator+s+path

**Comment by MariiaNebesnova** [comment]
3.1.140

**Comment by ioffem** [comment]
reopened

JDN v 3.1.140
Back-end v 2022-02-12-11.36.19
Chrome

copy and meatball menu icons cover locator. it's too inconvenient and looks awful.
<img width="532" alt="Screen Shot 2022-03-10 at 11 29 56 AM" src="https://user-images.githubusercontent.com/98175427/157620340-cd057b24-b94d-457b-b550-ce759fdd1ec9.png">

let's pin copy and meatball menu icons on the right side

**Comment by MariiaNebesnova** [comment]
_or should we add copy icon into meatball menu?_ - no, we should't by design

**Comment by MariiaNebesnova** [comment]
3.1.141

**Comment by ioffem** [comment]
JDN v 3.1.141
Back-end v 2022-02-12-11.36.19
Chrome

done
