### ISSUE TITLE
[US-14-2-1-1] Handle duplicating PO names

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#258]
after #256 
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22315067/US-14-2+Identify+elements+in+Page+Objects#UC-14-2-1-1-Create-the-Page-Object-(name-duplicate)

**Comment by MariiaNebesnova** [comment]
0.5 pt - fe

**Comment by IoffeM** [comment]
JDN v 3.1.119
Back-end v 2022-02-12-11.36.19
Chrome

was checked in #256 
done
