### ISSUE TITLE
Notification for Page Objects

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#262]

**Comment by mariia-tokarchuk** [comment]
![Notification](https://user-images.githubusercontent.com/89466817/153023841-e4b363a5-1675-4288-af72-568028c5f7bc.png)


**Link to the Figma:**

Example of a page with notification - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4048%3A46032

Components (all notification options) - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4048%3A45361

**Comment by SemyonKuznetsov** [comment]
need to update design

**Comment by SemyonKuznetsov** [comment]
#584 main task

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163828%3A166420)

![Frame 6](https://user-images.githubusercontent.com/101407186/194006754-1617d355-b555-45ca-bb89-3da7e0d2647a.png)

**Comment by MariiaNebesnova** [comment]
[3.3.282](https://github.com/jdi-testing/jdn-ai/releases/tag/3.3.282)
