### ISSUE TITLE
[0.5pt][Medium] Sometimes generation doesn't finish

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#263]
JDN v 3.1.118
Back-end v 2022-01-31-15.52.11
Chrome
https://www.uplabs.com/search?q=material%20design

1) open the page from the precondition
2) open JDN tab
3) select HTML5 library
4) identify

AR: no end and interesting logs in the middle:

jdi-qasp-ml-celery  | [2022-02-04 11:42:45,286: INFO/MainProcess] Task app.tasks.task_schedule_xpath_generation[ad9aab38-dece-428b-893b-5ca79e7cbd04] received
jdi-qasp-ml-celery  | [2022-02-04 11:42:46,353: ERROR/ForkPoolWorker-4] Task app.tasks.task_schedule_xpath_generation[ad9aab38-dece-428b-893b-5ca79e7cbd04] raised unexpected: AttributeError("'NoneType' object has no attribute 'getparent'")
jdi-qasp-ml-celery  | Traceback (most recent call last):
jdi-qasp-ml-celery  |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 450, in trace_task
jdi-qasp-ml-celery  |     R = retval = fun(*args, **kwargs)
jdi-qasp-ml-celery  |   File "/usr/local/lib/python3.7/site-packages/celery/app/trace.py", line 731, in __protected_call__
jdi-qasp-ml-celery  |     return self.run(*args, **kwargs)
jdi-qasp-ml-celery  |   File "/jdi-qasp-ml/app/tasks.py", line 7, in task_schedule_xpath_generation
jdi-qasp-ml-celery  |     return generate_xpath(element_id, document, config)
jdi-qasp-ml-celery  |   File "/jdi-qasp-ml/utils/robula.py", line 400, in generate_xpath
jdi-qasp-ml-celery  |     robust_path = robula.get_robust_xpath()
jdi-qasp-ml-celery  |   File "/jdi-qasp-ml/utils/robula.py", line 141, in get_robust_xpath
jdi-qasp-ml-celery  |     temp = self.generate_xpaths_for_current_level(current_xpath)
jdi-qasp-ml-celery  |   File "/jdi-qasp-ml/utils/robula.py", line 162, in generate_xpaths_for_current_level
jdi-qasp-ml-celery  |     temp.extend(self.transf_convert_star(xpath))
jdi-qasp-ml-celery  |   File "/jdi-qasp-ml/utils/robula.py", line 207, in transf_convert_star
jdi-qasp-ml-celery  |     ancestor = self.get_ancestor(len(xpath) - 1)
jdi-qasp-ml-celery  |   File "/jdi-qasp-ml/utils/robula.py", line 184, in get_ancestor
jdi-qasp-ml-celery  |     output = output.getparent()
jdi-qasp-ml-celery  | AttributeError: 'NoneType' object has no attribute 'getparent'
jdi-qasp-ml-redis   | 1:M 04 Feb 2022 11:43:08.044 * 100 changes in 300 seconds. Saving...
jdi-qasp-ml-redis   | 1:M 04 Feb 2022 11:43:08.046 * Background saving started by pid 33
jdi-qasp-ml-redis   | 33:C 04 Feb 2022 11:43:08.092 * DB saved on disk
jdi-qasp-ml-redis   | 33:C 04 Feb 2022 11:43:08.093 * RDB: 0 MB of memory used by copy-on-write
jdi-qasp-ml-redis   | 1:M 04 Feb 2022 11:43:08.148 * Background saving terminated with success

ER: successful end

**Comment by aleksandrovskiys** [comment]
Исправлено

**Comment by IoffeM** [comment]
qa - 0,5 pt

**Comment by IoffeM** [comment]
JDN v 3.1.118
Back-end v 2022-02-12-11.36.19
Chrome

done
