### ISSUE TITLE
[NR-4][High] Chrome emergency quit leads to plugin issue

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#266]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
MacOS
Chrome
behance.net

1) open the page from the preconditions (or another page with long generation)
2) open JDN tab
3) new page object - generate
4) open activity monitor
5) kill all chrome processes (also it can be not responding browser, reboot, sleep or just device dead battery)
6) open chrome again
7) open JDN tab

AR: warning about several tabs, but there is only one tab
<img width="1349" alt="Screen Shot 2022-02-09 at 10 04 37 AM" src="https://user-images.githubusercontent.com/98175427/153138997-61877942-6095-4ffb-b656-a5cf37dffbf4.png">
the only way to fix it is to reinstall plugin

ER: emergency quit should not break our plugin

**Comment by IoffeM** [comment]
[gif.zip](https://github.com/jdi-testing/jdn-ai/files/8030322/gif.zip)

**Comment by MariiaNebesnova** [comment]
Retry button is back again
Design https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=0%3A1

**Comment by MariiaNebesnova** [comment]
3.1.169
