### ISSUE TITLE
[US-6-11] Search locators in the Locator List

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#267]
Search
https://github.com/jdi-testing/jdn-ai/issues/267#issuecomment-1221990539

Link to Figma - [Figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6851%3A342248)

[US-6-11](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/42008644/US-6-11+Search+for+locators+in+the+Locator+list)

Example: https://ant.design/components/tree/#components-tree-demo-search

**Comment by savinovava** [comment]
@mariia-tokarchuk It is needed to add the state if the user starts typing. Maybe we can add clear button

**Comment by SemyonKuznetsov** [comment]
[Figma](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163655%3A165386) 

![search](https://user-images.githubusercontent.com/101407186/185869871-6adc41c9-ee60-484d-b64f-97565317d948.png)

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6851%3A342252)

чекбокс - статус дизейблед, текст и иконки - цвет из библиотеки Character/Disabled&Placeholder .25  (000000 25%).
иконку экстеншена оставить без изменений

<img width="275" alt="Снимок экрана 2022-10-26 в 10 48 28" src="https://user-images.githubusercontent.com/101407186/197966226-12e8babd-9666-4400-a1ff-72e337e10ee9.png">

**Comment by SemyonKuznetsov** [comment]
логика работы поиска в дереве

![Frame 1147](https://user-images.githubusercontent.com/101407186/197993938-1ff0eb2d-3e88-4572-ae9c-7994f5b97935.png)

**Comment by MariiaNebesnova** [comment]
[3.3.283](https://github.com/jdi-testing/jdn-ai/releases/tag/3.3.283)
