### ISSUE TITLE
[US-6-9] Filter locators in the Locator list

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#268]
[US-6-9](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/25231386/US-6-9+Filter+locators+in+the+Locator+list)

**Comment by savinovava** [comment]
@mariia-tokarchuk is the quality needed now?
It is needed to add the state if filters are applied

**Comment by MariiaNebesnova** [comment]
is it actual for locators tree?

**Comment by AlexeyGirin** [comment]
1. Итоговый результат - попадают те локаторы которые были прочеканы пользователем. Даже если они находятся за пределами видимости из-за наложенного фильтра
2. Если нажимаем Select All при наложенном фильтре - должны быть прочеканы только те, которые видимы после наложения фильтра
3. При выфильтровывании родительского элемента - дочерний выдвигается на место родительского. Но так - древовидную структуру мы пытаемся сохранить
4. Удаляем только те, которые прочеканы и которые мы видим
5. Фильтр налагается на любые элементы - даже на прочеканные (но чек с элемента не снимается даже если он за пределами видимости фильтра)
-----------------------------------------------
Идея оставить фильтр только для распознавания элементов
-----------------------------------------------
А нужны ли нам групповые операции типа - удаления? и повышения приоритета?
-----------------------------------------------
А какие типы фильтрации нам нужны?
-----------------------------------------------
Ждём от Семёна прототип

**Comment by savinovava** [comment]
Список будет большой (около 50): нужны возможность быстро найти нужный тип, такая же функциональность при редактировании

autocomplete при фильтре

**Comment by SemyonKuznetsov** [comment]
Фильтр к локаторам применяется сразу, без нажатия кнопок "применить" и тд

**Comment by AlexeyGirin** [comment]
Фильтры для локаторов в разных статусах (инвизибл, удалённые) - не делаем

**Comment by SemyonKuznetsov** [comment]
эскизное для дейли

<img width="1002" alt="Снимок экрана 2022-10-20 в 10 34 30" src="https://user-images.githubusercontent.com/101407186/196885381-43f72f7a-2797-4b3e-9140-b2a49a7e1549.png">

**Comment by SemyonKuznetsov** [comment]
можно ли убрать из [ant.component](https://ant.design/components/select/#components-select-demo-multiple) вот этот раздвигающийся список вариантов при первом нажатии? 
<img width="419" alt="Снимок экрана 2022-10-21 в 10 32 29" src="https://user-images.githubusercontent.com/101407186/197139132-b43be949-ddad-4738-9938-6a48f9802586.png">

так как структура фильтров предполагает наличие этих же списков под этим же поиском
<img width="153" alt="Снимок экрана 2022-10-21 в 10 32 03" src="https://user-images.githubusercontent.com/101407186/197139035-71d44273-e716-4a31-a2e5-5782d8734002.png">

**Comment by SemyonKuznetsov** [comment]
[figma prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=6998%3A348486&viewport=319%2C-4833%2C0.17&scaling=scale-down-width&starting-point-node-id=7008%3A358274)
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7008%3A358274)

![Default](https://user-images.githubusercontent.com/101407186/198414463-5319e22e-468f-4e36-afad-18224d0b2d39.png)

<img width="734" alt="Снимок экрана 2022-10-28 в 01 58 04" src="https://user-images.githubusercontent.com/101407186/198413299-dce1746d-20f0-4700-874d-3608b20c5130.png">

для состояний ховера при вводе текста
<img width="543" alt="Снимок экрана 2022-10-28 в 01 58 52" src="https://user-images.githubusercontent.com/101407186/198413552-a89b0cc3-0ced-4066-8f71-39fb874eb6e4.png">

**Comment by SemyonKuznetsov** [comment]
![2](https://user-images.githubusercontent.com/101407186/198537207-dfae38f1-6d36-45fe-9eea-cda9274aa056.png)

**Comment by MariiaNebesnova** [comment]
[3.4.293](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.293)

**Comment by savinovava** [comment]
Default set появится тогда, когда у нас будет большее количество классов. После доработок библиотек

**Comment by SemyonKuznetsov** [comment]
Обновили логику фильтрации чекбоксов при вводе текста

<img width="521" alt="Снимок экрана 2022-11-30 в 14 35 35" src="https://user-images.githubusercontent.com/101407186/204786062-84e35531-1198-46ff-9ed3-27de23326079.png">


по факту убрали вот эту часть и упростили флоу

<img width="268" alt="Снимок экрана 2022-11-30 в 14 36 33" src="https://user-images.githubusercontent.com/101407186/204786276-26df6c53-f758-4741-b89b-996cc81d129c.png">

**Comment by Maksim-Kviatkovskii** [comment]
Баги:
- https://github.com/jdi-testing/jdn-ai/issues/781
- https://github.com/jdi-testing/jdn-ai/issues/782
- https://github.com/jdi-testing/jdn-ai/issues/783
