### ISSUE TITLE
[US-6-10] Sort locators in the Locator list

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#269]
Sort by parameters:
- DOM tree (default)
- Locator type
- Locator name

![sort](https://user-images.githubusercontent.com/89466817/153166105-31cd7e10-37ce-492f-9642-6ba85c7d0ff1.png)

Link to Figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4070%3A52394

[US-6-10](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/42008606/US-6-10+Sort+locators+in+the+Locator+list)

**Comment by savinovava** [comment]
@mariia-tokarchuk create the state of app if sorting is applied

**Comment by MariiaNebesnova** [comment]
how it's possible with a tree?

**Comment by AlexeyGirin** [comment]
Возможно - эта функциональность нам не нужна.
Пока в релиз её не будем брать

**Comment by savinovava** [comment]
Outdated
