### ISSUE TITLE
[High] Work with locator through the desktop is unavailable

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#270]
JDN v 3.1.118
Back-end v 2022-01-31-15.52.11
Chrome

1) open any page
2) open JDN tab
3) identify
4) try to work with locator through the desktop

AR: nothing happens
ER: it should be possible to work with locator through the desktop

**Comment by MariiaNebesnova** [comment]
3.1.121

**Comment by IoffeM** [comment]
JDN v 3.1.121
Back-end v 2022-02-12-11.36.19
Chrome

done
