### ISSUE TITLE
[Medium] Plugin returns to start after page scrolling and loses the result

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#274]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome
https://www.uplabs.com/search?q=material%20design

1) open the page from the preconditions
2) open JND tab
3) new page object
4) generate
5) wait for finish
6) scroll the page

AR: plugin returns to start, there is no available result
ER: results should be available if user has not clear it or close plugin/page

**Comment by Maksim-Kviatkovskii** [comment]
Связано с динамическими страницами, понизил до медиума

**Comment by MariiaNebesnova** [comment]
[3.8.396](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.396)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.8.396 Back-end v 0.2.22, Google Chrome Version 110.0.5481.77 (Official Build) (x86_64), macOS 12.6.1
