### ISSUE TITLE
[US-15-2] Импрувнуть генерацию локаторов (добавление генерации от пэрента))

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#275]
Необходимо доработать генерацию локаторов следующим образом.
Если стандартный расчёт локатора (за установленное время) не даёт лучший локатор (т.е. мы остаёмся с полным икспасом), необходимо:
1. Найти элемент являющийся родительским к этому (если не нашли, то оставить как есть) и проверить есть ли у него лучший локатор. Если нет - найти элемент являющийся родительским к этому и делать так пока не найдётся родительский элемент с оптимальным локатором
2. Попытаться найти локатор для нужного нам элемента передав в алгорим не всё дерево элементов, а только ветку растущую от найденного нам родительского элемента.
3. Финальный локатор должен формироваться так: [локатор родительского элемента]//[локатор нашего элемента]
Например: .//*[@class="sidebar-menu left"]//a[*[contains(text(),"Elements packs")]

**Comment by rrr3try** [comment]
Ограничения по времени какое-то дополнительное ввести или повторно использовать текущее?

 Нужно ли уведомлять фронт что локатор просчитывается по дополнительному алгоритму?

**Comment by AlexeyGirin** [comment]
1. Нет
2. Просто нет

**Comment by AlexeyGirin** [comment]
![image](https://user-images.githubusercontent.com/26869421/170033715-a489c171-fb16-4043-9746-717e86d02e76.png)
