### ISSUE TITLE
[Medium] Report a problem button disappeared from main plugin meatball menu

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#276]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

1) open any page
2) open JDN tab
3) click New page object
4) click Generate
5) open the plugin meatball menu

AR: there is no Report a problem button, only Readme
ER: there should be both Readme and Report buttons

**Comment by MariiaNebesnova** [comment]
3.1.130

**Comment by IoffeM** [comment]
JDN v 3.1.130
Back-end v 2022-02-12-11.36.19
Chrome

done
