### ISSUE TITLE
[US-14-9] Add an ability to clear the page object list

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#277]
As user 
I want to be able to clear the page object list
In order not to download page objects created by mistake

Add a button Clear all to the page object list

**Comment by AlexeyGirin** [comment]
На доработку Маше

**Comment by mariia-tokarchuk** [comment]
![choose a page](https://user-images.githubusercontent.com/89466817/154026989-704ffb61-3c52-4777-bf3d-1c402b101b55.png)

![result of first PO](https://user-images.githubusercontent.com/89466817/154027081-5f1cf4ac-f696-4dc4-83e3-32c0bec3eebb.png)

Link to Figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4268%3A50987

**Comment by mariia-tokarchuk** [comment]
в случаи удаления всех ПО показывать поп-ап с предупреждением:

![delete all](https://user-images.githubusercontent.com/89466817/155102036-9f60ae72-adea-47c4-91c9-3698988d51d0.png)

Link to Figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4477%3A51873

**Comment by savinovava** [comment]
US was created: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/30113824/US-14-9+Clear+all+page+objects+in+the+list

**Comment by MariiaNebesnova** [comment]
3.1.128

**Comment by IoffeM** [comment]
JDN v 3.1.130
Back-end v 2022-02-12-11.36.19
Chrome

done
