### ISSUE TITLE
[US-2-2] Settings for page object

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#279]

**Comment by MariiaNebesnova** [comment]
clarify #174

**Comment by AlexeyGirin** [comment]
Решили: Спрятать все настройки для локаторов - и время и идексы (индексы предварительно отключить по умолчанию)

**Comment by MariiaNebesnova** [comment]
3.1.126

**Comment by IoffeM** [comment]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

done

test cases and mind map are updated
