### ISSUE TITLE
[2pt]Приведение бэкэнда в порядок

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#28]
Детали у Семёна

- [x] Переезд на гитхаб
- [x] Удалить неиспользуемое (почистить)
- [x] Разделить сервисы на разные контейнеры

**Comment by savinovava** [comment]
[2pt] backend
тестирование на общем регресс-тесте

**Comment by pulya-na-vullet** [comment]
Plugin version JDN v 3.0.83
Back-end v 2021-11-01-06.14.14

bug doesn't repeat

https://user-images.githubusercontent.com/61897393/143183641-a339f376-60db-484b-b748-c5a422d2f8d7.mp4
