### ISSUE TITLE
[Medium] Download button is available for empty page objects list

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#280]
JDN v 3.1.119
Back-end v 2022-02-12-11.36.19
Chrome

1) open any page
2) open JDN tab

AR: there is download button, it can download an empty archive
ER: no download button for empty page objects list

**Comment by MariiaNebesnova** [comment]
3.1.125

**Comment by IoffeM** [comment]
JDN v 3.1.125
Back-end v 2022-02-12-11.36.19
Chrome


done
test cases and mind map are updated
