### ISSUE TITLE
[Low] Locators are visible between page objects containers

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#281]
JDN v 3.1.119
Back-end v 2022-02-12-11.36.19
Chrome
https://mui.com/components/buttons/

1) open the page from the preconditions
2) open JDN tab
3) click New page object
4) click Generate
5) wait for finish, select all and confirm
6) repeat steps 1-5
7) open and scroll the second page object in the page objets list

AR:
<img width="499" alt="Screen Shot 2022-02-15 at 11 23 57 AM" src="https://user-images.githubusercontent.com/98175427/154021830-d6fd7870-606b-4e44-966f-3b20eb0d87ce.png">

ER: it should not be visible, containers should be close to each other

**Comment by ioffem** [comment]
JDN v 3.1.140
Back-end v 2022-02-12-11.36.19
Chrome

is not actual anymore

**Comment by MariiaNebesnova** [comment]
3.1.145

**Comment by ioffem** [comment]
reopened

JDN v 3.1.145
Back-end v 2022-02-12-11.36.19
Chrome
https://www.behance.net/

1) waiting and deleted containers have different height 
<img width="578" alt="Screen Shot 2022-03-16 at 3 58 36 PM" src="https://user-images.githubusercontent.com/98175427/158596316-9f0c910d-54f8-4fcd-af92-c7e35cde953c.png">

2) several page objects can be expanded at the same time
<img width="578" alt="Screen Shot 2022-03-16 at 4 11 12 PM" src="https://user-images.githubusercontent.com/98175427/158597300-4337a8f6-cc94-4cdd-b311-3c855e1d2463.png">


3) locators and page object name are not aligned with each other
<img width="578" alt="Screen Shot 2022-03-16 at 4 03 21 PM" src="https://user-images.githubusercontent.com/98175427/158596715-9318ed50-e989-429f-afc0-c9e516fe18d3.png">

4) page object meatball menus are not pin at the right side and depend on the name length

<img width="578" alt="Screen Shot 2022-03-16 at 4 09 06 PM" src="https://user-images.githubusercontent.com/98175427/158597045-4c869c26-7936-4bd9-8f49-4ab3e02f4b5c.png">

**Comment by ioffem** [comment]
@MariiaNebesnova  please, fix also https://github.com/jdi-testing/jdn-ai/issues/343 here, if possible

**Comment by MariiaNebesnova** [comment]
1 - suggest to leave as is for now, it's a crunch that prevents gap between panels
2 - do we really should close this possibility?
3 and 4 will be fixed in #322

**Comment by AlexeyGirin** [comment]
Closed.

**Comment by AlexeyGirin** [comment]
Решили пофиксить только первый пункт (разный размер табов), но потом.
