### ISSUE TITLE
Collapse expanded page object after New page object button clicking

### ISSUE THREAD

**Issue by IoffeM** [jdi-testing/jdn-ai#282]
As user
I want to be moved to new page object immediately with no scrolling
In order not to be confused

When we have several page objects with huge amount of locators and expand one of these page objects, we can scroll it.  But if user clicks New page object button, he doesn't want to scroll or to collapse manually, his only aim is to create new page object. So New page objects button clicking should collapse all expanded page objects.

When user confirms locators and page objects list appears, there should be only last expanded page object. Old page objects should be collapsed. Current behavior is not correct (you can check in gifs)

When user expands page object manually, it should NOT scroll to the end. It should stay at the beginning of the expanded page object.

The example of current behavior is attached as gifs
![po](https://user-images.githubusercontent.com/98175427/154022877-73321f5e-7687-4b61-b7cf-dc61ae48ade7.gif)

![scroll](https://user-images.githubusercontent.com/98175427/154189487-b7341c6a-4079-4740-8418-8d0e06c054bf.gif)

**Comment by MariiaNebesnova** [comment]
не надо разбивать, это одна механика

**Comment by MariiaNebesnova** [comment]
3.1.131

**Comment by IoffeM** [comment]
reopened

JDN v 3.1.131
Back-end v 2022-02-12-11.36.19
Chrome

Correct collapsing and expanding - done
Scroll - failed (all screenshots below) - try to reproduce it by 3 POs creating and scrolling

1. Immediately after confirmation
<img width="1276" alt="Screen Shot 2022-02-28 at 3 05 52 PM" src="https://user-images.githubusercontent.com/98175427/156126306-442b48eb-674c-4024-91a9-5d82fd246446.png">

2. Collapsed PO expanding
<img width="1276" alt="Screen Shot 2022-02-28 at 3 07 16 PM" src="https://user-images.githubusercontent.com/98175427/156126321-8f26a957-3ec4-4231-b363-2fb194ce5ded.png">

3. Several collapsed POs expanding
<img width="1276" alt="Screen Shot 2022-02-28 at 3 08 11 PM" src="https://user-images.githubusercontent.com/98175427/156126338-664f30bc-8de5-437a-acb6-278364a2b4fd.png">

You can check it also in gif below
![scrollPO](https://user-images.githubusercontent.com/98175427/156126366-aa075b68-badc-4a24-927b-fde280d378f9.gif)

**Comment by MariiaNebesnova** [comment]
3.1.132

**Comment by IoffeM** [comment]
JDN v 3.1.132
Back-end v 2022-02-12-11.36.19
Chrome

looks great. done.
