### ISSUE TITLE
[US-14-2] [High] User can confirm with no selected locators

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#283]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

1) open any page
2) open JDN tab
3) new page object
4) generate

AR: Confirm button is active and clickable
ER: no selected locators - disabled Confirm button
<img width="494" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/98175427/154054423-e76ca51e-c288-4a56-8825-74bc68fdcdac.png">

**Comment by savinovava** [comment]
UC-14-2-4-2 were created https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22315067/US-14-2+Identify+elements+in+Page+Objects#UC-14-2-4-2-No-locators-were-selected

**Comment by MariiaNebesnova** [comment]
3.1.133

**Comment by ioffem** [comment]
reopened 

JDN v 3.1.133
Back-end v 2022-02-12-11.36.19
Chrome

no tooltip as on screenshot in expected result

**Comment by MariiaNebesnova** [comment]
3.1.134
