### ISSUE TITLE
[Medium] Remove the download button on the Locators list page

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#287]
Remove the Download button on the Locators list page. Instead, the user will click the Confirm button.

(The download button is already displayed on the Page Object page)

<img width="596" alt="Screenshot 2022-02-16 at 08 39 09" src="https://user-images.githubusercontent.com/89466817/154211086-3864c871-5b25-4516-ba65-479d9611618f.png">

**Comment by MariiaNebesnova** [comment]
So, we don't need Download popup anymore?

**Comment by MariiaNebesnova** [comment]
3.1.125

**Comment by IoffeM** [comment]
JDN v 3.1.125
Back-end v 2022-02-12-11.36.19
Chrome


done
test cases and mind map are updated
