### ISSUE TITLE
[Medium] Fix Page Object page behavior when scrolling

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#288]
JDN v 3.1.119
Back-end v 2022-01-21-15.18.28
https://jdi-testing.github.io/jdi-light/different-elements.html

1. New Page Object
2. Generate
3. Select all locators and click Confirm
4. Generate some more Page Objects
5. On the Page Objects page: 
- collapse tab with the first 2 Page Objects in the list
- leave all other PageObject tabs open
- scroll the page

Result: the headings of the first 2 Page Objects are fixed at the top of the table, but all others are scrolled

<img width="601" alt="Screenshot 2022-02-16 at 08 51 38" src="https://user-images.githubusercontent.com/89466817/154213914-801a100c-a896-4737-b9b5-54facfd10823.png">

**Another case:**

5. On the Page Objects page: 
- collapse second tab with the Page Object in the list
- leave all other PageObject tabs open
- scroll the page

Result: the heading of the second Page Object is fixed, but all others are scrolled

<img width="588" alt="Screenshot 2022-02-16 at 09 11 35" src="https://user-images.githubusercontent.com/89466817/154214404-8236a70b-81e8-4e8a-8458-14e458488bec.png">

It is necessary to bring the work of scrolling and tabs to a single view.

**Comment by MariiaNebesnova** [comment]
3.1.125

**Comment by IoffeM** [comment]
JDN v 3.1.125
Back-end v 2022-02-12-11.36.19
Chrome

done
