### ISSUE TITLE
[UC-14-2-6][Medium] Old page objects are saved for new page

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#290]
JDN v 3.1.120
Back-end v 2022-02-12-11.36.19
Chrome

1) open any page
2) open JDN tab
3) new page object
4) generate
5) select locators and confirm
6) optional step - repeat 1-5 steps 
7) open new webpage in the same tab, don't close JDN tab

AR: new webpage was loaded, but we can find previous page objects in the page objects list
ER: new webpage opening should lead to JDN plugin reload, all old page objects should be deleted

**Comment by MariiaNebesnova** [comment]
isn't it a feature?

**Comment by AlexeyGirin** [comment]
В случае если пользователь меняет страничку в процессе создания ПО нужено засветить диалог вопрос - Продлолжаем создавать ПО со старой странички или Начинаем проесс  с самого начала?

**Comment by mariia-tokarchuk** [comment]
JDN v 3.1.127
Back-end v 2022-01-21-15.18.28
Mac OS

1) На данный момент существует стандартный диалог с предупреждением о том что мы покидаем страничку:

<img width="1418" alt="Screenshot 2022-02-22 at 15 02 09" src="https://user-images.githubusercontent.com/89466817/155273612-9ee7366f-9d35-4907-81a6-b8b68473389a.png">

2) При нажатии Leave  - плагин возвращается на страницу ПО. При этом:
- Если локаторы не были выбранные, отображается первоначальный вид ПО:
![Screenshot 2022-02-22 at 15 25 1](https://user-images.githubusercontent.com/89466817/155275098-9933a4dc-1678-4a6d-81f9-f53063bf2e44.png)

- Если локаторы были выбранные, они автоматически добавляются в новый ПО:
![Screenshot 2022-02-22 at 15 28 1](https://user-images.githubusercontent.com/89466817/155275124-36a332fa-0495-4768-8a2a-ed5db9130619.png)

**Варианты решения:**
1) нужно проверить такой ли же механизм работы на Windows ?
2) привести уже существующий механизм работы к одному виду
3) заменить стандартное диалоговое окно на наше:
![Generated](https://user-images.githubusercontent.com/89466817/155276292-0d6b4265-8e69-409a-bef5-130fa5ba9490.png)

**Comment by AlexeyGirin** [comment]
Создание ПО должно происходить и заканчиваться по нажитию кнопки Конфирм.
Если в процессе создания пользователь поменял страницу - всё должно обнуляться и никакой ПО создаваться не должен (т.к. кнопка Конфирм нажата не была)

**Comment by MariiaNebesnova** [comment]
3.1.141

**Comment by MariiaNebesnova** [comment]
Back button removed from Page Objects, untill decisions for https://github.com/jdi-testing/jdn-ai/issues/260

**Comment by ioffem** [comment]
reopened

JDN v 3.1.143
Back-end v 2022-02-12-11.36.19
Chrome

1) Back button clicking leads to backend failure
Steps to reproduce:
generate
click Back
try to generate again or just read terminal 
AR: there are lots of warning about invalid result
ER: there should be no way to affect backend

2) Even if just one of Waiting locator was checked confirmation leads to empty page object with saved process
Steps to reproduce:
generate
check several locators (even of of them should be from Waiting group)
confirm
approve confirm
AR: we see the page objects list with our empty page object
click generate again
AR: we are returned to old process from beginning steps, not new process
ER: confirmation should be successful no matter which locators are checked (generated and waiting locators should be added to PO, deleted locators - not). Moreover, every Generate button clicking should start new process.

**Comment by MariiaNebesnova** [comment]
3.1.144

**Comment by ioffem** [comment]
JDN v 3.1.144
Back-end v 2022-02-12-11.36.19
Chrome

done

**Comment by savinovava** [comment]
The new UC was created: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22315067/US-14-2+Identify+elements+in+Page+Objects#UC-14-2-6-User-changes-website-in-the-process-of-creating-Page-Objects
