### ISSUE TITLE
[E-18] Учесть в дизайне генерацию локаторов от пэрентов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#296]
- [ ] https://github.com/jdi-testing/jdn-ai/issues/424
- [x] #425 
- [x] #426
- [x] #427
- [x] #428
- [x] #439
- [x] Document this feature
- [x] https://github.com/jdi-testing/jdn-ai/issues/317
- [ ] #440 
- [x] #446 
- [x] #460 
- [ ] #503 
В данный момент мы эволюционным образом пришли к генерации локаторов относительно родительских элементов. Естественным кажется - отразить иерархию локаторов в на экране.
Очевидно, что начальный список локаторов (не просчитанных) так и должен остаться списком (он всё равно временный).
Но вот список сгенерённых локаторов - видимо нужно превращать в дерево.
Вероятно, что в большинстве случае - вложенность этих элементов не превысит трёх.
![image](https://user-images.githubusercontent.com/26869421/154652564-4d81d14e-01b1-4d29-83cf-94efef2244fa.png)

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4782%3A54546)

Generation of locators from parents in the form of a tree. at the moment allows you to make a maximum of 4-5 levels, a greater number must be worked out. Generated and unloaded locators are displayed in the same tree.

Also in the future we need to make a design and prescribe a script for deleting locators (transfer to the group *deleted*)

![In progress](https://user-images.githubusercontent.com/101407186/158960630-7f2dc403-24df-4421-a594-032b71be34fa.png
<img width="1406" alt="Снимок экрана 2022-03-18 в 11 05 46" src="https://user-images.githubusercontent.com/101407186/158961074-4199f89f-9dee-498f-ab23-51e8b3298b59.png">
)

**Comment by SemyonKuznetsov** [comment]
[Figma prototype](https://www.figma.com/proto/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?page-id=4944%3A56055&node-id=4948%3A64197&viewport=351%2C48%2C0.25&scaling=scale-down-width&starting-point-node-id=4948%3A64197)  
 and [Figma link](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4948%3A64197)

The locators inside Deleted are not restored to the parent tree, but go in the order of deletion, the Deleted category itself is attached to the last locator, not to the bottom of the field, because it is not visible in the notifications and creates visual garbage. Also it is necessary to allow opening locators list and Deleted category at the same time

The locator level in the parent tree is hidden (but you cannot remove it from the characteristics, so that when you restore the locator back to its original place)

<img width="1275" alt="Снимок экрана 2022-03-25 в 07 25 36" src="https://user-images.githubusercontent.com/101407186/160054108-d00171a5-ff3b-4261-9409-e865a84173f3.png">

Also need to fix the UI of the deleted category, a [detailed description is here](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4948%3A68796)

<img width="563" alt="Снимок экрана 2022-03-25 в 07 33 52" src="https://user-images.githubusercontent.com/101407186/160054829-9334d2e2-cde3-4e40-868a-f1bc6b450f2f.png">

**Comment by SemyonKuznetsov** [comment]
Update icons for the parent tree view option, [Figma link](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4782%3A54546)
1) eye icon to the left of the text
2) arrow icons are subordinated to the general directional logic (down = open, up = hide)
3) prescribed frame width distances for icons and margins

<img width="1275" alt="Снимок экрана 2022-03-25 в 07 39 30" src="https://user-images.githubusercontent.com/101407186/160055504-c22568f7-87ec-478f-a24f-8feed9f81f54.png">

**Comment by AlexeyGirin** [comment]
@savinovava подскажи - нужна ли тут работа с твоей стороны?

**Comment by savinovava** [comment]
1. How will we prioritize it?
2. Will the displayed hierarchy be the same for in progress and generated section too?
3. How it will be displayed if filtered?

**Comment by savinovava** [comment]
The US was created: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/35356673/US-6-10+Display+generated+locators+hierarchically+to+a+user

**Comment by MariiaNebesnova** [comment]
это для текущего релиза?

**Comment by AlexeyGirin** [comment]
> это для текущего релиза?

Да, для этого

**Comment by MariiaNebesnova** [comment]
как будет происходить сортировка локаторов inProgress?

**Comment by AlexeyGirin** [comment]
> как будет происходить сортировка локаторов inProgress?
Есть дефолтная сортировка у Вадима, но есть возможность выставить "наивысший приоритет" через контекстное меню - Increase Calculation Priority - и такие считать в первую очередь. Нужна поддержка со стороны бэка, дизайн от Семёна, поддержка на фронте

> Все дерево по умолчанию развернуто?
Да. Планируется, что Вадим обогатит список элементов полем Parent куда запишет указатель на родительский элемент (JDIHash) и Маша соберёт дерево на фронте. End Point Predict. (что бы это не значило)

> Что будет с детьми локатора в случае, когда после редактирования он начинает ссылаться на новый элемент? Мы ищем ему новых детей?
1. Этот элемент появляется как верхнеуровневый в конце списка

A1-A

**Comment by MariiaNebesnova** [comment]
![image](https://user-images.githubusercontent.com/82033805/165541639-fd902080-40d4-4724-a5df-f43a204b0f0a.png)
как здесь подсветить headerMenu? как выбранный (голубым) или как нет (желтым)?

**Comment by AlexeyGirin** [comment]
AAAA - AAAA
  ~BBBB - AAAA//BBBB~
    CCCC - AAAA//BBBB/CCCC

**Comment by AlexeyGirin** [comment]
Семён должен прописать дизайн

**Comment by SemyonKuznetsov** [comment]
**Юзер хочет удалить локатор:**
- Митболс меню ( это которое ···) локатора -> удалить -> локатор переходит в состояние Удалённый + иконка нового статуса

**Юзер хочет изменить локатор:**
- Митболс меню ( это которое ···) локатора -> редактирование -> локатор переходит в состояние Изменённый + иконка нового статуса, старая версия локатора в состоянии Удалённый появляется в конце списка 1го уровня

**Юзер хочет поставить приоритет генерации:**
- Один локатор -> Митболс меню ( это которое ···) -> задать приоритет  -> выбор приоритета (сколько приоритетов может быть?)
![image](https://user-images.githubusercontent.com/101407186/165871011-66fcc644-6eb5-4169-ac57-0b8e6eb66451.png)
- Выделение нескольких локаторов -> ? верхняя навигация, кнопки для действий с несколькими объектами

**Вопросы:**

1. 3 уровня приоритета достаточно? высокий - средний (по умолчанию) - низкий
2. Есть возможность вызова кастомного меню через ПКМ по локатору, например, или там по умолчанию браузерное

**Comment by SemyonKuznetsov** [comment]
>  3 уровня приоритета достаточно? высокий - средний (по умолчанию) - низкий

2 - высокий и по умолчанию

**Comment by savinovava** [comment]
**Перенос изначально сгенерированного локатора после редактирования:**

отредактированный локатор, который не указывает на элемент из списка (т.е. какой-то новый элемент), появляется на верхнем уровне в конце списка локаторов (в корень) + старый локатор остаётся на месте (аналогично с новым элементом)
Как будем создавать дочерний элемент? Будет дополнительно обсуждено при имплементации функции наследования
(JDN hash есть у всех элементов)
если в процессе редактирования локатор указывает на новый элемент, то создаётся в корень первой нодой
если отредактированный локатор указывает на тот же элемент, что и редактируемый, то редактируемый отображается с иконкой deleted
наследуемые элементы изменяются по иерархии - желательный вариант (frontend необходимо знать, что унаследовал локатор от parent - возвращает backend)
наследуемые локаторы не изменяются - простая версия (решили сразу имплементировать желательный вариант)
Restore локаторов

**Секция "Deleted"** Отказываемся, заменяем иконками-статусами

**Изменение наследования (приоритизация) локаторов**
_Не в приоритете_

**Comment by savinovava** [comment]
Checked and Decomposed
