### ISSUE TITLE
[US-7-2][Locator editor] The editing functionality breaks down when entering the maximum values

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#297]
JDN v 3.0.88
Back-end v 2021-11-26-14.32.52
Версия 95.0.4638.69 (Официальная сборка), (x86_64)
[US-7-2] Edit locator dialog 
1. Open JDN plugin
2. Open website mail.ru
3. Press [Identify]
4. Press [...]
5. Press [Edit]
6. Edit field "Name:" write:
"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
7. Press [Save]
8. Press [...]
9. Press [Edit]

ER: User can edit locator name again.
AR: User can't edit locator name again.
https://user-images.githubusercontent.com/61897393/143993958-48cbda08-15fd-4745-9962-462ae0ffaf50.mp4

**Comment by MariiaNebesnova** [comment]
set max length according to java conventions

**Comment by IoffeM** [comment]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

is not reproducible anymore
