### ISSUE TITLE
[US-14-6-1] Rename Page object

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#298]
stories https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27721756/US-14-6+Page+Object+s+settings#UC-14-6-1-Rename-Page-Object
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27721756/US-14-6+Page+Object+s+settings#UC-14-6-2-1-Rename-Page-Object-validation

**Comment by MariiaNebesnova** [comment]
waiting for icon

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4901%3A56065) + svg
![type=rename, color=black, size=18](https://user-images.githubusercontent.com/101407186/159800735-a4c0f855-1c43-43fb-ab95-0aa5dfafa7c6.svg)

**Comment by MariiaNebesnova** [comment]
- icons in context menus moved right, according to mockups
- for naming repeated Page objects, brackets aren't used anymore

**Comment by MariiaNebesnova** [comment]
3.1.152

**Comment by ioffem** [comment]
reopened

JDN v 3.1.152
Back-end v 2022-02-12-11.36.19
Chrome

1) we can save any characters quantity in the Name field, that doesn't correlate with requirements
BUT
max file name length for Mac, Win and Linux is 255 symbols. So it can be our max characters quantity for this field.
2) if we use huge name (like 65535 symbols or smth else), it leads to zip archive extracting issues.
<img width="1397" alt="Screen Shot 2022-03-24 at 11 02 50 AM" src="https://user-images.githubusercontent.com/98175427/159874091-13b74264-9d4d-49b7-9c33-4aa076b46335.png">

3) if we use [0-246] symbols, it's ok. if more (247 and more) - our files is reading like empty. I'm not sure, i should find the max value for issue №2 and min value for issue №1.
<img width="1397" alt="Screen Shot 2022-03-24 at 11 30 12 AM" src="https://user-images.githubusercontent.com/98175427/159874639-c0b5b732-e2ed-4ff6-8b74-5399a9bfed30.png">

**I suggest to set max name field length = 255 and fix issue №3**

**Comment by ioffem** [comment]
QA note: 255 symbols text to check
Dsfsdfsdfsdfsfdsfddsfsdfsdfsdfsfdsfddsfsdfsdfsdfsfdsfddsfsdfsdfsdfsfdsfddsfsdfsdfsdfsfdsfddsfsdfsdfsdfsdfsfdsfddsfsdfsdfsdfsfdsfddsfsdfsdfsdfsfdsfddsfsdfssfdsfddsfsdfssdfssfdsfddsfsdfssdfssfdsfddsfsdfsdfssfdsfddsfsdfssdfssfdrtttttttttteeeeeeeeeerererererr

**Comment by MariiaNebesnova** [comment]
3.1.153

**Comment by ioffem** [comment]
reopened

JDN v 3.1.153
Back-end v 2022-02-12-11.36.19
Chrome
 
name length from 247 to 255 symbols leads to empty file issue on the archive extracting step
<img width="1397" alt="Screen Shot 2022-03-24 at 2 47 54 PM" src="https://user-images.githubusercontent.com/98175427/159910024-e6b380cd-32c6-4dc9-ac69-fd358e9316c5.png">

**Comment by AlexeyGirin** [comment]
Ограничиваем максимальную длинну - 60 символами

**Comment by ioffem** [comment]
JDN v 3.1.155
Back-end v 2022-02-12-11.36.19
Chrome

done
