### ISSUE TITLE
[US-14-6-3]  Delete Page Object

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#299]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27721756/US-14-6+Page+Object+s+settings#UC-14-6-3-Delete-Page-Object

**Comment by MariiaNebesnova** [comment]
3.1.137

**Comment by ioffem** [comment]
JDN v 3.1.137
Back-end v 2022-02-12-11.36.19
Chrome

done
test cases and mind map are updated
