### ISSUE TITLE
[US-14-6-4] Download Page Object

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#300]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/27721756/US-14-6+Page+Object+s+settings#UC-14-6-4-Download-Page-Object

**Comment by MariiaNebesnova** [comment]
3.1.138

**Comment by ioffem** [comment]
JDN v 3.1.138
Back-end v 2022-02-12-11.36.19
Chrome

what about empty page objects?
when we implemented Download button for page objects list, we decided to let user download empty page object. But current feature avoid user to download single empty page object. Let's discuss it again and find one common decision.

**Comment by AlexeyGirin** [comment]
Done. (as per Margarita request)
