### ISSUE TITLE
[Critical] Huge locators queue

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#305]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

1) open any page 
2) open the JDN tab
3) new page object
4) generate and DO NOT wait for finish
5) confirm
6) new page object

AR: new page object can be generated really slow cause we have a queue from the previous generation. Sometimes plugin breaks and we should reload it.
ER: only current page object locators can be in queue

**Comment by IoffeM** [comment]
@AlexeyGirin please, add URL of the page, where plugin broke and there was a long turn.

**Comment by AlexeyGirin** [comment]
I used the following site: https://jdi-testing.github.io/jdi-light/html5.html

**Comment by MariiaNebesnova** [comment]
v3.1.139

**Comment by ioffem** [comment]
JDN v 3.1.139
Back-end v 2022-02-12-11.36.19
Chrome

done
