### ISSUE TITLE
Change the page object url color

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#308]
As user
I want to have correct color for non-clickable url
In order not to be confused

Current blue color can confuse user cause this color is usually used for clickable links.

Change the color of page object tooltip (is marked on the screenshot below) to color: #888 in order to show user that it is not a link, just text
<img width="519" alt="Screen Shot 2022-02-25 at 11 46 56 AM" src="https://user-images.githubusercontent.com/98175427/155684179-8b9d7fef-7623-4d49-840d-d3bdf8abfc47.png">

**Comment by AlexeyGirin** [comment]
Надо бы как-то сделать так что бы не вызывало желания кликнуть на эту ссылку (при том, что это не ссылка, конечно)

**Comment by mariia-tokarchuk** [comment]
Change the color of the url to Hex #808080

![choose a library](https://user-images.githubusercontent.com/89466817/157436557-35ee01a8-f228-4a7b-86db-96d242eac6fb.png)

Link to Figma - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=3489%3A49008

**Comment by MariiaNebesnova** [comment]
3.1.151

**Comment by ioffem** [comment]
JDN v 3.1.151
Back-end v 2022-02-12-11.36.19
Chrome

done
