### ISSUE TITLE
[US-6-6][E-18] Add modal for deleted locators confirmation

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#317]
US: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910696/US-6-6+Delete+elements+from+generation
Design: 

Add additional confirmation modal for the case with at least one selected deleted locator:
  - it look like our usual confirmation modal (modal for locators in progress)
  - it should contain another text: Attention! Selected locators from Deleted group won't be include to the page object. We recommend restore it before confirmation.
  - it should contain Cancel, Confirm the selection and X buttons
  - Cancel and X return user to locators generating
  - Confirm the selection moves user to page objects list with last expanded page object with NO DELETED locators

**Comment by AlexeyGirin** [comment]
Вопрос нужно обсудить с @mariia-tokarchuk

**Comment by SemyonKuznetsov** [comment]
Почему мы не можем дать пользователям возможность добавлять локаторы из Deleted? Это же по факту просто пропуск шага Restore + эти локаторы так просто мискликом не выбрать, они в изначально скрытой папке, если выбрали, значит надо 🤷‍♂️

Можем пойти от положительного действия и при подтверждении говорить "you add 5 locators from Deleted, are you sure?" etc и варианты confirm&cancel

Если такой вариант не подходит, то можно поставить условия — если выбран локатор, нельзя выбрать удалённый локатор или наоборот, а на UI показывать нотификейшн "impossible to combine"

**Comment by ioffem** [comment]
В текущей ситуации могу согласиться. Когда заводили тикет, чекбоксы с удаленных не убирались автоматически, что могло быть просто не замечено про большом списке других групп. Сейчас же удаленный локатор действительно нужно выбрать специально. Ну почему бы и нет, собственно. @SemyonKuznetsov выноси сегодня на обсуждение

**Comment by AlexeyGirin** [comment]
Решили: Если решили что-то сделать с удалёнными локаторами (селектнули из) - то кнопка Confirm становится недоступной пока существует на экране кнопка Restore
Если при выделенных удалённых локаторах мы начинаем выделять обычные - нотификейшен без кнопок что выделять одновременно и нормальные и делетед - нельзя

**Comment by savinovava** [comment]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910696/US-6-6+Delete+elements+from+generation#UC-6-6-3-1-User-can%E2%80%99t-confirm-identification-with-deleted-locators
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910696/US-6-6+Delete+elements+from+generation#UC-6-6-4-User-can%E2%80%99t-select-deleted-and-non-deleted-locators-at-one-selection
UC were added, waiting for design
Q: What will happen If we choose non-deleted locator and after choose deleted? Is it possible in one selection?

**Comment by SemyonKuznetsov** [comment]
1 [figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5292%3A313011)
![4](https://user-images.githubusercontent.com/101407186/165463512-ff87d6f8-b0c7-4f82-a2a1-2af1a959859b.png)

2 [figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5294%3A313430)
![5](https://user-images.githubusercontent.com/101407186/165463611-78ece59b-1e85-4ae9-bb42-4d1bf515c6d1.png)

[protorype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=5292%3A313011&viewport=241%2C48%2C0.49&scaling=scale-down-width&starting-point-node-id=5292%3A313011)

**Comment by savinovava** [comment]
User check deleted and non-deleted locator - confirm disabled
1 node inside the group - won't be checked if the group is checked
Only deleted locators - confirm disabled and restore is in header

UC 
1. Не выделять при выделении группы
2. При выделении группы confirm is disabled и дополнительный варнинг
3. При выделении группы доступен confirm и дополнительный варнинг - (как сейчас) 
4. Вернуть deleted section

**Comment by savinovava** [comment]
UC to discuss:

UC 6-6-4 User can’t confirm deleted and non-deleted locators selection
GIVEN user check the deleted and non-deleted locator
WHEN  I hover the confirmation
THEN the warning should appear
AND the button “Confirm” will be active

or these locators can't be selected together? https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=5292%3A313011&viewport=241%2C48%2C0.49&scaling=scale-down-width&starting-point-node-id=5292%3A313011

**Comment by AlexeyGirin** [comment]
Модальное окно должно быть чёрным

**Comment by MariiaNebesnova** [comment]
3.1.182
