### ISSUE TITLE
[Medium] Locator name selecting leads to warning appearance and disabled Save button

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#320]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome

1) open any webpage
2) open JDN tab
3) new page object
4) generate
5) open any locator Edit menu
6) select the name in the Name container
7) unselect

AR: warning and disabled Save button
<img width="591" alt="Screen Shot 2022-03-02 at 1 13 05 PM" src="https://user-images.githubusercontent.com/98175427/156341714-529e4b1f-4441-485d-8678-5333de80c0b6.png">

![edit1](https://user-images.githubusercontent.com/98175427/156342253-ca17733f-fe3f-40ac-b100-c991e081ee22.gif)

ER: if there are no changes, there should be no warning and no button status changes

**Comment by MariiaNebesnova** [comment]
can't reproduce
