### ISSUE TITLE
[NR-5] Adapt titles to JDN tab size

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#322]
Adapt titles to JDN tab size:
1) if the tab is too small for the title, there should be a line break
2) when user changes a tab size, all titles should be changed with it. line breaks can appear and disappear depending on the tab

The best way to understand the idea is to look at the browser console dependence on tab resize

Aim: user should not scroll right and left, should not resize tab to find something. If he doesn't know that we have a meatball menu for objects with long names, he won't use. Look at the example below (https://www.behance.net/):

<img width="591" alt="Screen Shot 2022-03-03 at 4 09 21 PM" src="https://user-images.githubusercontent.com/98175427/156571043-a95c3bbf-a543-4f63-8c22-990ff7641c66.png">

**Comment by AlexeyGirin** [comment]
Сделать перенос строки названия PO в две-три строки, что бы меню было всегда видно, а горизонтальный скролл никогда не появлялся

**Comment by AlexeyGirin** [comment]
@mariia-tokarchuk please have a look

**Comment by mariia-tokarchuk** [comment]
Examples of such POs:
![Plugin width adaptation](https://user-images.githubusercontent.com/89466817/157447607-665ac9c8-b1d9-40bd-9517-c03e4255bd07.png)

![3 line of PO name](https://user-images.githubusercontent.com/89466817/157447596-6a9996c2-1689-4d46-9e57-474f0466b2b7.png)

Also the comments above should be taken into account.

Link to Figma (with different number of characters in PO titles) - https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4635%3A51776

**Comment by MariiaNebesnova** [comment]
3.1.159

**Comment by VSemendiy** [comment]
Сайт для примера https://www.behance.net/
Разрыв строки в ряде случаев вставляется сначала в самом начале, а потом еще и в середине.
Думается, первый не нужен. Откомментировать в этой задаче или удобнее новым тикетом завести?
![image](https://user-images.githubusercontent.com/77847287/162377852-535b6c97-d38c-4c8c-b8fe-c914a8ba777f.png)

**Comment by MariiaNebesnova** [comment]
@VSemendiy строка xPath - это другой элемент, возможно, по нему уже есть баг. в этой задаче речь только о заголове Page object на стринице списка page objects.

**Comment by VSemendiy** [comment]
Хорошо. Тогда вопрос, касающийся и заголовка. Можнор ли установить для плагина минимальный размер?
Сейчас можно сделать вот так (меню опять исчезает):
![image](https://user-images.githubusercontent.com/77847287/162445907-1280eca3-0ce3-4db9-b9fa-4f92de2a7624.png)

**Comment by MariiaNebesnova** [comment]
@VSemendiy можно. нужно. есть где то в задачах
