### ISSUE TITLE
[Medium] Save button is active when locator field is empty

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#324]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome

1) open any webpage
2) open JDN tab
3) new page object
4) generate
5) open Edit menu for any locator
6) clear locators field

AR: Save button is active and clickable, warning is yellow which means that it's not OK, but user can save it. When user clicks it, modal disappears and no changes were applied to locator.
<img width="482" alt="Screen Shot 2022-03-04 at 2 14 30 PM" src="https://user-images.githubusercontent.com/98175427/156753790-26d306f6-8b9f-4405-afee-1e4b35c3fd66.png">

ER: Save button should be disabled, the warning should be red as for name field.

**Comment by AlexeyGirin** [comment]
Not a bug.
