### ISSUE TITLE
[US-13-1] Avoid empty page objects downloading by page objects list Download button

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#326]
When user downloads all page objects, empty page objects should be ignored.

**Comment by savinovava** [comment]
UC-13-1-1 was created: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/22315012/US-13-1+Create+the+package+of+generated+objects

**Comment by MariiaNebesnova** [comment]
3.1.151

**Comment by ioffem** [comment]
JDN v 3.1.152
Back-end v 2022-02-12-11.36.19
Chrome

done
