### ISSUE TITLE
Rename created but not generated page object after new webpage opening

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#327]
When user creates new page object, then opens new webpage in the same tab and generates current page object, the last one should be renamed, its URL should be changed. It should prevent the strange case as in gif below

Current strange behavior:
![rename1](https://user-images.githubusercontent.com/98175427/156880196-8b735b95-4296-4543-b770-c9d33074b271.gif)

**Comment by AlexeyGirin** [comment]
Подумать - что делать - либо сделать как изначально предлагала Маша - менять название ПО при смене странички
ИЛИ
Всё удалять что бы потом начать с начала

**Comment by MariiaNebesnova** [comment]
now we clean up empty POs when move to a new page
