### ISSUE TITLE
[Medium] Issues with bringing to front and back

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#329]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome

1) open any webpage (convenient webpage for current scenario is https://cbracco.github.io/html5-test-page/)
2) open JDN tab
3) new page object
4) generate
5) select any group of locators and try to bring them to front and to back (try HTML5 inputs group)

AR: no matter which locator was sent to front or to back, they all are clickable and active in every area
_can't attach gif cause of locator menu issues while using gif tool_

ER: if the back locator is full covered by front locator, it can't be clickable through front locator area. so the area of front locators should be clickable only for front locators. if you want to interact with back locator, you should bring it to front or find not covered area.

**Comment by MariiaNebesnova** [comment]
3.1.203
