### ISSUE TITLE
Onbording docs

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#33]
- [x] Create onboarding docs for front-end developers
- [x] Create onboarding docs for back-end developers
- [x] Create onboarding docs for data science
- [x] Create onboarding docs for QA
- [x] Create onboarding docs for designers
- [ ] Validatehttps://github.com/jdi-testing/jdn-ai/issues/33

**Comment by savinovava** [comment]
For Newcomer: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/14090291/For+Newcomer

For BA's: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/13435193/For+BA+s

For Backend Developers: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/14385269/For+Backend+Developers

For Frontend Developers: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/14647310/For+Frontend+Developers

For QA: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/16908454/For+QA

For Designers: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/18415727/For+Designers

**Comment by IoffeM** [comment]
done
