### ISSUE TITLE
[Medium] Locator editing leads to unmarking

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#331]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome

1) open any webpage
2) open JDN tab
3) new page object
4) generate
5) edit any locator (e.g. change type)
6) save

AR: locator was regenerated but it's not marked up anymore

![unmark1](https://user-images.githubusercontent.com/98175427/157657806-f17b7835-2781-4364-af07-879c60bb6d17.gif)

ER: editing is not deleting, locator should stay marked up after editing. Only deleting can unmark it.

**Comment by MariiaNebesnova** [comment]
3.1.181
