### ISSUE TITLE
[US-9-2] [NR-11] Проверять версию бэка на совместимость с фронтендом

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#333]
В данный момент - наш фронт никак не проверяет бэк на то, подходит ли он к нему или нет. Он просто пытается подключиться и дальше - могут происходить разные непонятные вещи если версия фронта не подходит бэку (например у меня - фронт вроде как подхватил бэк (показывал его версию) но утверждал, что не может работать в нескольких табах одновременно (хотя таб был один))
Необходимо при старте плагина - проверять корректность версии бэка и если она не та, которую мы ожидаем - просить пользователя обновить или сам плагин или бэк

NR: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/57802776/NR-11+Backend+and+Frontend+version+compatibility

- [x] Создать таблицу совместимости
- [x] Хранить совместимость версий hard code

**Comment by savinovava** [comment]
There are 2 possible ways of backend: server and local, so it depends

**Comment by MariiaNebesnova** [comment]
should we take existing warning box?

**Comment by savinovava** [comment]
#391

**Comment by AlexeyGirin** [comment]
Лера должна это задокументировать

**Comment by MariiaNebesnova** [comment]
draft implementation is in https://github.com/jdi-testing/jdn-ai/pull/651

**Comment by MariiaNebesnova** [comment]
3.2.242

**Comment by AlexeyGirin** [comment]
Задача станет доступной после имплементации #646

**Comment by MariiaNebesnova** [comment]
3.2.253

**Comment by MariiaNebesnova** [comment]
https://github.com/jdi-testing/jdn-ai#version-compatibility-list
