### ISSUE TITLE
[E-10] Dark theme

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#335]
1) Add dark theme, all colors we can select from console tab
Several mockups are on screenshots below (_just to show the idea, designer mockups are preferable_):
<img width="529" alt="Screen Shot 2022-03-15 at 12 00 48 PM" src="https://user-images.githubusercontent.com/98175427/158342693-e1720863-8575-4226-a2e8-5271f31811c8.png">
<img width="529" alt="Screen Shot 2022-03-15 at 12 00 32 PM" src="https://user-images.githubusercontent.com/98175427/158342700-3dcda006-4fa7-4d9c-aeb3-3be24b19d81d.png">
<img width="529" alt="Screen Shot 2022-03-15 at 12 00 16 PM" src="https://user-images.githubusercontent.com/98175427/158342703-616713cb-8064-4b63-afee-4958050a0d4a.png">
<img width="529" alt="Screen Shot 2022-03-15 at 12 02 51 PM" src="https://user-images.githubusercontent.com/98175427/158342980-17382135-ec98-422f-b2e8-9f72d09b8025.png">

2) Set theme automatically depending on browser settings 
OR
3) add an ability to select theme manually to main meatball menu
scenario: main meatball menu -> dark theme toggle (off by default) as on screenshot below
<img width="108" alt="Screen Shot 2022-03-15 at 12 29 31 PM" src="https://user-images.githubusercontent.com/98175427/158347854-19039cb0-1603-4e59-987a-807e6836e4c7.png">

(!) be sure #308 looks ok in dark theme

**Comment by MariiaNebesnova** [comment]
useful link: https://developer.chrome.com/docs/extensions/reference/devtools_panels/#property-themeName

**Comment by SemyonKuznetsov** [comment]
в Ant'е уже есть тёмная палитра

<img width="648" alt="Снимок экрана 2022-07-14 в 10 33 51" src="https://user-images.githubusercontent.com/101407186/178927456-18fd619d-ca1f-448a-ab72-4f6b6d61cd79.png">

**Comment by SemyonKuznetsov** [comment]
По результатам тестов, "нужна ли темная тема?"- Однозначного ответа нет. Большинство пользователей предпочитает использовать темную тему в своих ежедневных задачах. Работать с актуальной светлой цветовой схемой плагина комфотно.

**Comment by savinovava** [comment]
Fixed in the backlog

**Comment by savinovava** [comment]
Fixed in the backlog
