### ISSUE TITLE
[US-4-3] Показывать удаленные элементы на покрытии

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#34]
добавить подсветку удаленных элементов, см описание в макете
(old) https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=0%3A1
(new) https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5219%3A64680

https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/2424884/Feature+list#US-6-6

**Comment by SemyonKuznetsov** [comment]
[update old link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=1401%3A128368)

**Comment by savinovava** [comment]
Свойства элемента сохраняются
Если выделяем из списка, то отображаем покрытие, иначе покрытие не отображается
MoSCoW
COULD

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6984%3A349102)

color — Neutral/7(8C8C8C) 100% for stroke and 20% for fill background

// я не нашёл в материале примера для такого локатора, представим что этот подходит 🥲
![ll page](https://user-images.githubusercontent.com/101407186/197073474-af99be11-61ad-4b8b-9b11-226b702e1d98.png)

**Comment by MariiaNebesnova** [comment]
[3.3.283](https://github.com/jdi-testing/jdn-ai/releases/tag/3.3.283)

**Comment by Maksim-Kviatkovskii** [comment]
![image](https://user-images.githubusercontent.com/109746268/199953368-ea7eb485-c8ae-4ddd-a1f6-c2fae62a94a6.png)

**Comment by MariiaNebesnova** [comment]
[3.3.289](https://github.com/jdi-testing/jdn-ai/releases/tag/3.3.289)
