### ISSUE TITLE
[High] Back button clicking leads to backend failure

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#340]
JDN v 3.1.144
Back-end v 2022-02-12-11.36.19
Chrome

1) open any webpage
2) open JDN tab
3) new page object
4) generate
5) click Back
6) try to generate again or just read terminal
AR: there are lots of warning about invalid result - _attached to comments_
ER: there should be no way to affect backend

(!) it's not the only one scenario to break backend with the same result but currently i have no exact additional scenario. If you find it while researching, please fix it too.

**Comment by ioffem** [comment]
jdi-qasp-ml-api     | 
  0%|          | 0/1 [00:00<?, ?it/s, /jdi-qasp-ml/data/mui_dataset/df/202203160Build tree features: 100%|██████████| 464/464 [00:00<00:00, 2683.47it/s]
100%|██████████| 1/1 [00:00<00:00,  2.13it/s, /jdi-qasp-ml/data/mui_dataset/df/2100%|██████████| 1/1 [00:00<00:00,  2.12it/s, /jdi-qasp-ml/data/mui_dataset/df/20220316070939272379.pkl]2022-03-16 07:09:39,752 -INFO - dataset.py:165 - self.df.shape: (464, 27)
jdi-qasp-ml-api     | 2022-03-16 07:09:39,752 -INFO - dataset.py:108 - Check for duplicates...
jdi-qasp-ml-api     | 2022-03-16 07:09:39,754 -INFO - dataset.py:112 - Check for duplicates is OK
jdi-qasp-ml-api     | 2022-03-16 07:09:39,770 -INFO - features_builder.py:383 - used column: tag_name
jdi-qasp-ml-api     | 2022-03-16 07:09:39,770 -INFO - features_builder.py:386 - loading /jdi-qasp-ml/MUI_model/model/ohe_tag_name.pkl
jdi-qasp-ml-api     | 2022-03-16 07:09:39,773 -INFO - features_builder.py:383 - used column: tag_name_parent
jdi-qasp-ml-api     | 2022-03-16 07:09:39,773 -INFO - features_builder.py:386 - loading /jdi-qasp-ml/MUI_model/model/ohe_tag_name.pkl
jdi-qasp-ml-api     | 2022-03-16 07:09:39,775 -INFO - features_builder.py:311 - tag_name: (464, 8)
jdi-qasp-ml-api     | 2022-03-16 07:09:39,775 -INFO - features_builder.py:416 - used column: attributes
jdi-qasp-ml-api     | 
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
Extract "attributes": 100%|██████████| 464/464 [00:00<00:00, 10978.43it/s]2022-03-16 07:09:39,826 -INFO - features_builder.py:416 - used column: attributes_parent
jdi-qasp-ml-api     | 
Extract "attributes": 100%|██████████| 464/464 [00:00<00:00, 11945.55it/s]2022-03-16 07:09:39,871 -INFO - features_builder.py:326 - attributes_sm: (464, 31)
jdi-qasp-ml-api     | 2022-03-16 07:09:39,871 -INFO - features_builder.py:455 - used column: attributes
jdi-qasp-ml-api     | 2022-03-16 07:09:39,871 -INFO - features_builder.py:460 - CountVectorizer and TfidfTransformer for class attribute exist. Loading...
jdi-qasp-ml-api     | 2022-03-16 07:09:39,877 -INFO - features_builder.py:455 - used column: attributes_parent
jdi-qasp-ml-api     | 2022-03-16 07:09:39,877 -INFO - features_builder.py:460 - CountVectorizer and TfidfTransformer for class attribute exist. Loading...
jdi-qasp-ml-api     | 2022-03-16 07:09:39,883 -INFO - features_builder.py:333 - class_sm: (464, 914)
jdi-qasp-ml-api     | 2022-03-16 07:09:39,883 -INFO - features_builder.py:519 - used column: attributes
jdi-qasp-ml-api     | 2022-03-16 07:09:39,884 -INFO - features_builder.py:522 - loading /jdi-qasp-ml/MUI_model/model/ohe_type.pkl
jdi-qasp-ml-api     | 2022-03-16 07:09:39,886 -INFO - features_builder.py:519 - used column: attributes_parent
jdi-qasp-ml-api     | 2022-03-16 07:09:39,886 -INFO - features_builder.py:522 - loading /jdi-qasp-ml/MUI_model/model/ohe_type.pkl
jdi-qasp-ml-api     | 2022-03-16 07:09:39,888 -INFO - features_builder.py:340 - type_sm: (464, 2)
jdi-qasp-ml-api     | 2022-03-16 07:09:39,889 -INFO - features_builder.py:554 - used column: attributes
jdi-qasp-ml-api     | 2022-03-16 07:09:39,889 -INFO - features_builder.py:557 - loading /jdi-qasp-ml/MUI_model/model/ohe_role.pkl
jdi-qasp-ml-api     | 2022-03-16 07:09:39,891 -INFO - features_builder.py:554 - used column: attributes_parent
jdi-qasp-ml-api     | 2022-03-16 07:09:39,892 -INFO - features_builder.py:557 - loading /jdi-qasp-ml/MUI_model/model/ohe_role.pkl
jdi-qasp-ml-api     | 2022-03-16 07:09:39,893 -INFO - features_builder.py:347 - role_sm: (464, 8)
jdi-qasp-ml-api     | 2022-03-16 07:09:39,894 -INFO - features_builder.py:590 - used column: children_tags
jdi-qasp-ml-api     | 2022-03-16 07:09:39,894 -INFO - features_builder.py:594 - CountVectorizer and TfidfTransformer for children tags exist. Loading...
jdi-qasp-ml-api     | 2022-03-16 07:09:39,897 -INFO - features_builder.py:651 - used column: followers_tags
jdi-qasp-ml-api     | 2022-03-16 07:09:39,897 -INFO - features_builder.py:655 - CountVectorizer and TfidfTransformer for followers tags exist. Loading...
jdi-qasp-ml-api     | 2022-03-16 07:09:39,907 -INFO - dataset_collector.py:174 - X: (464, 2009)
jdi-qasp-ml-api     | 
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfVectorizer from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator OneHotEncoder from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator CountVectorizer from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
jdi-qasp-ml-api     | /usr/local/lib/python3.7/site-packages/sklearn/base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 1.0.1 when using version 0.24.1. This might lead to breaking code or invalid results. Use at your own risk.
jdi-qasp-ml-api     |   UserWarning)
100%|██████████| 464/464 [00:00<00:00, 3142.07it/s]INFO:     172.22.0.1:59800 - "POST /mui-predict HTTP/1.1" 200 OK

**Comment by rrr3try** [comment]
Воспроизвести, именно чтобы ломалось, не удалось(User warnings - не ошибка формально), обновил библиотеки до тех, которые использованы были при тренировке нейронки

**Comment by ioffem** [comment]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome

done
