### ISSUE TITLE
[Low] Locator status icons are not aligned

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#343]
JDN v 3.1.145
Back-end v 2022-02-12-11.36.19
Chrome

1) open any webpage
2) open JDN tab
3) new page object
4) generate
5) edit any locator

AR: 
<img width="578" alt="Screen Shot 2022-03-17 at 10 17 10 AM" src="https://user-images.githubusercontent.com/98175427/158756931-b9c48e3e-c031-4b19-9ddf-7d52eed4e17e.png">

<img width="578" alt="Screen Shot 2022-03-17 at 10 22 08 AM" src="https://user-images.githubusercontent.com/98175427/158757433-16a51e62-93c4-4042-bbe0-1b27a41b256d.png">

ER: status icons should be aligned with each other

**Comment by MariiaNebesnova** [comment]
list was removed from the UI
