### ISSUE TITLE
[Low] Notification cancel button is not aligned

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#344]
JDN v 3.1.145
Back-end v 2022-02-12-11.36.19
Chrome

1) open any webpage
2) open JDN tab
3) new page object
4) generate
5) edit/delete/restore locator

AR: 
<img width="578" alt="Screen Shot 2022-03-17 at 10 23 08 AM" src="https://user-images.githubusercontent.com/98175427/158757791-cbc5e325-217a-4b20-ba7b-72c1ffe5c2da.png">

ER: Cancel button in notification should be center aligned

**Comment by Aniuta907** [comment]
Version: 3.1.178
