### ISSUE TITLE
Optimize all clickable elements work while generating is in progress

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#347]
Currently large pages locators generating leads to really slow work of all buttons and modals. Sometimes it leads to several clicks by angry user and several modals opening. ANd he close one of them, but there are several additional modals. Tooltips are too slow. 

Nice example to test: https://www.behance.net/

We need to fix it somehow, cause user can wait for generating but he won't wait for slow UI elements work.

**Comment by AlexeyGirin** [comment]
Оставить пару ядер (или одно) - для фронта. Судя по всему сейчас бэк забирает себе всё из-за этого фронт тормозит

**Comment by MariiaNebesnova** [comment]
3.1.154

**Comment by ioffem** [comment]
JDN v 3.1.154
Back-end v 2022-02-12-11.36.19
Chrome

great job
done
