### ISSUE TITLE
[High] Marks are not pinned to locators while scrolling

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#348]
JDN v 3.1.147
Back-end v 2022-02-12-11.36.19
Chrome
https://www.behance.net/

1) open the page from the precondition
2) open JDN tab
3) new page object
4) generate
5) scroll the page

AR: marks are scrolling with no correlation with locators
ER: marks should be pinned to its locators and scroll together

**Comment by AlexeyGirin** [comment]
Проблема воспроизводится на страничке https://www.behance.net/
Судя по всему - это баг. Нужна инвестигация

**Comment by andrei-mikhailovskii** [comment]
Probably, the following bug is related to the current one: https://github.com/jdi-testing/jdn-ai/issues/1077

**Comment by arslanbekova** [comment]
[3.9.406](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.406)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.406 Back-end v 0.2.27

Test result - **fail**

Steps to reproduce:
1. Open https://www.behance.net/
2. Generate new page object via JDN plugin
3. Scroll page down

Actual result: marks are not pinned to locators on header while scrolling

https://user-images.githubusercontent.com/106632366/223121962-506bc8af-dda0-4b57-8004-34553d97a0f8.mp4

**Comment by arslanbekova** [comment]
> JDN v 3.9.406 Back-end v 0.2.27
> 
> Test result - **fail**
> 
> Steps to reproduce:
> 
> 1. Open https://www.behance.net/
> 2. Generate new page object via JDN plugin
> 3. Scroll page down
> 
> Actual result: marks are not pinned to locators on header while scrolling

please, not so fast, plugin needs some time to detect elements on page and highlight them while scrolling.
I don't know why behance is so slow, but it works.
You can check it in Linkedin or google images as well

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.407 Back-end v 0.2.27

The bug is fixed.
Marks are pinned to locators while scrolling. In some cases, plugin needs to wait some time to detect elements on a page as it is described in the [previous comment](https://github.com/jdi-testing/jdn-ai/issues/348#issuecomment-1456163004).

https://user-images.githubusercontent.com/106632366/223143288-fd546e58-3c82-45d7-afe9-f22cf9e8c601.mp4
