### ISSUE TITLE
[Low] Locator status icon was not changed after editing cancelling

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#352]
JDN v 3.1.147
Back-end v 2022-02-12-11.36.19
Chrome

1) open any page
2) open JDN tab
3) new page object
4) generate
5) edit any locator
6) cancel changes

AR: edited successfully icon
<img width="578" alt="Screen Shot 2022-03-22 at 9 15 17 AM" src="https://user-images.githubusercontent.com/98175427/159419330-3d70a095-af9f-408a-8ff6-698539da1f3e.png">

ER: default generated icon

**Comment by Maksim-Kviatkovskii** [comment]
Больше не актуально
