### ISSUE TITLE
[Low] Locator block type editing doesn't change the status icon

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#353]
JDN v 3.1.147
Back-end v 2022-02-12-11.36.19
Chrome

1) open any page
2) open JDN tab
3) new page object
4) generate
5) edit locators block type

AR: default generated icon
ER: edited successfully icon

**Comment by MariiaNebesnova** [comment]
decided, that we show Edited successfully only for edited xPathes
