### ISSUE TITLE
[1pt][US-6-4] Highlight locator on click

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#36]
[Related US-6-4](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910676/US-6-4+Manage+locators+from+locators+list)

**Comment by marusyaganza** [comment]
Fixed in version 3.0.65

**Comment by savinovava** [comment]
[1pt] - QA

**Comment by DaryaGurtovenko** [comment]
Verified on ver. 3.0.71
