### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#360]
- [x] 1.  #368
add checkboxes for page objects and packages. [figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6230%3A330960)
![#626](https://user-images.githubusercontent.com/101407186/190095011-74edb09a-b825-4fb5-8f98-b371a56db492.png)

- [ ] 2. #370
Is it possible to add the "manually create locator" function if the program did not read the needed object? (like a button +add locator at the locator generation stage)<img width="1275" alt="Снимок экрана 2022-03-25 в 08 05 13" src="https://user-images.githubusercontent.com/101407186/174746186-a5683ca8-262b-4012-bba8-7469853e1f7a.png">

- [x] 3. Необходимо пересобрать локатор из-за разных размеров текста, иконок и их фреймов и несовпадения всего этого с фреймворком, как результат - у всего прыгают отступы, нет чётких визуальных границ

- [x] 4. Нотификейшены и ошибки
#262 
#669 

- [x] 4. локаторы в списке сливаются с друг другом, необходимо поменять отступы или высоту строки
#681
<img width="1551" alt="Снимок экрана 2022-08-22 в 23 20 42" src="https://user-images.githubusercontent.com/101407186/186011664-f1ce343c-e842-4e55-83c8-3146005d1108.png">

- [x] 5. обновить report a problem до анта
#392 
<img width="290" alt="Снимок экрана 2022-09-02 в 17 42 59" src="https://user-images.githubusercontent.com/101407186/188174207-ec1e461d-9cb7-4549-8764-894af4357a3a.png">

- [x] 6. Visual update modals and popups #680

**Comment by SemyonKuznetsov** [comment]
3. Необходимо пересобрать локатор из-за разных размеров текста, иконок и их фреймов и несовпадения всего этого с фреймворком, как результат - у всего прыгают отступы, нет чётких визуальных границ

**Comment by SemyonKuznetsov** [comment]
4. Нотификейшены и ошибки

**Comment by SemyonKuznetsov** [comment]
локаторы в списке сливаются с друг другом, необходимо поменять отступы или высоту строки

<img width="1551" alt="Снимок экрана 2022-08-22 в 23 20 42" src="https://user-images.githubusercontent.com/101407186/186011664-f1ce343c-e842-4e55-83c8-3146005d1108.png">

**Comment by SemyonKuznetsov** [comment]
5. обновить report a problem до анта

<img width="290" alt="Снимок экрана 2022-09-02 в 17 42 59" src="https://user-images.githubusercontent.com/101407186/188174207-ec1e461d-9cb7-4549-8764-894af4357a3a.png">

**Comment by SemyonKuznetsov** [comment]
-[ ] 6. Visual update modals and popups #680

**Comment by AlexeyGirin** [comment]
Done.
