### ISSUE TITLE
[Critical] Not all page objects and not all new names are included to downloaded archive

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#363]
JDN v 3.1.153
Back-end v 2022-02-12-11.36.19
Chrome
(!) reproduce steps exactly

1) open https://www.behance.net/
2) open JDN tab
3) new page object
4) select HTML5 (i don't know about MUI behavior here cause of #364 )
5) generate
6) select locators and save changes
7) rename page objects to "Search"
8) repeat steps 3-6 and rename it to "SearchPage"
9) download all of them as archive
10) extract files

AR: not all page objects were included, only SearchPage page object was added

11) rename second page object to "SearcH"
12) download all

AR: SearchPage page object was included. so new name was missed

13) rename first page object to "SearCH"
14) download all

AR: only SearCH page object was downloaded in archive.... 
ER: all page objects except empty with all their new names should be included to archive and downloaded

**Comment by MariiaNebesnova** [comment]
3.1.156

**Comment by ioffem** [comment]
reopened

JDN v 3.1.156
Back-end v 2022-02-12-11.36.19
Chrome

Search and SearcH - only SearcH was included
SearCH and SearcH - only SearcH was included

i still can't see any logic.
@MariiaNebesnova  please, let me know about any specific cases if you find smth interesting.

**Comment by ioffem** [comment]
Решили не учитывать регистр и считать дубликатом все названия, которые совпадают по символам без учета регистра. То есть Search=SEARCh и так далее. Это решит все проблемы, описанные выше.

**Comment by MariiaNebesnova** [comment]
3.1.157

**Comment by ioffem** [comment]
JDN v 3.1.157
Back-end v 2022-02-12-11.36.19
Chrome

done
