### ISSUE TITLE
Plugin versions prioritization

### ISSUE THREAD

**Issue by ioffem** [jdi-testing/jdn-ai#366]
If we set several JDN versions and turn on all of them, chrome uses the last set version.
Can we add a rule to use the newest version? 

Logic:
If we set different versions and want special, we should turn off all other versions and turn on desirable. 
If more than 1 version is turned on, we should use the newest one.

**Comment by AlexeyGirin** [comment]
Есть две опции как нам справиться с этой проблемой:
1. Проверять и сообщать пользователю что несколько версий устновлено одновременно (если возможно)
2. Запускать наиболее новейшую версию (если возможно) - ПРЕДПОЧТИТЕЛЬНАЯ ОПЦИЯ

**Comment by savinovava** [comment]
Текущая проблема в основном ограничена разработчиками, так как может возникнуть только в случае установки вручную.
