### ISSUE TITLE
[1pt][US-11-1] Update context menu on page

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#37]
Привести в соответствие с дизайном
Сделать после: [#358 ](https://github.com/jdi-testing/jdn/issues/358) [#368](https://github.com/jdi-testing/jdn/issues/368)

**Comment by MariiaNebesnova** [comment]
3.0.67

**Comment by AlexeyGirin** [comment]
QA - 1pt

**Comment by MariiaNebesnova** [comment]
в меню по прежнему есть опции Change name и Change type, они уйдут с задачей #358

**Comment by pulya-na-vullet** [comment]
#358 пока не выполнена
 #368 связанных с задачей багов не обнаружил
Версия браузера 95.0.4638.69 (Официальная сборка), (64 бит)
Плагин 3.0.75
Багов связанных с текущей задачей не обнаружил
