### ISSUE TITLE
[US-7- ] Creating a custom locator (i.e. element w/locator in Locators list)

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#370]
Is it possible to add the "manually create locator" function if the program did not read the needed object? (like a button +add locator at the locator generation stage)

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7169%3A355075&t=LhzHaQONfoLXcrtU-4)
[prototype link](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=7169%3A355075&viewport=312%2C-9220%2C0.27&scaling=scale-down-width&starting-point-node-id=7169%3A355075&show-proto-sidebar=1)

upd: название окна поменяли на Create и Edit в классическом
![image](https://user-images.githubusercontent.com/101407186/201930338-907fdf8d-9942-4d3c-9e74-9f4258d7a398.png)
____
новый компонент с добавлением селекта на выбор css/xpath
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7171%3A357640&t=hBmhtnQ6qdcRJRov-4)
![image](https://user-images.githubusercontent.com/101407186/206400951-b4e84523-f94d-4236-8a0b-48fa277f47d5.png)

[US-15-3](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/21987332)

- По умолчанию создаём локатор 1 уровня в конце списка
- для некорректных или невалидных локаторов углубленный расчет (Advanced calculation) недоступен
- новый локатор добавляется в статусе selected

___
upd от 31.03
добавили текст "If you leave this field empty, the locator will be invalid" для локатор инпута
![image](https://user-images.githubusercontent.com/101407186/229126870-64a6bd07-4b41-4701-b7e2-66ee61a77373.png)

**Comment by savinovava** [comment]
It was in "SHOULD" scope. Let's define the priority.

**Comment by SemyonKuznetsov** [comment]
@savinovava I think this is an optional function, I would put low-mid priority.

**Comment by savinovava** [comment]
So let's move it after designing to the backlog

**Comment by SemyonKuznetsov** [comment]
blocking myself due to lack of ui-kit (inputs)

**Comment by SemyonKuznetsov** [comment]
Для создания локатора нужны:

![modal](https://user-images.githubusercontent.com/101407186/171110887-7441fbcb-4cdf-4ed9-9f35-1b942a579d20.png)

**Comment by SemyonKuznetsov** [comment]
1. Имя
2. Тип блока
3. Локатор

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5638%3A319073) 
[Prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=4945%3A56513&viewport=251%2C97%2C0.13&scaling=scale-down-width&starting-point-node-id=4945%3A56513)
![modal](https://user-images.githubusercontent.com/101407186/171757527-88820468-226b-4213-bf25-24c64824620c.png)

**Comment by SemyonKuznetsov** [comment]
По умолчанию создаём локатор 1 уровня в конце списка

**Comment by SemyonKuznetsov** [comment]
last visual updates
[same link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=4945%3A56513)
[same Prototype link](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=4945%3A56513&viewport=251%2C97%2C0.13&scaling=scale-down-width&starting-point-node-id=4945%3A56513)

![default](https://user-images.githubusercontent.com/101407186/174745798-ba567aae-1afc-4b14-a0b8-8283e5932fe5.png)
![modal](https://user-images.githubusercontent.com/101407186/174745807-e233d7bd-33a3-41c4-bb7e-49a33f7a8baf.png)

**Comment by MariiaNebesnova** [comment]
в какой момент отрисовываем локатор на странице? после нажатия кнопки Save?

**Comment by SemyonKuznetsov** [comment]
> в какой момент отрисовываем локатор на странице? после нажатия кнопки Save?

@MariiaNebesnova 
отрисовываем это в плане когда они появляются в списке локаторов?
тогда да, потому что до нет информации для создания, как с page object наверное не сработает

**Comment by MariiaNebesnova** [comment]
нужно ли искать новому локатору пэрента и ставить на правильное место в дереве?

**Comment by SemyonKuznetsov** [comment]
> нужно ли искать новому локатору пэрента и ставить на правильное место в дереве?

создана отдельная задача #765

> новый локатор по умолчанию в статусе Selected?

да

**Comment by savinovava** [comment]
нужно ли искать новому локатору пэрента и ставить на правильное место в дереве?
- найти в дереве можно #765 
пока оставляем в конец списка (в корень)
______
новый локатор по умолчанию в статусе Selected (включение в генерацию кода)?
- добавляем селектнутым, чтобы включить в генерацию
_____
будет ли оптимизация добавленного локатора?
- пользователь может скопировать полный xPath из Chrome Tools (?) - скорее всего будет сразу написан оптимальный
оптимизация опциональна (?): будем тригерить расчёт, если пользователь ввёл полный xPath, иначе не трогаем автоматически, но для элемента д.б. перезапустить расчёт

**Comment by SemyonKuznetsov** [comment]
> если пользователь ввел невалидный xpath, опция Advanced calculation делаем недоступной?

для некорректных или невалидных локаторов углубленный расчет недоступен

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7169%3A355075&t=LhzHaQONfoLXcrtU-4)
[prototype link](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=7169%3A355075&viewport=312%2C-9220%2C0.27&scaling=scale-down-width&starting-point-node-id=7169%3A355075&show-proto-sidebar=1)

![image](https://user-images.githubusercontent.com/101407186/201930338-907fdf8d-9942-4d3c-9e74-9f4258d7a398.png)


[component figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7171%3A357640)
![image](https://user-images.githubusercontent.com/101407186/201682913-4eb1cb92-367b-47ca-8107-ebc3009e1c24.png)

**Comment by SemyonKuznetsov** [comment]
необходимо добавить новый селект xpath/css в модальное окно создания

**Comment by savinovava** [comment]
Can be connected with: https://github.com/jdi-testing/jdn-ai/issues/780

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7171%3A357640&t=hBmhtnQ6qdcRJRov-4)

![image](https://user-images.githubusercontent.com/101407186/206400951-b4e84523-f94d-4236-8a0b-48fa277f47d5.png)

**Comment by AlexeyGirin** [comment]
Решили добавить надпись под локатором, что если он оставит это поле пустым - локатор будет невалидным
Семён - добавит

**Comment by arslanbekova** [comment]
Будем ли давать возможность пользователю добавлять кастомный локатор в режиме редактирования ПО (после того как ПО был сохранен)?

Нет покрытия => нет возможности валидировать. Можем просто  добавлять невалидный локатор в дерево.

**Comment by SemyonKuznetsov** [comment]
1. Такие локаторы валидны, но мы их не разрешаем. Надо предложить навигирование к существующему
2.

**Comment by SemyonKuznetsov** [comment]
1. Такие локаторы валидны, но мы их не разрешаем. Надо предложить навигирование к существующему
2. invalid
3. Тоже нет, локатор должен указывать на один элемент. Блокируем кнопку и говорим "xpath not unique"
4. invalid

**Comment by arslanbekova** [comment]
[3.10.439](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.439)
