### ISSUE TITLE
Remove status icon from generated locators

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#371]
as a suggestion for a cleaner UI: change the logic of status icons, empty = generated, the rest = as it was
![In progress](https://user-images.githubusercontent.com/101407186/160058646-d9e838c1-9e57-4c68-be06-3c24dea23bc7.png)

**Comment by SemyonKuznetsov** [comment]
the green "Generated" status icons have been removed on all new designs
![selected locators](https://user-images.githubusercontent.com/101407186/162859017-ffc84a42-7331-4652-8b6e-e773961465fd.png)

**Comment by MariiaNebesnova** [comment]
discussed with @SemyonKuznetsov: for current implementation, without tree, remove icons only from list and leave them in group headers.

**Comment by Aniuta907** [comment]
version: 3.1.164
