### ISSUE TITLE
[US-6-6] Deleted locators

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#372]
- [ ] visual fix
need to fix the UI, a [detailed description is here](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4948%3A68796)<img width="563" alt="Снимок экрана 2022-03-25 в 07 33 52" src="https://user-images.githubusercontent.com/101407186/160054829-9334d2e2-cde3-4e40-868a-f1bc6b450f2f.png"><img width="652" alt="Снимок экрана 2022-03-28 в 21 58 43" src="https://user-images.githubusercontent.com/101407186/160467792-3184c747-3b5e-424b-8bed-3658a4eb38aa.png">

 - [ ] New logic for the Deleted category
[Figma prototype](https://www.figma.com/proto/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?page-id=4944%3A56055&node-id=4948%3A64197&viewport=351%2C48%2C0.25&scaling=scale-down-width&starting-point-node-id=4948%3A64197) and [Figma link](https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=4948%3A64197)
The locators inside Deleted are not restored to the parent tree, but go in the order of deletion, the Deleted category itself is attached to the last locator, not to the bottom of the field, because it is not visible in the notifications and creates visual garbage. Also it is necessary to allow opening locators list and Deleted category at the same time
The locator level in the parent tree is hidden (but you cannot remove it from the characteristics, so that when you restore the locator back to its original place)
![3](https://user-images.githubusercontent.com/101407186/160468490-63404b26-904a-494d-baf9-14a34ccd3279.png)

**Comment by MariiaNebesnova** [comment]
let's move it to backlog for next release

**Comment by AlexeyGirin** [comment]
> let's move it to backlog for next release

Вопрос снимается.

**Comment by savinovava** [comment]
Как выглядит удаление invisible element? @SemyonKuznetsov

**Comment by savinovava** [comment]
Перенос изначально сгенерированного локатора после редактирования:

-  отредактированный локатор, который не указывает на элемент из списка (т.е. какой-то новый элемент), появляется на верхнем уровне в конце списка локаторов (в корень) + старый локатор остаётся на месте (аналогично с новым элементом)
_Как будем создавать дочерний элемент?_  Будет дополнительно обсуждено при имплементации функции наследования
- (JDN hash есть у всех элементов)
- если в процессе редактирования локатор указывает на новый элемент, то создаётся в корень первой нодой
- если отредактированный локатор указывает на тот же элемент, что и редактируемый, то редактируемый отображается с иконкой deleted 
1. наследуемые элементы изменяются по иерархии - желательный вариант (frontend необходимо знать, что унаследовал локатор от parent - возвращает backend)
2. наследуемые локаторы не изменяются - простая версия (решили сразу имплементировать желательный вариант)
 

Restore локаторов

Секция "Deleted"

Изменение наследования (приоритизация) локаторов
Не в приоритете

**Comment by savinovava** [comment]
Outdated https://github.com/jdi-testing/jdn-ai/issues/296

**Comment by savinovava** [comment]
Outdated https://github.com/jdi-testing/jdn-ai/issues/296
