### ISSUE TITLE
[Low]  While the extension is running error appear in console

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#379]
JDN v 3.1.157
Back-end v 2022-03-30-06.47.33
Chrome 100.0.4896.75(64 bit)

1. Open [any page](http://www.u-d-a.com/html-markup-test-page/).
2. Open DevTools and select JDN
3. Create new page object.
4. Geberate
5. Select Console in DevTools

AR:
In the console: "Uncaught (in promise) Error: The message port closed before a response was received".
In the extension log: 
![image](https://user-images.githubusercontent.com/77847287/162137464-18487730-02db-4995-8b25-34b29b4b5af5.png)
ER: No errors.

P.S. Errors do not visually affect using of the extension, or I have not found it yet.

**Comment by MariiaNebesnova** [comment]
3.1.180
