### ISSUE TITLE
[US-2-3] Сохранять сеттинги в локал сторадж

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#38]
Сейчас - изменение дефолтных настроек пропадает когда пользователе закрывает браузер или сам плагин.
Это неудобно.
Необходимо добавить сохранение глобальных настроек из Setting в локал сторадже браузера

US: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/23527447

**Comment by MariiaNebesnova** [comment]
сейчас по кнопке Clear All настройки сбрасываются. Уточнить, надо ли продолжать так делать?

**Comment by savinovava** [comment]
Насколько это актуально для следующей версии плагина? В текущем дизайне нас нет глобальных настроек, которые можно указать для дальнейшей генерации и для каждой Page Object нужно указывать свои либо пользоваться дефолтными.

**Comment by savinovava** [comment]
US-2-3 Store general settings of generation was created.

**Comment by MariiaNebesnova** [comment]
2pt - fe

**Comment by DaryaGurtovenko** [comment]
2 pt - qa

**Comment by AlexeyGirin** [comment]
Вернёмся к этой задаче когда у нас опять появятся сеттинги
