### ISSUE TITLE
[Low]Extra line breaks for xpath

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#382]
Example site https://www.behance.net/
A line break in some cases inserted at the beginning of the line.
![image](https://user-images.githubusercontent.com/77847287/162447873-cd1d4dc5-74d0-4b5c-8c8c-bfb2bf0193f0.png)

**Comment by Aniuta907** [comment]
It was fixed as part of the tasks:
https://github.com/jdi-testing/jdn-ai/issues/205
https://github.com/jdi-testing/jdn-ai/issues/371

@VSemendiy, retest please
