### ISSUE TITLE
[Critical] JSONs are creating differently for different viewports

### ISSUE THREAD

**Issue by suppnova** [jdi-testing/jdn-ai#385]
JDN v 3.1.127
Chrome

https://www.buybags.de/

The model identifies only the objects from the viewport. Probable reason is different JSONs input. 
Two screenshots and JSONs are presented below. If the whole page is visible 46 elements are identified, otherwise - only 7.

<img width="958" alt="7_items" src="https://user-images.githubusercontent.com/65091469/162634029-93d02c05-6c76-4fd2-b08d-c8acf034c8ed.PNG">

 -------------------

![46_items](https://user-images.githubusercontent.com/65091469/162634038-146f2729-1e0b-440e-9be8-3247bc25afe0.png)

**Comment by suppnova** [comment]
[7items_20220407133127777104.zip](https://github.com/jdi-testing/jdn-ai/files/8459703/7items_20220407133127777104.zip)
[46items_20220407125219555002.zip](https://github.com/jdi-testing/jdn-ai/files/8459704/46items_20220407125219555002.zip)

**Comment by MariiaNebesnova** [comment]
Everything works as designed: 
1) main content with images and buttons is inside a scrollable parent. at first picture the whole content is under scroll, so it exist in json, but filtered from prediction. at the second picture all the content isn't hided by parent, so we got with prediction.
2) this site load some extra styles and elements with viewport size change, some elements could be changed, shown or hidden

For a described case option 1 has much more influence on the result.

**Comment by AlexeyGirin** [comment]
Связаться со Славой Фуга, который выкинул невидимые элементы из распознования

**Comment by suppnova** [comment]
Вячеслав Фуга подтвердил, что элементы, находящиеся вне зоны видимости (viewport) были не выкинуты, а не добавлялись изначально. Это не баг, ("everything works as designed"), такое не было предусмотрено изначально. Необходимо обсуждение

**Comment by suppnova** [comment]
Fixed in the same way as #402
