### ISSUE TITLE
[Low] Extension not working in incognito mode

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#386]
1. Go to chrome://extensions
2. Find the extension, click Details on JDN
3. Toggle the button "Allow in Incognito" to allow the extension to run in incognito mode
4. Open any web page and try to use JDN

ER: Extension works correctly.
AR: Empti screen on JDN tab.

We need fix it or add information to RN.

![image](https://user-images.githubusercontent.com/77847287/162680097-21754979-429f-4c93-80f7-e9a3a374a9f2.png)

**Comment by Maksim-Kviatkovskii** [comment]
Not reproducing
