### ISSUE TITLE
[Medium] Menus of all Object pages open at the same time

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#387]
Create several Object Pages. It will be better to expand them all.
Click o meatball menu of one of them.
ER: The context menu of the selected page is open
AR: All context menus are opened.
![image](https://user-images.githubusercontent.com/77847287/162697190-ec8fc335-8620-4530-a9ac-a47d49678e21.png)

**Comment by Aniuta907** [comment]
version: 3.1.166

**Comment by VSemendiy** [comment]
TEsted
JDN v 3.1.166
Back-end v 2022-04-21-06.59.56
