### ISSUE TITLE
[Low] Errors in the extension log after the start of locator generation

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#390]
JDN v 3.1.162
Back-end v 2022-03-30-06.47.33

1. Open https://www.behance.net/
2. Create new Page Object and click Generate
3. In browser menu open Settings->Extensions
4. Look for errors in the extension logs.

Errors:
1. **Uncaught (in promise) Error: TypeError: Failed to fetch**
**Контекст**
devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@d9568d04d7dd79269c5a655d7ada69650c5a8336/&can_dock=true
**Трассировка стека**
main.bundle.js:2 (анонимные функции)

2. **Uncaught (in promise) Error: Error: TypeError: Failed to fetch
Контекст**
devtools://devtools/bundled/devtools_app.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@d9568d04d7dd79269c5a655d7ada69650c5a8336/&can_dock=true
**Трассировка стека**
main.bundle.js:2 (Object.post)
async chrome-extension://pcckboimcmpjcognkbianegkihgfnljg/main.bundle.js:2 (анонимные функции)
async chrome-extension://pcckboimcmpjcognkbianegkihgfnljg/main.bundle.js:2 (анонимные функции)

**Comment by MariiaNebesnova** [comment]
can't reproduce
