### ISSUE TITLE
[NR-9] Check backend availability and show warning if backend is unavailable

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#391]
Check backend availability and disable controls if backend is unavailable.
It will be good to show a warning in modal window.
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/43548673/NR-9+Backend+crush

**Comment by MariiaNebesnova** [comment]
isn't it duplicates #18 ?

**Comment by savinovava** [comment]
There is no need to disable controls

**Comment by savinovava** [comment]
Possible solutions:
**- Check after user click on a control**
- Check the availability of server
- Timer (1 min or 5 min)
