### ISSUE TITLE
[US-9-1] [Suggestion] "Report a problem" link should always be availabale

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#392]
Now it available only after locatos generation.

**Comment by savinovava** [comment]
UC
User opens plugin
WHEN User start generation
AND Plugin crashes
THEN User should be able to report a problem

**Comment by SemyonKuznetsov** [comment]
#584 есть новые иконки для новой полоски с версией

**Comment by SemyonKuznetsov** [comment]
![#392 Report a problem](https://user-images.githubusercontent.com/101407186/189838597-fae51b05-ed18-4908-8fbb-e848b9f87479.png)

**Comment by SemyonKuznetsov** [comment]
![#392 Report a problem 2](https://user-images.githubusercontent.com/101407186/189842048-9bbe1a3f-eb12-41b3-bcb9-23d0d9a338a5.png)

**Comment by AlexeyGirin** [comment]
Текст - 2000 символов максимум
Аттачменты - не более 10 файлов, не более 2мб на файл, не более 10 мегабайт на все файлы

**Comment by SemyonKuznetsov** [comment]
500px максимальная высота

![#392 Report a problem](https://user-images.githubusercontent.com/101407186/190090793-bdb36305-50a3-4f8f-bb8d-5c7e974cec5d.png)
![#392 Report a problem max size-1](https://user-images.githubusercontent.com/101407186/190090807-f85b99d6-a408-43ef-8738-04779cb510dd.png)
![#392 Report a problem max size](https://user-images.githubusercontent.com/101407186/190090818-40d10473-bfd2-4067-9031-a5f9b3417ed2.png)

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6464%3A335008)

Для инпута с почтой ограничение в 28 символов
Максимум 10 файлов для загрузки

Файлы: 1 это ховер, второй это ошибка
![#392 Report a problem max size 1](https://user-images.githubusercontent.com/101407186/190093681-35a9701a-6cd4-470e-88bd-c8088572b46b.png)
![#392 Report a problem max size 2](https://user-images.githubusercontent.com/101407186/190093685-14ccfffa-c482-4e5b-9101-88897b5dfab1.png)
![#392 Report a problem max size 3](https://user-images.githubusercontent.com/101407186/190093690-08d907e5-fdb9-4858-b690-d61187990e90.png)

**Comment by AlexeyGirin** [comment]
Отказываемся от авто аттача скриншота.
Невалидные файлы (с неразрешённым скрином) - выделяем красным и ставим в начало списка
Мыло валидируем
Правила по которым мы ограничиваем аттачменты - Семён думает, но первая идея - показывать иконку i с тултипом, но показывать хотим не все правила (хотя это и странно)

**Comment by MariiaNebesnova** [comment]
- при открытии диалога автоматом прикладываем данные страницы .json, это файл можно скачать, можно удалить без эрроров
- разрешенные расширения: image/*, *.zip, *.rar, *.json, *.txt
- невалидные файлы сортируем в начало списка, ошибку валидации показываем тултипом

**Comment by MariiaNebesnova** [comment]
sorting of invalid files wasn't implemented, It's considered as a low-priority feature and doesn't worth frontender's pain and tears of using ugly antd's components

**Comment by MariiaNebesnova** [comment]
3.2.259
