### ISSUE TITLE
[Medium] The locator disappears from the page after clicking Edit and Save without any changes.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#393]
Tested on web page which opened after redirection from https://spb.beeline.ru/customers/products/

Generation locators result
![image](https://user-images.githubusercontent.com/77847287/162969007-028031a3-3684-455b-a9cb-f5b6e4a4694f.png)

Click right mouse button on any locator and clcik Edit. Click Save without any changes. Result
![image](https://user-images.githubusercontent.com/77847287/162968940-59e05be5-2874-4586-a921-623ae209e94e.png)

**Comment by MariiaNebesnova** [comment]
3.1.181
