### ISSUE TITLE
[High] Incorrect notification after pressing Back button and starting new locators generation

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#394]
After pressing the back button, creation of a new Page Object and starting of locators generation, notifications of actions from the canceled session are displayed.

1. Open web page.
2. Create new Page object
3. Generate locators.
4. Delete them all
![image](https://user-images.githubusercontent.com/77847287/162991635-c3d43525-0e5c-49d1-9578-5a28b62b240f.png)
5. Press the Back button.
6. Repeat 1-3.
![image](https://user-images.githubusercontent.com/77847287/162991864-b7fe8e5d-62a6-4c01-a6a6-ab54f31e5060.png)

**Comment by MariiaNebesnova** [comment]
Let's remove progress bar too

**Comment by Aniuta907** [comment]
version: 3.1.168
