### ISSUE TITLE
[Medium]The locator editing form opens simultaneously in two windows.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#398]
JDN v 3.1.162
Back-end v 2022-03-30-06.47.33

1. Open two Chrome windows
2. Open the same page in both
3. In the right window, open JDN and generate locators
4. Open JDN in the left window and close it.
5. In the right window select any locator and edit it.

ER: An editing dialog has opened in the right window. The left one doesn't.
AR: Edit dialog opened in both windows.

![image](https://user-images.githubusercontent.com/77847287/163537767-f6debe01-2ba7-46c4-9e89-aece6727926d.png)

**Comment by MariiaNebesnova** [comment]
now we allow to work with plugin in only one window
