### ISSUE TITLE
[Low] when highlighting locators on a page, page styles can be intercepted.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#401]
JDN v 3.1.162
Back-end v 2022-03-30-06.47.33

When highlighting locators on a page, page styles can be intercepted.
Example of html file I used to reproduce it in the attachment.
Result:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/77847287/163767124-8a68b72f-6e03-4f31-b32d-b8656f0e6581.png)

[3.zip](https://github.com/jdi-testing/jdn-ai/files/8504035/3.zip)

**Comment by MariiaNebesnova** [comment]
[3.7.389](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.389)
