### ISSUE TITLE
[Critical]The number of locators depends on the page size

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#402]
JDN v 3.1.162
Back-end v 2022-03-30-06.47.33
Example of html I used to reproduce it in the attachment [3.zip](https://github.com/jdi-testing/jdn-ai/files/8504077/3.zip)
Screenshots with error (there are three locators on the first and two on the second)
![image](https://user-images.githubusercontent.com/77847287/163767995-c959c176-4062-4fa6-8fbb-0efbd1a40733.png)
![image](https://user-images.githubusercontent.com/77847287/163768065-7b81ed1e-c150-48fc-8c97-2ecbc00d6f90.png)

**Comment by suppnova** [comment]
Проверка работы MUI-модели на страничке с html объектами не совсем корректна, стоит доработать кейс. 
html5-модель в данном случае работает одинаково вне зависимости от размера окна.

**Comment by VSemendiy** [comment]
https://cjc8ic.csb.app/
По этой ссылке полностью прогружаются три кнопки.
Если в момент генерации локаторов видны все три, то возвращается два локатора, соответствующих первой и последней кнопке.
![image](https://user-images.githubusercontent.com/77847287/165451783-d5c48771-54b7-4564-83b5-65019bf44f88.png)
Если изменить размер окна так, чтобы были видны две кнопки, не важно первая и вторая или вторая и третья, то локатор вернется только для первой.
![image](https://user-images.githubusercontent.com/77847287/165452132-082ebbb7-56b7-4887-af81-57f69ad1d181.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/77847287/165452260-3b3c03d7-a588-48b9-a964-7305742cb48b.png)

**Comment by suppnova** [comment]
Excluding hidden elements functionality removed. Model retrained and updated
