### ISSUE TITLE
[Critical] Не работает максимайз виндоу при распознавании

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#408]
...

**Comment by suppnova** [comment]
maximize_window на данный момент не используется в проекте, только в тестовых ноутбуках. Работает для сгенерированных и наших тестовых сайтов, для некоторых валидационных (e. g. [buybags ](https://www.buybags.de/)) - нет.
Мы могли бы использовать подобный подход (масштабирование и скроллинг) для распознавания элементов за пределами видимости?

**Comment by suppnova** [comment]
(!) На данный момент нет функционала для распознавания элементов за пределами viewport. Это не баг, такое не было предусмотрено изначально. Необходимо обсуждение

**Comment by AlexeyGirin** [comment]
Closed since not actual any more
