### ISSUE TITLE
[High] Разобраться с временем расчёта локаторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#412]

**Comment by rrr3try** [comment]
Есть случаи когда ограничение по времени не работает точно и возможно ухудшает в целом возможности алгоритма, тк таймер проверяется только при итерации по возможным локаторам( некоторые из них рассчитывались локально до 40 секунд) получается вместо проверки всех возможных с ограничением по времени каждого, проверяется единственный дольше ограничения и при следующей итерации останавливается
