### ISSUE TITLE
[High] Allow plugin work with local html

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#417]

**Comment by MariiaNebesnova** [comment]
dev notes: edit `host_permissions` to enable work with local files
useful links: https://developer.chrome.com/docs/extensions/mv3/declare_permissions/
https://developer.chrome.com/docs/extensions/mv3/match_patterns/

**Comment by Aniuta907** [comment]
version: 3.1.171
