### ISSUE TITLE
[Medium] JDN does not generate locators for some buttons

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#419]
JDN v 3.1.171
Back-end v 2022-04-28-11.47.36

- disabled (In version 4.12 MUI Buttons without children <span> not implemented). Currently, **test cases should be done in MUI 4.12**. 
- [x] alarm (MuiIconButton-root, MuiSvgIcon-root, MuiTouchRipple-root)
- [x]  fingerprints (MuiIconButton-root)
- bootstrap (MuiButton-root without children **not implemented in version 4.12 MUI**)
- MuiLoadingButton-root (**In version 4.12 MUI Loading Buttons are not implemented**)
- [x] breakfast/burgers (recognized as link, it is not a button, right?)
     - [x] retrain model

Examples:
https://cjc8ic.csb.app/
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/77847287/165453157-fd77d0ed-61f5-4d8c-ba75-8275a1d2dc22.png)

https://35ehf7.csb.app/
![image](https://user-images.githubusercontent.com/77847287/165452935-d44775ea-d659-4f8a-80bf-273949b96d6b.png)

https://6dvjw4.csb.app/
![image](https://user-images.githubusercontent.com/77847287/165453588-ea86e2cb-f855-4e68-a71d-22b8217eb28a.png)

https://242p99.csb.app/
![image](https://user-images.githubusercontent.com/77847287/165454157-78972f67-7a31-4ec5-a6c7-1db6abbe08c1.png)

https://oti50e.csb.app/
![image](https://user-images.githubusercontent.com/77847287/165454506-4b0d9439-7e12-4162-9c27-68d653ee823c.png)

https://6swktb.csb.app/
![image](https://user-images.githubusercontent.com/77847287/165455494-d6655648-8226-447c-8971-43e7ab53f363.png)

**Comment by suppnova** [comment]
JDN v 3.1.171
Back-end v 2022-04-28-11.47.36

- [ ] (?) disabled (should be recognized?)
- [ ] alarm (MuiIconButton-root, MuiSvgIcon-root, MuiTouchRipple-root)
- [ ] fingerprints (MuiIconButton-root)
- [ ] bootstrap (MuiButton-root without children, parent - css-e53awj-MuiStack-root)
- [ ] loading buttons (MuiLoadingButton-root)
    - [ ] check progressbarSpan as separate element (?) (MuiLoadingButton-loadingIndicator)
- [ ] breakfast/burgers (recognized as link, it is not a button, right?)

**Comment by AlexeyGirin** [comment]
LoadingButton выделяем в отдельную задачу (т.к. требуется изменение генератора страничек для модели)
а остальные пункты решаем в рамках этой задачи
