### ISSUE TITLE
[Medium] JDN does not generate locators for some autocomplete components

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#420]
- [x] add (SELECT?) MuiAutocomplete-root into generator - YES, it's a SELECT
- [x] retrain model

Examples:
https://77eo6q.csb.app/

**Comment by suppnova** [comment]
Currently this object is detected as button and textfield. I'm sure it's wrong recognition. Should it be SELECT class?
![image](https://user-images.githubusercontent.com/65091469/165950800-177991e5-3e1a-4eba-b74c-55057d5cd4c1.png)
