### ISSUE TITLE
[US-18-1] Add select locator functionality to Locators tree

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#426]

**Comment by SemyonKuznetsov** [comment]
I need to check the logic of checkboxes in the tree

**Comment by SemyonKuznetsov** [comment]
[checkboxes figma prototype link](https://www.figma.com/proto/mVVywBvAaJDa0QmDROQJFB/%F0%9F%8E%A8-UI-Kit-(JDN)?page-id=25%3A3871&node-id=135%3A7335&viewport=-97%2C182%2C0.43&scaling=min-zoom&starting-point-node-id=135%3A7335)

**Comment by SemyonKuznetsov** [comment]
visual update: 
checkboxes moved closer to the text for visual unity
![2](https://user-images.githubusercontent.com/101407186/168163779-5b6700b0-bf69-46d7-9240-b39c1812f939.png)


description of the logic of using checkboxes
<img width="507" alt="Снимок экрана 2022-05-12 в 23 42 21" src="https://user-images.githubusercontent.com/101407186/168164438-9a9497fd-8b40-4e8b-a21a-4e9d29591036.png">

**Comment by MariiaNebesnova** [comment]
3.1.183
