### ISSUE TITLE
[US-7-2] [E-18] Rework Edit locator

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#427]
US: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12877879/US-7-2+User+can+edit+locators+manually
Design: https://www.figma.com/file/mVVywBvAaJDa0QmDROQJFB/%F0%9F%8E%A8-UI-Kit-(JDN)?node-id=3%3A44
Dependencies: https://github.com/jdi-testing/jdn-ai/issues/296#issuecomment-1110938344

**Comment by MariiaNebesnova** [comment]
для отредактированных generated мы показываем иконки edited?
https://www.figma.com/file/BVIiVfeuQfQuD1fi7HP99K/JDN-(v.2)?node-id=3284%3A216900

**Comment by AlexeyGirin** [comment]
Семён соберёт иконки и их описание и от этого будем идти. Что бы всё выглядело логично

**Comment by AlexeyGirin** [comment]
Решили:
1. Избавляемся от Waiting for generation
2. Если пользователь вводит локатор который указывает на друго элемент с другим JDN Hash то мы запрещаем его сохранять
3. Если пользователь вводит неправильный (мусорный локатор) - то мы разрешаем такое сохранять

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/mVVywBvAaJDa0QmDROQJFB/%F0%9F%8E%A8-UI-Kit-(JDN)?node-id=3%3A44)
<img width="814" alt="Снимок экрана 2022-05-12 в 11 50 32" src="https://user-images.githubusercontent.com/101407186/168031497-98a0cb09-b40e-45ab-93ca-6e9bd8dc1308.png">

**Comment by AlexeyGirin** [comment]
Галочка с карандашиком остаётся только для случая когда был отредактирован локатор что бы пользователь понимал.

**Comment by MariiaNebesnova** [comment]
also fixed #393 , #331

**Comment by MariiaNebesnova** [comment]
3.1.181
