### ISSUE TITLE
[US-6-6][E-18]Delete/restore locators, single and multiple

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#439]
Section "Deleted" should be removed
US: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910696/US-6-6+Delete+elements+from+generation
Design: 
Connected task: https://github.com/jdi-testing/jdn-ai/issues/317

**Comment by SemyonKuznetsov** [comment]
Решили что иконки статусов не активны

**Comment by SemyonKuznetsov** [comment]
[Figma prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=5513%3A314690&viewport=249%2C-3123%2C0.42&scaling=min-zoom&starting-point-node-id=5513%3A314690)
[Figma design](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5513%3A314690)

**Comment by SemyonKuznetsov** [comment]
Почему мы не используем белые модалки из фреймворка? И насколько это трудозатратно?
[Link to modal in ant.framework](https://ant.design/components/modal/)
![7](https://user-images.githubusercontent.com/101407186/169240028-8cc4e2ae-20b6-4a1a-a4ce-a25db336ea44.png)

Если переделывать, то придётся приводить к киту и фремворку вот эти все модалки:
<img width="475" alt="Снимок экрана 2022-05-19 в 10 52 41" src="https://user-images.githubusercontent.com/101407186/169241887-0394676b-1712-4c52-9f95-4c86dd443191.png">

Где-то 4-5 модальных и контекстное меню, текстареа. На анте есть готовые элементы.

**Comment by SemyonKuznetsov** [comment]
Решили перенести на следующий релиз

**Comment by AlexeyGirin** [comment]
Решили - всё переделать на ант (что бы было проще), но не в этом релизе

**Comment by MariiaNebesnova** [comment]
3.1.187
