### ISSUE TITLE
[0.5pt]Проверить взятие бэкэнда из нового места

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#44]

**Comment by savinovava** [comment]
#28 
Проблема создания окружения
[0.5pt] QA

**Comment by toshQA** [comment]
Verified for versions: JDN v 3.0.68
Back-end v 2021-11-02-06.53.28

In general works correctly, reported defect:
https://github.com/jdi-testing/jdn-ai/issues/50

Close this one.
