### ISSUE TITLE
[US-6-3][E-18] Increase Calculation Priority option menu

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#440]
US: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/17956865/US-6-3+Prioritize+the+generation+of+elements
Design:

**Comment by savinovava** [comment]
https://github.com/jdi-testing/jdn-ai/issues/296#issuecomment-1112961617
**Юзер хочет поставить приоритет генерации:**
- Один локатор -> Митболс меню ( это которое ···) -> задать приоритет  -> выбор приоритета (сколько приоритетов может быть?)
![image](https://user-images.githubusercontent.com/101407186/165871011-66fcc644-6eb5-4169-ac57-0b8e6eb66451.png)
- Выделение нескольких локаторов -> ? верхняя навигация, кнопки для действий с несколькими объектами

**Вопросы:**

>1.  3 уровня приоритета достаточно? высокий - средний (по умолчанию) - низкий

Два уровня - высокий и по умолчанию

3. Есть возможность вызова кастомного меню через ПКМ по локатору, например, или там по умолчанию браузерное

**Comment by SemyonKuznetsov** [comment]
[Prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=5566%3A317549&viewport=365%2C-1433%2C0.16&scaling=min-zoom&starting-point-node-id=5566%3A317549&hide-ui=1)

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5566%3A317549)
![US-6-3 E-18  Increase Calculation Priority option menu](https://user-images.githubusercontent.com/101407186/169899442-4b32e6f3-1166-4991-85bf-2498a7a5ca87.png)

<img width="338" alt="Снимок экрана 2022-05-23 в 23 23 37" src="https://user-images.githubusercontent.com/101407186/169899926-1e6383da-c685-4787-916f-d879261fb63e.png">

**Comment by SemyonKuznetsov** [comment]
Через чекбоксы:

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5571%3A319179)
[Prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=5571%3A319179&viewport=365%2C-1433%2C0.16&scaling=scale-down-width&starting-point-node-id=5566%3A317549)

![with checkboxes](https://user-images.githubusercontent.com/101407186/169902789-7cf698b1-eb81-4dea-a307-a7de56570ae0.png)

**Comment by MariiaNebesnova** [comment]
controls are hidden for release 3.2

**Comment by MarinaFm** [comment]
Checked: Controls 'Up priority/Down priority' are hidden in v 3.1.216
