### ISSUE TITLE
[Low] All POs but one minimize, when I click on kebab-menu

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#442]

**Comment by VSemendiy** [comment]
JDN v 3.1.179
Back-end v 2022-05-06-09.10.09

1. Create several POs.
2. Maximize them.
3. Click on kebab-menu of one of them.

ER: Menu is opened. And nothing else.
AR: Menu is opened and all but one POs are minimized.
![1](https://user-images.githubusercontent.com/77847287/168252467-303b8039-ecff-4b9e-a572-ae75b1eafef5.gif)

**Comment by MariiaNebesnova** [comment]
3.1.195
