### ISSUE TITLE
Visual improvement / replacement of locator icons

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#446]

**Comment by SemyonKuznetsov** [comment]
[Figma Icons Library](https://www.figma.com/file/mVVywBvAaJDa0QmDROQJFB/%F0%9F%8E%A8-UI-Kit-(JDN)?node-id=3%3A44)

<img width="309" alt="Снимок экрана 2022-05-17 в 10 53 39" src="https://user-images.githubusercontent.com/101407186/168759122-d998dccf-5b29-4717-837b-3ac98661261d.png">

**Comment by SemyonKuznetsov** [comment]
[Figma Locators list screen]
(https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5406%3A313755)
![Locators list](https://user-images.githubusercontent.com/101407186/168759510-aab9646b-c7ba-4ca4-8d1c-b38b08942130.png)

**Comment by SemyonKuznetsov** [comment]
@savinovava завёл новую задачу под #427 для визуальных улучшений

**Comment by MariiaNebesnova** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/82033805/170645131-0effde3e-5593-4fb7-b242-d589140848ad.png">

**Comment by MariiaNebesnova** [comment]
3.1.183
