### ISSUE TITLE
[Low] Visual improvement of the locator list

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#447]
Visual improvement of the locator list to increase the space by reducing the height of the string (replacing the styles text1 -> text2) and adding the Display option.

<img width="759" alt="Снимок экрана 2022-05-17 в 11 12 36" src="https://user-images.githubusercontent.com/101407186/168762808-9c2a4b2b-6d36-4ce1-9fb9-1aecf00d7163.png">

[Figma link on example](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5461%3A313682)

[Prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=5406%3A313755&viewport=-49%2C-4044%2C0.63&scaling=min-zoom&starting-point-node-id=4945%3A56513)

**Comment by SemyonKuznetsov** [comment]
@savinovava тоже новая, тоже улучшение, но эта с низким приоритетом

**Comment by MariiaNebesnova** [comment]
3.2.244

**Comment by MariiaNebesnova** [comment]
3.2.246
