### ISSUE TITLE
[1.5pt][US-6-6] Функционал восстановления удаленных локаторов некорректно работает при выделении локаторов с разных вкладок

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#45]
JDN v 3.0.66
Back-end v 2021-09-28-08.31.54

Шаги:
- Выделяю 2 локатора 
- нажимаю Delete
- они остаются выделеные + выделяю еще один с вкладки сгенерированных
- нажимаю Restore
- восстанавливаются не все локаторы с вкладки deleted 
- нажимаю еще раз restore - часть локатор падает снова в Deleted

**Comment by savinovava** [comment]
[1pt] - front
[0.5pt] - QA

**Comment by MariiaNebesnova** [comment]
3.0.70

**Comment by lisatatarinova** [comment]
test passed JDN v 3.0.82
Back-end v 2021-09-28-08.31.54
