### ISSUE TITLE
[Medium]Из выделенных локаторов на паузу ставятся только те, что генерируются в данный момент.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#452]
1. Запустить генерацию локаторов
2. Выделить весь список waiting for generation и остановить генерацию для выделенных элементов.

ОР: На паузе весь список Waiting for generation
ФР: Приостановлены только те элементы из выделенных, которые расчитывались в момент остановки, остальные выделенные продолжают расчитываться.

**Comment by MariiaNebesnova** [comment]
нужна ручка, которая позволит тормозить на бэкенде все, что есть у него в очереди, т.к. клиент не может остановить локаторы, которые еще не начали считаться, т.е. не вернули на клиент свой номер таски

**Comment by AlexeyGirin** [comment]
Фёдор дорабатывает бэк и возвращает её Маше

**Comment by MariiaNebesnova** [comment]
3.1.196

**Comment by VSemendiy** [comment]
На 3.1.196 проблема воспроизводится.
Выделил список сразу после того, как он был построен.
Поставил на паузу и понаблюдал - через несколько секунд снова появилась кнопка постановки на паузу. Прокрутил список вниз - обнаружил локаторы, которые в процессе расчета.
И так несколько раз подряд.
