### ISSUE TITLE
[High] Пропал элемент реализующий функцию Select all

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#456]
JDN v 3.1.184
Back-end v 2022-05-25-08.44.15

Пропал элемент реализующий функцию Select all
![image](https://user-images.githubusercontent.com/77847287/170964293-b639c0c5-e7a5-4e4c-a459-cd73660ff8b1.png)

**Comment by SemyonKuznetsov** [comment]
![default](https://user-images.githubusercontent.com/101407186/172115893-18149ee1-cf7a-4c10-bf40-9f43d0e085c1.png)

**Comment by MariiaNebesnova** [comment]
3.1.191
