### ISSUE TITLE
[Suggestion] Не хватает функций collapse all и expand all для дерева.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#457]
Не хватает функций collapse all и expand all для дерева.

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5667%3A320170)
[Prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=4944%3A56055&node-id=5667%3A320170&viewport=433%2C-8827%2C0.7&scaling=scale-down-width&starting-point-node-id=5667%3A320170)
![Collapse all](https://user-images.githubusercontent.com/101407186/172387017-46637a1e-5743-43c9-aace-3ad6d951713c.png)
![Expand all](https://user-images.githubusercontent.com/101407186/172387026-91fa5649-87e6-4ba6-b8ee-42ffab006385.png)

comment: if at the initial stage something is already collapsed, then clicking on the icon will collapse everything, when you click again it will expand everything, including what was initially collapsed

**Comment by SemyonKuznetsov** [comment]
design task: when hovering over it, it should show an explanation. or "expand all" or "collapse all"

**Comment by MariiaNebesnova** [comment]
3.1.192
