### ISSUE TITLE
[High] Удаленные элементы никак не отличаются от неудаленных в списке локаторов.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#459]
JDN v 3.1.184
Back-end v 2022-05-25-08.44.15

Выделить элементы и удалить их.
Удаленные элементы никак не отличаются от неудаленных в списке локаторов. При этом выделение снимается и всякое отличие уже невозможно.

**Comment by MariiaNebesnova** [comment]
все так, задача #439 еще не реализована

**Comment by MariiaNebesnova** [comment]
3.1.187
