### ISSUE TITLE
[US-5-5] Натренировать модель на распознавание Bootstrap элементов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#461]
Описание элементов тут - https://jdi-docs.github.io/jdi-light/#3-1-bootstrap-common-elements
Eхamples: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/26673168/Bootstrap+examples
- [x] https://github.com/jdi-testing/jdn-ai/issues/469
- [ ] https://github.com/jdi-testing/jdn-ai/issues/474

**Comment by suppnova** [comment]
html-5 модель достаточно хорошо себя показывает при распознавании элементов bootstrap.
https://jdi-testing.github.io/jdi-light/bootstrap-new.html
![image](https://user-images.githubusercontent.com/65091469/171176174-61667f5f-1e88-4bf6-8a3f-020f1e7eb3d4.png)

После закрытия задачи #163 предлагаю оценить объем полноты распознавания и выявить недостающие элементы, если таковые будут (сейчас их очень мало).

**Comment by AlexeyGirin** [comment]
Создать отдельную модель для Бутстрапа, передать эстфету Фёдору что бы он сделал руку, передать эстафету Маше что бы она сделала мэпинг

**Comment by suppnova** [comment]
https://github.com/jdi-testing/jdi-qasp-ml/pull/41

Создана отдельная функция для bootstrap_predict, передаю Федору

**Comment by AlexeyGirin** [comment]
Эстафета передана Маше для деланья мэпинга для бутстрап элементов

**Comment by MariiaNebesnova** [comment]
after #469

**Comment by savinovava** [comment]
Со стороны JDI не подготовлены классы.

**Comment by savinovava** [comment]
Переход на рулы
