### ISSUE TITLE
MUI v.4 Add elements to the generator

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#468]
- [ ] Modal https://jdi-testing.github.io/jdi-light/material/modal - решили не добавлять
- [x] Alert https://jdi-testing.github.io/jdi-light/material/alert
- [x] Card https://jdi-testing.github.io/jdi-light/material/card_surface
- [x] Complex buttons with pictures https://jdi-testing.github.io/jdi-light/material/buttons

https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/35553284/Element+s+table

**Comment by suppnova** [comment]
What classes should be predicted and mapped for modal, alert, card?
Should we add new classes into https://github.com/jdi-testing/jdi-qasp-ml/blob/develop/data/mui_dataset/classes.txt ?

**Comment by MarinaFm** [comment]
Лежит в ветке add_new_classes, не в релизной ветке
