### ISSUE TITLE
[1pt]Design review

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#47]
**Визуальные правки:**

- [x] Вкладка Deleted  - отображается с иконкой с закрытым глазом, а должна быть с корзиной. 
- [x] Подсветка локаторов при выделении (голубой и серый фон) не отображается на всю строку
- [ ] Все тултипы с разными шрифтами, размером, междустрочным расстоянием. Можно ли все привести к одному виду?   

Все правки рассписаны в ссылке в фигме со скриншотами как есть/и как нужно и подробным описанием:
https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=3578%3A72364

**Comment by MariiaNebesnova** [comment]
3 пункт - задача #74

**Comment by Dashnik** [comment]
Первый два пункта выполнены и готовы к просмотру в билде 79 и выше.

**Comment by pulya-na-vullet** [comment]
Plugin version JDN v 3.0.83
Back-end v 2021-11-01-06.14.14

bug doesn't repeat

https://user-images.githubusercontent.com/61897393/143185317-d26aa62f-0762-4326-bac6-090553f94821.mp4
