### ISSUE TITLE
[Low]Некорректно работает Cancel на уведомлении о приостановке генерации.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#477]
Открыть web-страницу.
Начать генерацию локаторов. 
Выделить все локаторы в процессе генерации и приостановить генерацию.
На всплывшем в нижней части экрана уведомлении нажать Cancel.

Ожидается: Генерация продолжилась, локаторы в дереве не промаркированы как приостановленные.
Фактически: Появляется уведомление Action canceled, генерация части локаторов продолжается, часть локаторов отмечены как приостановленные.

**Comment by MariiaNebesnova** [comment]
со стороны фронтенда неработающий код поправлен - 3.1.196.
но обнаружилось некорректное поведение на бэкенде:
остановили расчет локатора, запустили его расчет заново, но в ответ получаем только статус REVOKED. локатор в результате так и не рассчитался. вся последовательность сокет сообщений видна на скриншоте:
![image](https://user-images.githubusercontent.com/82033805/174733296-3048d5bc-c890-40f2-a43b-6aa89c4b858e.png)

**Comment by VSemendiy** [comment]
@AlexeyGirin  Думается, на этом основании приоритет можно поднять до высокого.
