### ISSUE TITLE
[US-6-1] Зафиксировать вкладки и нотификации внизу локатор листа

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#48]
Вкладки Generated, Waiting for genereting, Currently invisible on the page, Deleted, а также строку нотификации, при их наличии на странице и скроле, зафиксировать внизу локатор листа.

**Comment by marusyaganza** [comment]
https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=3578%3A72364

**Comment by savinovava** [comment]
@marusyaganza укажи pt, затраченные на разработку, пожалуйста, в комментариях
@DaryaGurtovenko оцени, пожалуйста, в комментариях

2pt =1 рабочий день

**Comment by MariiaNebesnova** [comment]
3pt - fe

**Comment by marusyaganza** [comment]
implemented in version 3.0.76

**Comment by pulya-na-vullet** [comment]
Текущая реализация на версии
JDN v 3.0.75
Back-end v 2021-11-01-06.14.14
Работает корректно. Верстка не едет 
Пример:
![image](https://user-images.githubusercontent.com/61897393/142574132-0030a993-54fb-4614-b503-43d10d91c383.png)
