### ISSUE TITLE
Components update

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#486]
1. - [x] Typography review
synchronize with the design, possibly apply to Font-weight +Dispaly

2. - [x] Icons review
Ideally, the size of the icon should be equal to the size of the text

3. - [x] upgrade in front
Buttons - disabled buttons look different, visual suggestion
synchronize with the Ant.design
dark theme colors

4. - [x] upgrade in figma
Dropdown
Textarea
Notification
Modal

**Comment by SemyonKuznetsov** [comment]
![buttons](https://user-images.githubusercontent.com/101407186/174675387-cb650413-460b-435a-90bc-75897d2f9707.png)
![inputs](https://user-images.githubusercontent.com/101407186/174675388-8c658c0d-28af-4e0d-ba55-3d145fd123e7.png)

даже если мы не берём во внимания различия в цвете и ротацию по цвету в состояниях default-hover, у компонентов есть критические различия (на примерах) какие из них мы будем соблюдать и менять в дизайне, а какие можно игнорить? или мы идём в полное соответствие с фреймворком и так будет проще?

**Comment by AlexeyGirin** [comment]
Решили что переходим на антовские элементы в дизайне. Подозреваем что будез запарно, но это в будущем упростит много. Сейчас начинаем копировать то, что у фрэймворка в наш дизан

**Comment by SemyonKuznetsov** [comment]
Обсудили, что оставляем компоненты анта такими, какие они есть. После обновления дизайна, при необходимости, будем менять размеры шрифтов (например)

**Comment by SemyonKuznetsov** [comment]
Обновление иконок

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6283%3A331127)

<img width="247" alt="Снимок экрана 2022-09-02 в 12 16 32" src="https://user-images.githubusercontent.com/101407186/188107187-8ae1c81a-0b76-4f84-a95f-54b531ae2494.png">

**Comment by MariiaNebesnova** [comment]
Buttons, Inputs and Icons are updated

**Comment by MariiaNebesnova** [comment]
[3.2.270](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.270)

**Comment by Maksim-Kviatkovskii** [comment]
В целом ок, расхождения с макетом вынесены в https://github.com/jdi-testing/jdn-ai/issues/680
