### ISSUE TITLE
[US-6-4] Скрол до нужного локатора при выделении локатора на покрытии

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#49]
Сейчас при клике на покрытии локатор подсвечивается в локатор листе. Но если он находится вне зоны видимости на данный момент - нам нужно скролить страницу / открывать вкладки и искать где подсветилось.

Можно ли сделать, чтоб плагин автоматически скролился в локатор листе до нужного локатора при выделении? И наоборот?

**Comment by marusyaganza** [comment]
fixed in version 3.0.74

**Comment by savinovava** [comment]
@marusyaganza укажи pt, затраченные на разработку, пожалуйста, в комментариях
@DaryaGurtovenko оцени, пожалуйста, в комментариях

2pt =1 рабочий день

**Comment by savinovava** [comment]
@marusyaganza оцени задачу, пожалуйста, в комментариях
@DaryaGurtovenko оцени тестирование, пожалуйста, в комментариях

**Comment by pulya-na-vullet** [comment]
Автоскрол при выделении локатора работает корректно.
JDN v 3.0.75
Back-end v 2021-11-01-06.14.14
сайт  mail.ru

**Comment by savinovava** [comment]
fe = 4pt
