### ISSUE TITLE
[Low] Поставленные на паузу локаторы отмечаются разными иконками.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#491]
Открываем https://shiftbrain.com/about/?lang=en
Начинаем генерацию и ставим на паузу для всех локаторов.

Смотрим на иконки. Локаторы корневого уровня без дочерних элементов отмечены иконкой с двумя полосками. Локаторы с дочерними элементами и локаторы некорневого уровня отмечены иконкой с квадратом. 
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/77847287/175505617-145e690e-3b7f-4abe-a00a-f0c0ea232d89.png)

**Comment by MariiaNebesnova** [comment]
@VSemendiy какое разрешение монитора ты изпользуешь? плагин в отдельном окне или в окне страницы?

**Comment by MariiaNebesnova** [comment]
наблюдаю небольшое размытие иконок при  такой настройке дисплея: 
![image](https://user-images.githubusercontent.com/82033805/176123400-cde0a7c9-7652-4a72-8e5c-1eba87155abb.png)
![image](https://user-images.githubusercontent.com/82033805/176123632-7e133f62-0c9f-4c15-8aa3-903775e82a38.png)


при этом на дисплее ноутбука все предельно четко

**Comment by MariiaNebesnova** [comment]
3.1.202

**Comment by MariiaNebesnova** [comment]
it's might be blurry, but there's a lot of work to fix it now. check if it's clearly readable at least

**Comment by MarinaFm** [comment]
Открываем https://discoverlexus.com/stories/
Начинаем генерацию ->ставим на паузу Locator List -> смотрим размер иконок паузы.
ФР: Иконки имеют разный размер 
![image](https://user-images.githubusercontent.com/88709848/177194127-3f12422a-caed-4062-91e8-303e9ef61390.png)

**Comment by MariiaNebesnova** [comment]
3.1.205
