### ISSUE TITLE
[Low] При постановке генерации на паузу продолжаем отображать уведомление Locators generation is running in background.

### ISSUE THREAD

**Issue by VSemendiy** [jdi-testing/jdn-ai#492]
JDN v 3.1.196
Back-end v 0.1.12022-06-23-10.36.50

Открываем любую страницу и начинаем генерацию, ставим её на паузу и немного ждем.

ПО таймауту исчезает уведомление о постановке на паузу. При этом уведомление о том, что генерация идет в фоне, остается. ВОзникает некоторый диссонанс между написанным и действительно происходящим. О текущем статусе говорят только иконки в списке и кнопка запуска генерации.
![image](https://user-images.githubusercontent.com/77847287/175510121-5058d2ba-1a10-4884-82e3-8bbeb23ae7ad.png)

**Comment by savinovava** [comment]
Can't be reproduced
