### ISSUE TITLE
500 error when opening http://localhost:5000/files

### ISSUE THREAD

**Issue by toshQA** [jdi-testing/jdn-ai#50]
JDN v 3.0.68
Back-end v 2021-11-02-06.53.28

Steps:
1. Open http://localhost:5000/files

Expected result: site is successfully opened
Actual result: there is 500 error

**Comment by MariiaNebesnova** [comment]
https://github.com/jdi-testing/jdi-qasp-ml/commit/c55ed0fbf634e1e033ab1b72b4a68f824c5cca94
