### ISSUE TITLE
[US-1-2] Add plugin to Google Chrome extensions

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#504]
https://support.google.com/chrome/a/answer/2714278?hl=ru

**Comment by MariiaNebesnova** [comment]
Requirements from Developer Dashboard:

- [ ]  At least one screenshot or video is required.
- [ ]  You must verify your contact email before you can publish any item. Begin the verification process on the Account tab.
- [ ] Icon image is missing.
- [ ] A justification for scripting is required. This can be entered on the Privacy practices tab.
- [ ] The single purpose description is required. This can be entered on the Privacy practices tab.
- [ ] You must provide a contact email before you can publish any item. Enter your contact email on the Account tab.

**Comment by MariiaNebesnova** [comment]
![image](https://user-images.githubusercontent.com/82033805/181046861-07c1d08e-60f7-438f-83ed-2c2a3634c12a.png)

**Comment by MariiaNebesnova** [comment]
#562

**Comment by AlexeyGirin** [comment]
Done.
