### ISSUE TITLE
[E-18] Оптимизация дерева

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#506]
Performance of interface

- [x] #505 Происходит из-за того, что backend работает локально на ПК, возможен фикс после переноса на сервер
- [x] https://github.com/jdi-testing/jdn-ai/issues/424

- [x] Вынуждены оперировать большим количеством элементов - оптимизация компонента дерева.

**Comment by MariiaNebesnova** [comment]
[3.3.288](https://github.com/jdi-testing/jdn-ai/releases/tag/3.3.288)

**Comment by AlexeyGirin** [comment]
Closed due to Maksim's request
