### ISSUE TITLE
Testing on real data

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#507]
Tестирование на реальных данных:

Имеющимся скриптом выкачиваем парсинг HTML на объекты → на выходе датафреймы → разметка ручная для добавления label (https://github.com/jdi-testing/jdi-qasp-ml/blob/develop/data/mui_dataset/classes.txt)

Решение с фронтенда

Meeting notes: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/42827777/04072022+Metrics

Таким образом - нужно сделать следующее:
1. Найти 10 сайтов написанных на HTML5 (желательно - небольших)
2. Для каждого сайта посчитать метрику Accuracy ([ссылка](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/42827777/04072022+Metrics#Accuracy)).

**Comment by AlexeyGirin** [comment]
Список страничек на которых тестировать - взять у Василия Семендия (связаться с ним по скайпу)
