### ISSUE TITLE
Импорты в результирующих файлах должны зависить от выбранной модели для распознования элементов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#509]
Сейчас в артефактах используется следующие импорты:
package net.creativegigs.html.pages;
import com.epam.jdi.light.elements.pageobjects.annotations.locators.*;
import com.epam.jdi.light.elements.composite.*;
import com.epam.jdi.light.elements.complex.*;
import com.epam.jdi.light.elements.common.*;
import com.epam.jdi.light.elements.complex.dropdown.*;
import com.epam.jdi.light.elements.complex.table.*;
import com.epam.jdi.light.ui.html.elements.complex.*;
import com.epam.jdi.light.ui.html.elements.common.*;
import net.creativegigs.html.sections.*;

Это не совсем корректно.
Для любой элемент лайбрари - должен быть следующий **обязательный блок**:
import com.epam.jdi.light.elements.pageobjects.annotations.locators.\*;
import com.epam.jdi.light.elements.composite.\*;
import com.epam.jdi.light.ui.html.elements.common.\*;

Далее для **HTML5 нужно добавлять**:
import com.epam.jdi.light.elements.complex.\*;
import com.epam.jdi.light.elements.common.\*;
import com.epam.jdi.light.elements.complex.dropdown.\*;
import com.epam.jdi.light.elements.complex.table.\*;
import com.epam.jdi.light.ui.html.elements.complex.\*;

Для **Material UI нужно добавлять**:
import com.epam.jdi.light.material.elements.displaydata.\*;
import com.epam.jdi.light.material.elements.displaydata.table.\*;
import com.epam.jdi.light.material.elements.feedback.\*;
import com.epam.jdi.light.material.elements.feedback.progress.\*;
import com.epam.jdi.light.material.elements.inputs.\*;
import com.epam.jdi.light.material.elements.inputs.transferlist.\*;
import com.epam.jdi.light.material.elements.layout.\*;
import com.epam.jdi.light.material.elements.navigation.\*;
import com.epam.jdi.light.material.elements.navigation.steppers.\*;
import com.epam.jdi.light.material.elements.surfaces.\*;
import com.epam.jdi.light.material.elements.utils.\*;

**Comment by pnatashap** [comment]
Кастомизированные элементы (они не заменяют все, кнопки, например, везде одинаковые, сейчас посмотрю, какие импорты html нужно оставлять):
import com.epam.jdi.light.material.elements.displaydata.*;
import com.epam.jdi.light.material.elements.displaydata.table.*;
import com.epam.jdi.light.material.elements.feedback.*;
import com.epam.jdi.light.material.elements.feedback.progress.*;
import com.epam.jdi.light.material.elements.inputs.*;
import com.epam.jdi.light.material.elements.inputs.transferlist.*;
import com.epam.jdi.light.material.elements.layout.*;
import com.epam.jdi.light.material.elements.navigation.*;
import com.epam.jdi.light.material.elements.navigation.steppers.*;
import com.epam.jdi.light.material.elements.surfaces.*;
import com.epam.jdi.light.material.elements.utils.*;

**Comment by pnatashap** [comment]
Вот эти импорты нужны во всех (это локаторы, WebPage, общие элементы):
Было бы идеально их строкой отделить друг от друга, чтобы видно было
```
import com.epam.jdi.light.elements.pageobjects.annotations.locators.*;
import com.epam.jdi.light.elements.composite.*;
import com.epam.jdi.light.ui.html.elements.common.*;
```
