### ISSUE TITLE
[2pt] Добавить адаптивное поведение кнопок в заголовке Locators list

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#51]
![image](https://user-images.githubusercontent.com/82033805/139828641-dff5fe9a-dae4-4c59-9fb5-5776787c6011.png)

**Comment by MariiaNebesnova** [comment]
1 pt - fe

**Comment by MariiaNebesnova** [comment]
3.0.87

**Comment by MariiaNebesnova** [comment]
дубли: https://github.com/jdi-testing/jdn/issues/387
https://github.com/jdi-testing/jdn/issues/381

**Comment by lisatatarinova** [comment]
test passed 3.0.88
