### ISSUE TITLE
Результат экспорта должен представлять собой зип файл с шаблоном проекта включающий в себя созданные пользователем пэйдж объекты

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#514]
Результат экспорта должен представлять собой зип файл с шаблоном проекта включающий в себя созданные пользователем пэйдж объекты
Шаблон проекта необходимо забирать с https://github.com/jdi-templates/jdi-light-testng-template
добавлять туда наши пэйдож объекты, зиповать и давать пользователю на скачиваение

Позднее - мы сделаем форму выбора шаблона из заранее предопределённого списка, если это можно учесть сейчас - давайте сделаем это - адрес шаблона будет прилетать с фронта

**Comment by spiridonovfed** [comment]
Эндпоинт для выдачи зип-архива содержимого репозитория готов ("/download_template").
Передаю таску на фронтенд

**Comment by MariiaNebesnova** [comment]
3.1.208
