### ISSUE TITLE
Переделать логику работы спиннеров для непросчитанных локаторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#515]
В данный момент - рядом с каждым непросчитанным локатором - мы помещаем вращающийся спиннер, что, в случае большого количества элементов, драмматически влияет на производительность (UI начинает ощутимо тормозить даже на весьма шустрых машинах).
Необходимо сделать так, что бы спинеры показывались (ну или хотя бы вращались) только рядом с теми элемантами которые в данный момент показываются на экране. А за пределами экрана - пусть не вращаются.

**Comment by MariiaNebesnova** [comment]
3.1.207
