### ISSUE TITLE
Заказать виртуальный сервер и поднять там версию

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#518]
1.	Заказ через support.epam.com
2.	Ещё вариант – Order Virtual Server - https://support.epam.com/esp/ess.do#orderitem/caVirtualMachineConfiguration
3.	Цена заваит от – 100-150$

**Comment by MariiaNebesnova** [comment]
сборка с новым адресом
[dist_3.1.208..zip](https://github.com/jdi-testing/jdn-ai/files/9102832/dist_3.1.208.zip)

**Comment by AlexeyGirin** [comment]
Инструкция - что где лежит и как выкладывать новую версию - на конфлюэнсе

**Comment by spiridonovfed** [comment]
> Инструкция - что где лежит и как выкладывать новую версию - создать на конфлюэнсе

Инструкция здесь: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/44728321/Back-end+server+in+EPAM+Cloud
