### ISSUE TITLE
Заимплементировать логику поиска бэка со стороны фронта

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#521]
При запуске - плагин должен следовать следующей логике коннекта к бэку:
1. По умолчанию - коннектимся к выделенному серверу.
2. Если сервер недоступен - пытаемся подцепиться к локальному докеру
3. Если локальный докер недоступен - засвечиваем диалоговое окно с инструкцией как запустить докер локально и кнопками Кансел и Ретрай

**Comment by MariiaNebesnova** [comment]
на первом этапе договорились вместо инструкции показывать заглушку, красивую инструкцию про установку имплементиорвать в #18

**Comment by MariiaNebesnova** [comment]
если возникакет задержка при попытке плагина отправить запрос на удаленный сервер:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/82033805/179684805-edfa31d0-b255-4a9b-aa37-956092b18b33.png">
если не ответил ни удаленный, ни локальный
<img width="528" alt="image" src="https://user-images.githubusercontent.com/82033805/179740980-eabd4e0e-4905-4fd7-bed3-c9970007febc.png">

**Comment by AlexeyGirin** [comment]
Please, check network settings or set up ...

**Comment by MariiaNebesnova** [comment]
3.1.215

**Comment by MarinaFm** [comment]
завела баг https://github.com/jdi-testing/jdn-ai/issues/551

**Comment by MarinaFm** [comment]
Баг https://github.com/jdi-testing/jdn-ai/issues/551 закрыт.
