### ISSUE TITLE
Обновить тесткейсы (деревья и прочее)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#522]
Текущая версия тест кейсов - не содержит те изменения, которые мы заимплементили в релизе 1.0
Необходимо осуществить ревью имеющихся тест-кейсов, удалить неактуальные и добавить (желательно со ссылками на стори) новые по всем сторям которые мы заимплементили

**Comment by MarinaFm** [comment]
Необходима ссылка на тест-кейсы ( хотя бы устаревшие)
По ссылке указанной здесь: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/8290314/Test+Cases при регистрации не открываются тест-кейсы JDI

**Comment by AlexeyGirin** [comment]
Болеее не актуально - тест кейсы которые были ранее - потеряны (видимо безвозвратно)
