### ISSUE TITLE
[Low] Unnecessary tooltip

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#525]
JDN v 3.1.208
Back-end v 0.1.22022-07-13-12.34.13

1.Открыть web-страницу 
2. Начать генерацию локаторов 
3. Выделить любой локатор 
4. Проверить тултип для '1 selected'

ОР: При наведении нет тултипа
ФР: При наведении появляется тултип 'с12'

![image](https://user-images.githubusercontent.com/88709848/178980759-fc215f76-81ce-4ae3-87a9-3445375162cf.png)

**Comment by MariiaNebesnova** [comment]
3.1.209
