### ISSUE TITLE
Create icon for Chrome add-on shop

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#527]
Декомпозиция #504

icon 128 x 128 px is needed

По замыслу - в иконке фоном должны быть разные прямоугольники синего и жёлтого цветов (имитация нашего покрытия после распознования) - и над этим в уголке парит манускрипт с жава кодом как бы вылетая из покрытия
(ну может не манускрипт, а файл - если есть его представление в современной иконописи - должен быть узнаваемый образ)

**Comment by SemyonKuznetsov** [comment]
нужны будут иконки 36x36 px и 24x24 px

**Comment by AlexeyGirin** [comment]
В иконки 36 и 24 просто впихнуть абривиатуру JDN (никакой связи с 128 размером)

**Comment by AlexeyGirin** [comment]
Но пока - делаем только 128 на 128

**Comment by SemyonKuznetsov** [comment]
![128](https://user-images.githubusercontent.com/101407186/179932772-83924c82-0208-40aa-b8b8-ac3a6ec95c90.png)
![4](https://user-images.githubusercontent.com/101407186/179932791-2b1c4fcd-57f0-4c17-b345-6d65cbff746c.png)
![3](https://user-images.githubusercontent.com/101407186/179932796-296b76a8-78d6-42eb-af62-995f954831d1.png)

**Comment by SemyonKuznetsov** [comment]
![icon_logo_128](https://user-images.githubusercontent.com/101407186/180724740-de39ac44-0ee4-46f7-9308-4972bc9426b3.png)

**Comment by SemyonKuznetsov** [comment]
![Frame 1199](https://user-images.githubusercontent.com/101407186/181117958-706e2506-024d-4aa1-83a5-ea201eb27b16.png)

**Comment by SemyonKuznetsov** [comment]
![Frame 1201](https://user-images.githubusercontent.com/101407186/181191059-b2067a0d-eb29-4c76-b3d5-01f1b66ac975.png)

**Comment by SemyonKuznetsov** [comment]
[JDN Icon Design Pres.pdf](https://github.com/jdi-testing/jdn-ai/files/9478616/JDN.Icon.Design.Pres.pdf)

[JDN Icon Design 2 Pres.pdf](https://github.com/jdi-testing/jdn-ai/files/9478615/JDN.Icon.Design.2.Pres.pdf)

**Comment by SemyonKuznetsov** [comment]
<img width="712" alt="Снимок экрана 2022-09-07 в 15 32 33" src="https://user-images.githubusercontent.com/101407186/188879006-defd0af5-8c17-490a-b921-b0c5a934fdb7.png">

**Comment by SemyonKuznetsov** [comment]
![JDN Banner](https://user-images.githubusercontent.com/101407186/188879701-50099f29-7d7d-4cd1-8137-cca217ea4b54.png)

![Logo 1](https://user-images.githubusercontent.com/101407186/188879754-9958e765-5a1c-4491-b4d6-6126970b1b24.svg)

**Comment by AlexeyGirin** [comment]
Done.
