### ISSUE TITLE
Prepare promo video, screenshots, url, support url for Chrome add-on shop

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#529]
Декомпозиция #504

about description:
https://www.youtube.com/watch?v=JZTO-Z8MBEc&t=260s

**Comment by savinovava** [comment]
Инструкцию редактирую здесь: https://epam-my.sharepoint.com/:w:/p/valeriia_savinova1/EVkiA3860vtDt7RzCCTcwx0B--VPPeHhBIwcm1rdrX796w?e=fv25jO

**Comment by AlexeyGirin** [comment]
Как доделает инструкцию Лера - так и закроем

**Comment by savinovava** [comment]
![image](https://user-images.githubusercontent.com/53625116/192277094-6f2c762a-facf-402a-b382-b82aaeded8ef.png)

**Comment by savinovava** [comment]
#703
