### ISSUE TITLE
[High]Переделать логику отображения прогресса рачёта локаторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#534]
В данный момент - расчёт большого количества локаторов при невозможности посмотреть что твориться на сервере - вызывает непонимание о прогрессе (полоска прогресса - практически не двигается)
Нужно сделать отображение прогресса - более наглядным Например - сделать отображение - сколько посчитано и сколько осталось - 54/150 processed so far и увеличивать каунтер в случае когда локатор закончил обсчитываться)

**Comment by SemyonKuznetsov** [comment]
![notification](https://user-images.githubusercontent.com/101407186/179532702-58839992-bb43-4d15-8c5b-e38e45d886a8.png)

решили добавить без дополнительных стилей

**Comment by MariiaNebesnova** [comment]
3.1.212
