### ISSUE TITLE
Продумать логику углублённого расчёта локатора

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#539]
В данный момент - мы ограничиваем время рассчёта одного локатора (сейчас это 1 секунда).
Иногда (примерно не более 5% случаев) результат получается весьма плохой.
Нужно дать пользователю возможность выбрать локатор (или группу локаторов) и попросить систему более углублённо посчитать их (с возможностью выбора времени которое система на это потратит - 1с, 3с, 5с, 10с, 1м, анлим)

**Comment by AlexeyGirin** [comment]
10с - дефолтное времся углублённого расчёта

**Comment by SemyonKuznetsov** [comment]
![3](https://user-images.githubusercontent.com/101407186/182550413-3600f468-1efa-4cd6-a29e-e34d2566e8ba.png)

**Comment by SemyonKuznetsov** [comment]
<img width="232" alt="Снимок экрана 2022-08-03 в 10 40 29" src="https://user-images.githubusercontent.com/101407186/182551898-b6d937da-3a6e-4e85-81de-b13e17d26c51.png">

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5936%3A321031)
<img width="1304" alt="Advanced calculation 2" src="https://user-images.githubusercontent.com/101407186/182602518-e2174c64-7e9d-43d2-bbaa-40592de7706e.png">

**Comment by MariiaNebesnova** [comment]
as figured out, backend remains to calculate locator with 1s time, despite sent time value.
for now: menu options are added, sockets messages are sending with selected time option. also menus UI is reworked according to new design

**Comment by MariiaNebesnova** [comment]
3.2.249

**Comment by spiridonovfed** [comment]
Fixed from back-end side. Ready to be tested
