### ISSUE TITLE
[1pt][US-6-1] Исправить содержимое локатора в локатор листе

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#54]
- [x] в дизайне:  локатор - public - тип блока - имя переменной
в плагине: локатор - тип блока - имя переменной

- [x] Цветовая разметка локатора:
в дизайне: выделен синим цветом “тип блока”.
в плагине: выделен синим цветом "public".

**Comment by MariiaNebesnova** [comment]
1pt - frontend

**Comment by MariiaNebesnova** [comment]
3.0.75

**Comment by pulya-na-vullet** [comment]
Locator list work correctly. 
JDN v 3.0.75
Back-end v 2021-11-01-06.14.14
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910649/US-6-1+See+the+generated+elements
![image](https://user-images.githubusercontent.com/61897393/141988682-f3acee90-ea56-4dfb-b081-ed219e237045.png)
