### ISSUE TITLE
After editing generation of locator continues

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#540]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12877879/US-7-2+User+can+edit+locators+manually#UC-7-2-6-User-edit-the-locator%2C-that-isn%E2%80%99t-generated
GIVEN locator is generating
AND The window “Edit” is active
WHEN I edit the locator’s fields
AND save the new locator
THEN locator should be shown as edited 
AND generation of locator should be stopped

**Comment by MariiaNebesnova** [comment]
3.1.214

**Comment by MarinaFm** [comment]
Checked and closed
