### ISSUE TITLE
Наделать скриншоты

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#549]

**Comment by MariiaNebesnova** [comment]
![image](https://user-images.githubusercontent.com/82033805/180156788-7844c3b9-7bd8-4fe2-8b61-c3521caf7d32.png)

**Comment by MarinaFm** [comment]
![4 (640х640)](https://user-images.githubusercontent.com/88709848/180973059-4e9596a5-66c3-43b0-a9f8-4f49c74c8e44.jpg)

![5 (1280х800)](https://user-images.githubusercontent.com/88709848/180973095-3b0d85d3-42d8-436f-a4d1-2a4a430fb848.jpg)

![6 (1280х800)](https://user-images.githubusercontent.com/88709848/180973119-9a94fdb5-fc8d-4d36-9150-42efc343b789.jpg)

**Comment by MarinaFm** [comment]
![2 (1280х800)](https://user-images.githubusercontent.com/88709848/180986421-5d8af9e8-2af2-461d-8ba7-7a197f50b7a8.jpg)
