### ISSUE TITLE
[US-7-2] При открытии поп-апа с настройками покрытие локаторов остается кликабельное

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#55]
На некоторых сайтах существует проблема с кликабельностью покрытия на странице, когда открыты настройки.

JDN v 3.0.70
Back-end v 2021-09-28-08.31.54

Шаги:
1. Открываю страницу https://jdi-testing.github.io/jdi-light/material/radio
2. Генерирую локаторы
3. Выбираю несколько локаторов - нажимаю "настройки"
4. При этом на странице покрытие остается кликабельное.

Например, при клике на чекбокс, покрытие, которое находится под поп-апом меняет цвет с оранжевого на голубой.

<img width="1435" alt="Screenshot 2021-11-03 at 13 41 15" src="https://user-images.githubusercontent.com/89466817/140059303-4800f889-39c8-4233-9c34-5db988b5265b.png">

И в целом мне удается прокликать все покрытие на странице и поменять его цвет, без закрытия поп-апа.

<img width="1438" alt="Screenshot 2021-11-03 at 13 41 45" src="https://user-images.githubusercontent.com/89466817/140059349-03e4f54a-882d-4a44-bfbd-976fd5133a5f.png">

**Comment by MariiaNebesnova** [comment]
если вывести контекстное меню так, чтобы оно накрыло другой элемент подстветки, тоже можно выделить элемент, который не планировали

**Comment by lisatatarinova** [comment]
QA 3pt (с расчетом, что нужно будет убедиться на нескольких сайтах, что перекрытия нет)

**Comment by lisatatarinova** [comment]
not reproduced anymore,
test passed in 3.0.88
