### ISSUE TITLE
Плагин не переключается с локального на удаленный сервер

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#551]
JDN v 3.1.216
Back-end v 0.1.2

1. Впн -выключен, локальный докер - включен
Начать генерацию локаторов
2. Впн - включить, локальный докер - остается включенным
Начать генерацию локаторов повторно
3. Впн-остается включен, локальный докер - отключить
Начать генерацию локаторов повторно

ОР: Плагин видит удленный сервер, Генерация локаторов началась
ФР: Плагин видит удленный сервер, Генерация локаторов не начинается, спиннер кнопки Generate бесконечно крутится

**Comment by MariiaNebesnova** [comment]
3.1.217

**Comment by MarinaFm** [comment]
JDN v 3.1.219
Back-end v 0.1.2

Впн -выключен, локальный докер - включен
Начать генерацию локаторов
Впн - включить, локальный докер - остается включенным
Начать генерацию локаторов повторно
Впн-остается включен, локальный докер - отключить
Начать генерацию локаторов повторно
ОР: Плагин видит удленный сервер, Генерация локаторов началась, прогресс бар считает кол-во сгенерированных локаторов
ФР: Плагин видит удленный сервер, Генерация локаторов началась, спиннеры крутятся, количество сгенерированных локаторов не увеличивается

![image](https://user-images.githubusercontent.com/88709848/181067739-4e7dae2f-6541-4f53-8f46-4a6d7983c990.png)

**Comment by MariiaNebesnova** [comment]
удается стабильно воспроизвести без второго шага

**Comment by MariiaNebesnova** [comment]
3.1.220

**Comment by MarinaFm** [comment]
Checked and closed
