### ISSUE TITLE
Пинг?

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#554]
После вынесения серверной части в облако - появилось необходимость иметь механизм мониторинга доступности и работоспособности сервера (т.к. сетевая конфигурация и настройки ВНЕЗАПНО меняются прямо в время работы)
Для этого давайте попробуем ввести сервис пинга.
Клиент должен регулярно (например - каждые 30 секунд) размещать на сервере фейковое задание на расчёт и получать от него ответ через заданный провемежуток времени (например - не позднее чем через 1-2 секунды)
Если это не произошло - засвечивать пользователю комбо-бокс или как-то другим образом информировать что сервер недоступен - проверьте сетевые настройки (ВПН?) или поднимите сервер локально

**Comment by SemyonKuznetsov** [comment]
<img width="536" alt="Снимок экрана 2022-07-27 в 11 09 41" src="https://user-images.githubusercontent.com/101407186/181196113-e7bc6dc1-f334-4dcc-bf67-a515ec66e0d7.png">

новые нотификейшены в Ант.Фреймфорк

**Comment by AlexeyGirin** [comment]
При возникновении проблем с сетью
1. Валим все проблемные локаторы в состояние с иконкой Error (с тултипом - Network Error has been encountered)
2. В нотификейшен строке выводим ошибку с красной иконкой и сообщением об ошибке - Network error, check network settings or run server locally

**Comment by MariiaNebesnova** [comment]
WebSocket:
Request:
{"action": "ping","payload": {}}
Response:
{'pong': {}}

Request:
{"action": "ping","payload": {'mock_data': 'mock_data'}}
Response:
{'pong': {'mock_data': 'mock_data'}}

**Comment by MariiaNebesnova** [comment]
3.1.221

**Comment by MariiaNebesnova** [comment]
<img width="610" alt="Screenshot 2022-08-02 104547" src="https://user-images.githubusercontent.com/82033805/182321046-499926de-171d-4a59-b4eb-992320153862.png">

**Comment by Maksim-Kviatkovskii** [comment]
В целом всё ок, кроме замечания по реконнекту (вынесено в 578)
