### ISSUE TITLE
[Medium] Modal window 'Confirm the selection' isn't closed from the first button click

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#557]
JDN v 3.1.217
Back-end v 0.1.2 (vpn - вкл)

1.Начать генерацию локаторов
2.Выделить все локаторы, когда локаторы в процессе генерации
3. Нажать 'Save changes' 
4. В открывшемся окне 'Confirm the selection' нажать 'Cancel'

ОР: Модальное окно 'Confirm the selection' закрывается. Генерация продолжается
ФР: Модальное окно 'Confirm the selection' не закрывается, фон становится менее темным. Генерация продолжается
Окно закрывается c 3го клика, фон становится совсем светлым

Note: такой же кейс с модальным окном 'You have unsaved changes'

![image](https://user-images.githubusercontent.com/88709848/180855330-c8bd8fa3-a507-46d2-9f0a-0ff83974e045.png)
![image](https://user-images.githubusercontent.com/88709848/180855360-e4c35fe4-044a-4339-b201-070272a15b04.png)
![image](https://user-images.githubusercontent.com/88709848/180855379-54c6c42e-a5da-4fe7-999b-f6b121d3e3d4.png)

**Comment by Maksim-Kviatkovskii** [comment]
Больше не актуально
