### ISSUE TITLE
[Low] Button 'Back' has no respond from the first click while locators are generated

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#558]
JDN v 3.1.217
Back-end v 0.1.2 (vpn -вкл)

1.Запустить генерацию локаторов
2. Во время генерации нажать нопку 'Back'

ОР: Открывается модальное окно 'You have unsaved changes'
ФР: При клике ничего не происходит, модально еокно не открывается, генерация локаторов продолжается. Модальное окно открывается с 3-4 клика, когда почти все локаторы сгенерированы

**Comment by MariiaNebesnova** [comment]
предполагаю, в этот момент сокет-месседжи идут плотным потоком и вызов диалога не отвечает моментально

**Comment by Maksim-Kviatkovskii** [comment]
Больше не актуально
