### ISSUE TITLE
Locator is not displayed on the webpage if it was edited and than action was canceled

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#559]
JDN v 3.1.217
Back-end v 0.1.2 (vpn -вкл)

1.Начать генерацию локаторов
2. Нажать 'Edit' для локатора которы йв процессе генерации
3.Изменить поле 'Locator' в модальном окне
4. Нажать 'Cancel' на панели 'Locator edited successfully!'

ОР: После отмены изменений локатор отображается на странице
ФР:  После отмены изменений локатор не отображается на странице

![image](https://user-images.githubusercontent.com/88709848/180863818-61b7df0c-f80c-427a-b128-f24ffba5cd95.png)
![image](https://user-images.githubusercontent.com/88709848/180863955-4b6e6528-686b-44d1-af8a-ac9deeedf7fc.png)
![image](https://user-images.githubusercontent.com/88709848/180863995-3e637078-9a44-4305-b9a4-ffe356da2b35.png)

**Comment by MariiaNebesnova** [comment]
3.1.219

**Comment by MarinaFm** [comment]
Checked and closed
