### ISSUE TITLE
Создать описание для плагина

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#562]
Для публикации в магазин плагинов - требуется описание

**Comment by savinovava** [comment]
The current version:
𝐖𝐡𝐚𝐭 𝐢𝐬 𝐍𝐞𝐰?
‣ Recognition of HTML5 elements
‣ Recognition of MUI elements

𝐏𝐫𝐨𝐛𝐥𝐞𝐦:
QA Engineers usually spend enormous amount of time on writing Page Objects for test frameworks and on checking after. This type of work is monotonous and time-consuming.

𝐒𝐨𝐥𝐮𝐭𝐢𝐨𝐧:
EPAM provides the "𝑱𝒖𝒔𝒕 𝑫𝒐 𝑵𝒐𝒕𝒉𝒊𝒏𝒈 (𝑱𝑫𝑵)” - a Google Chrome plugin for optimization of the Page Objects TF layer creation process. This optimization leads to reduce time spent by testing engineers on writing the test framework.

The solution delivers the following functionality:

• Automatic recognition of objects on the web page;
• Java code creation for UI testing of web objects; 
• Ability to manage objects while creating code;
• Chrome extension with a user-friendly interface to interact with the solution.
• Recognition of MUI and HTML5 elements;

**Comment by AlexeyGirin** [comment]
Для манифеста - JDN – helps Software Test Automation Engineer to create Page Objects in the test automation framework and speed up automation test development

**Comment by AlexeyGirin** [comment]
Done.
