### ISSUE TITLE
[E-20] Создание лог-файла

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#563]
Для обработки информации, которая не изменяется после начала генерации, необходимо писать логи
Meeting Notes: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/46858248/25072022+Usage+Metrics

- ID
- EPAM login/IP
- Date and Time
- Locators List -> Generated Locator Name, Locator Time, Inheritance

#565 
- Page Object Creation
- Element Library
- URL

_Format: csv/xls_

**Comment by savinovava** [comment]
Как получить EPAM login/IP для подсчёта уникальных пользователей? Консультация по Google Analytics

**Comment by spiridonovfed** [comment]
Тестируем пока локально (docker-compose) и с помощью сборки ниже

**Comment by spiridonovfed** [comment]
[dist (6).zip](https://github.com/jdi-testing/jdn-ai/files/9266650/dist.6.zip)

**Comment by spiridonovfed** [comment]
Логи можно взять отсюда http://localhost:5050/docs#/default/export_logs_export_logs_get

**Comment by MariiaNebesnova** [comment]
3.2.243
