### ISSUE TITLE
Доработки экспорта

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#569]
Это кейс - для случая одно пэйдж обжекта на страничке у которой есть адрес (т.е. что то после имени домена есть)
1. Шаблон проекта берем из https://github.com/jdi-templates/jdi-light-testng-empty-template ветка main
2. Сгенерированный файл добавляем в src/main/java/site/pages
3. В начало сгенерированного файла добавляем пространство имен 'package site.pages;' (см. https://github.com/jdi-templates/jdi-light-testng-empty-template/blob/main/src/main/java/site/pages/FirstPage.java)
4. Прочитать адрес открытой страницы и разделить на домен и адрес страницы (при полном адресе страницы https://jdi-testing.github.io/jdi-light/contacts.html, считаем доменом https://jdi-testing.github.io, адресом страницы /jdi-light/contacts.html )
домен вставляем в test.properties вместо ${domain} (в строке domain=${domain})
адрес страницы добавить в MySite после комментария '// ADD SITE PAGES WITH URLS' в формате
@Url("адрес страницы")
public static ИМЯ_КЛАССА имяPage;
5. Сгенерировать файл с тестом в папку src/test/java/tests по примеру ExampleTests (требуется другое имя класса и имя новой переменной подставить)

Кейс - для случая нескольких пэйдж обжектов на одной и той же страничке у которой есть адрес (т.е. что то после имени домена есть)

Кейс - для случая нескольких страничек с разными URL  (т.е. что то после имени домена есть) на которых есть один обжект

Кейс - для случая нескольких страничек с разными URL  (т.е. что то после имени домена есть) на которых есть несколько обжектов на каждой страничке

**Comment by spiridonovfed** [comment]
Default download link change to https://github.com/jdi-templates/jdi-light-testng-empty-template.
You can check the endpoint details here: http://ecsb003017b9.epam.com/docs#/default/download_template_download_template_get

**Comment by AlexeyGirin** [comment]
в test.properties должно было быть domain=https://jdi-testing.github.io/jdi-light/
если анализировали https://jdi-testing.github.io/jdi-light/contacts.html (т.е. все без имени страницы)

**Comment by MariiaNebesnova** [comment]
[3.2.223](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.223)
