### ISSUE TITLE
[3pt]Рефакторинг диалогов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#57]
- [x] Повыносить стили в общий файл
Что бы выглядили одинаково с точки зрения кода

**Comment by savinovava** [comment]
@kostrubin оцени, пожалуйста

**Comment by kostrubin** [comment]
Если в часах, то где-то часов 6

**Comment by MariiaNebesnova** [comment]
3.0.78

**Comment by lisatatarinova** [comment]
test passed 3.0.88
