### ISSUE TITLE
[US 14-2-5] PopUp: unsaved changes

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#571]
Change text to:
"You have unsaved changes in the locator list. Do you want to discard them?"

_How it works now:_
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/53625116/182141493-d0ec77b3-0eb2-4d20-9880-2e36fcc7b371.png)

**Comment by savinovava** [comment]
To be approved by Designer: @SemyonKuznetsov

**Comment by SemyonKuznetsov** [comment]
👍 по тексту мне добавить нечего

**Comment by MariiaNebesnova** [comment]
[3.4.294](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.294)
