### ISSUE TITLE
[US-9-1] Email validation

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#576]
UC 9-1-2 Email validation
GIVEN I am a user 
AND I opened “Report a problem” window
AND I started typing in the email field

WHEN the value should be validated

THEN warnings should be shown if needed
AND “Send” button should be deactivated

US: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910713/US-9-1+Report+a+problem

**Comment by AlexeyGirin** [comment]
Already done.
