### ISSUE TITLE
[Medium] Previous path is displayed in Locator field after editing

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#577]
JDN v 3.1.222
Back-end v 0.1.2

1. Локаторы сгенерированы
2. Выбрать локатор и открыть окно 'Edit'
3. Очистить поле 'Locator'
4. Нажать 'Save'
5. Открыть редактированный локатор снова

ОР: Поле Locator пустое
ФР: Поле Locator заполнено, данные в поле не удалены
![image](https://user-images.githubusercontent.com/88709848/182867123-dd55d399-5d92-4e37-9d23-f3a870ce69c1.png)

Уточнить желаемое поведение: 
При пустом поле 'Locator' кнопка 'Save' должна быть заблокирована или возможно сохранение с пустым полем 'Locator'?

**Comment by AlexeyGirin** [comment]
Мы разрешаем пользователю сохранять тот локатор, который он хочет. В том числе - и пустой тоже.
Предыдущий локатор - подставляться в этом случае не должен

**Comment by MariiaNebesnova** [comment]
[3.7.388](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.388)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.7.388 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1
