### ISSUE TITLE
Переделать скриншоты для магазина плагинов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#580]
В данный момент - скриншоты которые мы загрузили в магазит - выглядят сплюснуто. Видимо ошиблись с размерность.
Необходимо поправить эту историю
Наделать хорошие интересные скрины - поможет Марина.
Загрузить их в магазит - поможет Маша

![image](https://user-images.githubusercontent.com/26869421/183367647-7c12444c-d96b-48f0-a6e6-0d91afbeacbd.png)

**Comment by SemyonKuznetsov** [comment]
![image](https://user-images.githubusercontent.com/101407186/183591468-44083a83-ff2d-4dd2-a962-b9da8a9a0565.png)

**Comment by SemyonKuznetsov** [comment]
нужен 5ый завершающий скриншот

**Comment by SemyonKuznetsov** [comment]
<img width="1280" alt="screenshot21" src="https://user-images.githubusercontent.com/101407186/184040771-5bd8e78b-0be5-4e94-9eb3-a9ee40a06a91.png">

<img width="1280" alt="screenshot22" src="https://user-images.githubusercontent.com/101407186/184040770-006cd8ab-3302-468b-8349-50955cc78e0a.png">

<img width="1280" alt="screenshot23" src="https://user-images.githubusercontent.com/101407186/184040768-9e9cf674-7936-48ea-924e-3f77add8d039.png">

<img width="1280" alt="screenshot24" src="https://user-images.githubusercontent.com/101407186/184040767-2b306010-3991-4374-8285-b5e6c292678e.png">

<img width="1280" alt="screenshot25" src="https://user-images.githubusercontent.com/101407186/184040754-f0dfe06c-865b-49bc-b33a-94a3fd292730.png">

[Архив.zip](https://github.com/jdi-testing/jdn-ai/files/9305113/default.zip)

**Comment by SemyonKuznetsov** [comment]
[Архив 2.zip](https://github.com/jdi-testing/jdn-ai/files/9308191/2.zip)

**Comment by MariiaNebesnova** [comment]
залито
