### ISSUE TITLE
Переделать логику обнаружения бэка и придумать как пользователь может этим управлять

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#584]
У нас есть две опции размещения бэка:
1. Использование внешнего сервера
2. Использование локального сервера в докере

Необходимо продумать UI который будет решать 2 вопроса:
1. Позволить пользователю самостоятельно выбрать тот вариант который он хочет (видимо текущий выбор - нужно как-то показывать на экране, что бы это не было тайной)
2. Продумать как и что мы показываем пользователю если текущий выбор (например - сохранённый из прошлой сессии) теперь не рабочий и нужно предложить переключиться на другой вариант

**Comment by AlexeyGirin** [comment]
Учесть, что эта задача будет выполняться вместе с задачей #191 и (вероятно) являться поводом для возраждения идеи меню глобальных настроек

**Comment by savinovava** [comment]
При закрытии необходимо актуализировать следующие задачи:
#18 
#333 

endpoint: со стороны Фёдора - для динамического отображения текста

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6130%3A329033)

![modal error](https://user-images.githubusercontent.com/101407186/187263805-8480debc-b7e1-49eb-92a2-8773c688310b.png)
![modal menu](https://user-images.githubusercontent.com/101407186/187263811-7fef184d-43d1-456d-82da-25721ce3adfe.png)

**Comment by SemyonKuznetsov** [comment]
572 пикселя это максимальна ширина меню

задизейбленные пункты настроек из фигмы в имплементацию не идут

**Comment by AlexeyGirin** [comment]
В рамках этой задачи - нужно сделать только первый скрин (т.е. в углу показывать значок показывающий - куда подключился пользователь - докер или клауд, ну и логика когда иконка меняется на красную если пропадает связь - тоже)

**Comment by AlexeyGirin** [comment]
Задача для Семёна - увязать существующий дизайн (с кнопками типа Репорт э проблем) с новым дизайном

**Comment by SemyonKuznetsov** [comment]
![#584 external server icon](https://user-images.githubusercontent.com/101407186/188181657-443faf02-a9c4-4fb2-99b3-fab8152eeb48.png)

![#584 local server icon](https://user-images.githubusercontent.com/101407186/188181667-06c63f1d-7901-402b-aa40-71d548f12999.png)

![error](https://user-images.githubusercontent.com/101407186/188181678-e05973e9-ee18-41ac-9240-45a1c0531b25.png)

![#584 tooltips for report a problem](https://user-images.githubusercontent.com/101407186/188181660-2d782798-d09b-45fb-afba-58157e9b006a.png)

![#584 tooltips for readme](https://user-images.githubusercontent.com/101407186/188181665-28c23683-3f2f-4d49-9665-d290bfa653a1.png)

**Comment by MariiaNebesnova** [comment]
3.2.250

**Comment by SemyonKuznetsov** [comment]
![error](https://user-images.githubusercontent.com/101407186/188816527-a4290d26-fc9f-45f6-8d47-e4cd8891497a.png)

**Comment by SemyonKuznetsov** [comment]
![#584 error](https://user-images.githubusercontent.com/101407186/188870542-7483dd05-841f-4edf-a586-efa7d32b2cf5.png)

**Comment by SemyonKuznetsov** [comment]
завести задачу на апдейт нотификейшенов

**Comment by MariiaNebesnova** [comment]
3.2.253

**Comment by Maksim-Kviatkovskii** [comment]
Иконка при потере соединения с облаком не соответствует макету
![image](https://user-images.githubusercontent.com/109746268/189916860-e53a59c5-1175-4289-a8b7-f36c244cebc1.png)
