### ISSUE TITLE
Баг со съезжанием разметки

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#587]
Зайти на www.google.com 
Дальше - как на видео 

https://user-images.githubusercontent.com/26869421/183664270-435e9746-bc5b-49ae-90fb-706f8b27395f.mp4

(использует мак)

**Comment by MariiaNebesnova** [comment]
потому что добавление подсветки выходит за пределы страницы и повляются скроллы

**Comment by MariiaNebesnova** [comment]
3.2.224

**Comment by MarinaFm** [comment]
Checked and closed
