### ISSUE TITLE
Доработка экспорта 2

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#588]
В случае если мы создаём два пэйджобжекта - система скачивает 2 одинаковых и правильных архива при нажатии на кнопку Download All.

Нужно что бы скачивался один :-)

P.S. Если создать N пэйдж обжектов - скачивается N архивов!
Версия фронта - 3.1.233
Мак ноутбук

**Comment by MariiaNebesnova** [comment]
пэйджобжекты для одной страницы сгенерены?

**Comment by MariiaNebesnova** [comment]
для ситуации, когда ПО сгенерены для разных доменов, неоходимо генерить разные архивы с темплейтами. Какова вероятность, что такой кейс сейчас понадобится?

**Comment by AlexeyGirin** [comment]
Оставляем только один домен и один шаблон для него (берём по умолчанию - последний домен)

**Comment by MariiaNebesnova** [comment]
3.2.225
