### ISSUE TITLE
Падение бэка

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#589]
Открыть ссылку https://www.google.com/search?q=JDI&sxsrf=ALiCzsYK4OXgGkddFikQiE26rqF9fLiyTQ:1660053049422&source=lnms&tbm=isch&sa=X&ved=2ahUKEwidncbC87n5AhXhD1kFHbLZBbsQ_AUoAXoECAIQAw&biw=994&bih=747&dpr=2

Дальше как в видео

https://user-images.githubusercontent.com/26869421/183668921-740c0a59-66e0-4b82-9ce7-a04dedb199b7.mp4

 Сеть падает

**Comment by MarinaFm** [comment]
Другой вариант (При работе через локальный докер):
генерация локаторов доходит до 100% -> Указано 'Locators generation is successfully completed' -> У локаторов отображаются иконки паузы

![image](https://user-images.githubusercontent.com/88709848/183835527-e87aed03-aac1-4cfe-a286-a49bccd3b050.png)

**Comment by spiridonovfed** [comment]
Устранено падение бэкенда из-за переполнения хранилища тасок - установлено ограничение по памяти, более старые записи перетираются более новыми

**Comment by MarinaFm** [comment]
Проверить задачу когда будет готова https://github.com/jdi-testing/jdn-ai/issues/608

**Comment by AlexeyGirin** [comment]
На гугл поиске картинок JDI расчёт повисает
