### ISSUE TITLE
Кнопка Retry - в случает падения сети

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#590]
Возможно нам стоит добавить кнопку Retry в строку состояния - позволяя пользователю ещё раз запустить задачи на расчтёт если первый раз не получилось

И досылать на расчёт только то, что не успели просчитать (иногда - перед падением оно успевает просчитать несколько локаторов)

**Comment by AlexeyGirin** [comment]
Решили делать в этом релизе

**Comment by SemyonKuznetsov** [comment]
<img width="578" alt="Снимок экрана 2022-08-11 в 16 28 46" src="https://user-images.githubusercontent.com/101407186/184144469-1d7d8f52-b647-41cb-8b8a-8dd06f0402ef.png">

**Comment by SemyonKuznetsov** [comment]
в следующем релизе будет нужен визуальный апргейд до ант.фреймворка

**Comment by MariiaNebesnova** [comment]
обсудили с Семёном, крестик не нужен

**Comment by MarinaFm** [comment]
Таска будет закрыта после проверки пофикшенных багов 613 и 615

**Comment by MarinaFm** [comment]
Проверено, в случае падения сети (и удаленный сервер,и локальный докер) кнопка Retry появляется.
