### ISSUE TITLE
Свалившийся в сетевую ошибку локатор должен переходить в состояние остановки

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#597]
1. Запустить расчёт локаторов который вызовет их общее падение с сетевой ошибкой (в моём случае - https://www.google.com/search?q=JDI&sxsrf=ALiCzsYK4OXgGkddFikQiE26rqF9fLiyTQ:1660053049422&source=lnms&tbm=isch&sa=X&ved=2ahUKEwidncbC87n5AhXhD1kFHbLZBbsQ_AUoAXoECAIQAw&biw=994&bih=747&dpr=2 )
2. Локаторый упадут
3. Выдели отдельный локатор галочкой - внезапно - система показывает что он считается СЧИТАЕМЫМ и предлагает кнопку паузы (это странно - я бы ожидал что она преложит мне перезапустить выполнение и покажет кнопку запуска (Play button)
4. Ну окей. Давайте нажмём на паузу.
5. После этого - нажмём на плэй
В этот момент - система запустить на расчёт - ВСЕ локаторы. Хотя я бы ожидал - запуск на расчёт только те, что я выделил

**Comment by MariiaNebesnova** [comment]
3.2.226

**Comment by AlexeyGirin** [comment]
Вместо кнопки Play - показывать для выделенного упавшего локатора кнопку Retry (закрученная стрелка)

**Comment by MariiaNebesnova** [comment]
опция retry добавлена в контекстное меню в списке локаторов и для элемента подсветки.
так же восстановлена красный бэграунд элементов подсветки для зафейленных локаторов.
<img width="293" alt="image" src="https://user-images.githubusercontent.com/82033805/184649317-1d9208d4-006a-49a3-b89c-b161c30d97d3.png">

3.2.229
