### ISSUE TITLE
Кастомизация - какие элементы распознавать, а какие - нет

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#598]
Добавить возможность пользователю - выбирать какие элементы распонавать, а какие - нет.
Сейчас - этот список захардкожен, однако - бывают ситуации когда даже нон-экшанабл элементы имеют смысл и должны быть распознаны

**Comment by SemyonKuznetsov** [comment]
https://github.com/jdi-testing/jdn-ai/issues/268

**Comment by AlexeyGirin** [comment]
Будет сделано в расках задачи #268
