### ISSUE TITLE
[US-5-3] JDI site - password field на форме логина определяется как DateTimeSelector

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#600]
JDI site (https://jdi-testing.github.io/jdi-light/index.html) - password field на форме логина определяется как DateTimeSelector

**Comment by JuliaElizarova** [comment]
ML модель в любом случае не обладает 100% точностью, поэтому при ее применении могут возникать ошибки определения класса. Поле для ввода пароля с тегом input внешне похоже на поле с выбором даты, поэтому скорее всего при построении модели просходит построение признаков так, что эти два поля легко перепутать. Вожможно, модель смущает то, что поле имеет тип не text, а password. Дальше можно попробовать создавать новые признаки, улучшать модель и тд.

**Comment by AlexeyGirin** [comment]
Задача для Фёдора - обогатить генератор такими полями (с типом password)

**Comment by MarinaFm** [comment]
JDN v 3.2.243
Back-end v 0.1.3 (локальный докер_ develop version)

Для JDI site (https://jdi-testing.github.io/jdi-light/index.html) - password field не распознается
![image](https://user-images.githubusercontent.com/88709848/186930078-a7c750a1-8823-4c9d-b62c-5b81b9b24187.png)

На других сайтах баг воспроизводится: Field type - DateTimeSelector
1. Например, сайт Gitlab https://gitlab.com/users/sign_in/
![image](https://user-images.githubusercontent.com/88709848/186931020-a0922094-c0f6-46f0-a16a-f56b7ce8fe8b.png)

2. сайт Github
![image](https://user-images.githubusercontent.com/88709848/186931233-da318151-e838-45ec-8398-cd5fc0672f5a.png)

**Comment by AlexeyGirin** [comment]
Сейчас - просто перестало разпозноваться вообще

**Comment by savinovava** [comment]
Необходимо дополнительно добавить распознавание TextField с типом password

<label type = password><input> | textfield | TextField

**Comment by Maksim-Kviatkovskii** [comment]
JDN v 3.2.248
Back-end v 0.1.3

Поведение такое же, как описано в коменте Марины 5 дней назад (https://github.com/jdi-testing/jdn-ai/issues/600#issuecomment-1228586539)

**Comment by Maksim-Kviatkovskii** [comment]
Результат тот же, что и в последнем коменте

**Comment by AlexeyGirin** [comment]
Договорились сделать ещё один if в модели на элементах которые не распознались на 100%
если есть тег Input - строго распознавать как TextField, если его нет - распознавать как UIElement

**Comment by Maksim-Kviatkovskii** [comment]
3.2.258 / 0.2.2
https://my.1password.com/signin?l=ru
Поле с паролем определяется как dateTimeSelector, а не как UIElement
![image](https://user-images.githubusercontent.com/109746268/191243922-43f0e7bc-a71a-4846-9a59-fe1b7ce5c767.png)

**Comment by AlexeyGirin** [comment]
Зависит от задачи #691
