### ISSUE TITLE
Редактирование элемента не работает: жмешь на карандашик, исправляешь имя, тип, жмешь Save и ничего не меняется

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#602]
Редактирование элемента не работает: жмешь на карандашик, исправляешь имя, тип, жмешь Save и ничего не меняется

**Comment by MarinaFm** [comment]
Заведен похожий баг https://github.com/jdi-testing/jdn-ai/issues/593

**Comment by MariiaNebesnova** [comment]
3.2.228

**Comment by MarinaFm** [comment]
Checked and closed
