### ISSUE TITLE
[Нестабильный баг] Наведение курсора на очень левый локатор вызывает окошко за пределами окна браузера

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn-ai#61]
JDN v 3.0.66
Back-end v 2021-09-28-08.31.54

Actual:
{я потеряла картинку, а локатор больше не идентифицируется...}

Expected: юзер видит все окошки, даже самые левые

**Comment by lisatatarinova** [comment]
QA 1pt

**Comment by MariiaNebesnova** [comment]
3.0.98

**Comment by pulya-na-vullet** [comment]
Баг воспроизводится
JDN v 3.0.99
Back-end v 2021-11-26-14.32.52
<img width="885" alt="Снимок экрана 2021-12-14 в 9 24 57 AM" src="https://user-images.githubusercontent.com/61897393/145944586-5a5057f8-42f1-4379-bd1b-c97b2c123c99.png">

**Comment by pulya-na-vullet** [comment]
Разбил баг на два бага, лейбл не влазит в поле видимости
