### ISSUE TITLE
Некоторые типы элементов в HTML5 задваиваются

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#612]
Открыть страничку https://jdi-testing.github.io/jdi-light/contacts.html (не забыв залогиниться - Roman/Jdi1234)

Распознать элементы.
Выбрать редактирование локатора для поля passportNumber (например)

В выпадушке с типом - есть задвоенные типы + странный тип UIElement(radiobatton) - что это такое вообще?

![image](https://user-images.githubusercontent.com/26869421/184895382-db1b38dc-ce50-4432-81a0-a9229914ed3a.png)

**Comment by MariiaNebesnova** [comment]
3.2.231
