### ISSUE TITLE
Добавить HTML5 элемент - SVG - должно распозноваться как img src

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#614]

**Comment by savinovava** [comment]
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/39223297/HTML5+Element+s+table
Обычно мы не распознаём картинки, что-то изменилось?

**Comment by savinovava** [comment]
Ещё один элемент, который нужно добавить: https://github.com/jdi-testing/jdn-ai/issues/467

**Comment by savinovava** [comment]
Ещё один элемент, который нужно добавить: https://github.com/jdi-testing/jdn-ai/issues/467

**Comment by AlexeyGirin** [comment]
> https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/39223297/HTML5+Element+s+table Обычно мы не распознаём картинки, что-то изменилось?

В конце концов - распознавать мы будем вообще все элементы, но показывать пользователю только те, которые проставлены в фильтре (по умолчанию)
