### ISSUE TITLE
Отмена успешно посчитанных локаторов?

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#615]
Воспроизведите баг #613
Локаторы повиснут в состоянии паузы.
Выделите один или все локаторы и запустите их на расчёт снова.
Система их успешно обсчитает (нет) но при этом - в нотификационном сообщении будет кнопка Cancel
И сообщение нужно подправить - Generation of 110 [locators] re-run successfully.

![image](https://user-images.githubusercontent.com/26869421/184898556-7dea2220-0d31-4ecc-9966-ddbae59fa2a7.png)

**Comment by MariiaNebesnova** [comment]
один раз такое увидела, в сокетах была отправка schedule и потом входящие сообщения со статусами Revoked, хотя на фронте ничего специально не останавливалось. больше не воспрозводилось.
@MarinaFm у тебя это повторялось?

**Comment by AlexeyGirin** [comment]
1. Подправить текст сообщения
2. Убрать кнопку Cancel для этого конкретного мессаджа

**Comment by MariiaNebesnova** [comment]
3.2.234
