### ISSUE TITLE
Дабл клик для редактирования локатора?

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#616]
Возможно стоит добавить дабл клик по локатору что бы вызывать окно редактирования
Кликать надо во фрейм с текстом (от иконки состоянии - до иконки меню справа)

**Comment by SemyonKuznetsov** [comment]
нажатие по области текстового фрейма

**Comment by MariiaNebesnova** [comment]
надо ли убирать опцию Edit из меню?

**Comment by AlexeyGirin** [comment]
Опцию меню - сохранаяем

**Comment by MariiaNebesnova** [comment]
3.2.234
