### ISSUE TITLE
Перепридумать архитектуру отправку тасок на бэк

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#617]
Сейчас - вместе с каждым локатором который отправляется на сервер для расчёта - отправляется вся страничка целиком. Нормально для пары локаторов, но для сотни - это уже огромная проблема - система зависает в состоянии ожидания начала расчёта на десятки секунд. Это плохо.
Нужно перепридумать архитектуру таким образом, что бы единожды отправленную страничку - не переотправлять ещё раз заново хотя бы в ближайшее время

**Comment by MarinaFm** [comment]
В рамках этой задачи порегрессили плагин
