### ISSUE TITLE
Не попасть в меню локатора - оно закрывается быстрее чем я навожу мышку

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#619]
Не попасть в меню локатора - оно закрывается быстрее чем я навожу мышку

**Comment by AlexeyGirin** [comment]
Решили сделать по закрытие меню по Click Away

**Comment by MariiaNebesnova** [comment]
+ сдвинуть так, чтобы дроп даун не закрывал кнопки "..." для локатоорв ниже

**Comment by MariiaNebesnova** [comment]
3.2.234

**Comment by MarinaFm** [comment]
Меню локатора не прикреплено к кнопке меню '...' ,поэтому при скроле меню локатора уползает от него и становится непонятно к какому локатору оно было открыто.
Уточнить, нужно ли прикрепить меню к локатору?

**Comment by MarinaFm** [comment]
Приклеили меню к кнопке в сборке 3.2.235
