### ISSUE TITLE
[US-14-8] Редактирование локатора после ухода со странички

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#625]
Если вернуться к редактированию пэйдж обжекта после того как мы ушли со странички с которой он был создан - у нас изчезает техническая возможность валидации локаторов элементов (странички то - уже нет, а если есть - она может быть не в том состоянии)
В этом случае - стоит предупреждать пользователя, что валидация локатора работать не будет и все изменения он делает на свой страх и риск

**Comment by MariiaNebesnova** [comment]
В какой момент появляется предупреждение? когда выбрали в меню опцию Edit list?

**Comment by AlexeyGirin** [comment]
> В какой момент появляется предупреждение? когда выбрали в меню опцию Edit list?

Если на момент открытия редактивания локатора - он валиден - валидацию оставляем
если нет - выводим предупреждение, что валидация не доступна

**Comment by MariiaNebesnova** [comment]
на предупреждение нужен дизайн или просто сделаем антовским статичным Alert'ом?

**Comment by SemyonKuznetsov** [comment]
дубликат #926?
