### ISSUE TITLE
Внести информацию о страничке в заголовок пэйдж обжекта

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#626]
При создании пэйджобжекта - информация о том с какой странички мы его создали - отсутствует.
Необходимо это поправить

**Comment by savinovava** [comment]
Пытаемся решить следующие проблемы:
- Отображение того, что Page Object в состоянии редактирования
- Отображение названия Page Object
- Если страница изменила состояние или мы пытаемся редактировать Page Object на другой странице, и, мы пытаемся на ней редактировать Page Object -> разрешаем редактирование, но валидация отключена

**Comment by SemyonKuznetsov** [comment]
<img width="565" alt="Снимок экрана 2022-08-24 в 10 36 16" src="https://user-images.githubusercontent.com/101407186/186359045-8ace861d-a22a-4abc-b3dd-58b00b906a34.png">

**Comment by SemyonKuznetsov** [comment]
<img width="580" alt="Снимок экрана 2022-08-24 в 10 37 03" src="https://user-images.githubusercontent.com/101407186/186359224-e317da11-f0a3-4f59-adc5-fdab4ce03bf4.png">

**Comment by AlexeyGirin** [comment]
2 типа редактирование
1. Create
2. Editing

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6083%3A327610)

задача решалась в контексте #584, необходимо проверить правильность текстов

**Comment by SemyonKuznetsov** [comment]
<img width="349" alt="Снимок экрана 2022-08-30 в 18 34 36" src="https://user-images.githubusercontent.com/101407186/187479422-ae8555f8-b9f7-4664-b7e9-ed4948c91a00.png">

**Comment by AlexeyGirin** [comment]
Не Generating а Creating

**Comment by SemyonKuznetsov** [comment]
Нужно поменять текст кнопки "Generate" на "Create"

**Comment by SemyonKuznetsov** [comment]
<img width="314" alt="Снимок экрана 2022-08-31 в 11 50 52" src="https://user-images.githubusercontent.com/101407186/187638714-e6447ea6-6177-49af-87b3-51caecd6d720.png">

**Comment by SemyonKuznetsov** [comment]
Необходимо решить, что важнее -- начало или конец ссылки URL? Можем сделать тултип с многоточием в начале или середине и занять им до 70% ширины экрана плагина

<img width="458" alt="Снимок экрана 2022-09-05 в 17 43 19" src="https://user-images.githubusercontent.com/101407186/188474206-a5286183-1cad-4ffc-88d4-61b7b97943e3.png">

**Comment by AlexeyGirin** [comment]
1. Сделать тултип полноразмерным (без элипсинга)
2. Добавить функцию копирования (например - по нажатию на тултип)

**Comment by SemyonKuznetsov** [comment]
![400](https://user-images.githubusercontent.com/101407186/188576283-e6844f6e-ccb4-41e4-aece-2a32e58efb64.png)

**Comment by SemyonKuznetsov** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/101407186/188729976-0608156c-0f7f-4639-94d2-3a41f428f0be.png)

**Comment by SemyonKuznetsov** [comment]
есть проблема -- из контекстного меню не получается скопировать выделенный текст из тултипа (потому что когда курсор уходит в поле контекстного меню, тултип изчезает), при этом ctrl+c работает

**Comment by MariiaNebesnova** [comment]
3.2.254
