### ISSUE TITLE
При открытии плагина для новой веб-страницы появляется сообщение 'You can use the plugin only within 1 tab!'

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#629]
JDN v 3.2.232
Back-end v 0.1.2

Используется впн
1. Открыть веб-страницу_1 и плагин для нее
2. Закрыть веб-страницу_1
3. Открыть веб-страницу_2 и плагин для нее

ОР: Плагин показывает 'Trying to access server...', затем готов к генерации пейдж объектов
ФР: Плагин показывает 'Trying to access server...', затем появляется предупреждение 'You can use the plugin only within 1 tab!'
(При нажатии 'Retry' плагин готов к работе)

**Comment by MariiaNebesnova** [comment]
3.2.243

**Comment by Maksim-Kviatkovskii** [comment]
С локальным бэком не воспроизводится, на облаке нет возможности проверить
