### ISSUE TITLE
[US-6-2]Чекбоксы следует очищать после удаления/восстановления локаторов

### ISSUE THREAD

**Issue by Dashnik** [jdi-testing/jdn-ai#63]
Шаги для воспроизведения:
1) открыть JDN вкладку>Выполнить Идентификацию.
2) Выделить несколько локаторов из раздела Generated и нажать удалить.

**Фактический результат:**
Локаторы перемещены в раздел Deleted и они выделены.
![image](https://user-images.githubusercontent.com/35660327/141098153-00fe714d-1544-406a-b7bd-944df562424d.png)

**Ожидаемый результат:**
Локаторы перемещены в раздел Deleted и чекбоксы с локаторами не выделены.
![image](https://user-images.githubusercontent.com/35660327/141098293-83b6bdbe-dcda-492c-a2d3-2d57ace49805.png)

**Comment by AlexeyGirin** [comment]
@IoffeM проверить - если пофикшено - закрыть

**Comment by IoffeM** [comment]
JDN v 3.1.127
Back-end v 2022-02-12-11.36.19
Chrome

still actual

**Comment by MariiaNebesnova** [comment]
3.1.146

**Comment by MariiaNebesnova** [comment]
By clicking Delete single or Delete Group: delete and unselect locators
By clicking Restore: restore locator (one or many) with a selection value as it was in Deleted state
By clicking Cancel on Notification panel: restore locator with a selection value as it was before deleting

**Comment by ioffem** [comment]
JDN v 3.1.146
Back-end v 2022-02-12-11.36.19
Chrome

By clicking Delete single or Delete Group: delete and unselect locators - passed

By clicking Restore: restore locator (one or many) with a selection value as it was in Deleted state - passed

By clicking Cancel on Notification panel: restore locator with a selection value as it was before deleting - passed

Restore cancelling - @MariiaNebesnova  are we going to use Cancel logic or skip it?

**Comment by MariiaNebesnova** [comment]
3.1.147

**Comment by ioffem** [comment]
JDN v 3.1.147
Back-end v 2022-02-12-11.36.19
Chrome

done
