### ISSUE TITLE
Одновременный поиск серверов бэка

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#633]
Cейчас - мы ищем возможные сервера бэка (клауд или локальный) последовательно. Сперва один, а если не нашли - следующий.
Эта логика приводит к долгой задержке если первый сервер (клаудный, на данный момент) не доступен.
Хотелось бы осуществлять поиск серверов - в параллели. И если какой-то находится первым - тут же его брать как основной и начинать использовать.

**Comment by MariiaNebesnova** [comment]
3.2.237
