### ISSUE TITLE
[Medium] При нажатии Retry не происходит переключение с удаленного сервера на локальный докер (и наоборот)

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#634]
JDN v 3.2.236
Back-end v 0.1.2

1. Запустить генерацию с впн
2. Отключить впн в момент генерации локаторов
3. Запустить локальный докер
4. Нажать в плагине Retry 

ОР: Генерация локаторов возобновляется используя локальный докер
ФР: Генерация локаторов возобновляется и появляется сообщение 'Network error...'. Генерацция не идет

При этом, если снова включить впн -> генерация локаторов возобновляется.

Уточнить, должен ли плагин переключаться с удаленного сервера на локальный докер (и наоборот), если генерация локаторов уже началась?

**Comment by AlexeyGirin** [comment]
Не баг
