### ISSUE TITLE
На больших страничках - не обновляется UI если свернуть браузер

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#638]
Воспроизводится на локально запущенном докере.

Откройте - https://www.google.com/search?q=JDI&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiDzvjtoc35AhV8hP0HHcCZAI0Q_AUoAXoECAIQAw&biw=1904&bih=959&dpr=1
промотайте до конца (там примерно будет 2000 картинок)

Создайте новый пэйдж объект (HTML5) - система начнёт распознавать объекты.
Сверните окно браузера.
(за состоянием процессе можно наблюдать через консоль сервера)
В тот момент когда сервер начнёт считать локаторы - разверните окно браузера обратно

В браузере - попрежнему не обновлённое окно и нет возможности управлять ситуацией

**Comment by Maksim-Kviatkovskii** [comment]
Not reproducing, window updates after a 1-2 seconds
