### ISSUE TITLE
Не работает транслитерация на русский в экспортируемых файлах

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#642]
JDN v 3.2.239
Back-end v 0.1.22022-08-22-12.21.39

1.Открыть страницу с русским текстом
(например, https://ru.wikipedia.org/wiki/%D0%A4%D0%B8%D0%BA%D1%83%D1%81)
2. Сгенерировать локаторы
3. Загрузить файл к себе
4. Открыть java файл в папке src\main\java\site\pages

ОР: Русский текст локатора отображается корректно, также как в плагине
ФР: Транслитерация не работает

![image](https://user-images.githubusercontent.com/88709848/186370997-a8220cb3-e008-4eb4-a957-23b8db3f9674.png)

**Comment by MariiaNebesnova** [comment]
3.2.240
