### ISSUE TITLE
[US-9-2]Дизайн показа инструкции на панели плагина (не модалкой, как это хотели изначально)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#646]
Система должна проверять наличие доступного и запущенного бэкэнда (одновременно проверять два источника - наличие локального сервера и доступность клауд сервера).
Если таковые недоступны совсем вообще - выводить на экран инструкцию по запуску и инсталляции серверной части (раздел "Setup server part" из файла https://github.com/jdi-testing/jdn-ai/blob/master/README.md).
Если что-то есть - подключаться к нему. Если доступны оба - подключаться к тому который обнаружили первым.
Если версия первого попавшегоя сервера - несовместима с версией плагина - пробовать подключиться ко второму источнику. Если его нет или его версия тоже не совместима с версией плагина - выводить инструкцию по обновлению плагина и/или серверной части (разделы "Setup plugin to Chrome" и "Setup server part" из файла https://github.com/jdi-testing/jdn-ai/blob/master/README.md)

Изначально - мы планировали это делать выводя инструкцию через модалку (был даже сделан дизайн который можно посмотреть в задаче #18)
Но потом, мы эту историю перепридумали в следующем направлении:
1. Инструкция выводится на панели плагина
2. Инструкция не захардкоржена, а динамически подгружается из ReadMe файла из репозитория

**Comment by SemyonKuznetsov** [comment]
может ли быть такая ситуация, что у пользователя на 3 шаге с проверкой (при условии что он всё сделал правильно) всё равно что-то не сработает (например проблема с интернетом)? 

1. Какие проблемы могут возникнуть?
2. Даём ли мы дальнейшие инструкции или просим связаться с нами?

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6207%3A330344)


![step 1](https://user-images.githubusercontent.com/101407186/187476949-e73d7dec-253b-4531-b95d-b285a7cb0dec.png)

![step 2](https://user-images.githubusercontent.com/101407186/187476954-a956dbed-7c8e-4253-ab8b-9e5405fcc55b.png)

![step 3](https://user-images.githubusercontent.com/101407186/187476959-f4fe7553-38ca-4fb4-bce7-39beffac30cd.png)

![error alert](https://user-images.githubusercontent.com/101407186/187477034-ab99f1f3-7291-47ac-979b-075f65f2e538.png)

![error alert 2](https://user-images.githubusercontent.com/101407186/187477032-2c0020d5-796f-41f4-8077-fb0db9254104.png)

**Comment by SemyonKuznetsov** [comment]
хочу узнать мнение про ошибку при проверке, в первом случае это общее флоу когда мы выводим алерт снизу плагина, во втором как будто бы "ближе" к пользователю и месту действия

**Comment by SemyonKuznetsov** [comment]
Необходимо обновить строчку про повершелл, перенести её наверх над строчками с кодом

![step 2](https://user-images.githubusercontent.com/101407186/187626820-894b77a6-7f7e-4cb6-8427-b35165df88e3.png)

**Comment by AlexeyGirin** [comment]
Инструкция к продукту - лежит тут - https://github.com/jdi-testing/jdn-ai/blob/master/README.md

**Comment by AlexeyGirin** [comment]
Готово. Остальное будет делаться в контексте задачи #18
