### ISSUE TITLE
При генерации плагин выдает поломанные символы для других языков

### ISSUE THREAD

**Issue by MarinaFm** [jdi-testing/jdn-ai#649]
JDN v 3.2.241
Back-end v 0.1.2

Пока что, поломанные символы замечены только для гугл картинок для иврита:
1. Открыть https://www.google.com/search?q=jdn&rlz=1C1SQJL_enRU922RU923&sxsrf=ALiCzsY-ilmz9GDgpHSOdDM5cWshpLU5ug:1661437320372&source=lnms&tbm=isch&sa=X&ved=2ahUKEwix_q-qmOL5AhViX_EDHf3UBcwQ_AUoAXoECAIQAw&biw=726&bih=572&dpr=1.5
2. Сгенерировать
3. Проверить список локаторов

ФР: Для элемента на иврите плагин выдает поломанные символы. При загрузке файла - поломанные символы отображаются в файле \src\main\java\site\pages
ОР: Все элеменнты отображаются корректно, нет поломанных символов. В экспортируемом файле сохраняются элементы с корретными символами.

![image](https://user-images.githubusercontent.com/88709848/186700820-0ee0a922-d3fb-4fb9-928f-b2b265729fb5.png)
![image](https://user-images.githubusercontent.com/88709848/186701020-b8d32a41-980e-40af-838d-8dbe0c6b3a30.png)

Некорректное отображение некоторых умляутов:
![image](https://user-images.githubusercontent.com/88709848/186707929-1dfefaca-bd5d-40e5-a394-7d9afde662d8.png)

**Comment by spiridonovfed** [comment]
Добавил фикс в бэкенд. Проблема решается автоматически без правок со стороны фронтенда

**Comment by Maksim-Kviatkovskii** [comment]
Проблема с локалью вынесена в отдельную таску
https://github.com/jdi-testing/jdn-ai/issues/659
