### ISSUE TITLE
[NR-11] Проинвестигировать возможность авто-инкремента версии бэка при сборке (на тех же принципах на которых это сделано с фронтом)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#650]
Проинвестигировать возможность авто-инкремента версии бэка при сборке (на тех же принципах на которых это сделано с фронтом)

**Comment by MariiaNebesnova** [comment]
3.2.257

**Comment by spiridonovfed** [comment]
http://ecsb003017b9.epam.com:5000/docs
версия меняется рядом с заголовком (текущая 0.2.1) и автоинкрементиться на каждый пуш в ветку develop

**Comment by MariiaNebesnova** [comment]
3.2.258
