### ISSUE TITLE
Maintenance time notification logic implementation

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#654]
Сейчас при обновлении бэка - для фронта эта ситуация остаётся ВНЕЗАПНОЙ.
Возможно нам нужно придумать механизм, который позволяет пользователю узнать что именно сейчас сервер может ВНЕЗАПНО исчезнуть потому, что мы его обновляем

**Comment by savinovava** [comment]
В процессе выкладки новой версии, видно, работает ли кто-то с сервером. Мы рассчитываем, что обновлять версию будем, когда с сервером никто не работает.
