### ISSUE TITLE
[US-5-6]Create generator for Vuetify model

### ISSUE THREAD

**Issue by JuliaElizarova** [jdi-testing/jdn-ai#665]
Element's table: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/59670529/Vue.js+Element+s+table

US: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/61603841/US-5-6+Recognition+of+elements+from+Vue.js+library

- [x] Alerts
- [x] Application - НЕ РАСПОЗНАЁМ
- [x] Aspect ratios - НЕ РАСПОЗНАЁМ
- [x] Badge
- [x] Avatars - НЕ РАСПОЗНАЁМ
- [x] Banners - НЕ РАСПОЗНАЁМ
- [x] App bars
- [x] Toolbars
- [x] System bars
- [x] Bottom navigation
- [x] Bottom sheets
- [x] Buttons
- [x] Floatingactionbuttons
- [x] Breadcrumbs
- [x] Calendars
- [x] Cards
- [x] Carousel
- [x] Chip
- [x] Dialogs
- [x] Dividers - НЕ РАСПОЗНАЁМ
- [x] Expansion Panels
- [x] Footers - НЕ РАСПОЗНАЁМ
- [x] Autocomplete
- [x] Checkboxes
- [x] Combobox
- [x] File inputs
- [x] Forms - НЕ РАСПОЗНАЁМ
- [x] Input
- [x] OTP Input
- [x] Overflow buttons
- [x] Radio Buttons
- [x] Range Slider
- [x] Selects
- [x] Slider
- [x] Switches
- [x] Text fields
- [x] Text areas
- [x] Grid system - НЕ РАСПОЗНАЁМ
- [x] Button Groups
- [x] Chip Groups
- [x] Item Groups - НЕ РАСПОЗНАЁМ
- [x] List Item Groups - НЕ РАСПОЗНАЁМ
- [x] Slide Groups
- [x] Windows
- [x] Hover
- [x] Icons - НЕ РАСПОЗНАЁМ
- [x] Images - НЕ РАСПОЗНАЁМ
- [x] Lazy - НЕ РАСПОЗНАЁМ
- [x] Lists
- [x] Menu
- [x] Navigation Drawer
- [x] Overlays - НЕ РАСПОЗНАЁМ
- [x] Pagination
- [x] Parallax - НЕ РАСПОЗНАЁМ
- [x] Colorpicker
- [x] Date Picker
- [x] Date pickers - month
- [x] Time picker
- [x] Progress Circular - НЕ РАСПОЗНАЁМ
- [x] Progress Spinner - НЕ РАСПОЗНАЁМ
- [x] Progress Linear - НЕ РАСПОЗНАЁМ
- [x] Progress Bar - НЕ РАСПОЗНАЁМ
- [x] Ratings
- [x] Sheets - НЕ РАСПОЗНАЁМ
- [x] Skeleton Loaders - НЕ РАСПОЗНАЁМ
- [x] Snackbars - НЕ РАСПОЗНАЁМ
- [x] Sparklines - НЕ РАСПОЗНАЁМ
- [x] Steppers
- [x] Subheaders - НЕ РАСПОЗНАЁМ
- [x] Data iterators - НЕ РАСПОЗНАЁМ
- [x] Simple tables
- [x] Data Tables
- [x] Tabs
- [x] Timelines
- [x] Tooltips - НЕ РАСПОЗНАЁМ
- [x] Treeview
- [x] Virtual scroller

**Comment by AlexeyGirin** [comment]
Done
