### ISSUE TITLE
Update progress bar and notifications

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#669]
it is necessary to assemble all the components according to the notifications at the bottom of the plugin and update them to ant.design

**Comment by SemyonKuznetsov** [comment]
#584 main task

**Comment by SemyonKuznetsov** [comment]
[progress bar prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=6727%3A339996&viewport=473%2C-8227%2C0.35&scaling=scale-down-width&starting-point-node-id=6727%3A339996) click to start

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6722%3A339096)

[component link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163826%3A164032)

[ant link](https://ant.design/components/progress/)

<img width="524" alt="Снимок экрана 2022-10-04 в 19 50 51" src="https://user-images.githubusercontent.com/101407186/193879402-0d5822b1-8494-4a30-89de-1a11e88e677e.png">


![ll page](https://user-images.githubusercontent.com/101407186/193880627-007bbbc5-374b-479f-85d4-cd291224f46c.png)

![ll page-1](https://user-images.githubusercontent.com/101407186/193880621-c67565e1-6f28-4753-8f8f-cb6beb274925.png)

![ll page](https://user-images.githubusercontent.com/101407186/193880808-18365bf7-eed9-4255-81ab-48472473cd3c.png)

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163828%3A166420)

![Снимок экрана 2022-10-04 в 20 04 52](https://user-images.githubusercontent.com/101407186/193882127-b1e33c0e-b0e7-4ff3-bfd4-4836f29e5cf2.png)

**Comment by AlexeyGirin** [comment]
Убираем successfully везде!

**Comment by MariiaNebesnova** [comment]
notifications are reworked in [3.2.272](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.272)

task was decomposed and progress bar will be updated in #726
