### ISSUE TITLE
[1pt][NR-2] Исправить отображение поп-апов

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#67]
На сторонних от JDN сайтах, поп-апы отображаются не верно - изменяется стиль, шрифт, положение элементов.

1) Settings
<img width="1435" alt="Screenshot 2021-11-03 at 10 39 02" src="https://user-images.githubusercontent.com/89466817/141939525-5b970179-f495-4292-a016-b109abc585b5.png">

2) Download
<img width="1438" alt="Screenshot 2021-11-16 at 07 42 14" src="https://user-images.githubusercontent.com/89466817/141939296-2f644401-581f-4400-914c-fda6eee7b299.png">

**Comment by MariiaNebesnova** [comment]
also see [#369](https://github.com/jdi-testing/jdn/issues/369)

**Comment by MariiaNebesnova** [comment]
3.0.95

**Comment by MariiaNebesnova** [comment]
3.0.96

**Comment by pulya-na-vullet** [comment]
<img width="1240" alt="Снимок экрана 2021-12-09 в 11 42 58 AM" src="https://user-images.githubusercontent.com/61897393/145363053-20d44115-6620-44d1-b296-647deca6978d.png">
Баг воспроизводится
https://www.serioverify.com/
JDN v 3.0.96
Back-end v 2021-11-26-14.32.52

**Comment by MariiaNebesnova** [comment]
![image](https://user-images.githubusercontent.com/82033805/145951099-13fba460-370e-4667-bd97-7596f496f121.png)

https://mui.com/discover-more/showcase/

**Comment by mariia-tokarchuk** [comment]
JDN v 3.0.100
Back-end v 2021-12-01-14.52.21

https://vuetifyjs.com/en/components/data-tables/#usage

<img width="565" alt="Screenshot 2021-12-14 at 20 51 57" src="https://user-images.githubusercontent.com/89466817/146071546-d899f8f4-3639-4562-8f1e-7273f94fd776.png">

<img width="504" alt="Screenshot 2021-12-14 at 20 52 28" src="https://user-images.githubusercontent.com/89466817/146071567-60536ddd-e5a5-4056-9975-20abacfcfcf8.png">

<img width="754" alt="Screenshot 2021-12-14 at 20 52 40" src="https://user-images.githubusercontent.com/89466817/146072014-8890f271-838d-4d71-ad2e-3f4a9c260590.png">

**Comment by savinovava** [comment]
Задача по приоритезации стилей на @kostrubin 
в MVP не включаем, так как потребуется визуальный регресс

**Comment by MariiaNebesnova** [comment]
see also #177

**Comment by savinovava** [comment]
С комментариями от @toshQA 
Сайт “https://www.doit-intl.com/?utm_source=materialui&utm_medium=referral” некорректно отображается попап настроек
![image](https://user-images.githubusercontent.com/53625116/147539619-2023bd17-e1d2-4fd6-bbf6-5ba5ed35fb53.png)

**Comment by AlexeyGirin** [comment]
Нужно залить в мастер и можно будет тестировать

**Comment by MariiaNebesnova** [comment]
3.1.108

**Comment by DaryaGurtovenko** [comment]
1 pt for the first retest. Potentially, +0.5/1 pt if additional defects

**Comment by lisatatarinova** [comment]
со стороны QA закрыто в рамках ошибки приоритезации стилей.
однако с отображением поп-ап все еще возникают проблемы, будут заведены отдельные баги
