### ISSUE TITLE
Иконка при потере соединения с облаком не соответствует макету

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#677]
Иконка при потере соединения с облаком не соответствует макету (можно глянуть в https://github.com/jdi-testing/jdn-ai/issues/584)
![image](https://user-images.githubusercontent.com/109746268/189916860-e53a59c5-1175-4289-a8b7-f36c244cebc1.png)

**Comment by MariiaNebesnova** [comment]
3.2.261
