### ISSUE TITLE
Visual update modals and popups

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#680]
update to ant.desgn

**Comment by SemyonKuznetsov** [comment]
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/101407186/190399153-b372a095-31af-453b-b6c5-80e741766034.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/101407186/190399156-f3dbaeeb-a248-486b-8cfe-be38f723bbd4.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/101407186/190399158-eeb921e1-5321-4449-8294-000efb498d04.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/101407186/190399159-66566783-5ed8-45b0-a7e8-c7ed7e5fb131.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/101407186/190399162-b15c0d20-c356-4646-89c4-80ee2396ff34.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/101407186/190399165-b06f6256-6fa2-4014-8c4b-c29f43bfa2cf.png)
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/101407186/190399169-fdd6a575-495e-4eb2-bc0a-0226ffbf2812.png)
![MicrosoftTeams-image](https://user-images.githubusercontent.com/101407186/190399172-1ad5e17b-889d-4a8a-86f7-247f7a10a1cf.png)

**Comment by SemyonKuznetsov** [comment]
предлагаю вместо 1 сделать 2

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6563%3A337132)
![Confirm the selection](https://user-images.githubusercontent.com/101407186/191274824-65ef713e-f970-43ae-a5af-a69cec79704e.png)

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6563%3A337166)
![Confirm the selection-1](https://user-images.githubusercontent.com/101407186/191274819-d435de17-62d6-4a2b-929b-e4e457b8aae8.png)

**Comment by SemyonKuznetsov** [comment]
в целом то же самое, но у старого варианта на месте соединения накладываются бэкграунды компонента и видно полоску (вторая картинка) — пофикшено

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6564%3A337115)
![Tooltip](https://user-images.githubusercontent.com/101407186/191275484-09bee9db-3f27-441f-a495-92926f9ccb00.png)

<img width="748" alt="Снимок экрана 2022-09-20 в 16 52 26" src="https://user-images.githubusercontent.com/101407186/191276211-07bc4c58-0d3f-4008-9bf7-2be4ae78bc68.png">

**Comment by SemyonKuznetsov** [comment]
2 версии

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6562%3A337080)
![You have unsaved chages](https://user-images.githubusercontent.com/101407186/191273989-0a00887f-0cb2-4550-bb18-801b2cd83a4b.png)

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6578%3A337102)
![Confirm the selection](https://user-images.githubusercontent.com/101407186/191777902-50a32e23-725e-424e-a88b-70be25b5d47b.png)

**Comment by SemyonKuznetsov** [comment]
@MariiaNebesnova я сделал вторую версию модалки с сохранением👆 
пока не знаю насколько критично что без cancel (третья кнопка тут кажется перебором) и крестика на закрытие модалки (он не предусмотрен антом), хотелось бы потестить

**Comment by MariiaNebesnova** [comment]
> @MariiaNebesnova я сделал вторую версию модалки с сохранением👆 пока не знаю насколько критично что без cancel (третья кнопка тут кажется перебором) и крестика на закрытие модалки (он не предусмотрен антом), хотелось бы потестить

вприципе, есть креситк чтобы отменить случайно открытый диалог

**Comment by MariiaNebesnova** [comment]
[3.2.265](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.265)

**Comment by MariiaNebesnova** [comment]
please, also check #701

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6703%3A338289)

![Снимок экрана 2022-10-03 в 14 14 1](https://user-images.githubusercontent.com/101407186/193573076-b43c69d5-70e3-4a1a-a57c-866132a14e0b.png)

![11](https://user-images.githubusercontent.com/101407186/193573233-4d2061b1-3906-41ee-ac8a-a179ea9b0dcd.png)

**Comment by Maksim-Kviatkovskii** [comment]
В целом ок, расхождения с макетом вынесены в https://github.com/jdi-testing/jdn-ai/issues/680
