### ISSUE TITLE
Visual update Page object

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#681]
- [x] 1. локаторы в списке сливаются с друг другом, необходимо поменять отступы или высоту строки
- [x] 2. изменить иконки и чекбоксы самих PO
- [x] 3. верхняя навигация
- [x] 4. нижний отступ у основного фрейма

**Comment by SemyonKuznetsov** [comment]
![image](https://user-images.githubusercontent.com/101407186/190410581-fdfd4e50-baeb-44c5-8603-2351a71a4330.png)

**Comment by SemyonKuznetsov** [comment]
![po page](https://user-images.githubusercontent.com/101407186/195278829-de90a604-2c79-4d65-8b84-9443c703492a.png)

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6791%3A339089)
[prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=6791%3A339089&viewport=661%2C-4576%2C0.2&scaling=scale-down-width&starting-point-node-id=6791%3A339089)

![po page-1](https://user-images.githubusercontent.com/101407186/195306055-632cf224-4712-4bc9-a567-8c3c71e65307.png)
![po page-2](https://user-images.githubusercontent.com/101407186/195306064-6379fea4-7359-43fd-96cd-7f88d9796275.png)
![po page](https://user-images.githubusercontent.com/101407186/195306073-80e7a11e-4459-4817-82be-27079e30abac.png)
<img width="323" alt="Снимок экрана 2022-10-12 в 12 30 38" src="https://user-images.githubusercontent.com/101407186/195306160-c413f2f8-d15f-4439-8fce-0f858222159a.png">

**Comment by SemyonKuznetsov** [comment]
общие обновленные характеристики для фрейма Locators_list:
Radius 2px
border: 1px solid #D9D9D9 **Outer** border

**Comment by MariiaNebesnova** [comment]
[3.2.275](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.275)
