### ISSUE TITLE
[US-9-1] Возможность посылать множество разноформатных аттачментов с "report problem"

### ISSUE THREAD

**Issue by spiridonovfed** [jdi-testing/jdn-ai#682]

**Comment by spiridonovfed** [comment]
Отредактированный эндпоинт:
http://ecsb003017b9.epam.com:5000/docs#/default/report_problem_report_problem_post

Для тестирования есть вспомогательный эндпоинт, переводящий файл в строку base64:
http://ecsb003017b9.epam.com:5000/docs#/default/file_bytes_to_str_file_bytes_to_str_post
В таком формате приходит содержимое файла в поле file_content

**Comment by spiridonovfed** [comment]
Письма приходят на SupportJDI@epam.com

**Comment by Maksim-Kviatkovskii** [comment]
![image](https://user-images.githubusercontent.com/109746268/196625421-af5914c6-59c3-4069-b75e-de799cdb4d28.png)

Запрос вроде правильный уходит, а в консоли всё равно ошибка incorrect padding

**Comment by Maksim-Kviatkovskii** [comment]
- Файлы с расширениями .json, .txt, .zip (и .rar тоже, наверное) - не принимает бек, нужно поправить string который отдаётся с фронта
- Файлы с расширением .rar не проходят валидацию на фронте

**Comment by MariiaNebesnova** [comment]
3.2.280
