### ISSUE TITLE
[US-9-1] Требования к аттачментам

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#690]
На диалоге Report a problem нам нужно показывать весьма объемные ограничения к аттачментам которые мы предъявляем пользователю.

1. Разрешенные расширения: image/*, *.zip, *.rar, *.json, *.txt
2. Общий размер всех файлов - не более 10 Мб
3. Размер одного файла - не более 2 Мб
4. Можно приложить не более 10 файлов
5. При открытии диалога автоматом прикладываем данные страницы .json, это файл можно скачать, можно удалить без эрроров

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7446%3A360721&t=SMUVOHz5xGrcrewJ-4)

![image](https://user-images.githubusercontent.com/101407186/206552460-17751e76-e63a-4f37-8429-7f086db53622.png)

**Comment by SemyonKuznetsov** [comment]
попробовал сократить описание, чтобы оно влезало хотя бы к 2ум файлам, если больше -> оно уезжает скроллом, тк по умолчанию у модального окна стоит максимальная высота

![#392 Report a problem max size 1](https://user-images.githubusercontent.com/101407186/191768172-499fadb4-30f1-458e-b383-1cc98a84994b.png)

**Comment by SemyonKuznetsov** [comment]
мы знаем причину еррора и поэтому в тултипе текст будет по конкретным ошибкам

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6613%3A337394)

<img width="283" alt="Снимок экрана 2022-09-23 в 15 19 48" src="https://user-images.githubusercontent.com/101407186/191958711-482a186c-0a62-4ca0-a6c6-f4f9a73b4aec.png">

**Comment by savinovava** [comment]
#682

**Comment by MariiaNebesnova** [comment]
[3.4.294](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.294)

**Comment by Maksim-Kviatkovskii** [comment]
Нужно допилить валидацию на максимальное количество файлов и максимальный общий размер

**Comment by savinovava** [comment]
Updated: https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/12910713/US-9-1+Report+a+problem

**Comment by arslanbekova** [comment]
[3.4.302](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.302)
