### ISSUE TITLE
[E-5] Обогатить элементы даталэйблами с типом после распознавания

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#691]
Сейчас - после распознавания - мы добавляем к каждому элементы атрибут jdn-hash.
Необходимо добавлять так же атрибут data-label со значением из мэпига.
Важно - при обновлении типа элемента после редактирования - data-label тоже должен обновляться

**Comment by MariiaNebesnova** [comment]
это нужно в продакшн? или сделать опционально?

**Comment by MariiaNebesnova** [comment]
[3.2.268](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.268)
