### ISSUE TITLE
B кнопке upload нет отступа между иконкой и текстом

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#698]
3.2.261

![image](https://user-images.githubusercontent.com/109746268/192002803-46f3aadb-63d9-457d-9283-d46704794ca3.png)

**Comment by MariiaNebesnova** [comment]
[3.2.266](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.266)
