### ISSUE TITLE
Fix parsing of Readme

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#703]
@savinovava please, check Readme and clarify what sections and at what steps should be presented

**Comment by savinovava** [comment]
![image](https://user-images.githubusercontent.com/53625116/192780537-b64d76f9-07d4-43d0-a5e6-d1810e624cfc.png)

**Comment by savinovava** [comment]
![image](https://user-images.githubusercontent.com/53625116/192780907-6fdd41f4-cbbf-4335-b1fe-9db2da2f10af.png)

**Comment by savinovava** [comment]
Версию из ветки можно публиковать: https://github.com/jdi-testing/jdn-ai/tree/savinovava-readme-changes

**Comment by MariiaNebesnova** [comment]
[3.2.267](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.267)
