### ISSUE TITLE
[Low] Icons displaying bug

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#708]
upd: иконки остаются в одну строчку, но наезжают на название пейджобжекта

![image](https://user-images.githubusercontent.com/53625116/216031535-23480134-b6b0-417a-bb8f-f84ad9ac4337.png)

ограничить фрейм текста по ширине, больше чем * - переносить на вторую строку
![image](https://user-images.githubusercontent.com/101407186/216032390-0bb4955f-6ffa-4dfb-9ada-7021c602ece7.png)

**Comment by SemyonKuznetsov** [comment]
https://user-images.githubusercontent.com/101407186/193586266-072ad850-9ea1-4789-84df-8d7ca8f04c68.mov

**Comment by SemyonKuznetsov** [comment]
если будут проблемы на реализации или ещё что-то, то было второе решение: дать иконке копирования белый фон и выносить её поверх фрема с текстом при ховере на строку

**Comment by arslanbekova** [comment]
[3.7.383](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.383)

**Comment by Maksim-Kviatkovskii** [comment]
3.8.390
Опять начал воспроизводиться :(

**Comment by arslanbekova** [comment]
[3.8.395](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.395)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.8.395 Back-end v 0.2.22, Google Chrome Version 110.0.5481.77 (Official Build) (x86_64), macOS 12.6.1
