### ISSUE TITLE
[High] Нет возможности закрыть окно "You have unsaved changes"

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#709]
1. Запустить генерацию
2. Нажать кнопку "Back"
3. Проверить возможность закрыть появившееся окно "You have unsaved changes"

AR: Можно либо сохранить изменения и вернуться к списку пейдж обжектов, либо задискардить и вернуться
ER: Можно закрыть окно и остаться

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=6578%3A337102)

![Confirm the selection](https://user-images.githubusercontent.com/101407186/193809271-4751a5d4-a57c-4184-8c5c-b6931a705054.png)

**Comment by SemyonKuznetsov** [comment]
есть второй вариант -- добавить крестик, но это только для базового/кастомного большого модального окна, для [Information modal dialog](https://ant.design/components/modal/#components-modal-demo-info) который бы хотелось использовать в этих диалогах, ант не предусматривает иконки закрытия, но даёт возможность добавить больше кнопок

![You have unsaved chages](https://user-images.githubusercontent.com/101407186/193809480-6a7e29ef-81f1-4c23-b85a-c86032d5d72d.png)
