### ISSUE TITLE
icon hovering state (cursor change)

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#711]
добавить изменение курсора для V-иконки в хедере для улучшения юзабилити

https://user-images.githubusercontent.com/101407186/193847750-b24c49b0-ba5b-4847-a395-4c3672998dcb.mov

**Comment by MariiaNebesnova** [comment]
[3.2.276](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.276)
