### ISSUE TITLE
[High] Расхождения с макетом

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#718]
[Figma](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=5919%3A320755)

1. Попап Edit locator
	- У поля name есть звёздочка, у поля locator её нет. В макете звёздочек нет совсем
	- Нотификашки please fill out this field разных цветов у полей name и locator

2. Попап Delete this all
	- Название "Delete all". В макете - "Delete this page objects?"
	- Кнопка "Delete all" белая с красным контуром. В макете - полностью красная

3. Иконки в верхнем правом углу
	- Иконки на разной высоте и на разном расстоянии друг от друга
	- У иконок Readme и Report a problem нет тултипа

4. Тултипы в окне плагина
	- Видно стык между тулом тултипа и стрелкой

**Comment by MariiaNebesnova** [comment]
> * У поля name есть звёздочка, у поля locator её нет. В макете звёздочек нет совсем
обсудили с @SemyonKuznetsov, звездочка нужна

> * Нотификашки please fill out this field разных цветов у полей name и locator
подразумевается, что с красными эррорами форму сохранить нельзя, а с желтыми варнингами - можно. мы разрешаем сохранять локатор с пустым икс пасом

**Comment by MariiaNebesnova** [comment]
> Тултипы в окне плагина
> 
> * Видно стык между тулом тултипа и стрелкой

пожалуйста, приложи скриншот/сайт/путь воспроизведения. у меня пока не воспроизводится 
<img width="176" alt="image" src="https://user-images.githubusercontent.com/82033805/195599095-87a39bdb-52f3-4cb9-b4b9-7891c129d932.png">

**Comment by Maksim-Kviatkovskii** [comment]
![image](https://user-images.githubusercontent.com/109746268/195600149-8aa0635c-2fec-442e-a60c-1a7c36b85c67.png)

**Comment by MariiaNebesnova** [comment]
[3.2.276](https://github.com/jdi-testing/jdn-ai/releases/tag/3.2.276)

**Comment by MariiaNebesnova** [comment]
пункт 4 надо делать отдельной таской, потому что это баг анта и потребует больше времени на решение

**Comment by Maksim-Kviatkovskii** [comment]
п.4 вынес в https://github.com/jdi-testing/jdn-ai/issues/739
