### ISSUE TITLE
Сделать секретную кнопку или секретную комбинацию клавиш для Юли

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#719]
Проблема: Иногда - наша модель ошибается и определяет тип некоторых элементов неправильно.
В этом случае - дата сайнтист должен взять такую страничку, разметить её правильно и занести в дата сет на котором переобучить модель.
Сейчас - это делается руками и требует много действий и занимает много времени.

Ожидаемое решение:
Дата сайнтист заходит на страничку, распознаёт элементы, исправляет локаторы с неправильного типа на правильный после чего - нажимает на секретную кнопку (или секретную комбинацию клавиш - например CTRL+SHIFT+0) и получает на скачивание уже готовый для занесения в дата сет файл

**Comment by MariiaNebesnova** [comment]
что за файл?

**Comment by AlexeyGirin** [comment]
> что за файл?
Тот json который отправляется в модель

**Comment by AlexeyGirin** [comment]
Описать тут альтернативный путь
