### ISSUE TITLE
[US-3-1] Perception bar doesn't work

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn-ai#72]
Perception bar (Prediction accuracy) doesn't work with all it features:
- moving of the pointer doesn't change the marked locators on target page
- the percent value is always 50%
- all locators go to the result file

**Comment by DaryaGurtovenko** [comment]
qa = 1 pt

**Comment by MariiaNebesnova** [comment]
3.0.92

**Comment by DaryaGurtovenko** [comment]
Verified on ver. 3.0.93, fixed
