### ISSUE TITLE
[Low] Унаследовались стили сайта, не хватило изоляции (liferesources.cc)

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#721]
https://www.liferesources.cc/login.php?action=create_account

Текст в тултипах серый

![image](https://user-images.githubusercontent.com/109746268/194856669-8428e0ac-7237-48ea-ae57-99719702a96a.png)

**Comment by arslanbekova** [comment]
fixed 
https://github.com/jdi-testing/jdn-ai/issues/875
