### ISSUE TITLE
[High] add "close when clicking outside" for dropdown components

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#723]
for menu on "page objects" page and others. on the locator edit page it works

<img width="727" alt="Снимок экрана 2022-10-11 в 10 33 03" src="https://user-images.githubusercontent.com/101407186/195024691-79cf59e1-b0fe-4965-ba1f-0e24823e636f.png">

**Comment by AlexeyGirin** [comment]
Разное поведение меню на уровне ПО и на уровне локаторов

**Comment by MariiaNebesnova** [comment]
components were reworked in previous versions
