### ISSUE TITLE
[US-7-1] Улучшить наименование имени элемента, базируясь на имеющихся атрибутах элемента

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#731]
[US-7-1](https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/17956876/US-7-1+The+locators+names+are+generated+based+on+their+headings)
Сейчас правила формирования имени локаторов достаточно просты - если есть атрибут Name, то используем его, в противном случае - в качестве имени используется тип элемента и число делающее эту комбинацию уникальной.
Этого не всегда достаточно.

Нужно подумать как это сделать эту историю интересней.

**Comment by AlexeyGirin** [comment]
Требования мы собрали - Лера выложит

**Comment by MariiaNebesnova** [comment]
вопрос по пункту 3 "based on (contains text(),'Example Text')" : как ограничивать текст?

**Comment by MariiaNebesnova** [comment]
[3.4.291](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.291)
