### ISSUE TITLE
[US-15-1] Возможность выбора CSS селекторов для элементов вместо хPath или сгенерённых локаторов на основе атрибутов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#732]
Сейчас мы не предоставляем пользователю выбор типа локатора - если не получается сгенерить короткий локатор на основе атрибутов - используем полный xPath.
В то же время - пользователи иногда предпочитают использовать CSS локаторы (зачастую - только их)

Нужно дать такую возможность пользователям.
А именно:

1. Генерить JDI CSS selector locators
2. Генерить по-прежнему JDI xPath локаторы

Вопрос который надо прояснить - делать ли глобальный переключатель или всё же - дать ещё дополнительно возможность пользователю переключать единичные элементы в нужный нам тип

CSS/xPath/based on DOM-attribute

_@UI("//*[@class='MuiBox-root jss1']/div//fieldset[2]//div")
public RadioButtons radiobuttonsDiv; - class_
1. @UI("//*[@class='MuiBox-root jss1']/div//fieldset[2]//div") - (JDI xPath) locator
2. @UI - JDI attribute
3. "//*[@class='MuiBox-root jss1']/div//fieldset[2]//div" - xPath

4. @UI("#-blink-dev-tools > div:nth-child(7)") - (JDI CSS selector) locator
5. #-blink-dev-tools > div:nth-child(7) - CSS selector

### Дополнения
+ У нас могут быть в одном PO локаторы с xPath и CSS одновременно
+ не используем слово selectors, xPath & CSS locators
+ хотим переключать типа локатора после генерации, а именно в окне Edit, потому что информация у каждого элемента должна хранить оба типа локаторов
+ при смене типа локатора в окне Edit тело локатора автоматически поменяется при выборе нужного типа в селекторе
+ Имплементация на frontend

**Comment by savinovava** [comment]
Как получать CSS локатор со страницы?

Нужно ли иметь одновременно xPath локаторы и CSS локаторы? 

Применимо к каждому локатору по отдельности и/или ко всему PO (?)

**Comment by MariiaNebesnova** [comment]
Selenium локаторы и CSS селекторы - декомпозируются на разные задачи.
задача по css селекотрам требует инвестигации: необходимо найти алгоритм, позволяющий создавать оптимальный css селектор.

**Comment by AlexeyGirin** [comment]
> Как получать CSS локатор со страницы?
> 
> Нужно ли иметь одновременно xPath локаторы и CSS локаторы?
> 
> Применимо к каждому локатору по отдельности и/или ко всему PO (?)

1. Есть алгоритм (Маша умеет получать CSS селектор для элемента)
2. Нет, либо то, либо другое - это один из трёх способов как искать элемент (один из трёх типов локаторов)
3. PO может содержать микс из элементов которые ищутся разными способами

**Comment by savinovava** [comment]
Design discussion:
xPath -> CSS selector
- Нужно ли использовать selector naming? 
Chrome предлагает copy selector/copy xPath
https://www.lambdatest.com/blog/locators-in-selenium-webdriver-with-examples/
**Мы оставляем locators, не используем selectors**

**Comment by SemyonKuznetsov** [comment]
> Вопрос который надо прояснить - делать ли глобальный переключатель или всё же - дать ещё дополнительно возможность пользователю переключать единичные элементы в нужный нам тип

1. У нас могут быть в одном PO локаторы с xPath и CSS одновременно?
2. Надо/можем ли мы добавить функционал переключения типа локатора после генерации? Переключать в редактировании?

**Comment by AlexeyGirin** [comment]
1. У нас могут быть в одном PO локаторы с xPath и CSS одновременно?
Да.

2. Надо/можем ли мы добавить функционал переключения типа локатора после генерации? Переключать в редактировании?
Да, можем. Информация у каждого элемента должна хранить оба типа локаторов

**Comment by AlexeyGirin** [comment]
Делим задачу на две:
1. Сперва делаем CSS локаторы в режиме Read Only
2. Редактирование CSS локаторов и их валидация - это будет отдельная задача

**Comment by MariiaNebesnova** [comment]
использовать библиотеку для конвертации xPath в css

**Comment by savinovava** [comment]
Для первоначальной имплементации в начале создания PO:

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7366%3A358476&t=WLIBx3uA1Y6CmfdO-4)

![image](https://user-images.githubusercontent.com/53625116/212863962-4c9f4057-1fb5-418c-8a2c-beb21c7c0683.png)

**Comment by SemyonKuznetsov** [comment]
- [ ] 1. Убрать из создания PO
- [ ] 2. Добавить в настройки
- [ ] 3. Добавит в Edit локатора

### 2. Добавить в настройки
Запоминаем выбор пользователя

[Figma link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=164236%3A168181&t=Ycz9KRAnhFFUQs3Z-4)
![image](https://user-images.githubusercontent.com/101407186/213670898-203e6c98-5eb9-43d0-86e6-eb7ecd3547b0.png)

![image](https://user-images.githubusercontent.com/101407186/213670838-fa812fb9-16b8-4e4e-a478-0ea920dbdc11.png)

### 3. Добавит в Edit локатора

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7368%3A358904&t=WLIBx3uA1Y6CmfdO-4)

- При смене типа в селекте просчитвыаем локатор и показываем его текст
- Локатор в списке меняется по нажатию кнопки Save

![image](https://user-images.githubusercontent.com/101407186/205625087-f6fdc04f-f8d5-4306-ba87-222d6b4362f1.png)
![image](https://user-images.githubusercontent.com/101407186/205625104-3567b792-c786-45d5-bec1-0080e9f62e7a.png)

**Comment by SemyonKuznetsov** [comment]
спросить Машу про Edit локатора до завершения генерации

**Comment by AlexeyGirin** [comment]
1. Если ввели кастомный локатор ДО окончания расчёта - показываться будет кастомный локатор в любом случае
2. Если вместо CSS - ввели xPath или наоборот - система должна сказать что локатор не валиден

**Comment by MariiaNebesnova** [comment]
[3.9.417](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.417)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.421 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Test result - **fail**
_Error: Invalid or unsupported XPath_ is displayed in console when generating PO with CSS locators; no generated locators are displayed in the plugin window.

Steps to reproduce:

1. Open JDN plugin
2. Click _+ Page Object_ button
3. Select any Library (e.g. HTML5)
4. Select _CSS selector_ locators type
5. Click _Generate_ button

Expected result: locators are generated

Actual result: generation starts and stops almost immediately, no generated locators are displayed in the plugin window; _Error: Invalid or unsupported XPath_ is displayed in console

https://user-images.githubusercontent.com/106632366/226570843-76df555e-be11-4823-bc3d-a61ab2be5d8a.mp4

**Comment by MariiaNebesnova** [comment]
a library, that is chosen for xPath convertation to css selectors doesn't work with xPathes that are using contain(text(), ...) functions. Moreover, as it found out, current CSS specification doesn't support selectors based on content. I can suggest few solutions:
- find a new tool for creating robust CSS selector,
- configurate Robula to avoid generating selectors using forbidden xPath functions,
- for such xPathes use full xPath for convertation to css selector

**Comment by MariiaNebesnova** [comment]
> * for such xPathes use full xPath for convertation to css selector

[3.9.427](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.427)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.428 Back-end v 0.2.27
Chrome Version 111.0.5563.112 (Official Build) (64-bit)c

Test result - **pass**
CSS locators are generated in read only mode (according to the [comment above](https://github.com/jdi-testing/jdn-ai/issues/732#issuecomment-1337186009), there will be a separated task for editing CSS locators)
![2023-03-28 11_01_47-Settings](https://user-images.githubusercontent.com/106632366/228187774-03b86c87-9586-403a-98bb-eb9d869189c9.jpg)

In the same PO, locators with xPath and CSS can be presented at the same time.
Locator type can be changed in Edit window, the body of the locator automatically changes when you select the desired type in the selector.
If CSS is entered instead of xPath, the system shows that the locator is not valid
![2023-03-28 11_07_01-Settings](https://user-images.githubusercontent.com/106632366/228189032-066d9903-b8e7-4053-87b2-618423e4244c.jpg)
