### ISSUE TITLE
[Medium] У тултипов в окне плагина видно стык между телом тултипа и стрелкой

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#739]
Вынесено из https://github.com/jdi-testing/jdn-ai/issues/718

![image](https://user-images.githubusercontent.com/109746268/196224504-2ba02665-eea3-43eb-8287-cc527e980ae0.png)

**Comment by AlexeyGirin** [comment]
Маша предоставит список всех тултипов которые нужно починить

**Comment by MariiaNebesnova** [comment]
1. Readme в Статус баре: 
<img width="215" alt="image" src="https://user-images.githubusercontent.com/82033805/200310159-e17a5c55-91fd-49c6-9912-d8d537e1196b.png">
2. Кнопка копирования, описано выше
3. Кнопки Delete all и Download all 
![image](https://user-images.githubusercontent.com/82033805/200311052-8893fcaf-0223-4a05-96e3-b828cd6013f1.png)
4. Кнопка копирования в гайде: 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/82033805/200311396-a25ac265-ed40-420a-92f5-48f4ce36814b.png">

**Comment by Iogsotot** [comment]
https://github.com/jdi-testing/jdn-ai/pull/1723
[3.15.29](https://github.com/jdi-testing/jdn-ai/releases/tag/3.15.29)

**Comment by InnaRadionova** [comment]
JDN v 3.15.31 Back-end v 0.2.70
![2024-05-13 15 04 41](https://github.com/jdi-testing/jdn-ai/assets/162306672/4170ea2d-f72d-4892-a384-50b81161ddf2)
![2024-05-13 15 05 40](https://github.com/jdi-testing/jdn-ai/assets/162306672/280eea7f-faef-4884-a59a-361b615a6699)
