### ISSUE TITLE
[1pt]Исправить стили тултипов на странице

### ISSUE THREAD

**Issue by MariiaNebesnova** [jdi-testing/jdn-ai#74]
https://www.figma.com/file/8wieNfnIvfSET3zq0r8LbX/JDN?node-id=3578%3A72364

**Comment by MariiaNebesnova** [comment]
проверить. возможно, после рефача все уже само пофиксилось

**Comment by Dashnik** [comment]
1s.p.  frontend

**Comment by Dashnik** [comment]
Бага пофикшена. Можно смотреть в билде 3.0.85 и выше.

**Comment by lisatatarinova** [comment]
test passed 3.0.88
