### ISSUE TITLE
[High] В поле поиска нет кнопки очистки

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#750]
На макете есть кнопка для очистки поля, можно глянуть в https://github.com/jdi-testing/jdn-ai/issues/267

![image](https://user-images.githubusercontent.com/109746268/198982410-adea8b05-4a21-4e1a-acab-05708c4f0366.png)

**Comment by MariiaNebesnova** [comment]
[3.3.286](https://github.com/jdi-testing/jdn-ai/releases/tag/3.3.286)
