### ISSUE TITLE
[High] Контекстное меню обрезается, если после поиска осталось меньше трёх локаторов

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#751]
Из https://github.com/jdi-testing/jdn-ai/issues/267

![image](https://user-images.githubusercontent.com/109746268/198988483-2a0f64f8-4a2f-4142-b89d-c232db71c6e0.png)

**Comment by Maksim-Kviatkovskii** [comment]
Так же при большем количестве локаторов меню уезжает наверх (думаю, rootcause тот же, так что прилеплю сюда)

![image](https://user-images.githubusercontent.com/109746268/198989498-65e25194-02e7-4afc-9520-270a84020a0c.png)

**Comment by MariiaNebesnova** [comment]
[3.3.286](https://github.com/jdi-testing/jdn-ai/releases/tag/3.3.286)
