### ISSUE TITLE
[Medium] Некорректно меняется имя локатора, если сменить тип, а потом (не закрывая попап) сменить его обратно

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#754]
JDN v 3.3.287 Back-end v 0.2.19

Из https://github.com/jdi-testing/jdn-ai/issues/121

Steps:
1. Дойти до списка локаторов (например, шаг Creating)
2. Найти локатор с именем без цифры в конце (например, "label") и открыть попап редактирования локатора
3. Сменить Block type на любой другой
4. Не закрывая попап сменить Block type на исходный

ER:
- Имя локатора сменилось на изначальное (в описанном примере - "label")

AR:
- К изначальному имени добавляется 0 ("label0")

**Comment by MariiaNebesnova** [comment]
[3.4.298](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.298)
