### ISSUE TITLE
[High] locator selection by clicking on the text (from the locator list)

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#757]
_Связана с задачей #155_

Сделать возможным выделение локатора по нажатию на текст и/или тело локатора одним кликом (даблклик для редактирования), при наведении на строку чекбокс должен получать статус hovering

**Comment by savinovava** [comment]
![image](https://user-images.githubusercontent.com/53625116/202721803-14250198-22b0-4820-a245-bb38152e1dfe.png)
Выделение локатора по клику на текст локатора ->статус active (без выделения чекбокса)

**Comment by MariiaNebesnova** [comment]
[3.5.320](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.320)

**Comment by MariiaNebesnova** [comment]
обсудили с @SemyonKuznetsov, решили, что подсвечивать в данном кейсе чекбокс - уже не актуальное требование
