### ISSUE TITLE
[US-4-5] Color mismatch when selecting

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#758]
_Связана с задачей #155_

## Несоответствие цветов, цвета поменяны наоборот

проработать дополнительно цвета с правилом "выделенное темнее выбранного"

<img width="1222" alt="Снимок экрана 2022-11-07 в 14 32 54" src="https://user-images.githubusercontent.com/101407186/200300591-d7ccaf4c-db13-4fa5-8a47-93cfca207cc5.png">

_Originally posted by @SemyonKuznetsov in https://github.com/jdi-testing/jdn-ai/issues/155#issuecomment-1305479142_

**Comment by SemyonKuznetsov** [comment]
сейчас так

<img width="448" alt="Снимок экрана 2022-11-07 в 16 51 30" src="https://user-images.githubusercontent.com/101407186/200326808-8139b85c-c60e-47fb-8845-bb1011272256.png">

**Comment by SemyonKuznetsov** [comment]
<img height="400" src="https://user-images.githubusercontent.com/101407186/200331440-2b274a12-abe2-422b-9b9e-14990d2ba6b7.png">

**Comment by SemyonKuznetsov** [comment]
зафейленный есть активный

**Comment by MariiaNebesnova** [comment]
эта задача только про подсветку страницы, для плагина - задача #766

**Comment by AlexeyGirin** [comment]
Поменять цвет выделения не входящего в ПО блока на менее красный (сейчас он красноватый)

**Comment by arslanbekova** [comment]
[3.6.360](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.360)

**Comment by arslanbekova** [comment]
Желтый цвет заменили на другой

`FFD666 для светлого, фон так же 20%
FAAD14 для активного с теми же 20% для фона`
