### ISSUE TITLE
[US-4-5] Контекстное меню для группы

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#759]
_Связана с задачей #155_

### Меню слоёв
1. Выделите группу объектов на покрытии
2. Щелкните пкм, чтобы открыть контекстное меню
3. Наведите указатель мыши на Select layer
4. Выберите локатор из списка
5. Локатор будет выделен, остальное выделение будет снято, а контекстное меню закрыто

<img width="652" alt="Снимок экрана 2022-11-07 в 15 30 39" src="https://user-images.githubusercontent.com/101407186/200310938-f90450d7-1b37-41e4-8c72-0a9b94bdc5e7.png">

**Comment by SemyonKuznetsov** [comment]
![image](https://user-images.githubusercontent.com/101407186/200402997-af797661-b468-4827-9df1-8f3fd002bdbe.png)
Здесь должны выделиться все и в меню должны быть общие действия, сейчас выполняются только для одного

Какие действия для группы есть/будут? Есть различия между меню при нажатии на экране и в списке?

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7165%3A356572)

для sub menu минимальная ширина = 150px

![image](https://user-images.githubusercontent.com/101407186/201068765-565718ab-2d38-42fe-a9d1-c0ed8b0d9274.png)

**Comment by savinovava** [comment]
Select = Add to the saved list → Add to the PO /Checkbox select/unselect

**Comment by SemyonKuznetsov** [comment]
может:
**select/unselect** для действий влияющих на чекбокс
**choose/unchoose** для действий влияющих на группу

тем самым мы разделим групповые операции и выбор локаторов на сохранение?

будет такое:
<img width="495" alt="Снимок экрана 2022-11-18 в 18 34 18" src="https://user-images.githubusercontent.com/101407186/202741950-9cead7d8-d4c2-4437-96d5-a5ca5c193bc2.png">
<img width="188" alt="Снимок экрана 2022-11-18 в 18 34 47" src="https://user-images.githubusercontent.com/101407186/202742058-bbe98bfa-2729-442a-863a-6dbccc629127.png">

**Comment by AlexeyGirin** [comment]
select/unselect - для действий влияющих на группу
add to PO/remove from PO -  для действий влияющих на чекбокс

**Comment by savinovava** [comment]
**Меню групповых операций**
![image](https://user-images.githubusercontent.com/53625116/205044735-21e8c219-459a-4df8-ad16-92b92027d1bc.png)

- Advanced calculation
- Delete

Применятся должно к группе
