### ISSUE TITLE
[US-4-5] Улучшение логики выделения локаторов в списке

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#766]
_Связана с задачей #155_ 

Наведение на локатор подсвечивает (Neutral/2) строку и чекбокс (status Hovering), первое нажатие на локатор ставит чекбокс в статус Checked и не меняет фон, при открытии контекстного меню на экране или в списке у выбранных локаторов (любого статуса - выбранные, невыбранные, удалённые или с ошибкой) фон становится темнее (Neutral/4)

Идея удаления синего выделения:
+ к любым выделенным локаторам независимо от статуса будет применяться единое действие, а синий = ассоциация активных локаторов
+ старая логика путала в цвете (ховер=выбор, разный цвет состояния ховера и выбора при разных статусах)
+ синий цвет это primary, он нужен для самых важных элементов и действий с активной логикой

+ групповые операции относим к выделенной группе

[Figma prototype](https://www.figma.com/proto/DxLzXoAT23Gcu9DmCIuTcW/Design?page-id=5919%3A320755&node-id=7106%3A350971&viewport=945%2C-11682%2C0.38&scaling=scale-down-width&starting-point-node-id=7106%3A352318)

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7106%3A352318)

<img width="1174" src="https://user-images.githubusercontent.com/101407186/200370667-ab71763b-33fd-4621-bd90-9a12c66eecc0.png">

_Originally posted by @SemyonKuznetsov in https://github.com/jdi-testing/jdn-ai/issues/155#issuecomment-1305913133_

**Comment by SemyonKuznetsov** [comment]
Поменять подсветку строк

1. Дефолт белый 
![image](https://user-images.githubusercontent.com/101407186/213690936-f4a4fb49-0462-4738-b1a0-ab54e07678e0.png)

2. Ховер на чекбокс (ховер чекбокс, светло-серый локатор) 
![image](https://user-images.githubusercontent.com/101407186/213690982-2c30f919-e860-44b2-b15c-1ed8ef3c4a95.png)

3. Ховер на строку (чекбокс дефолтный, светло-серый локатор) 
![image](https://user-images.githubusercontent.com/101407186/213691060-274e4dce-9543-4700-ad40-8855c2d79af9.png)

4. Выбранный чекбокс (селектнутый чекбокс, белый локатор) 
![image](https://user-images.githubusercontent.com/101407186/213691092-4ad978f6-9cef-460b-a686-b535fb2c2d03.png)

5. Выбранный локатор (чекбокс дефолтный, тёмно-серый локатор) 
![image](https://user-images.githubusercontent.com/101407186/213691156-162d64b1-93eb-4720-a368-112a7b50012b.png)

6. Выбран и чекбокс и локатор (селектнутый чекбокс, тёмно-серый локатор)
![image](https://user-images.githubusercontent.com/101407186/213691228-8e756fed-4000-458d-8f46-8053a39f6712.png)

7. Выбран и чекбокс и локатор и ховер (селектнутый чекбокс, тёмно-серый локатор)
![image](https://user-images.githubusercontent.com/101407186/213691292-8fec1584-960a-4bf0-b6b1-5ab1d0ce7863.png)


Если локатор выбран (тёмно-серый), то состояние ховера на строку (3 и 7) никак не меняет цвет и не делает его темнее

светло-серый FAFAFA (neutral/2)
тёмно-серый F0F0F0 (neutral/4)

**Comment by arslanbekova** [comment]
[3.6.363](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.363)
