### ISSUE TITLE
[US-11-3] доработать функционал Copy в списке локаторов и контекстном меню

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#769]
- Клик по иконке быстрого копирования всегда копирует тот full code, который мы видим
- Групповое копирование возможно только в списке

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7421%3A361071&t=os0SfWwnO3ah4vgX-4)
![image](https://user-images.githubusercontent.com/101407186/212878897-c23175c1-e9f1-4892-9a49-23726ec0f68b.png)

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7424%3A359415&t=os0SfWwnO3ah4vgX-4)
![image](https://user-images.githubusercontent.com/101407186/212878859-766f72dc-9041-4b51-83de-e4ccacb1ed45.png)

[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7663%3A361827&t=rKYgD6mHZ9bKVBLm-4)
![image](https://user-images.githubusercontent.com/101407186/212892923-45f2e6c5-91a3-4907-88ba-a79f246fb7ab.png)

**Comment by SemyonKuznetsov** [comment]
возможно ли добавить Copy в контекстное меню на покрытие?

**Comment by SemyonKuznetsov** [comment]
[Figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7421%3A361071&t=os0SfWwnO3ah4vgX-4)
![image](https://user-images.githubusercontent.com/101407186/206159924-e06189ce-90e9-4d54-a784-079b33573e9e.png)

**Comment by SemyonKuznetsov** [comment]
> * для чего пользователь копирует локатор?

чтобы вставить в свой код

> * возможно ли добавить Copy в контекстное меню на покрытие?

у нас работает негласное правило, копируем только то что видим

> * возможно ли групповое копирование?

получается что только в списке

> * имеет ли смысл полное копирование локатора или только тело xpath/css?

вопрос для будущих тестирований

**Comment by savinovava** [comment]
Что копируем?
- xPath
- Весь путь и класс, который отображен в списке
- Класс, CSS selector и xPath локатор

**Comment by SemyonKuznetsov** [comment]
возможные варианты копирование и возможная визуализация выбора
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7501%3A360900&t=WBaciC8heoON0t3P-4)

![image](https://user-images.githubusercontent.com/101407186/207925635-b5542f29-2f3f-4458-b604-f09c331bdf13.png)

**Comment by SemyonKuznetsov** [comment]
@savinovava добавил ещё контекстное меню для PO (3 скрин)

**Comment by SemyonKuznetsov** [comment]
> Что копируем?
> 
> * xPath
> * Весь путь и класс, который отображен в списке
> * Класс, CSS selector и xPath локатор
>   @Кира

Наиболее часто используемый кейс – 3, xPath + Selenium Annotation. Второе место поделили 6 Full code и 2 xPath + JDI annotation. Третье место – 1, xPath.

**Comment by SemyonKuznetsov** [comment]
по нажатию на иконку быстрого копирования мы копируем фул код, а в выборе контексного меню у нас будут варианты 1, 2, 3, 6?

**Comment by AlexeyGirin** [comment]
> по нажатию на иконку быстрого копирования мы копируем фул код, а в выборе контексного меню у нас будут варианты 1, 2, 3, 6?

По быстрому копированию - копируем то, что видим на экране (т.е. Full Code)

**Comment by arslanbekova** [comment]
[3.6.365](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.365)
