### ISSUE TITLE
[E-5] Исследовать существующие решения (ML vs Rules)

### ISSUE THREAD

**Issue by savinovava** [jdi-testing/jdn-ai#771]
Meeting Notes:
https://jdi-family.atlassian.net/wiki/spaces/JDN/pages/91914241/16112022+ML+vs+Rules+Discussion

Посмотреть вот эти решения:
 https://github.com/televator-apps/vimari
 https://github.com/philc/vimium

Использовать Vuetify элемент лайбрари в качестве таргета.
Вот эти элементы в первую очередь:
- [x] alerts
- [x] toolbars
- [x] bottomnavigation
- [x] bottomsheets
- [x] vuetifybuttons
- [ ] floatingactionbuttons
- [x] calendars
- [x] cards
- [x] carousels
- [x] dialog
- [x] autocompletes
- [x] checkboxes
- [x] combobox
- [x] inputs
- [x] radiobuttons
- [x] rangeslider
- [x] select
- [x] sliders
- [x] switch
- [x] textfields
- [x] icons
- [x] lists
- [x] menus
- [x] pagination
- [x] datepickers
- [x] datepickersmonth
- [x] timepickers
- [x] dataiterators
- [ ] simpletables
- [ ] datatables
- [ ] tooltips

**Comment by savinovava** [comment]
При переходе на rules возможен будет перенос функциональности на фронтенд.
Ограничение: сбор статистики.

**Comment by savinovava** [comment]
Acceptance criteria:
1. Имплементировать для Vuetify
- [ ] Создать дерево решений (рулов) элементов (?) - возможно будет представлено в коде

2.  Весь список элементов JDI Light
3. Для первой итерации возможно 5 элементов: modal, dropdown ... 
4. Отдельно от релизной ветки
5. Создание тестовой среды — тестирование вне плагина. QA Максим К. 

Мы ожидаем, что по завершению задачи, потребуется человек уроня Junior

**Comment by savinovava** [comment]
![image](https://user-images.githubusercontent.com/53625116/212319983-a54bb1be-7f82-4a49-9c97-7df8c2ef591c.png)

**Comment by MariiaNebesnova** [comment]
прототип с пятью рулами:
[dist.zip](https://github.com/jdi-testing/jdn-ai/files/10412567/dist.zip)

**Comment by MariiaNebesnova** [comment]
[3.6.361](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.361)

**Comment by AlexeyGirin** [comment]
Остатки перенесены в #1062
