### ISSUE TITLE
[US-7-2] Поменять инпут в окне Edit

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#780]
Поменять инпут block type в окне Edit чтобы можно вводить текст и фильтровать выдачу

<img width="550" alt="Снимок экрана 2022-11-30 в 13 24 51" src="https://user-images.githubusercontent.com/101407186/204771620-88fe7424-846e-467d-b3da-a143b4a68f25.png">

**Comment by SemyonKuznetsov** [comment]
<img width="271" alt="Снимок экрана 2022-11-30 в 14 03 49" src="https://user-images.githubusercontent.com/101407186/204779930-51c858f5-f9c5-4f80-bd8c-55dd8f4eece4.png">

https://github.com/ant-design/ant-design/edit/master/components/select/demo/search-sort.md

**Comment by arslanbekova** [comment]
[3.6.331](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.331)

**Comment by Maksim-Kviatkovskii** [comment]
JDN v 3.6.341, изменений не вижу

![image](https://user-images.githubusercontent.com/109746268/211511723-90abd909-7766-4be5-9bfa-7c741904288a.png)

**Comment by arslanbekova** [comment]
> JDN v 3.6.341, изменений не вижу
> 
> ![image](https://user-images.githubusercontent.com/109746268/211511723-90abd909-7766-4be5-9bfa-7c741904288a.png)

Эта фича для 3.7 релиза была влита в master, в master ветке сейчас последняя версия 3.6.331 - `Pre-release`.

3.6.341 - последняя версия для релиза 3.6, там этих изменений действительно нет.

**Comment by arslanbekova** [comment]
Обновили master ветку - последняя актуальная версия, которая содержит эти изменения
[3.6.352](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.352)
