### ISSUE TITLE
[High] Нажатие на Select all при наложенном фильтре выделяет все локаторы (в том числе те, что не видны после наложения фильтра)

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#782]
JDN v 3.4.295
Steps:
1. Открыть плагин и перейти на шаг Creating/Editing
2. Открыть окно фильтров и снять чекбокс с типа Х
3. Нажать на кнопку Select all

AR:
- Локаторы с типом Х прочеканы, хотя не попадали под фильтр

ER:
- Если нажимаем Select All при наложенном фильтре - должны быть прочеканы только те, которые видимы после наложения фильтра

**Comment by MariiaNebesnova** [comment]
[3.4.301](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.301)
