### ISSUE TITLE
[High] Групповое удаление удаляет все чекнутые локаторы (в том числе те, что не видны после наложения фильтра)

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#783]
JDN v 3.4.295
Steps:
1. Открыть плагин и перейти на шаг Creating/Editing
2. Чекнуть локатор с типом Х
3. Чекнуть локатор с типом У
4. Открыть окно фильтров и снять чекбокс с типа Х
5. Удалить группу чекнутых локаторов

AR:
- Локаторы с типом Х удалены, хотя не попадали под фильтр

ER:
- Удаляем только те, которые прочеканы и которые мы видим

**Comment by MariiaNebesnova** [comment]
будет переработано вместе с #759

**Comment by MariiaNebesnova** [comment]
[3.4.301](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.301)
