### ISSUE TITLE
[Medium] Древовидная структура локаторов отображается некорректно, у локаторов без потомков нет отступа слева

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#784]
JDN v 3.4.295
Steps:
1. Открыть плагин и перейти на шаг Creating/Editing
2. Проверить отображение древовидной структуры

AR:
- У локаторов без наследников нет отступов слева
![image](https://user-images.githubusercontent.com/109746268/204834859-3754e2d9-cfec-44a4-bc1e-e0b390c37287.png)

ER:
- На макете у таких локаторов есть отступы
![image](https://user-images.githubusercontent.com/109746268/204835019-3aff7593-e85a-4d7c-8263-e8b4e84b670d.png)

**Comment by arslanbekova** [comment]
[3.5.308](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.308)
