### ISSUE TITLE
Вопросы для тестирований

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#789]
- [x] по закрытии задачи необходимо убрать статус blocked с упомянутых задач

#732 
- [x] По умолчанию PO создаётся c CSS локаторами?

результаты по предпочтению xpath/css 50/50
- [x] Имеют ли смысл Css локаторы от корня

нет

#760
- [x] возможно есть смысл по умолчанию делать все локаторы приватными, а чекбокс сделать чтобы он делал их публичными? 

Алексей сказал что делать публичными по умолчанию это наша селлинг фича

#335
- [x] нужна ли темная тема?

50/50

#769
- [x] имеет ли смысл полное копирование локатора или только тело xpath/css?

данные в задаче

### Общие вопросы
- [x] xpath / css?

поровну

- [x] public / private?

- [x] default time for generation? 1second? как часто вы пользуетесь опцией углубленного расчета, хватает ли одной секунды?

функцией не пользуются, её не понимают и не помниает где, зачем и так далее. ждёт реворк

**Comment by AlexeyGirin** [comment]
Done.
