### ISSUE TITLE
[Medium] При отправлении локаторов на перегенерацию, всегда появляется нотификашка "The generation of 2 locators was rerun"

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#790]
Precons:
- JDN v 3.4.298
- Шаг Creating

Steps:
1. Отправить на перегенерацию X локаторов
2. Проверить нотификашку

AR:
- The generation of 2 locators was rerun

ER:
- The generation of X locators was rerun

![image](https://user-images.githubusercontent.com/109746268/205934616-d57c6cbb-e101-49a3-8e91-04851d3fd9c1.png)

**Comment by savinovava** [comment]
#937 
#936 
#934

**Comment by MariiaNebesnova** [comment]
can't reproduce

**Comment by Maksim-Kviatkovskii** [comment]
Больше не воспроизводится
