### ISSUE TITLE
[Medium] На некоторых сайтах не работает выделение рамкой на покрытии (пока нашёл только 1 пример)

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#795]
Precons:
- JDN v 3.4.300 
- https://www.behance.net/
- Шаг Creating

Steps:
1. Выбрать рамкой несколько элементов на покрытии

AR:
- Выделение рамкой не работает

ER:
- Выделение рамкой работает

**Comment by MariiaNebesnova** [comment]
у меня работает 
![image](https://user-images.githubusercontent.com/82033805/219403916-7760b7bf-47d0-4143-a134-36f546ae2dc6.png)

behance вообще богат на плавающие баги

**Comment by OlgaTitovaEPAM** [comment]
Can't reproduce
JDN v 3.8.396 Back-end v 0.2.22, Google Chrome Version 110.0.5481.77 (Official Build) (x86_64), macOS 12.6.1
