### ISSUE TITLE
[Critical] Нет контекстного меню для выделенных элементов на покрытии

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#796]
Precons:
- JDN v 3.4.300 
- Шаг Creating

Steps:
1. Нажать пкм на элемент на покрытии
2. Выделить несколько элементов и нажать на них пкм
3. Выделить несколько элементов рамкой с зажатой пкм

AR:
- Контекстного меню нет

ER:
- Открывается контекстное меню

**Comment by MariiaNebesnova** [comment]
инкогнито мод - не наш кейс
