### ISSUE TITLE
[High] Нажатие на кнопку Cancel после удаления не возвращает элементы на покрытие

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#803]
Precons:
- JDN v 3.4.302
- Шаг Creating

Steps:
1. Удалить один элемент (или несколько элементов группой)
2. Нажать кнопку Cancel на появившемся сообщении locator was deleted (или X locators were deleted)
3. Проверить отображение восстановленных элементов на покрытии

AR:
- Элементы не отображаются, если их прочекать - отображаются чёрной рамкой
![image](https://user-images.githubusercontent.com/109746268/206735479-020c868a-9c30-400e-b821-9075df828129.png)

ER:
- Элементы восстановлены, отображаются без изменениий

**Comment by MariiaNebesnova** [comment]
[3.4.305](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.305)

**Comment by Maksim-Kviatkovskii** [comment]
Проблема воспроизводится при удалении из окна плагина (не с покрытия)

**Comment by MariiaNebesnova** [comment]
[3.4.306](https://github.com/jdi-testing/jdn-ai/releases/tag/3.4.306)
