### ISSUE TITLE
[US-5-2] Переработать генератор для Material UI

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#81]
Доработать генератор таким образом, что бы он не создавал списки и группы элементов группировка которых не поддерживается JDI.
Например - есть элемент ButtonGroup - вот он должен распознаваться на страничке и потому - присутствовать в сгенерированной страничке
Но вот группы радио баттонов - такого элемента (как единого целого) нет, поэтому на сгенерированной страничке все такие элементы должны присутствовать как отдельные элементы.

В дальнейшем - мы в UI плагина добавим возможность объединять элементы в листы заменяя объявления вида
public List<Checkbox> basicCheckbox;

Финальные подробности у Михаила.

**Comment by savinovava** [comment]
Решили убрать non-actionable элементы

**Comment by savinovava** [comment]
Done.
