### ISSUE TITLE
[Low] Некооректная иконка закрытия окна с фильтрами

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#816]
Precons:
- JDN v 3.5.307
- Шаг Creating

Steps:
1. Открыть окно с фильтрами
2. Проверить отображение иконки закрытия окна с фильтрами

ER:
- Иконка отображается в соответствии с макетом (крестик)

AR:
- Иконка отображается некорректно
![image](https://user-images.githubusercontent.com/109746268/207368827-26f2832e-3d48-4195-bf6f-f13a7a9001db.png)

**Comment by MariiaNebesnova** [comment]
[3.7.376](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.376)
