### ISSUE TITLE
[Low] Некорректный скроллбар в окне с фильтрами

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#817]
Precons:
- JDN v 3.5.307
- Шаг Creating

Steps:
1. Открыть окно с фильтрами
2. Проверить отображение скроллбара в окне с фильтрами

ER:
- Скроллбар отображается в соответствии с макетом

AR:
- Отображается дефолтный скроллбар
![image](https://user-images.githubusercontent.com/109746268/207368827-26f2832e-3d48-4195-bf6f-f13a7a9001db.png)
![image](https://user-images.githubusercontent.com/109746268/207369534-066c178f-b883-4624-b8f5-d77407b1c575.png)

**Comment by MariiaNebesnova** [comment]
существующими средствами анта скроллбар как на макете не добавить

**Comment by AlexeyGirin** [comment]
Фильтры перенесём в окно настроек, это ещё много раз поменяется, поэтому пока - закрываем
