### ISSUE TITLE
[3pt][US-2-1]Generated locators look as not converted 

### ISSUE THREAD

**Issue by DaryaGurtovenko** [jdi-testing/jdn-ai#82]
Tagret page: https://jdi-testing.github.io/jdi-light/complex-table.html
![image](https://user-images.githubusercontent.com/80756170/142981918-fc61e5e1-ed46-4ec8-9978-8a63f6a611c9.png)

The problem is generate locators look like '@UI("/html/body/div[1]/div[2]/main/div[2]/div/table/tbody/tr/td/div/table/tbody/tr[3]/td[2]/p[1]") text-field text-fieldP11' and deleting of time limit in settings doesn't help to convert them to needed view
![image](https://user-images.githubusercontent.com/80756170/142982115-f0a9dd38-1ac8-41b8-8aa6-9f6358325faa.png)

**Comment by DaryaGurtovenko** [comment]
1 pt - qa

**Comment by MariiaNebesnova** [comment]
3.0.86

**Comment by DaryaGurtovenko** [comment]
Impossible to check on original page because of difference between old and new back-ends. 
On https://mui.com/ looks good (v. 3.0.88)
