### ISSUE TITLE
[High] Если кликнуть в пустую область на покрытии, то появится выделенная область 1х1px и останется на экране, блокируя одно следующее выделение

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#822]
Precons:
- JDN v 3.5.307
- Шаг Creating

Steps:
1. Кликнуть в пустую область на покрытии
2. Выделить рамкой какой-нибудь элемент

ER:
1. Ничего не происходит
2. Элемент выделяется

AR:
1. Создаётся выделенная область 1х1px и остаётся на экране (см скрин)
2. Элемент не выделяется, область из п.1 пропадает, дальше всё работает как обычно

![image](https://user-images.githubusercontent.com/109746268/207854043-6ef9ed01-231f-449a-a6e1-aeb0731c6ec3.png)

**Comment by MariiaNebesnova** [comment]
[Release 3.5.312](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.312)

**Comment by MariiaNebesnova** [comment]
[3.5.314](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.314)

**Comment by Maksim-Kviatkovskii** [comment]
1. Если открыть контекстное меню для одного элемента, а потом кликнуть в другой - меню останется открытым для первого
2. Если зажать лкм\пкм и увести курсор за пределы страницы - рамка после этого остаётся и ездит за курсором, даже если отпустить кнопку
3. Не появляется контекстное меню при выделении рамкой с зажатой пкм

**Comment by MariiaNebesnova** [comment]
[3.5.315](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.315)
