### ISSUE TITLE
[High] Падает плагин, если добавить несколько PO и сразу удалить

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#828]
Precons:
- JDN v 3.5.311
- Шаг создания PO

Steps:
1. Создать несколько PO (2+)
2. Удалить последний PO

ER:
- Последний PO удалился, остальные остались

AR:
- Падает плагин
![image](https://user-images.githubusercontent.com/109746268/208422785-b86e386c-1812-4d41-893d-285f4dd4eb99.png)

**Comment by MariiaNebesnova** [comment]
[Release 3.5.313](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.313)
