### ISSUE TITLE
[1pt][US-11-1] Не появляется меню сеттингов при клике на локатор правой кнопкой мыши

### ISSUE THREAD

**Issue by lisatatarinova** [jdi-testing/jdn-ai#83]
JDN v 3.0.82
Back-end v 2021-09-28-08.31.54

Identify
На стороне веб-страницы нажимаю левой кнопкой мыши на локатор
Фактический результат: ничего не происходит
Ожидаемый результат: открывается меню сеттингов

**Comment by lisatatarinova** [comment]
QA: 0.5pt

**Comment by MariiaNebesnova** [comment]
3.0.86

**Comment by lisatatarinova** [comment]
test passed
