### ISSUE TITLE
[High] Если добавить PO а потом удалить его - то следующий добавляемый РО добавляется в коллапснутом виде

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#830]
Создайте простой PO.
После создания (ну т.е. надо прочекать локаторы, нажать на кнопку Save) - удалите его.
Снова нажмите на кнопку +Page Object

Наблюдаем - Система добавляет строку в список, но в схлопнутом состоянни.
Нужно - что бы была раскрыта

![image](https://user-images.githubusercontent.com/26869421/208436510-3a69b129-0168-45ae-afc3-7f727bf78b9f.png)

**Comment by MariiaNebesnova** [comment]
[Release 3.5.313](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.313)
