### ISSUE TITLE
[Medium] Баг двойной отмены

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#845]
после генерации PO можно удалить его и в UNDO алерте 2 раза нажать на cancel, тем самым сначала отменив действие удаление, а потом и действие создания. после этого если ещё раз нажать на генерацию, то создаётся пустой PO

https://user-images.githubusercontent.com/101407186/209125247-991ca2bc-2228-4a82-99e8-e40282a52e5e.mov

**Comment by Maksim-Kviatkovskii** [comment]
Пофикшено в https://github.com/jdi-testing/jdn-ai/issues/867
