### ISSUE TITLE
Обновить контекстное меню: иконки, текст, порядок расположения

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#846]
Придумать иконки для групповых операций: Add to Page Object/Remove to Page Object и Bring to front/Bring to background
___

1. Обновить иконки
3. Поменять местами строки (группировка между дивайдерами)
4. Поменять текст на Bring to front / Send to back

[figma link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163762%3A163505&t=1Edtqdu6Wae7tbp2-4)

![image](https://user-images.githubusercontent.com/101407186/235982097-f11a2413-81ef-43d9-85cd-bd8cf2849ae7.png)

соответственно новые иконки для операций:
- Select element
- Add to Page Object
- Remove from Page Object
- Bring to front
- Sent to back

- [ ]  обновить Readme

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163762%3A163505&t=WwsMlGCwmgl9cwry-4)

<img width="300" src="https://user-images.githubusercontent.com/101407186/209935445-32845d95-9059-4e2c-b877-f4311eae01bc.png">

после добавления иконок надо немного поменять местами строки + (это описано в #755) поменять текст на Bring to front / Send to back

**Comment by arslanbekova** [comment]
[3.12.480](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.480)

**Comment by arslanbekova** [comment]
Также были обновлены иконки в плагине и добавлены дивайдеры

**Comment by AlexadrK** [comment]
JDN v 3.12.480 Back-end v 0.2.37
Chrome Version 114.0.5735.110 (Official Build) (64-bit)

Test result - PASS
![context menu_4](https://github.com/jdi-testing/jdn-ai/assets/21053451/7908b754-09ff-489d-9dff-191750986803)
![context menu_3](https://github.com/jdi-testing/jdn-ai/assets/21053451/d5d63415-2006-4df5-adee-bd3b2d1aa582)
![context menu_plagin window_1](https://github.com/jdi-testing/jdn-ai/assets/21053451/722b302c-75dd-4d50-945b-2bbe8aefb3ce)
![context menu_plagin window_2](https://github.com/jdi-testing/jdn-ai/assets/21053451/52c22c17-e9a8-4c16-8758-f235d8cdbe15)
![context menu_1](https://github.com/jdi-testing/jdn-ai/assets/21053451/7842f2e3-cd83-4e11-950d-10758f35cb2c)
![context menu_2](https://github.com/jdi-testing/jdn-ai/assets/21053451/3ee158ae-a5fd-4c8d-9f5e-1a7996bb90ca)
