### ISSUE TITLE
[High] После сохранения PO и возвращения к списку PO остаётся возможность группового выделения на покрытии

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#847]
Precons:
- JDN v 3.5.316
- Шаг Creating

Steps:
1. Добавить несколько элементов в PO
2. Нажать кнопку Save
3. Вернувшись к списку PO попробовать сделать групповое выделение на странице

AR:
- Рисуется рамка, кликабельные элементы страницы не прожимаются

ER:
- Нет возможности сделать групповое выделение, кликабельные элементы работают

**Comment by MariiaNebesnova** [comment]
[3.5.322](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.322)
