### ISSUE TITLE
[High] Пропадает содержимое PO при создании нового

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#848]
Precons:
- JDN v 3.5.316
- Шаг Creating

Steps:
1. Добавить несколько элементов в PO
2. Нажать кнопку Save
3. Добавить новый PO
4. Развернуть первый PO

AR:
- Содержимое не отображается, отображается кнопка Generate

ER:
- Содержимое отображается, кнопка Generate не отображается

**Comment by MariiaNebesnova** [comment]
[3.5.319](https://github.com/jdi-testing/jdn-ai/releases/tag/3.5.319)
