### ISSUE TITLE
[2pt][US-11-2] Поправить отображение меню локаторов

### ISSUE THREAD

**Issue by mariia-tokarchuk** [jdi-testing/jdn-ai#85]
JDN v 3.0.82
Back-end v 2021-09-28-08.31.54

При открытии меню последних в списке локаторов, меню перекрывается следующей вкладкой.

**Примеры:**
![Screenshot 2021-11-23 at 13 16 36](https://user-images.githubusercontent.com/89466817/143016163-c61757df-597e-4496-9fb4-a93fb98a03cb.png)

![Screenshot 2021-11-22 at 13 34 41](https://user-images.githubusercontent.com/89466817/143016215-0171d833-fef6-44f3-a8ef-94c55c88b2e9.png)

**Comment by savinovava** [comment]
fe=1pt

**Comment by MariiaNebesnova** [comment]
3.0.89

**Comment by DaryaGurtovenko** [comment]
Verified on ver. 3.0.93, fixed.
![image](https://user-images.githubusercontent.com/80756170/144806650-c02d886f-c373-432b-9141-8d7bb1ad0094.png)
