### ISSUE TITLE
[Medium] Не появляется контекстное меню при выделении уже выделенного элемента на покрытии, если начать выделение, пока курсор на нём

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#854]
Precons:
- JDN v 3.5.321
- Шаг Creating

Steps:
1. Кликнуть ЛКМ в любой элемент на покрытии
2. Навести на него курсор, зажать ПКМ и выделить рамкой область (см примеры в скринах)
3. Отпустить ПКМ

ER:
- Открылось контекстное меню для элемента из шага 1

AR:
- Открылось дефолтное браузерное контекстное меню, элемент похоже успевает деселектнуться в момент отпускания кнопки

Примеры: (сорри, курсор не попал в скрины, но он у меня всегда в нижнем правом углу рамки)
![image](https://user-images.githubusercontent.com/109746268/209322096-38a414cf-0c13-4b00-8c39-b32517cd5d45.png)
![image](https://user-images.githubusercontent.com/109746268/209322469-8d177327-141c-4808-b335-8e869bedd59c.png)
![image](https://user-images.githubusercontent.com/109746268/209322251-e38afe90-9d5c-4b3e-8a41-ae7d0fa1c885.png)

**Comment by MariiaNebesnova** [comment]
[Release 3.6.340](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.340)
