### ISSUE TITLE
[High] Нет возможности убрать выделение с локатора в списке через Ctrl-клик

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#855]
Precons:
- JDN v 3.5.321
- Шаг Creating

Steps:
1. Выделить несколько локаторов в списке через Ctrl-клик
2. Сделать Ctrl-клик на выбранном локаторе

ER:
- Выделение снимается (как в файл эксплорере)

AR:
- Выделение не снимается

**Comment by MariiaNebesnova** [comment]
[Release 3.6.346](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.346)

**Comment by MariiaNebesnova** [comment]
[Release 3.6.350](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.350)
