### ISSUE TITLE
Система жалуется на неуникальность имени локатора если такое же имя существует в другом пэйдж обжекте

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#859]
1. Создайте ПО для страницы (в моём случае - https://jdi-testing.github.io/jdi-light/contacts.html) - включите туда элемент первый в списке
2. Начните создавать ПО для этой же страницы ещё раз.
3. Откройте самый верхний элемент (он должен быть включен в первый ПО) на редактирование.
4. Сделайте обратимое изменение (например - поменяйте локатор и потом поменяйте обратно так что бы в итоге значение не поменялось).
5. Нажмите кнопку Ок.

Система начнёт жаловаться, что "This name already exists in the page object."
Хотя эта ситуация - абсолютно валидна, уникальность должна быть на уровне ПО.

![image](https://user-images.githubusercontent.com/26869421/209566153-f7c2d7dd-d767-41a9-be76-ab675cbf8202.png)

**Comment by MariiaNebesnova** [comment]
[Release 3.6.336](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.336)
