### ISSUE TITLE
[1pt][US-5-2] Убрать не экшанабл элементы из распознавания

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#86]
Ради улучшения распознования элементов давайте попробуем исключить из распознования декоративные элементы с которыми невозможны никакие экшены

1. icon
2. backdrop
3. avatar
4. paper
5. box
6. container
7. popper
8. grid
9. popover
10. divider
11. app-bar
12. card
13. typography

**Comment by MariiaNebesnova** [comment]
осталась задача по сборке с гитхаб

**Comment by AlexeyGirin** [comment]
Done.
