### ISSUE TITLE
А зачем нужна красная звёздочка на форме редактирования локатора?

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#861]
Не уверен - баг ли это, но помоему - красная звёздочка не несёт никакой смысловой нагрузки рядом с названием поля "Name:"

![image](https://user-images.githubusercontent.com/26869421/209566923-a3b9e322-025b-453d-9701-dc3767e28410.png)

**Comment by SemyonKuznetsov** [comment]
- звездочки в этих модалках говорят нам о том, что мы не можем оставить поле пустым
- при этом у нас есть валидация на пустоту, оставить локатор пустым не получится
- * несут косметический характер

в целом можем убрать, сильно ничего не изменится

**Comment by AlexeyGirin** [comment]
Не баг
