### ISSUE TITLE
Выделение элемента в списке - не пролистывает экран покрытия что бы показать его

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#862]
1. Попробуйте распознать элементы на странице где есть прокрутка. (в моём случае - это была - https://www.linkedin.com/jobs/)
2. Выделите в списке локаторов элемент который находится за пределами видимости.

Я бы ожидал, что система промотает страничку и покажет  покрытие этого элемента.
Обратное - должно быть тоже верно - выделение элемента на покрытии - долдно проматывать список и показывать его выделение в списке локаторов

ВНИМАНИЕ: В случае группового выделения мышкой на покрытии - список должен промотаться только до первого элемента из этих выделенных элементов.
В случае выделения элементов по одному (с зажатым CTRL) - должно работать как описано выше - система должна показывать каждый выделеный элемент на покрытии (если выделение идёт через список) или в списке (если выделение идёт через покрытие)

**Comment by MariiaNebesnova** [comment]
поштучное проставление галочек Genеrate в списке тоже должно проскролливать страницу до этого элемента?

**Comment by MariiaNebesnova** [comment]
[Release 3.6.342](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.342)
