### ISSUE TITLE
Добавить контекстное меню для списка элементов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#863]
Сейчас - контекстное меню существует только для области покрытия, в то время как групповые операции в списке - осуществляются через трёх-точечное меню в верхнем правом углу

Думаю - стоит добавить поддержку контекстного меню и в список тоже

**Comment by MariiaNebesnova** [comment]
дубль #917 ?

**Comment by AlexeyGirin** [comment]
Дупликат
