### ISSUE TITLE
Закрытие плагина не выводит область странички из режима группового выделения элементов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#864]
1. Распознайте HTML5 элементы на страничке https://www.linkedin.com/mynetwork/
2. Выделите группу элементов
3. Закройте плагин

Несмотря на то, что плагин закрыт - я не могу нажимать на линки и функция группового выделения элементов тоже включена. Я бы ожидал, что бы она исчезала вместе с выходом из режима создания ПО (или с выходом из плагина)

Альтернативный сценарий:
1. Распознайте HTML5 элементы на страничке https://www.linkedin.com/mynetwork/
2. Проскроллите страничку вниз
3. Выделите группу элементов и добавьте их в ПО.
4. Создайте ПО

После создания ПО - я не могу нажимать на линки и функция группового выделения элементов тоже включена. Я бы ожидал, что бы она исчезала вместе с выходом из режима создания ПО (или с выходом из плагина)

**Comment by MariiaNebesnova** [comment]
[Release 3.6.324](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.324)

**Comment by MariiaNebesnova** [comment]
[Release 3.6.325](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.325)

**Comment by AlexeyGirin** [comment]
Closed
