### ISSUE TITLE
Система создаёт ПО с невалидным именем (не проверяет его валидность перед созданием)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#865]
1. Я попробовал создать ПО на страничке - https://www.linkedin.com/mynetwork/
2. Обратил внимание, что имя ПО - не проходит валидацию как валидное имя жава класса.

Я бы ожидал, что перед созданием ПО - система бы трансформировала его имя в валидное (в данном случае - убирала бы цифры из начала имени бы)

![image](https://user-images.githubusercontent.com/26869421/209571925-51193bad-f3c5-4664-9679-722670573eee.png)

**Comment by MariiaNebesnova** [comment]
@AlexeyGirin по какому событию выполнять преобразование?

**Comment by AlexeyGirin** [comment]
Автоматически - имя должно создваться валидным сразу

**Comment by arslanbekova** [comment]
[3.6.345](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.345)

**Comment by Maksim-Kviatkovskii** [comment]
JDN v 3.6.347

Воспроизводится на https://www.google.com/search?q=123abc
![image](https://user-images.githubusercontent.com/109746268/212034017-0a1f415e-e320-4e93-b29b-913c99eb43c6.png)

**Comment by arslanbekova** [comment]
[3.6.349](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.349)

**Comment by Maksim-Kviatkovskii** [comment]
JDN v 3.6.350 

https://www.google.com/search?q=123qwe
Цифры обрезаются, оставляя после себя имя с маленькой буквы
![image](https://user-images.githubusercontent.com/109746268/212097072-7b8a38ef-4ce6-4064-b594-52659e5fd87d.png)

**Comment by arslanbekova** [comment]
[3.6.351](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.351)
