### ISSUE TITLE
[Minor] Система пробрасывает клики сквозь модальное окно редактирования имени ПО

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#866]
1. Откройте Rename page object окно.
2. Кликните на любую его область.

Обратите внимание, что ПО в списке под окном - схопнется или расхлопнется

**Comment by arslanbekova** [comment]
[3.6.338](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.338)
