### ISSUE TITLE
Множественное нажатиен на линк Cancel (в нотификашке про удаление ПО) отменяет все предыдущие действия до упора

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#867]
1. Создайте несколько ПО
2. Удалите один
Система покажет натификашку что удалено с кнопкой Cancel.
3. Много раз нажмите на Cancel пока она не исчезла.

Система начнёт отменять все действия подряд (а может и просто - действовать хаотично - тут не понять).
Всё бы ничего, но после этого - работа с плагином становится невозможной - он переходит в сломанное состояние (распозанвание перестаёт работать - см. скриншот)
Я бы ожидал, что система отменит только последнее действие

![image](https://user-images.githubusercontent.com/26869421/209573003-9d821650-181a-4d4d-934f-2a0691fb7595.png)

**Comment by MariiaNebesnova** [comment]
[Release 3.6.336](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.336)

**Comment by Maksim-Kviatkovskii** [comment]
Фиксит так же https://github.com/jdi-testing/jdn-ai/issues/845
