### ISSUE TITLE
[Minor] Множественное нажатие на кнопку +Page Object создаёт много пустых ПО. Это смысла не имеет

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#868]
Множественное нажатие на кнопку +Page Object создаёт много пустых ПО. Это смысла не имеет.
Если у нас есть уже заготовка ПО (с кнопкой Генерэйт), то повторное нажатие на +Page Object закрывать все открытые ПО и окрывать существующую заготовку и скроллировать к ней

![image](https://user-images.githubusercontent.com/26869421/209573577-f23afad5-9ba4-4271-bcf4-253d30fe9cc7.png)

**Comment by MariiaNebesnova** [comment]
обращаю внимание, что открывать таким образом "заготовку" можно, только если у нее тот же урл, что в данный момент на странице. что делать с кучей заготовок, если у них другие урлы? чистить?

**Comment by AlexeyGirin** [comment]
> обращаю внимание, что открывать таким образом "заготовку" можно, только если у нее тот же урл, что в данный момент на странице. что делать с кучей заготовок, если у них другие урлы? чистить?

Да, тоже чистить.
Переход на другую страничку - должен очищать все заготовки.
Создавать несколько заготовок для одной странички не надо (нужно видимо дизаблить кнопку)
