### ISSUE TITLE
Загрузка аттачментов на форме Report Problem длится бесконечно

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#869]
Откройте форму Report Problem и попробуйте приаттачить пяток маленьких архивов.

Визуально - приаттачится только один, а остальные - будут бесконечно грузиться

![image](https://user-images.githubusercontent.com/26869421/209575090-6391cdb5-93ee-4db0-bc15-b5967adfd8ee.png)

В логах сервера вроде бы есть ошибка:
![image](https://user-images.githubusercontent.com/26869421/209575063-ed8c8298-734d-4954-aef6-117e5d95db87.png)
[jdi-light-testng-empty-template-main (25).zip](https://github.com/jdi-testing/jdn-ai/files/10304469/jdi-light-testng-empty-template-main.25.zip)
[jdi-light-testng-empty-template-main (26).zip](https://github.com/jdi-testing/jdn-ai/files/10304470/jdi-light-testng-empty-template-main.26.zip)
[jdi-light-testng-empty-template-main (27).zip](https://github.com/jdi-testing/jdn-ai/files/10304471/jdi-light-testng-empty-template-main.27.zip)
[jdi-light-testng-empty-template-main (23).zip](https://github.com/jdi-testing/jdn-ai/files/10304472/jdi-light-testng-empty-template-main.23.zip)
[jdi-light-testng-empty-template-main (24).zip](https://github.com/jdi-testing/jdn-ai/files/10304473/jdi-light-testng-empty-template-main.24.zip)

**Comment by arslanbekova** [comment]
[3.6.335](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.335)
