### ISSUE TITLE
Edit опция из контекстного меню в покрытии - ломается после определённых действи

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#870]
1. Распознайте HTML5 элементы на страничке https://www.linkedin.com/mynetwork/invite-connect/connections/
2. Широким жестом выделите группу и добавьте её в ПО

Начиная с этого момента - Edit опция из контекстного меню в покрытии - перестаёт работать

![image](https://user-images.githubusercontent.com/26869421/209576772-3167c2e3-8587-441a-a739-14a6e15928b9.png)

![image](https://user-images.githubusercontent.com/26869421/209576784-05734e0c-787b-402c-8d19-491bf7265d6a.png)

**Comment by MariiaNebesnova** [comment]
ломается для элементов, которые спрятаны под скроллом в списке

**Comment by MariiaNebesnova** [comment]
[Release 3.6.342](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.342)

**Comment by Maksim-Kviatkovskii** [comment]
Список теперь скролится к элементу, для которого вызвано контекстное меню, описанная проблема не воспроизводится
