### ISSUE TITLE
Использование Edit из области покрытия - позволяет открыть много окон редактирование элемента одновременно

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#871]
Использование Edit из контекстного меню в области покрытия - позволяет открыть много окон редактирования.
Работает это корректно, но не уверен что это хорошо.

![image](https://user-images.githubusercontent.com/26869421/209577083-030d5e55-6baf-4ba2-9b66-c95bcaf99f22.png)

**Comment by MariiaNebesnova** [comment]
как это должно работать? блокировать интерфейс страницы оверлеем, пока открыт диалог?

**Comment by AlexeyGirin** [comment]
> как это должно работать? блокировать интерфейс страницы оверлеем, пока открыт диалог?

Ответ - блокировать интерфейс страницы оферлеем.

**Comment by arslanbekova** [comment]
[3.6.344](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.344)
