### ISSUE TITLE
[Minor] Иконку Pause Generation нужно подправить

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#874]
![image](https://user-images.githubusercontent.com/26869421/209580854-eafca07e-87cd-4940-88a3-6329a6fa8031.png)
![image](https://user-images.githubusercontent.com/26869421/209580930-911030f1-0fcc-4cc1-99b9-4cae4a8211be.png)

**Comment by arslanbekova** [comment]
[3.6.333](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.333)
