### ISSUE TITLE
Тултип чот слегка темноват (сломался)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#875]
![image](https://user-images.githubusercontent.com/26869421/209581302-af113e7d-6846-456e-9b4d-6f9e194500d4.png)

**Comment by MariiaNebesnova** [comment]
connected #721

**Comment by arslanbekova** [comment]
[3.6.332](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.332)

**Comment by AlexeyGirin** [comment]
Fixed.
