### ISSUE TITLE
Контекстное меню выпадает за пределы видимости (под панель плагина) если открыто рядом с полосой прокрутки

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#876]
Возможно - можно сделать так, что бы выпадушка выпадала бы с другой стороны?
![image](https://user-images.githubusercontent.com/26869421/209581652-85f923eb-9f9f-4c7f-8d4d-2be8de04be58.png)

**Comment by arslanbekova** [comment]
[3.6.334](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.334)

**Comment by Maksim-Kviatkovskii** [comment]
В целом пофикшено, но частично воспроизводится для широких страниц, которые не влезают в окно браузера, вынес в отдельный минор https://github.com/jdi-testing/jdn-ai/issues/903
