### ISSUE TITLE
[Pause] Doesn't work this functhionality

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#88]
JDN v 3.0.83
Back-end v 2021-11-01-06.14.14
Browser: 96.0.4664.45 (Официальная сборка), (64 бит)
Site: mail.ru

Steps:
1. Open site
2. Open plugin
3. Press [Identify]
4. Press [II] (Pause button)

ER: Locator search stop work
AR: Locator searcher does'n stop

https://user-images.githubusercontent.com/61897393/143386049-41f73d8b-4c28-4a8b-aa74-11d9b8cc7ec3.mp4

**Comment by MariiaNebesnova** [comment]
2pt - fe

**Comment by MariiaNebesnova** [comment]
3.0.90

**Comment by MariiaNebesnova** [comment]
3.0.91

**Comment by pulya-na-vullet** [comment]
Ретест бага произведен. Дефект не воспроизводится. 
JDN v 3.0.92
Back-end v 2021-12-01-14.52.21
