### ISSUE TITLE
[Critical] Создание ПО после группового выделения элементов на покрытии убирает групповое выделение на покрытии навсегда

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#881]
1. Создайте ПО через групповое выделение элементов на страничке (в моём случае - https://www.linkedin.com/notifications/?filter=all )
2. Начните создавать ПО на этой же или на другой страничке.
В этот момент - блоки уже не выделяются через групповое выделение (хотя рамка появляется)
Перегрузка плагина не чинит эту ситуацию, только перегрузка плагина и странички чинит

**Comment by MariiaNebesnova** [comment]
Additional case to reproduce: create PO on a page (ex. https://www.linkedin.com/mynetwork/), than navigate to another page on the same site (ex. https://www.linkedin.com/notifications/?filter=all)

**Comment by MariiaNebesnova** [comment]
[Release 3.6.329](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.329)
