### ISSUE TITLE
Добавить точку с запятой в локатор на панели локаторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#885]
Необходимо добавить точку с запятой (после имени элемента) на панели локаторов. Что бы результат копирования и результат экспорта - совпадали полностью:

![image](https://user-images.githubusercontent.com/26869421/210176413-f9fd1601-8907-4406-8036-af3baacb38bc.png)

@UI("//*[@rows='4']")
public Text description;

**Comment by arslanbekova** [comment]
[3.6.339](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.339)
