### ISSUE TITLE
При установке плагина в браузере появляется старый логотип

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#886]
<img width="360" alt="Снимок экрана 2023-01-03 в 14 02 54" src="https://user-images.githubusercontent.com/101407186/210345187-46d6329f-438c-49a1-966a-24f85b703e13.png">

можно посмотреть [тут (запись интервью)](https://epam-my.sharepoint.com/:v:/r/personal/kira_bagrova_epam_com/Documents/Recordings/Test%20with%20Alina%20Lysenko1-20221226_170127-Meeting%20Recording.mp4?csf=1&web=1&e=AHwZ0o) на 14:58

<img width="551" alt="Снимок экрана 2023-01-09 в 14 27 02" src="https://user-images.githubusercontent.com/101407186/211298171-ab6a685f-9d2a-4154-938d-eeeb21cfab28.png">

можно посмотреть [тут (запись интервью)](https://epam-my.sharepoint.com/:v:/r/personal/semyon_kuznetsov_epam_com/Documents/Recordings/Usability%20test%20with%20Ivan%20Protasov1-20221222_120149-%D0%97%D0%B0%D0%BF%D0%B8%D1%81%D1%8C%20%D1%81%D0%BE%D0%B1%D1%80%D0%B0%D0%BD%D0%B8%D1%8F.mp4?csf=1&web=1&e=nAaeJf&nav=%7B%22playbackOptions%22%3A%7B%22startTimeInSeconds%22%3A1757.11%7D%7D) на 29:17

**Comment by MariiaNebesnova** [comment]
[Release 3.6.347](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.347)
