### ISSUE TITLE
[US-6-9] Visual updates of the filter icon

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#895]
- сейчас её плохо видно (в фигме сделал ярче до 85%)
- увеличить иконку до 16px, сейчас svg 14px
- неудобное расположение если плагин открыт в ширину, иконка отдельно остается справа
- добавить активное состояние

**Comment by savinovava** [comment]
#781

**Comment by SemyonKuznetsov** [comment]
все пункты так или иначе сделаны или будут сделаны в других задачах

**Comment by AlexeyGirin** [comment]
Not actual any more
