### ISSUE TITLE
[Settings] Doesn't worked notification when user press [Save] button in locator list

### ISSUE THREAD

**Issue by pulya-na-vullet** [jdi-testing/jdn-ai#90]
JDN v 3.0.83
Back-end v 2021-11-01-06.14.14
Browser: 96.0.4664.45 (Официальная сборка), (64 бит)
Site: mail.ru

Steps:

1. Open site
2. Open plugin
3. Press [Settings]
4. Choise one new check box in window "Settings"
5. Press [Save]

ER:  Open notification about user action (Откроется нотификатор сообщающий о проделанных изменениях (в локатор листе))
AR:  Notification does't open
https://user-images.githubusercontent.com/61897393/143388006-dba3e223-2a27-4ef4-b54c-e617a02bffcb.mp4

**Comment by MariiaNebesnova** [comment]
as discussed with @mariia-tokarchuk, no notification here is expected by design

**Comment by pulya-na-vullet** [comment]
Закрываем за ненадобностью.
