### ISSUE TITLE
[Low] Контекстное меню на покрытии может выйти за пределы страницы, если страница изначально шире окна браузера

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#903]
Precons:
- JDN v 3.6.341
- Страница, которая не влезает в окно браузера с открытым плагином (например https://www.google.com/search?q=qwe)
- Шаг Creating

Steps:
1. Проскроллить страницу вправо до конца
2. Выделить несколько элементов с края страницы
3. Нажать пкм по крайнему элементу справа и проверить отображение контекстного меню

ER:
- Контекстное меню полностью отображается на странице

AR:
- Страница расширилась вправо, контекстное меню выровнялось по новому правому краю, нужно опять скроллить вправо

![image](https://user-images.githubusercontent.com/109746268/211508261-6bd71c8d-2c90-48b0-bf69-db4b64a081b4.png)
![image](https://user-images.githubusercontent.com/109746268/211508940-095a828f-413a-4588-be55-b3030c50f4a5.png)

**Comment by arslanbekova** [comment]
не воспроизводится на macOS

**Comment by MariiaNebesnova** [comment]
[3.7.386](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.386)

**Comment by MariiaNebesnova** [comment]
[3.7.389](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.389)
