### ISSUE TITLE
Убрать стрелочки на контекстных меню (на покрытии и в самом плагине)

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#905]
В текущей реализации стрелка в половине случаев не попадает в элемент, на который должна указывать, так что решили убрать её совсем.
Напрашивается сделать "как в винде" - чтобы один из углов меню был в точке где кликнули пкм

![image](https://user-images.githubusercontent.com/109746268/211546405-096f8bab-02e7-4eeb-8ca7-605981d4bd19.png)
![image](https://user-images.githubusercontent.com/109746268/211546471-45399efb-0467-4cf8-9a4f-4872c5c1805b.png)

**Comment by MariiaNebesnova** [comment]
we can't get rid of arrows, AntD just doesn't have such api

**Comment by SemyonKuznetsov** [comment]
![image](https://user-images.githubusercontent.com/101407186/212047563-a475e650-f1dd-4594-9903-361cb5f722d8.png)

[link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=164096%3A167687&t=8xXppcUTmczKGOLb-4)

**Comment by MariiaNebesnova** [comment]
[3.8.392](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.392)

**Comment by MariiaNebesnova** [comment]
[3.8.394](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.394)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.8.395 Back-end v 0.2.22, Google Chrome Version 110.0.5481.77 (Official Build) (x86_64), macOS 12.6.1
