### ISSUE TITLE
[Low] Некорректный текст кнопки в попапе "Сonfirm this locators list"

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#913]
Precons:
- JDN v 3.6.347
- Шаг Creating
- Локаторы не досчитались

Steps:
1. Нажать Select all
2. Нажать Save
3. Проверить текст кнопки Confirm

AR:
- Confirm selection

ER:
- Confirm

![image](https://user-images.githubusercontent.com/109746268/212036610-f764a7ee-530c-43c9-9f66-5abb82c597a3.png)

**Comment by arslanbekova** [comment]
[3.7.379](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.379)
