### ISSUE TITLE
Добавить счётчик отмеченных локаторов к Save кнопке

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#916]
В списке локаторов для кнопки Save добавить счётчик выделенных чекбоксами локаторов (вместо "n selected")

Save 1 locator
Save 2+ locators

![image](https://user-images.githubusercontent.com/101407186/212052775-3f22c9b0-d3c8-4d4f-8b22-27eb4935d7ee.png)

**Comment by arslanbekova** [comment]
[3.9.408](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.408)

**Comment by arslanbekova** [comment]
[3.9.412](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.412)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.412 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Test result - **pass**
Selected via checkboxes elements counter is displayed in Save button and corresponds with the quantity of selected elements.
![2023-03-13 14_30_53-Settings](https://user-images.githubusercontent.com/106632366/224727979-6d865f4d-618b-4eed-a882-5fbe97ea9c6f.jpg)
