### ISSUE TITLE
[US-11-2] Контекстное меню на панели локаторов

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#917]
Сейчас контекстное меню на панели локаторов можно вызвать только через трёхточечное меню. В то же время - на панели покрытия - контекстное меню вызывается правой кнопкой мыши (что удобно).
В этом - есть некоторый инконсистенс.
Давайте добавим меню которое можно вызвать ПКМ.

**Comment by MariiaNebesnova** [comment]
по какой именно области кликать пкм?

**Comment by MariiaNebesnova** [comment]
дубль #863 ?

**Comment by SemyonKuznetsov** [comment]
> по какой именно области кликать пкм? три точки оставляем?

три точки надо оставить, это не взаимоисключающие элементы
я думаю что ПКМ должен работать по всему контейнеру локатора, кроме контейнеров иконок стрелок (если у них опасити=1), чекбокса и копирования

![image](https://user-images.githubusercontent.com/101407186/220349213-0eddc582-f7f8-4978-883c-7460a32de7c2.png)

**Comment by arslanbekova** [comment]
[3.9.411](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.411)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.411 Back-end v 0.2.27
Windows 10 (64 bit) / Chrome Version 111.0.5563.65

Test result - **fail**

A floating bug was discovered: right-click on Copy checkbox opens context menu if right-click has previously done on a locator container.
Occurs in ~1 out of 5-6 cases

https://user-images.githubusercontent.com/106632366/224297570-814d8f95-0dae-4265-9e3b-40941fcfc832.mp4

**Comment by arslanbekova** [comment]
[3.9.415](https://github.com/jdi-testing/jdn-ai/releases/tag/3.9.415)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.9.416 Back-end v 0.2.27
Chrome Version 111.0.5563.65 (Official Build) (64-bit)

Test result - **pass**
The context menu is opened by right-clicking under the cursor. The [aforementioned defect](https://github.com/jdi-testing/jdn-ai/issues/917#issuecomment-1463624724) is fixed.

https://user-images.githubusercontent.com/106632366/225902180-15ebc10c-091e-4f5d-9bd7-9fdc10b9d052.mp4
