### ISSUE TITLE
[Low] Поправить текст в попапе с предупреждением при удалении PO с кнопки Delete all

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#921]
1. "Delete these page objects?" -> "Delete all page objects"
2. Поправить основной текст

![image](https://user-images.githubusercontent.com/109746268/212288725-31eba724-dbce-4cfa-940f-82e74d625cb2.png)

1. "Delete this page objects?" -> "Delete page object"
2. Поправить основной текст
3. Убрать all из текста кнопки

![image](https://user-images.githubusercontent.com/109746268/212288854-e0ab427d-b491-40e7-a2c4-4d8c8d3c6657.png)

**Comment by SemyonKuznetsov** [comment]
[link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=163820%3A167426&t=4cW4I6TkPwerW2xE-4)

![image](https://user-images.githubusercontent.com/101407186/212330821-3218c45a-a617-435a-ae79-01e5fe23ae07.png)

**Comment by SemyonKuznetsov** [comment]
[link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=164110%3A171935&t=4cW4I6TkPwerW2xE-4)

![image](https://user-images.githubusercontent.com/101407186/212335270-fc4b9bfb-468f-4188-8779-fbc37a6c8f01.png)

**Comment by arslanbekova** [comment]
[3.7.379](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.379)

**Comment by OlgaTitovaEPAM** [comment]
done. tasted on macOS 12.6.1, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64)
