### ISSUE TITLE
[Medium] Клик по элементу на покрытии не снимает выделение с тех элементов в списке, которые не отображаются на покрытии

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#924]
Precons:
- JDN v 3.6.351
- https://www.google.com/search?q=312Qwe
- Шаг Creating

Steps:
1. Кликнуть на первый локатор в списке (Dialog dialog1;)
2. Кликнуть на любой элемент на покрытии

ER:
- Выделен только локатор из шага 2

AR:
- Выделены локаторы из обоих шагов

Шаг 1, результат:
![image](https://user-images.githubusercontent.com/109746268/212319058-c17edec5-8bdb-4804-9e7f-d749909f0d14.png)
Шаг 2, результат:
![image](https://user-images.githubusercontent.com/109746268/212319154-df9e6986-8f86-4e9f-8b14-090f2c00607c.png)

**Comment by OlgaTitovaEPAM** [comment]
Can't reproduce on 3.8.391
