### ISSUE TITLE
[Medium] Есть возможность редактировать локатор из шага Editing, но нет валидации

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#926]
Precons:
- JDN v 3.6.351
- Шаг Editing

Steps:
1. Открыть окно редактирования элемента

ER: ???
- Либо нужна валидация
- Либо нужно предупреждение об отсутствии валидации
- Либо не нужно давать возможность редактирования элемента

AR:
- Есть возможность редактировать локатор без валидации

**Comment by MariiaNebesnova** [comment]
обратить внимание на комментарии #625

**Comment by savinovava** [comment]
Предупреждение об отсутствии валидации

**Comment by AlexeyGirin** [comment]
Сообщение пользователю должно быть таким - "Validation is possible only on Page Object creation"

**Comment by SemyonKuznetsov** [comment]
Имя и тип блока валидируются

**Comment by MariiaNebesnova** [comment]
[3.7.387](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.387)
