### ISSUE TITLE
[US-5-1] разделить Download и Download all

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#927]
сейчас на вид одинаковые функции выполняют разные действия и скачивают по-разному собранные файлы, скорее всего надо поработать с текстом кнопок
____
Для Download:
уточнить в контекстном меню и поменять "Download" на "Download as .java"
[figma](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=164097-168333&t=yvVejp9vsCKIyd4g-4) контекстное меню для РО
![image](https://user-images.githubusercontent.com/101407186/235983666-c81676d7-014f-48c1-9c91-a01347506f98.png)
_____
Для Download all:
поменять иконку ![image](https://user-images.githubusercontent.com/101407186/236049539-6d7f9078-b762-4bd0-b3d1-16e738a6e17f.png) на текст "Download all as .zip"
![image](https://user-images.githubusercontent.com/101407186/236051467-e869802c-95f8-451e-bae0-6c9a6748e83b.png)
____
Решили: Оставить кнопку всегда Enabled пока что
кнопка должна быть задизейблена, если на странице идёт создание нового РО:
![image](https://user-images.githubusercontent.com/101407186/236051310-eb9aa327-41f6-42ce-9578-da2419ad7075.png)
relates to #1222

**Comment by MariiaNebesnova** [comment]
а как раздизейблить кнопку?

**Comment by AlexeyGirin** [comment]
> дание нов

Решили: Оставить кнопку всегда Enabled

**Comment by AlexeyGirin** [comment]
> а как раздизейблить кнопку, если открыл создание нового ПОб но передумал и так ничего и не создал?

Решили: Оставить кнопку всегда Enabled

**Comment by arslanbekova** [comment]
[3.12.475](https://github.com/jdi-testing/jdn-ai/releases/tag/3.12.475)

**Comment by AlexadrK** [comment]
JDN v 3.12.479 Back-end v 0.2.37
Chrome Version 113.0.5672.127 (Official Build) (64-bit)

Test result - PASS


https://github.com/jdi-testing/jdn-ai/assets/21053451/d3139c08-b3d8-49db-8e5d-49363d9983f3
