### ISSUE TITLE
Валидация на уникальность имени не работает если редактивароть ПОСЛЕ создания ПО

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#930]
1. Распознайте HTML5 элементы на страничке https://www.linkedin.com/jobs/
2. Выберите пару элементов с похожими именами (так будет легче) создайте ПО
3. Создайте ДРУГОЙ ПО (не важно какой)
4. С панели списка ПО попробуйте дать двум элементам одно и то же имя - НЕ ПОЛУЧАЕТСЯ (ок)
5. Откройте (расколлапсите) предыдущий ПО и попробуйте дать одинковые имена двум элементам

Внезапно - это получается, хотя не должно

![image](https://user-images.githubusercontent.com/26869421/212350888-3a80b601-118d-48f4-873f-2f776677b496.png)

**Comment by OlgaTitovaEPAM** [comment]
can't reproduce
