### ISSUE TITLE
URL в экспорте не содержит сам сайт и URL страничек

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#931]
Попытайтесь создать ПО для нескольких страниц с линкедина.
В моём случае это было
1. https://www.linkedin.com/jobs/
2. https://www.linkedin.com/messaging/thread/2-NWRlZDNhNzEtN2RmZi00Y2M4LWE5ZmUtYWI2MWE3ZDU1OTdkXzAxMw==/
3. https://www.linkedin.com/notifications/?filter=all
4. https://www.linkedin.com/in/alexey-girin-288858246/

Но в экспорте в файле MySite.java результат выглядел так:
public class MySite {
    //@Url("{ENTER_HOME_PAGE_URL}")
    public static FirstPage firstPage;

    // ADD SITE PAGES WITH URLS
    @Url("/")
    public static alexeyGirinLinkedInPage alexeyGirinLinkedInPage;
                
    @Url("/?filter=all")
    public static notificationsLinkedInPage notificationsLinkedInPage;
                
    @Url("/")
    public static messagingLinkedInPage messagingLinkedInPage;
                
    @Url("/")
    public static jobsLinkedInPage jobsLinkedInPage;
                
    @Url("/")
    public static feedLinkedInPage feedLinkedInPage;
                
}

**Comment by MariiaNebesnova** [comment]
[Release 3.6.354](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.354)
