### ISSUE TITLE
Опция Retry должна быть групповой операцией а не операцией единичного элемента, как сейчас

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#933]
1. Промотать всю страничку - https://www.linkedin.com/mynetwork/invite-connect/connections/ до самого низа (на ней должно быть 599 контактов как меня)
2. Запустить распознавание HTML 5 элементов

Как результат - расчёт части локаторов свалится.

3. Если выделить несколько или все упавшие локаторы то станет понятно, что их перерасчёт (операция Retry) доступен только для каждого элемента по отдельности, что очень неудобно

Необходимо, что бы если в выделении есть упавшие локаторы - в меню (как на покрытии. так и в листе локатора) появилась операция Retry

**Comment by MariiaNebesnova** [comment]
[3.7.388](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.388)
