### ISSUE TITLE
Если в результате фильтрации остался один элемент, то для него контекстное меню уходит за пределы видимости и доступности

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#939]
Добейстесь того, что бы в результате фильтрации в списке у вас остался один локатор (например - вбейте его полное имя)
Попробуйте вызвать контекстное меню.
Результат будет таким:
![image](https://user-images.githubusercontent.com/26869421/212653901-0e6b2da4-15c7-44db-85ac-43e22dbbdc80.png)

**Comment by arslanbekova** [comment]
[3.6.353](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.353)

**Comment by arslanbekova** [comment]
[3.6.355](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.355)

**Comment by MariiaNebesnova** [comment]
[Release 3.6.356](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.356)
