### ISSUE TITLE
Дизейблить чекбокс при отсутствии локаторов в списке плагина

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#941]
![image](https://user-images.githubusercontent.com/101407186/212685131-a69f9196-3025-4c0b-b26d-103f371b696e.png)

после анселекта фильтров остался чекбокс
Как я понял импрув Киры, то ничего нет - ничего не показываем, из такой логики чекбокс должен быть задизейблен, если у нас пустая выдача

**Comment by MariiaNebesnova** [comment]
[3.7.386](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.386)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.7.379 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1
