### ISSUE TITLE
Обновить текст для ReportAProblem

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#942]
![image](https://user-images.githubusercontent.com/101407186/213137691-514069af-95ed-4e6d-9268-34e69b9fb354.png)

Кира: может не писать что is not available? Просто вот тебе е-мейл, пиши туда. Я когда такую страшную ошибку вижу сразу хочется закрыть табу.

**Comment by SemyonKuznetsov** [comment]
<img width="449" alt="Снимок экрана 2023-01-17 в 15 32 00" src="https://user-images.githubusercontent.com/101407186/212899887-f50863f3-5b30-46d2-a5e5-869150bbfc19.png">

https://ant.design/components/modal#components-modal-demo-info

**Comment by felisa13** [comment]
Я, как пользователь, хочу нажать на кнопку репорта и отправить свой фитбек. 
Сейчас я вижу "Report is not available", что во-первых, не совсем правда. У нас есть возможность оставить репорт -- на емейл. 
Надпись "Репорт недоступен" сбивает с толку и первое, что я хочу сделать -- закрыть окно, не вчитываясь в длинное сообщения с причиной и возможным вариантом решения проблемы. 
Что бы я предложила: 
Заголовок "Problem report", и в случае если "Mail server is not accessible from your location and problem report can't be created automatically"  
просто писать  доступный для репорта способ "Please send an email SupportJDI@epam.com"
[link 🎨 UI-Kit (Ant+JDN)](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=164224%3A168119&t=Om03QWCiyub3jVja-1)
 
![Problem report](https://user-images.githubusercontent.com/119865618/213131846-168e9006-93e2-4a27-a44d-3e3d90595652.png)

**Comment by savinovava** [comment]
"Please send an email **to** SupportJDI@epam.com

**Comment by MariiaNebesnova** [comment]
[3.7.386](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.386)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.7.386 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1
