### ISSUE TITLE
[US-6-11] Добавить возможность поиска по тексту содержимого (по контенту)

### ISSUE THREAD

**Issue by felisa13** [jdi-testing/jdn-ai#943]
Контекст: 
[Видео](https://epam-my.sharepoint.com/:v:/r/personal/kira_bagrova_epam_com/Documents/Recordings/Test%20with%20Alina%20Lysenko1-20221226_170127-Meeting%20Recording.mp4?csf=1&web=1)  с 39 минуты, пользователь производит поиск и не может найти нужный элемент по тексту содержимого;

Необходимо добавить возможность поиска по тексту элемента. При этом - на экране должно оторажаться, что поиск произошёл именно по тексту (контенту элемента)

**Comment by savinovava** [comment]
Текст, по которому идёт поиск, может не присутствовать (не показываться на экране) в локаторе (в элементах среди которых идет поиск)

**Comment by savinovava** [comment]
Поиск по контекнту без отображения его в панели локатора (если его нет) должен быть доступен.

**Comment by AlexeyGirin** [comment]
Просто поиск по контенту - без визуальной составляющей (т.к. сейчас в принципе для поиска визуальной состовляющей нет)

**Comment by MariiaNebesnova** [comment]
[3.10.436](https://github.com/jdi-testing/jdn-ai/releases/tag/3.10.436)

**Comment by andrei-mikhailovskii** [comment]
JDN v 3.10.436 Back-end v 0.2.31
Chrome Version 112.0.5615.49 (Official Build) (64-bit)

Test result - **PASS**
Elements are found based on search by content text
![2023-04-06 12_21_20-Settings](https://user-images.githubusercontent.com/106632366/230364532-89edb916-f830-4fcd-94f1-e5671fbe74ea.jpg)
![2023-04-06 12_43_41-](https://user-images.githubusercontent.com/106632366/230364595-9e73fecd-e53d-45bc-8592-176d0a06bd03.jpg)
