### ISSUE TITLE
Переименовать действие "Edit list" в существующем РО

### ISSUE THREAD

**Issue by felisa13** [jdi-testing/jdn-ai#949]
Переименовать в контекстом меню для РО "Edit list" = "Edit Page Object"

![image](https://user-images.githubusercontent.com/101407186/213991302-19ae6287-6869-4085-8fae-6a3a744d3755.png)

**Comment by SemyonKuznetsov** [comment]
[figma link](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=164096%3A167687&t=kJeVMzT14JJXGavQ-4)

![image](https://user-images.githubusercontent.com/101407186/213991302-19ae6287-6869-4085-8fae-6a3a744d3755.png)

так же тогда надо переименовать add to po / remove to po 
![image](https://user-images.githubusercontent.com/101407186/213990876-cc3982a3-e21f-4d42-adbb-a3ed82c10031.png)

**Comment by MariiaNebesnova** [comment]
[3.7.375](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.375)
