### ISSUE TITLE
Баг с отображением иконки и тени в фильтрах

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#952]
- Иконка "Х" отображается некорректно
 - У окна фильтров отсутствует тень, из-за чего оно сливается с плагином

`Effect style: drop-shadow/0.15`
`Effect: Drop shadow`
`Radius: 8px`
`Offset: 0px, 2px`
`rgba(0, 0, 0, 0.15)`

https://user-images.githubusercontent.com/101407186/212706389-cdfcec9a-cd6c-48fb-8fbd-c17a34e21a54.mov

**Comment by arslanbekova** [comment]
duplicate issue regarding cross icon
https://github.com/jdi-testing/jdn-ai/issues/816

**Comment by MariiaNebesnova** [comment]
[3.7.376](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.376)
