### ISSUE TITLE
Чтобы вызвать контекстное меню с помощью ПКМ требуется 2 клика

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#953]
Баг для выделение 1 локатора, не группы (macos)

Сейчас:
1 клик это выделение
2 клик это вызов контекстного меню

По идее должно выполняться 1 нажатием
1 клик - выделение и сразу вызов контекстного меню

https://user-images.githubusercontent.com/101407186/212709539-16d24da3-eda8-49b1-b740-c252e2ac4729.mov

**Comment by arslanbekova** [comment]
После открытия контекстного меню на покрытии, если продолжить выбирать элементы левой кнопкой мыши, то контекстное меню не закрывается.

**Comment by arslanbekova** [comment]
[1061 - Контекстное меню на покрытии исчезает при попытке взаимодействия с ним, если окно плагина открыто в режиме "Undock into separate window"](https://github.com/jdi-testing/jdn-ai/issues/1061)

**Comment by arslanbekova** [comment]
[3.8.393](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.393)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.7.394 Back-end v 0.2.22, Google Chrome Version 110.0.5481.77 (Official Build) (x86_64), macOS 12.6.1
