### ISSUE TITLE
Поменять на окне плагина клавишу модификатор для доп выбора на macOS

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#954]
Вместо control должен быть command
При нажатии control+пкм/лкм просто открывается контекстное меню

На записи я выбираю локатор и пытаюсь через control выбрать следующий

https://user-images.githubusercontent.com/101407186/212712253-a9774ecb-f3c4-418d-89b5-cdc4b40b850d.mov

Маша говорит что плагин может определить с какой платформы сидит пользователь

**Comment by arslanbekova** [comment]
[3.7.374](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.374)

**Comment by OlgaTitovaEPAM** [comment]
Если мы работаем с выделением элементов через окно плагина, то Множественное выделение работает через Command. При работе на покрытии Множественное выделение работает через Control.

**Comment by arslanbekova** [comment]
> Если мы работаем с выделением элементов через окно плагина, то Множественное выделение работает через Command. При работе на покрытии Множественное выделение работает через Control.

Это ожидаемое поведение для macOS в данной сборке.
Смена ctrl на cmd для покрытия отдельная задача [1021](https://github.com/jdi-testing/jdn-ai/issues/1021)
