### ISSUE TITLE
[Medium] Едет UI плагина при создании/редактировании PO с длинным именем

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#961]
Precons:
- 3.6.357 
- PO с длинным названием (создаётся например здесь: https://www.linkedin.com/jobs/)
- Шаг Creating/Editing

Steps:
1. Проверить отображение UI плагина

ER:
- Отображается в соответствии с макетом

AR:
- Из-за длинного имени PO едет вёрстка
![image](https://user-images.githubusercontent.com/109746268/212869354-60a74c2f-1ebb-4db7-bbcf-f97a1f95f84f.png)

**Comment by AlexeyGirin** [comment]
Показывать тултип если наводим мышкой на заэллипсированную строку

**Comment by SemyonKuznetsov** [comment]
@arslanbekova

[link to ant](https://ant.design/components/tooltip#components-tooltip-demo-basic:~:text=on%20mouse%20enter.-,Basic,-The%20simplest%20usage)

[figma component](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=60669%3A112419&t=a5uiCm17dITIqstu-4)

[example design](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7861%3A363533&t=z5xiMmyd8B5AUZlM-4)

![image](https://user-images.githubusercontent.com/101407186/215089591-09095c8f-fe58-4ad8-b84b-61fc3a830cc8.png)

**Comment by AlexeyGirin** [comment]
@SemyonKuznetsov добавит мокапы по которым Люда и сделает

**Comment by SemyonKuznetsov** [comment]
использовать элипсинг можно в таком формате, для сокращения в 1 строке, чтобы ">Creating" и иконка фильтров не переносились
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7898%3A365951&t=pszKu5yDp2TclIU1-4)
![image](https://user-images.githubusercontent.com/101407186/216008883-ac9bca7b-a512-4b7f-a558-647fe3c147bb.png)

[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7898%3A365555&t=pszKu5yDp2TclIU1-4)
![image](https://user-images.githubusercontent.com/101407186/216008911-6c919f5f-237c-4fcb-b587-1b3587bbc840.png)

**Comment by SemyonKuznetsov** [comment]
upd: решили что оверфинкинг и пока не запариваться на счёт этого

использовать элипсинг можно в таком формате, для сокращения в 1 строке, чтобы ">Creating" и иконка фильтров не переносились
[figma link](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7898%3A365951&t=pszKu5yDp2TclIU1-4)
![image](https://user-images.githubusercontent.com/101407186/216008883-ac9bca7b-a512-4b7f-a558-647fe3c147bb.png)

**Comment by arslanbekova** [comment]
[3.7.373](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.373)
