### ISSUE TITLE
UIElement should present in filter in any case

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#965]
Как воспроизвести:

1. Открыть страничку - https://www.linkedin.com/mynetwork/invite-connect/connections/ 
2. Запустить распознавание HTML5 элементов
3. Пойти в фильт и отключить все элементы
Как результат - на экране останутся элементы с типом UIElement которые отсутствуют в фильтре.

Думаю - нужно добавить этот тип в фильтр тоже для любой элемент лайбрари

![image](https://user-images.githubusercontent.com/26869421/212952260-743f2249-7a09-45ae-971e-8bb5a36c07a1.png)

**Comment by MariiaNebesnova** [comment]
[3.7.376](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.376)
