### ISSUE TITLE
После отключения некоторых элементов - система всё равно показывает часть из них, если проскролить вниз

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#966]
Как воспроизвести:

1. Открыть страничку - https://www.linkedin.com/mynetwork/invite-connect/connections/
2. Запустить распознавание HTML5 элементов
3. Пойти в фильт и отключить все элементы КРОМЕ TextField
Как результат - на экране останутся элементы с типом TextField и UIElement
4. Переместите курсор мышки на панель покрытия и крутаните колёсиком мышки что бы проскроллить вниз

Внезапно - элементы которые не должны показываться (кнопки и лэйблы) показываются

![image](https://user-images.githubusercontent.com/26869421/212958993-a50c7fad-a978-4ad1-b78c-77463e9b9940.png)

**Comment by MariiaNebesnova** [comment]
[3.7.372](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.372)

**Comment by Maksim-Kviatkovskii** [comment]
JDN v 3.7.377 
https://cbracco.github.io/html5-test-page

Воспроизводится:
![image](https://user-images.githubusercontent.com/109746268/216632969-a9e8831b-7c2d-494e-9ac0-9a0a4e81b726.png)

**Comment by MariiaNebesnova** [comment]
[3.7.382](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.382)

**Comment by OlgaTitovaEPAM** [comment]
Done
JDN v 3.7.382 Back-end v 0.2.22, Google Chrome Version 109.0.5414.119 (Official Build) (x86_64), macOS 12.6.1
