### ISSUE TITLE
[Minor] Клик на имя типа (лэйбел) должен работать так же как check/uncheck для чек бокса в фильтре

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#967]
Обратил внимание, что если кликнуть на имя типа элемента в фильтре - ничего не происходит - нужно кликать по чекбоксам.

Было бы удобней если бы включать и отключать типы элементов можно было бы и кликом по имени

![image](https://user-images.githubusercontent.com/26869421/212981938-ebddde59-838e-4f87-8421-88442fc2f1b9.png)

**Comment by MariiaNebesnova** [comment]
[3.7.382](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.382)

**Comment by OlgaTitovaEPAM** [comment]
done. tasted on macOS 12.6.1.

На функционал не влияет, но при работе с фильтром в режиме Editing в Console возникает ошибка:
Error in event handler: TypeError: Cannot read properties of null (reading 'filter')
    at <anonymous>:1:4934
    at b (<anonymous>:1:5108)
<img width="706" alt="Screenshot 2023-02-08 at 17 40 11" src="https://user-images.githubusercontent.com/112088719/217562559-63e0a2a2-617d-46c3-bf4d-1a0a922c5c1a.png">
