### ISSUE TITLE
[Medium] Добавление локаторов в ПО работает не всегда если часть типов элементов отключена в фильтре

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#968]
Как воспроизвести:

1. Промотать всю страничку - https://www.linkedin.com/mynetwork/invite-connect/connections/ до самого низа (на ней должно быть 600 контактов как у меня)
2. Запустить распознавание HTML 5 элементов
После некоторого ожидание - процесс расчёта упадёт.
4. Нажимаем Retry и добиваемся что всё просчитается до конца
5. Идём в фильтр и отключаем все элементы кроме Label и Table
6. Находим в списке локатор с именем ember1039 и зажав CTRL выделяем (не подряд) все локаторы между ember1039 и ember1212
7. Добавляем эти локаторы в ПО (я это делал через контекстное меню на покрытии)

Результат - почему-то не все локаторы попадают в ПО

![image](https://user-images.githubusercontent.com/26869421/212984208-fef78f5f-3190-4df6-8162-4a604fe6915d.png)

**Comment by MariiaNebesnova** [comment]
[3.8.393](https://github.com/jdi-testing/jdn-ai/releases/tag/3.8.393)
