### ISSUE TITLE
Скороллинг списка локаторов переоткрывает окно редактирования локаторов если это окно был когда-то открыто с покрытия

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#969]
Как воспроизвести:

1. Открыть страничку - https://www.linkedin.com/mynetwork/invite-connect/connections/
2. Запустить распознавание HTML 5 элементов
3. Выбрать любой локатор в середине списка локаторов (так удобней)
4. Открыть его на редактирование с ПАНЕЛИ ПОКРЫТИЯ (это важно)
5. Закрыть окно редактирования (я нажимал на Ок хотя никаких изменений не вносил)

Начиная с этого момент если пролистнуть колёсиком мышки список вверх (так что бы локатор который мы редактировали исчез из виду), а потом пролистнуть обратно (что бы он показался) то система почему-то будет открывать окно редактирования этого локатора.
Это, конечно, очень странно

**Comment by arslanbekova** [comment]
[3.6.369](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.369)
