### ISSUE TITLE
[1pt]Проверить новый бэкэнд на новом порту и с новой моделью из нового источника (с ГитХаба)

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#97]

**Comment by pulya-na-vullet** [comment]
<img width="1440" alt="Снимок экрана 2021-11-30 в 8 34 59 AM" src="https://user-images.githubusercontent.com/61897393/143991707-6a0c2b29-b89c-4fd1-9f0a-2f1e3c0b5aef.png">
Done. Worked In windows and mac os.
