### ISSUE TITLE
[Critical] Падает расчёт локаторов на странице пулреквеста в github

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#970]
Precons:
- JDN v 3.6.357
- https://github.com/jdi-testing/jdn-ai/pull/964

Steps:
1. Выбрать HTML5
2. Запустить генерацию

ER:
- Генерация работает

AR:
- Генерация падает, отображается пустой список локаторов

**Comment by arslanbekova** [comment]
[3.6.359](https://github.com/jdi-testing/jdn-ai/releases/tag/3.6.359)
