### ISSUE TITLE
[US-6-6] Переделать кнопку Delete

### ISSUE THREAD

**Issue by felisa13** [jdi-testing/jdn-ai#979]
Когда нечего удалять, когда 1 и когда несколько), при этом видимо добавить какое-то undo взамен удалению только что созданного РО

Relates #1222

**Comment by felisa13** [comment]
<img width="1028" alt="Screenshot 2023-01-24 at 14 29 57" src="https://user-images.githubusercontent.com/119865618/214268833-d8cf7ec2-de56-49e9-b37e-804f0f0b9a03.png">

**Comment by SemyonKuznetsov** [comment]
![image](https://user-images.githubusercontent.com/101407186/217833837-a25508de-7603-4a0d-b8a1-56771b4329f1.png)
https://www.figma.com/file/4475tQz3AS575emawDoLqC/UI%2FUX-improvments-%7C-Delete-button-part?node-id=3%3A4994&t=YdFc6myr9bGK5uIe-4
