### ISSUE TITLE
в инструкцию к установке плагина к кнопке "check" надо добавить Loading

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#984]
в редми плагина кнопке "check" надо добавить Loading, чтобы понимать когда происходит проверка, а когда что-то лагает и ничего не происходит

вот такой
https://ant.design/components/button#components-button-demo-loading

то что кнопка будет увеличиваться - не страшно

![image](https://user-images.githubusercontent.com/101407186/214286344-d3bac820-2c30-4de0-9909-abd86455a7d9.png)

**Comment by SemyonKuznetsov** [comment]
https://ant.design/components/button#components-button-demo-loading

**Comment by AlexeyGirin** [comment]
1. При невозможности присоединиться к серверу на третьем шаге во время проверки - нужно выводить сообщение с ошибкой в через notification bar
2. Кнопку Back не блокируем - позволяем вернуться назад в момент когда происходит чек

**Comment by MariiaNebesnova** [comment]
тексты ошибок : 
  TryToAccess = "Trying to access server...",
  Accessed = "Accessed",
  AccessFailed = "AccessFailed",
  OutdatedServerLocal = "Local server version need to be updated.",
  OutdatedPluginLocal = "Plugin version need to be updated.",
  IncompatibleVersionRemote = "Remote server version is incompatible. Please, update plugin",
  IncompatibleVersions = `Remote and local server versions are incompatible. 
  Please, update plugin or local server, or try to connect the remote server.`,

**Comment by arslanbekova** [comment]
[3.11.455](https://github.com/jdi-testing/jdn-ai/releases/tag/3.11.455)

**Comment by AlexadrK** [comment]
JDN v 3.11.455 Back-end v 0.2.36
Chrome Version 113.0.5672.64 (Official Build) (64-bit)

Test result - **PASS**


https://github.com/jdi-testing/jdn-ai/assets/21053451/a914c00d-2973-40cd-9535-b57e79ed97cf
