### ISSUE TITLE
[High] Не отправляются письма с формы "Report a problem"

### ISSUE THREAD

**Issue by Maksim-Kviatkovskii** [jdi-testing/jdn-ai#988]
Precons:
- JDN v 3.7.367 Back-end v 0.2.18
- Локальный докер
- Открыт плагин

Steps:
1. Нажать кнопку "Report a problem"
2. Заполнить поля "E-mail" и "Text", загрузить аттачмент
3. Нажать кнопку "Ok"

ER:
- Письмо с введёнными данными пришло в ДЛку

AR:
- Письмо не приходит, в консоли сервера повторяется ошибка

```
jdi-qasp-ml-celery  | [2023-01-27 11:23:56,094: INFO/ForkPoolWorker-7] File cat_caviar.jpg is attached to "Report Problem" email
jdi-qasp-ml-celery  | [2023-01-27 11:23:57,365: ERROR/ForkPoolWorker-7] 'NoneType' object has no attribute 'encode'
jdi-qasp-ml-celery  | [2023-01-27 11:23:57,473: INFO/ForkPoolWorker-7] Task send_report_mail_task[58f68d45-ac04-4e63-be46-adbfd7df3e14] retry: Retry in 60s: AttributeError("'NoneType' object has no attribute 'encode'")
```

**Comment by AlexeyGirin** [comment]
Как временно решение - отключить посылку писем и поставить заглушку как у нас есть при посылке писем изнутри епама

**Comment by AlexeyGirin** [comment]
![MicrosoftTeams-image (26)](https://user-images.githubusercontent.com/26869421/215079240-32f76c1c-66d0-463e-9f1a-6be0b04201bd.png)

**Comment by arslanbekova** [comment]
[3.7.368](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.368)
