### ISSUE TITLE
Проблема с множественным выделением

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#992]
0. Откройте https://www.linkedin.com/mynetwork/invite-connect/connections/ и запустите поиск по HTML5 элементам
1. Выделите группу элементов
2. Правой кнопкой мыши кликните на один из выделенных блоков и в контекстном меню кликните на Добавить в ПО

Как результат - в ПО добавится всё, кроме блока на который мы кликали
Я бы ожидал, что добавляться будет всё выделение

![image](https://user-images.githubusercontent.com/26869421/215351642-bc884d1a-96d3-4a08-bd0d-ee4eb8bf72b8.png)
![image](https://user-images.githubusercontent.com/26869421/215351655-f2d887fd-a019-4654-b1c1-84bb6c5c07c8.png)
![image](https://user-images.githubusercontent.com/26869421/215351688-c400bcb6-ac0e-4976-95c9-f68a769e9cc8.png)

**Comment by Maksim-Kviatkovskii** [comment]
В целом клик по УЖЕ выделенному элементу правой кнопкой снимает с него выделение

**Comment by MariiaNebesnova** [comment]
[Release 3.7.370](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.370)
