### ISSUE TITLE
Множественное выделение работает по умолчанию на покрытии без зажимания кнопки CTRL

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#993]
1. Сейчас на панели покрытия - клик на блок не снимает выделение с других блоков если оно было.
2. Более того, если в процессе кликов по блокам - кликнуть правой кнопкой мыши - то появится контекстное меню которое останется висеть навсегда если продолжить кликать на другим блоки

Я бы ожидал, что система будет снимать выделение со всех выделеных блоков если не зажата кнопка CTRL (а меню должно исчезать вообще всегда при клике мимо меню)

![image](https://user-images.githubusercontent.com/26869421/215352142-2a7c4340-e1c1-4311-b1a1-027f265c7671.png)

**Comment by Maksim-Kviatkovskii** [comment]
Клик в пустую область не снимает выделение с элементов, думаю rootcause тот же

**Comment by MariiaNebesnova** [comment]
[Release 3.7.370](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.370)
