### ISSUE TITLE
Копирование xPath + JDI annotation работает неверно

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#994]
Сейчас при выборе опции xPath + JDI annotation система воспринимает это буквально и выдаёт что-то типа
/html/body/div[5]/div[3]/div/div/div/div/div[2]/div/div/main/div/section/div[2]/div[1]/ul/li[28]/div/div/div[1]/a @UI("//*[@id='ember6659']")

Хотя ожидаемое поведение это:
@UI("//*[@id='ember6659']")

**Comment by arslanbekova** [comment]
[3.7.371](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.371)
