### ISSUE TITLE
Копирование xPath + Selenium не работает

### ISSUE THREAD

**Issue by AlexeyGirin** [jdi-testing/jdn-ai#995]
Сейчас опция xPath + Selenium не работает вообще

Хотя это сделать несложно.
Для генерации вида @UI("//*[@id='ember6659']") 
По нажатию должно помещатьв в буфер:
@FindBy(xpath = "//*[@id='ember6659']")

Проще говоря контент в кавычках (это xPath) просто помещается в другую обёртку - @FindBy(xpath = "тут xPath")

**Comment by arslanbekova** [comment]
Не согласна с тем, что это баг.
Этого не было в изначальных требованиях + disabled options обсуждались на scrum звонке.

**Comment by arslanbekova** [comment]
[3.7.371](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.371)
