### ISSUE TITLE
Обновление уведомлений с Alerts на Notifications

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#997]
1. Выглядит плоско и устаревший дизайн
2. Есть какие-то сложности у фронтенда с реализацией алертов в код плагина, сейчас необходимо вкладывать внутрь контейнера таблицы, что усложняет логику и увеличивает код

Предложение - перейти на [лучший компонент](https://ant.design/components/notification)

старый
![image](https://user-images.githubusercontent.com/101407186/215464305-811fbe9d-b055-456f-b0d9-58a05ea063de.png)

новый (иконка закрытия и кнопки - всё будет, пока что просто для примера)
![image](https://user-images.githubusercontent.com/101407186/215464351-6b16141b-83ee-4614-b3d8-78d549c688b3.png)

для задачи нужно 
- собрать старые алерты и проапдейтить на новый дизайн
- подогнать компонент по размеру плагина

связанные задачи
- #944
- #985

**Comment by SemyonKuznetsov** [comment]
[ant link (bottom placement)](https://ant.design/components/notification#components-notification-demo-placement)
сделал больше чем антовский, 80% от ширины плагина, но не больше 600px
большой 600px
минимальный 320px при 400px плагин

**Comment by SemyonKuznetsov** [comment]
[figma component](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=147864%3A182257&t=rHzCNmy0xo7tWEcM-4)
![image](https://user-images.githubusercontent.com/101407186/218983035-cd6b3976-68e8-40db-96b8-c8c4bd767a1e.png)


![image](https://user-images.githubusercontent.com/101407186/218982808-ca7803a0-5751-4157-a336-956f490b400b.png)
![image](https://user-images.githubusercontent.com/101407186/218982908-1ca117ae-9978-4122-bd90-3e9d727bb166.png)

**Comment by SemyonKuznetsov** [comment]
Modified:
- Body text - Line height from 22 to 20
- Spacing between items (vertical) from 8 to 4
- Added buttons
- Text buttons color 65%

and in these variants:
<img width="363" alt="Снимок экрана 2023-02-15 в 12 15 25" src="https://user-images.githubusercontent.com/101407186/218984862-57846a8b-622b-4508-a3fc-da345c880057.png">
- Title text (earlier body text) - Line height from 22 to 24
- text color 65% -> 85%

**Comment by SemyonKuznetsov** [comment]
Для будущих апдейтов по возможности:

![image](https://user-images.githubusercontent.com/101407186/218994548-2bece432-09b8-4e51-95c6-b97d5d5119fb.png)

**Comment by SemyonKuznetsov** [comment]
[вот тут в фигме](https://www.figma.com/file/9QYwsMasAE9EDYDZS1e37k/%F0%9F%8E%A8-UI-Kit-(Ant%2BJDN)?node-id=164299%3A167792&t=tZa12Y6dlnOXPc70-4)
есть вот такая картинка со старыми алертами и в какую группу я их передвинул, может быть это поможет не запутаться

![image](https://user-images.githubusercontent.com/101407186/219348815-b9e84ce1-323e-45b6-bc82-545db1eebeab.png)

**Comment by MariiaNebesnova** [comment]
Добавлять FileName в это сообщение нужно отдельной задачей 
![image](https://github.com/jdi-testing/jdn-ai/assets/82033805/ddeea3e3-1671-4a57-ba38-136760cb904a)

**Comment by MariiaNebesnova** [comment]
нотификейшены для гайда будут реализованы в рамках задачи https://github.com/jdi-testing/jdn-ai/issues/1344. сейчас все убраны до выяснения требований

**Comment by MariiaNebesnova** [comment]
[3.13.520](https://github.com/jdi-testing/jdn-ai/releases/tag/3.13.520)

**Comment by SemyonKuznetsov** [comment]
> Добавлять FileName в это сообщение нужно отдельной задачей ![image](https://user-images.githubusercontent.com/82033805/251697515-ddeea3e3-1671-4a57-ba38-136760cb904a.png)

дописал требование в #1300, новую не надо
