### ISSUE TITLE
Добавить отступ к кнопкам

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#998]
[можно тут в фигме посмотреть](https://www.figma.com/file/DxLzXoAT23Gcu9DmCIuTcW/Design?node-id=7421%3A361071&t=3ILoztJ64WjuWTBr-4)

![image](https://user-images.githubusercontent.com/101407186/215472003-a474ea2c-a23a-482d-b8a3-7e041d8f810b.png)

![image](https://user-images.githubusercontent.com/101407186/215473813-3efa7118-51d6-49cd-bf6f-f75bae516531.png)

**Comment by arslanbekova** [comment]
[3.7.377](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.377)

**Comment by Maksim-Kviatkovskii** [comment]
JDN v 3.7.377 

Под отступом 16рх остаётся ещё пространство:
![image](https://user-images.githubusercontent.com/109746268/216634877-7672c1b0-d571-4cf1-b7c9-4c61d8c95ca9.png)

**Comment by arslanbekova** [comment]
[3.7.378](https://github.com/jdi-testing/jdn-ai/releases/tag/3.7.378)
