### ISSUE TITLE
Баг на скролл при сворачивании/разворачивании родительских локаторов

### ISSUE THREAD

**Issue by SemyonKuznetsov** [jdi-testing/jdn-ai#999]
новый PO - дождаться конца генерации - иконка сернуть/развернуть

у меня скролл улетает куда-то в центр

https://user-images.githubusercontent.com/101407186/215473412-5e251a87-7c5d-40c6-9937-a73ff80dff12.mov

**Comment by savinovava** [comment]
Воспроизводится на Mac

**Comment by SemyonKuznetsov** [comment]
В 3.7.371 перестал воспроизводится
